sprite $Active_Directory [96x170/16z] {
pPk9hgDA34Izb0tv_nz-WtD1T9nkfJ58hxJETaxXIZ8xZS8m4teiy2tWP-XYxYPuoC0RNPd8R3FSJO_QycUA1xdxy2R7LJGPweTNReIMPgYSnXAAxvhXTFWl
1iCDfv7E7SepC9h3vs0pW0jqTChNPn1tJ_GSkMRWmU67CzGFNvzXy1asd87hhydw3CFJr6V0a5wVmLpeQlY7ZprtPheSUHk6V94qxlGC6F6X9GD6GmSVG38K
PiXyCuCALsSOyAi6JOR43qFbIFiCcGyx35mqWBlz8ohbTmDt-H5bgiumu7lj4HY86Hf-AzW_Jsj3SxT_28HkcI7ppIDGel8CtVwBBwKR4Ui-Wpjhxhyikw0s
0pO-aQR-8H2cwWnm3mXI_sLn2DSCqVQDu8_-4MX5m0Jtu4Vqity8wBA1p_m8ZlxlhEjRm9VecK-oz_TTi9ho1G5pvaVCtlI3lngOPWtSvPDQs_yGy0Hzm2Us
fl_hzPeJC0_u4RJzDy4-s0I-poVrlN_WJmAUeFVvn7xmNqamfcU-CENOgNyhu3wzmvTl1dlp3m4q2H9UUdmHIi7--ia27fVF_A-Fe4V_o0hvun07CU67V94a
aEF-aUKGxD147_Bp8_3o3tyMyBVt0Oi4RN3_FLy5xnml8ZhZcPYZsfuXNuMpu7MASHA8g2Pyhxzg5hnEXeNfOrfMu5U-YgfA5Wpv06RwPm7d_dIH7m-GRYJh
c6zp_RD0g_tR-lb6Mk7d_bc0U_ZQ5TY0hpBRFz9olCTN4PcuVrUmTlWYSg5_5d2Fpy8Nxfy5Uc__BB1-Vr6TldyMBBt-2kYL_e0sh4v_nPW_U81Me5_x_yxF
U40QmPN-m_gjGE_ltmZqtllZRU0nlzP_5upvobVl7ndpDUY5_j34htp-vFxGBZ_mrVw0zFYxe73_2FVu1roqq1_WRl-tGQ5Nxn_H7ZyY06hz8ODzX_nV1Lpj
d-cjeBUltDCV-dtVo_qLdodTHvC1duPHVvru_yxtr-BxTyoF5FlN-Jf_VtgqV-RB6L-yV-QBwe1Vxg_0W5--lm2FzXUC-wle_xs_Fdn_FDjVLHwzlp8_s3_o
sFqZp_T_wlwPVl3rtlwYRNy5zBxxRuYF_e11x-glEv_FV3FeFVTNVEk_1JVtfpC_elVrp_p8ZVtf6zzGxO_1VIBb_iA3_kQ6slsPtlXUVtShz0zofCztn-N-
mH_VnzqNA_Md0J_w--8ezHSTz_TbiUlzHVNWs_V-In9CyFN4XpiB4dwB0tK-YJj4xQlX6fyQFZ7SLP3f8QZpYTZS-7Y4as1ThSxVXv3KVzq5LNuSoGIVXlLV
bYjyOMhv53jhGm_-AmHpV67E_7Y4NT3y_VuoowVCFrR0_luz-6i8vlYK-ViBIUspVpp197yB9twy5s21F_YROPtlpwgP7uzazj4_19DyqSoFYBl16tu8VkNJ
EzhZ4ziXsCyJ6qpmUS3VFrQR_Y6ezi-2jH5OgNzUULc2VX9K-kULxTm_CiVdu8y4WJzbcU0B4rdY9y5hlSRdpU4E6WkkzOyeF0RhXaDmaS-mr7uWcEIpceDt
_bWmpsU6Wubuvmyty1b-u97-rTXGiCpmWvxvOy7FVA8uF203P19W_PKlC0VD1UxuaQ_cxaQN1MD-q1rCymApCvybyMDNR4teGinj2RwzcL6ovR_H8dGbl0c2
RnnyTstuMlhVVq6quFicO1UuyS4Nk1ic3v_V1i5t2pwnEVxuU9Ulu6DZt_Xm13--HecklshonkjYBk8gBiUlwODkGjN416Ok979qtUW0olHzWk0tWUFU_yxy
sPM5Rei5_xdmmtoIX_c4X_c4X_dCD9V_
}

