sprite $Advanced_VoIP_Gateway [96x68/16z] {
jPc9Sjim34Gz503YeFJ_dzjG88OAQsl4I7wzhxVMRiasoMkI1GcNrxTOY12Hw3i9YGWTelIy7Ltl47wbcWuHVD6EZywGSBH7IO_Cq8iV8S9dgtcyfFJ6das7
X8UBv_pC3424Lo22XuhF9jZ8ck-Kb8ZEgw63V_xAGC9P2DEDQa2DtbIJUNQ6i8zamS7lgREd8GtLF5mIlgq60r4CSkxMaojZgXeGVPDA5mzq2liCyIX3mdpn
8XWmJSvmVXcCrMJJePet1nek53ymUQ2NoUAZcei0Kfgv3COBJYqVgnbOKagm1oH4W8a3513ZHp-a7S3wubcA8U1pG6eiz2Ako2eJpt2ywqHnnDtkHr5LJyZN
0yO3FHRV_QHcgb8JTANx9OMz-qLKMuBDpI1oRW-_Q2H8qUipWEYvFVoU43CmtFnBqm4x-eSPRjiNtbRtHy3a3EVLv6th_jXWUeQmZ-2sDJ_pCK3w3F1tEzYs
Kuv-HpHco73D_fz_aQqXKFt702ig4pEuUon-zK-MyKNYVdQ_hUjgSdK6UFFQySUmrS-5QNcvdpr4jQmxof5mTXh0XVvL-mAsDgJQtL-XghJYh4LOJcQ8uWTv
0WcxPdpjW0WxfinMtMkDCE7J6SBiAVwT77RB_RyFvELeAKAifQFyUORTvmcHir1fM2s-0oGYjlyyMr7MOgLO_TGIP9nXMTBIIF4rcXTRYeGzI9X5hR4N4dX9
mYo76S8O2VNx8AKHnOy9sXA8MQsZ8ZL1MApiCq0eZm_0rj1CwSF_QzaJbDYCUKoe54Lmd-k3R44KVv9GKVuLeA8jOQNbFr2j8GIlCo2BEhKaPNLgG2Hienqa
x98ndTbZw8fKFRDsMa31ttfMKpCrrHpLd98ew-4P1aP_re2ls6C6SPdV49_zg44KVpL1H1t-uOCVH1jU_0oOnM5Ybk3e1-xsg6Q250bLpyoZFqimRUz3IuD6
Fqh0XFFgFdH83lvyj7lnDnAQv-3V-7Orumnk37-tmprvJ-2TN_uy5dzh1lUR-_c7k8KVIl1723z7yOy1MSJzspPH_DGC-aFPDYDyh9hnlDbgKVmNI7_xoCW_
}

