sprite $Application_Store [96x104/16z] {
jTg9Ukig40DWCz88Zltn_gzxEqwkwnH8S9FghDr-0TxeiimdaSiVXfA4lz8X-LVawIzqS_azuiVrHFbt97n-QSYJBq-VrXzzYHzSUBBr9NneuScU_v55mg6t
_lkBP1A1WV_s8YKF_RcVVxr8YNBWfP_pxwQ0qAVyBCb-i_1plfH5ulB2svGlZmbSNtYpAT-Lh_hOzIa_z8k-IJIRyptdYtxoqAVyqA_wb9lD-QvyrOSSAKtu
aPml-kP2IdC-bI_woSMKvdnALtt8BStvT4Mk-92mf2cVb2xxObgcVDAbJe50rprEMFhXmzAC7qZNToTvF2hS9QH7tsp2T-yLY6Z2g3ZxWJttuTxw1zwjmE4l
YmLZGnzixyoDtZROtOSjoKZIkdxe7Pzu4GetdzajfPsnrFWtlYc0mPu48JXtts8feo40_F39hW-R29pXBvvLIio10U3RDp3I-h2fG1Q-ILvAXYMZb3FllWNU
cm1jCb3u2_PRBcbVYVyLjsFmFT-c8mi_qRaN47j3AOK8lb_0UPyCVqaWFKUAHqCfUk9ZteTkVZ80NYAA5x8mBBZk7_S6m5BQDn9F_JITO_n7bdsv3hyjkEeJ
uPzodzPu0fptAQ4qz__3xnSGbtoKzCF7tSV8jqaUuHkRWiFl5X2Ou-tccpRhZnyZ7pR5tttpocRyumaGaUL54h3xjBsWM6_y6FkmfxpXVp_lubhpgM361-o5
lljm3n--rTACloqu_755GkJmBRlT_h_MJOY2QJ-I7koWVlYswYvv_geesSCV5n1pENnRomxT22ahVzP7gOw3aFe-V-NJeq1r7VXuquTW1d2jnL_u_9MV2Yp-
xslTyk4RZhpfBxRnndZPwbOqzlahVx7gtzltNDRowEDDFmeAVfm_rf_0TPyMLzrMVUpZ7HzbV_vwtVJesuTyAlnafMxg-9QQM9idldb9UqorhlhshNk7xBK0
vEqtsVgMIxh7j6xRMlpi3uT-TavfVSlL7W7f4Cnn9UhvfggnJvyF6vyAYBMozMttbojfV8Yxa-lc0n-TMF-HcrhV2ct_VwwruD6ty1D8f_ESTdy2bpjxFbRU
pm6LE4FP-6f2DhuaTNt3bd7SVvHByVp2zzPd_eht_2XOsTpVRkdwhfx_hvIEJuPIQXxx78m_dNuj_DVtKKA1RpNtV0l_t_yfzsJlZB_qVIlX0wgrpFkOzxaY
GcgjjQZZD_p0prtVVEFkawwoRciP-EM5dmU-UVNmX-lVy1TyXi6wSjhFKtwp_ozZl-6d_7R_xq_yqlZdipyDhby_xV_t3LpNR_Xs_7rV4CpAiV_NLyLQSkkV
-NcVMiAtTMts_mC_3tsuatpq7SjW___ebuCV-KVElliI_h7_x_kwv6T-yqg73vQw-Yi_N_0fJ_jymcZs_rq_N_0fBX5pl_iayx7_x_bvtgVSbdlSWs_s_usV
Ptrww4UI-yadNNh7bqHR7aBnxYlBY_Vyd6TzV_ADV6MIAtxwdSpuxGyYU0QvsQE_f4wMUVzeSFfNYlFiGtremcyQfERyT_-G7p5gxpXyIk_wxIHooMNt8O6k
nH2nX3sN_3Pftu5grvcMyDD3Blfj89LizukGxXeaToE_zADSrCNC-4iwha_3OmolOW_IVm
}

