sprite $Application_Sharing_Server [96x101/16z] {
jD3PUSGm3CHWayE1-kyuSfAzBqcV5mNy3zX62slxNb4Oybkym3qStz3J-2_GyMkCpt7u966Npy6Xan9STUk33XnVzU0VD2d-zKV_a4d2fUV-0PCIIdhdGwxh
tlMtVclWM1ulVV9xi3XU6l5fh8otSiJ7hR4oFdF4T-inFpvpn3TjtjUk3_Z_Ue_PyIE-tKunENx0t_LfFuhAY07Vj7bVkEj3FctQJ-ZwY5ymxOTHn8XVPjul
AcB0_zU1EH_5Dk1NmQAViNtqPIxD-gbyxykzLJzZr_Arh_AjpwI_nUxekI_vlrNVxhBArXDVvKUVARz-MhMx9STL60Z0OqdTKYZx_L_t7B2A689hdArX_-u-
0LRZP0VtcjuAsOUFo_X7VtDdWMnY837uPckVt_W_IaQ4oYOW7PA-p2SR_j7V00IfAY9mTwgeYjgzJtxZrm9M_LQ17k79BmfyxzVqMkO_K2j4K7_n-OLV2wWg
8Y9ArBnL_wx0ztwFRijnUo7ygTyAvAZyTlhwO8CU-2RTxmj9Vr7WUrzZjDD_i827laRdb_wwm7DVB1RpVx20fxvWbyNyrmj8zojVS60vVvryUkGeuUGZtrH4
RIywpN-nW5Fl5PxvwYrOSHIP_7a1oRjdWK8-yTMbIUKeMFfPWActqGhu8ryGIVb-5EgTxnVUSm5F-wTIESbI0axzBC0FVt_QFzoHVdPWzzSR56tiUrpzFBsM
_OEZsEWl2ZYPyZdxYxzf1WycT_qJ-CKdwNckdVnUUEgWlxkMClWYP_-W78NTbw50-fSlUF2tBwdtjiNW_o3x1x7lnUzyQxvPVkPYtv-DAVSrk0t-3qll7w_z
K_t50fYyPZTvQRxw9HXd0ShWRrF_FFBf7bvzn4VZ1gRl5tQ4JVwbmEnhzVtrElEx2DxExUr7xLmfH-2fR-cp-SfBWGm6vUqRjbf1zwoG_bWWVIny8NcwFNTx
wDiN-jQ6nh47V_7DiX7yvHxd_DlmfcSmmYw-H6mvj9q_Hgw-XH5dWVIPvwUH039uP7pwullu3OoGrGAo01hl0JOVp63a2Ld6_R4AyM3oLrzMFf0-sVqn62Mw
tyyVsm_Cyryl8FbmtFWWuze_G7Eu7ow_-UopVmLOd5NWtBWjTzqNvqcmvEih_MK1de_ozOfmzFdFmS3Lb_3BvfLmlVCDsOcl_ts2jxuClaInyVo1h0e0e5Uz
yW60zHomiNyyNhazG__uxpu0DBtv3WC9-P7qUp2SSlMzAjXtJlxSeXLnT1-vNxOn2oJFvAV-yMFtjPzyyyqzektEvTJc40nY-lmGE0NkH_7PpmBduKd8USxu
oVT7FWI3ao-5kS7mifSIdtwSPsV89d1dn-S2jNC_VIb5r_tJ2vmTudb8wU2_2vp1u3RxwWT_yvkKV1lJ0bem_0p6fG2DbS1HSEFBsxVcBpuP0Lv71eEqRT4_
XRS-cazDVlRFMFLWL4C_-yVt8pZvMO2dBxaxWuyf6CosbIVzaxurt_lqPr_TFABntX-AfYzQOj4_Qr_iwYTlXERx5vUdehr_OiVIxmMQp_D_MgRTps2Okpl6
lfNqLTdxP-b7LGnr-jDu1qDKfs2GtLUBeopzlW1Kt-RHWz6VpRM0_10zGktZpzhF16nousloS_1GNm_fcu6nxoMy-zCZrjNqit7NmJZVFwhfv_QiV90KMV3L
zsKmyWd_AAtxT2BzKSScW06plWh6rA8_GgGVK0tClkKhISWKqxxwilJpNMCysy1LjSZeAwcNUn34PP0z66eJd_vqnK4v-eey37CeE8mX6AbtlYNWNI5ByEAl
hco8D4L5jerClwitVl-IdFq_RFpz42A3iU91VFomYkuCz8r_SZF5T5lp-9oUW1w1xCc7Dp14RdYiPnIKV44y6KOrBFIx2MxsvUM3xMoD4GUJ_ukxIdBDHUhK
FxuZb7d8V-NFxmc9dZYWqdVcFm
}

