sprite $Application__generic [96x78/16z] {
xTc7SkiW50HGYzla___X9uI74UZgBHYHlYdJaiFEachhx2oj2V6b3ZbXufpDVu0i3tmIXUWof_TCvFXZFF27zTBlsCUxXoeKAh_OdsGWAdeLCvFeCuT94Trz
cXLEFikal7mAay8gk_-Ob8_pGriMI0RAEVfyYF1b25SMbIqHANonCdg8gAGmO__rkIAEx-79rtc-rFsNooHVWQ_d-btx967tpUtlj6_tdrlMc2lVQT--3_QT
g-tjlzh6c-_xuu_tLpj7wpJlV-vlpoBhARP5clmrxcEE3u-GjdrMq3_pZW-IVTH_FH_Gl8_hu_PjVlvWq7_aVajVphxJFlT7zrlqr-pZTThtKNDySBSz_khx
MNVvfdsIRuuFnk_UHplwMsz_nmTtszJVzKFouVZjlgcP-hxFT-vZbdtBFkPnV-1dVSXFlEy_7VvEt-7lyW7VVB_vhuBAT_do01M2_OF4S4pbWxjrV93IXxog
2O5zkdohelVsF-bZFk9jgg_3_T7uz_eE_gvFoOVZPt-vJAjlC_hZ-kE-F_xD_QsAwgs-gu_VBz17-okeF-fBIzxV9_1_GldbtVu36VN_VFtUFly4Fz0XoqA7
X6_Wpzr7UL9izzbxhiRYomqfoWkB6yqdTv-gi_CF
}

