sprite $Application_Server [96x105/16z] {
jTg9bfim38LXB5rTOJX-_zVjCSGPuW5YPTA_-_OPgwuxsnH8JAR_bnX9fF-a9v1cHkf_uPMqFLA-halLMryVKZ8QqFYl3maaqFdV6v9M_SGdqfS6ZtEVrEyC
_iB_-v10WzxutWqfFdZLMz_zuo79hj_vllNHa99L_Su_Be0K7tobHvwVxYGrEdWH7Nf-gqk41oyov5Szw2Uh-fXlvb4VD94nl-f1NqbDWtxLOxwGI6dCDthG
JrRrGT_SWxxIfF7lVBX7_3RuH-zyc0TzQVh0yyF8c9z0f2azk_C1ra8-BKtJc0_Z1xxAc8_kuXpt9KqZy__SLvNf_lcrkzaYVagY2hdn5TRvmVadhSg5N_NE
PyG7DKq9C4Fdxzcn3tnntuO4CuFqFd3cC-1FvZxFTGKpqew-A3hVFl25j7csRGMwKsfDnyK60lu4Cv_DJ59IkllZpA9siG5dm4_M4adgxjdRmrzkm0F-b7uG
5L7FEMllzmj4_2afrEOz4S60pv2VH5NKpAnUTuAixnRma5-J-jLKImC-EUWVx_yDtmQa0niOy_tWLri6VNBCDxlonuuezIwgq0Pyl6JtiNvwf2BPBdmzaDD9
wP2q5DYlTG2s-RBai7_DAqnXKDZJbrpG-T8l8BZkPaw4rKLPijpxPXhEZLJNRLFBjaBlwy6Fj_cIjMAmjIoMhdrCuNPVbmTakPI5Uk5hajFI2InR3rzGx06P
ULwMJ7lw-kEBuYJ52O-QDbzG_E7No0iV_eZEPpZppKbYyx4ji1QxyBNpcpxgguk8QYwB3VhEjxxdFC-s--hLhmTquPcllSyHVtxwatd5zkEJsNovyciXV_Ab
ASnhMRFxYw_Dj_pJtB8xdvi_vHN7yxFxSkVF8NzYyUvy7dqD-vpdsNSVLdy6PRNUbpE_v_sThxw_0fRh2XU-Tluyu7lp9U-lVqakgx_uSl3rtFS1NzVswfSj
PSsqtxusl-T7VC6Ar08zEt3Xz_orxmTVK79wLk67BvtVyoC-j3fBGUDFVNtwSz3Nl3bULltz_7Bd-vZVxhTwG2j_utVyjMzRapkfqkutU2dPNdtf_8xl_BxT
5y_FIyRh2NLS-1q_weiNQ7V_97bqzESFVM7ncE_3FbWHb6BdlfpvFkuhiHbULexw7l4benhxyJdnvPVlCLyMR3x0NChYkzzj07_mjL2VvyTpplxRjwVl7lL5
rmNz-UaNgFvPxtoW2hduMp-9Ff9ZwTPlzvkLmXU_Nu0wXNC_t6zUYb_x-DWNQwzCSoshi_d71Vxa2vUV-oslwvBzjwz_y8N5zDVvaOClcwzxIVTas1ShkVVx
3T0atDDNhCKx_tK7Plv9pLTbAMu7lzi0j0OOWvdkFk1hMVWw__wM0saQAe7D1sn_yN_tkmtikaxXZ5fhVx_qn_tMxK3nwRkhGHny7EPVQxpHPFei9PhlPkQs
-t8uGTreWWc97p_BxhSHNUYXbBJgrzRTRubU33w-mbOccY_rozS-OaP9zl--1aOJA2bhLlscO_fgIhhdlFc1mGS2MVt0u8Cbe-V0PH1FoD3Wuwcbxq3_
}

