sprite $Application_Sharing_Workload [96x96/16z] {
jTW7OkGW38LX2-azCPxS_xmBHXvWN5Bttrxo8J2fozybfcdvVnbBzhzq9Rr4_1SzeV8rwj_h0fY5x_mF1wyf9MNL7mzFyyv-cn7GmgjLllX8OyHlytLTMNX3
uQi_HF9B1tmixKdYkZvfXkPJjyoi_Y1_ns-_u_Fv19hlgB9Qz1N_KezK_VbqmF1mKnjza3_XfUDIUCFpkKALL9rz8tyrlPIgjJxNOcflcD_y1rdJmuS_NUc7
kFb9lbizSqqI6SnNasFMVBLlDkXnFhJJmkUtKXtv19hnlF3Jyer4rRekHfei5ttVtmv3NxgII4lljtwg-dWqr2MwzzM-a5ffqgqgCf6zqJV3PsswZWSF1NDh
pMuYrGTRc7tmFjWql9A4vwcLrUVUjtmx7ateOoj-vjl9qUIpLl-13pFCHuEqvCYZ_XpYhxxgmm1qFP5KMT3rUO7devHhN_CtNGztqW--nmQUuVkzttNOTF2o
tFiVXVUl-G21-KvglCFXbV_yMD_cbyrdZgRt3O36c_ka865Bb8O5vl4_dgFFtS-FkGnMJqGDLbCr0vOzHuWTR-D_VEHwFdxlisOfLJpILhn3fXF1zjRAVzJn
xtq7IIHHeFkcKJiVqWdIVU2hVkltew6cX9hrD8gR17Y9fBVoS_Sz--0Z_75uIy43DbRvzcOi_WdSGecvpt_jPqFLWmzbB4--rimC9Ju_ztEWoT3hE3m_wlcW
-lRkjmUGh_tWIHenzj9pvb8Al_9z0Re3wxFguNlt9zx37mez-tBjWqwkLtxm9Dr1lCSS_BNFd9sFIx_pJYZclE1GbJlVY-71y-0FlDFK4EsJMIeLNqgtVZxn
opzzF4Alavg277KjQlDhzds_t2pVNzyTPcor1P6aTl3jnNVVQtptu-O-Seqmi0IqqrAHy5Cx7oNw0jPy5Z_JSpxrrxNTqDrdhNXg5dhuMq8sFme_cntyj9__
u0C8N-Rs-PkFaOVJf41RFFU3z-fNuCnl6L4RU3gbGld6po-Vf463F_65mmAeELq_yVFemtZkonQ8AJfVRz9GE_gXty-lumPcth4iwRKf_SnNwCdvGvQMaIFl
Z3TEGxEVttmpbHF_jG4C2spylP_VVUgPJrlsGB9FNm1FrtuUQpx37tabEcBSQdprzOi-cy_ZupLoHqGHFEFsETzzl_Fx1hhlkoy6mBTomSE7VidtrmRIp6ls
zW0K9QjurODt0j1l-5xCaKyiYCRmC6VrS-EhRmR0z3FVdH6AElXQ64-IqCg8Zss3XrbRGJxpFVoAfT1BNXmkqdHrciS2dMyhw8tlM-5xWoNLZ6NG5BnfraGl
pNpVGlYSVPyNe4YA37XaNJHyPX7G8zeO0BdozvhldjeA2eBrfLxZKsA1hayBdFhUOtjlxD3IwwlxqlZYgvII0PRqnBVcw-3x4CaSrzfP0aj8YuQFBAyclZ_a
oM_DXzDv0DmoY_7fdM-z-nXydlRoKMDR8tndvoyMw7wo8N0lRtup8v9n_1ZuwCt7ony38u1zV3Fk2m1MVJtw-haVF0BRVHjyDZzr_ce33F-4Z_ZorGrRkn_y
dO-3dpeVsiuh-nFuYezJF_WXXf-C63QWtdYxzVdcfv7l70eloMtSGFFDRERlVPpuIF4cUdu0REENHltU5vxvgDBimmnj_2Zm7YO_nGIdFBJvmmCEVrRFVHjy
dFj81nzM5xtbHp-wyY4ryCtNExxxj3rU-JhuR7uI-PI7amQ-XKD4zMto9VnRtidnRozzLauPVAdwXdiThFv99pwhZ-wp-2YTwn5BIozT-U5fvnS1Tke21odB
tFa6Wgm-8sdJu2vYUG_SE_AqxiU5Ll9QPreE2Nk37kq-wlItAv3e-fZo9cs-BcC9nzr2PRd8U1sq3pycIG6s04qd-DTsO61QVfk0b-do5oNmD9FbZn8zEVpb
3uk75dT3DVqS-WS
}

