sprite $Archives [96x102/16z] {
jTM9bcCj20HWgGBU_ut_9OpMkKVwnZkTCFlINoce6KTbaHnVh2I_cM1fC6PyquSPqpzlkrlvW7rX31xCOFc0CTC-Ezd_CtBw-FWOqip6SFdux1Y2zaemg7v_
LYt2v5V0Aq5Dij_Tfza4zs6cBNnc30mpYrS2e_mkmN_X0_Pgiyd_p1Z8bp-Rm1ncgai0rXWiuZ0g8j8Pka_ojmHoDYbvEl5yFSQn40jJNPj4W40r4GJJZtop
GJVDSQyLG99Wf0T88j9FV2tnFe4WAo5VljrCt4plWHqcS5LjPGm3-p5upkIW7IOOg2f_3FHZI9jNtdreYNOVOBpMQ-L497T_NddAVxG59HWr1ldpoZFa7oIG
JPEC6eDbXfKF64FtgKiu2405p3441pFI9a3vsuKbYSNk7LAJB8A8-3FPCJpFxXCuNKMnguWWSft7OGUdVTsdgGBQmHv0lfuyvzvcwmhW343vOq0zwYfqtXzT
M1qLKxkQIjVdan8UtQVxX8XXyUG-DMTnt8x1Hye_63Jx9w7VWfCf_sWBO9T0cW4pGRmpwq5k4mX2yBu1pPb1lWAmhpze1nSMvCy1O4JGSDc2r_hhW3O9wq9X
zUNsf72sb0fmfXxaBK7hAtyOVaoe3bK2IYzV5w0P9RRxT7CMgMF12dZvbftVCVRkj1jMaUxb3_c_lh3oZUxyuzjDyKc2qvImrXzy4A0deJljtlb-x6iBGUmN
rYy-b-_ZC409wpxXmdU-3kXv02E2h452F5lVtlY6D_TfTTyTZQy3-cWBEes6MlxLnu6lui5zedo0a6y7XVi0ezDRNnVWyHQSbtRB9qZvxdPMUm1KyW6G1AVF
4rzdKVgFFgz-ZFTy1TYL9rIKJuAKRpcEz9MWWCudM5M-3kXH00nBzzO7D_z8tpwUsFdYKVx10HMYXEsyJv_4GnyAwCzxgVLdhfBlViohdBsl_d3wZEUyQVrb
ba-gbczvpAlOtAVUlpz0UEylxhaFlFT9_EtwOMzz_hX-B3_uZDVdaxfpvxi_vLc-U1BJLqsVlO-Rqdt2WH_dox-_hxrl-PWdk3pTLz0xVoGVDh_nIQz7LOdB
7vuyvE_lQsLS_Qf8dWsN4-tNhorS_M4H1xfUU3G-w5xVrNyLasUpPUkZ_dn9aAynl6i-Rloa4ZPVOvXIZz_uuKbIOv2lCOJMppr079lx5AyLSdL8leh9bK2s
lCxBxW_BMF_O-3K6jQFfZtpIDt-CEGR8tyPGcXA4YrjjbgyLwlEbAylGKUSCwDy3tIU6nfWavRTZ4Cc6Hwr_9SXNa-JtOz0M21AxlnAMh_9CxsLjKargofdN
2ol_iAWnz7u6bV3GrnYMj_c3UXButDSOYlVcyqzFmbDVOrYW--RhIMZyyoRjJmBArvFG-kTD8brDag_J3ldFw_hogZ_wzz_vm-9o5hVF9ulcFZqT0vKmVHKF
ZDCcELt-1yjJM_YOtu_XExx6mE_u6iDtV3q9N_Br943-TyQGuvlbCTxLlm
}

