sprite $Archiving_Store [96x116/16z] {
xTbfqjim38DX4o1v_njtiOAfCse-Imoxz-t_1xBbxiTtCj0ZyYp22JlQ0cEmuMSHvr8G7RX_fTp9v_ny77zpWi_sl959UqldJVK5IB_9Cr7WNVfzaMwRkaMI
u4eWc6dRF3PYx0s8NszhmCLlbB7Cey23oLK_0eLyzGrP4fLM7u29KXvhVZXACTVyPDMtHTyg_MZVbdt_qtrO9L_sQONu6_aiy5i-j_bDdvlyjaySonaBFccB
EbZpr_uK2xBWAriuUyrNi1kyvjzio6xn5SwekdtrtryCFzet_4WV00m_qjT2lm_v0ApVj-C0eGpjljbX09IXtV-AFIrueit7CHOCbo9fZVwym4pq-3pzQS4y
0xt-_9BSXWEq-3Q_97vb8ZDHzaszkWOau1dMufjT1qxOKs-hmPyN8XC0mKnMV1mt2oH07WPcekZFuHhnzUYwXZsVmv-xu20n_YYZQsZmxQ4FdhInaCacNmF4
vSzcq3Ki-_OwyUfqgMie-lCJF2-4andhFewFV4fN5X54ekJFWLCUPBZy-WLh0DC0oRG6NmjpoB0kVrvm4f6swD_OXcd0wOxm5jy0Q47ykS3iElzOu2LtN_Tn
fu_q23v-jFZYjQ21wVpL3mZFsHXm3Z_Uyw7pNxkStnVznTCh-iF7UnyGNWoOpdzab7o5LybdUla3Wk5bVFX7HDatm6vzowY-84pD_kh0pQSv9_ySy6rV-89_
MAGNpWzRy4VCy4qVQiK_B6uM9jqMVON8ZoQmUNpGvIkZ_ljwoiEdkrtrv_z-Z_1BCVv7Fhar87_AG8-y54xO-VvW2WjT_Jb9nxUOiNnyoj_9c2w-SFw5B99B
7mzOyiSru7w19L_NS7zw0gpukeRxXQglQ_WGFvDV2PbGd0RE1SYlnNGepgUNNyyyURrFHMBoQo6IuabDTPrVrw0JQu5jlhvLeSwnfHfyNOD4wNs-ha5alwzh
6BnJeSlNDGpUlTtNBnaFthtPrpM0T2t8RumPMZW7sEhh6ZXuzsvVrq2z9Fcj8RNWcFpUQw3yvip78yZl3v7JzzD_3PZyvcyr9xypSxVF
}

