sprite $Archiving_Server [96x116/16z] {
jTgDakCc40HWw9uPB5Vf_L_tZAok5GPZRdyc_udyDR2z8ibT-iyno-dlXl4O-oiT7lwOSFo5dYt2ZuduWqDYrJM_VaY8SBEB_wk71A_wwIlWrmufMzKx_xUQ
n0YpiH-EtpduiV_pGyeURkJ4_z4XsQ7F_5A-VqYCgFhSVypt3WbUzHM_9l3_TIVN_3g1_pruSiMFfov__U01hgu_NEjVFdXWsQ-w_CN64yl-Kr_tJVgQxr7a
hn_yikzUD87LWr_tfQ_vsQIl-HPbrTV1vxpiwsWMVKPO5h_Wczmb7rxrEck-HLdqTVr1_89l7l_ZLptblBf-iwYpx4Sm9_d87toZnt_wXfGMrrzrpR9F8Cl7
rATvVCi7LjRFzbvVzUr9ORP-wT_oKyge12Rhfxbt0Oi-cLC-ZW3lV8uknbZqKO8vurWYyyWtuKt0gfzAUIPK9jZxPZRoby_VIebxgGd7fwtrhSvu0uj-VZxg
g0drJrq-OVPJdodXkEdSMTdwgPiVFcWs2rZjPwAxLvzdmkssHGtuuCVY-bFcbr0JoctRDbP_7h2w_Xf0qvL7WANw2njOMt_A6HNp1xi5KmP2lkQxlkdr3Bte
dbVcnfKDBA__6EaPlM_VzCs-V6WZyjSsCFTl-F8r8z--wMFBlK_vInkO-xpdoVed6rZqOJl6_dm3PyXd7xvRx-F31XomHH-sRsXyVlAz-e1_zhrolE_UhNzo
G6JrwqHyy0khpxBldYT-6v1IDcqrFlMJE9HjtylGP-yV7FJiftuAUUpX7ZFVtFZbfwo429lsqwJuxVx8k3dblmOGgBjWIaq2uncPS-_NWBZUv55An1iVTSmj
QN2ErGH6MEvz-BvT_GZvRK2cIViIiX8yB0WF6_SpFlgyOFd47tDD044FZliPhTy7N0_al2cU2GeWo7H-CUJdIpzlFlNR0ydYwoY0h4kmi7pwJBYBgFqi8VyI
083ohmcN4K-YFg0lG_q3zuF_wkTMUhyce6jD4q22IW0zeFkNkm_wgO0CYXD_-Pe-QGLeKdOoe7__mNwtrtxAnvlMN0B0ym-NSQURxlUC-rxU-3p4Dg2xJf5U
0unavA_xtVUzjBu2-jQSemHjCkEQO4QF_7M_ewYV0xyEthI6EaRKeVWZm8xt9yw4EDvjylLudhT68hCIn9inTB-VmtZsqnj_sXfIWqG_glRavTS0RxzB3Bv1
0KYprk2bDHAqVjtl2ZYdyvTRWsDeylN-BFfmwqF-kzRWfJKuH_xbVX_x5F-nDKPh0nYJ-rr3lOY7hKbDQuvf_Ev-vy1lyAurfqZQeR3rs_kzFFgv5R_woBq_
RasxVbxw6QHTtZ_d-rFJyzFMo6_wsRq_fpwQ1ADCD7xRptKV6PTQ6jcWfbw_zhCi-j1SMqCyHpw9jfzyz7FpjVMt2SRU9ubXFs_nmSVB3DTF-QD-thVRpEyJ
Ef_oB_ta-tus_60uz9j-ZkztpPm7A9-W6NXEsyyrVvnm-YGxlppt4vD-Oh9y-JRmL_k96T-tflNLJtRzx7pCVGvzzTFUzbC-vkjdvy_xkRv-jZurytuk1x1f
fHaLGVcJVcecVjUQ2ZN-j9-Q2T_wi6DQl-_dqenQuwGImew0IJyN-CuF9qy_eGRmjPzbx7F0zwrnio1F_mWWv_qKvX53NwsHd-17GlKJmiKVVlZuV6WHPFXr
AsnyC_bIgv-oX-b-kHNdPYFVplz9Oc6InR-qflh7W-wHzAVoQ-gTyXizfsEo1I6QNMkghmSTBpz3oRnK7oy-FSv7zJJG-M7F1FcQ9g6U_zsizIs2gHc6dwth
MYD_b13TzvSElXiB0mzFFgj0ZdsTh4O-g8CVFApMoJ_sHVd3WKMKKg9ipS6FHYLNQwYgHEltdwe__dBu7i4q6SQbDTI-cER3Y59z7VniJ5kGlpIrFxRsCwko
1ob_URAlw3fG9-Kl3vOVLskO_cooXGNJ7mvypFy3
}

