sprite $Archive_Single [96x116/16z] {
jPC9akiu34DDGDJzRpnBw0pgmrMTqZI2BExrFJe2h__2RbxVIszox-yPDe7YxYyPQWD0mGnX_cseR_77q4a3z-uIFstW9l-blVWoi7T7-CrNzNSFNuPGMJUl
gklY5ZzgwBwgNWOeCZGJ_36KuIFhmE7BOFdjEd0FtmonijOMFcjGWSo0fu5Z2F1r2u6oga1nW_FF3SNcKK4_6q2jG-tktJmggF9v7PhwxcD1Jmmzp4sGyzsd
0edeaS0DmwTy7mfwP63l7Zv9K8OF1JeoS781yEe-2tHYuEi9tFnBXgC2-K4BJmxxvhlXdE_tG4fGqq8P3Wfg0XlV39prEoke6mZm4VnXg8E2UlJPc658TI_S
IK5TG4hmDC0Cf_mo-DDmBznHWPGBBd13DmdkNIhG0R-A5ZTqTo-YsmgQ4R3wtv3OTLPG1VmnxnkWyME6rKsIsmgKD70HcyuF7WCNk6a53Tt2cWUusmeQCQnv
aq05pHWMrpo9tIfGn32Jtv953hzP5JAiDtgz-FjJWSwh94MANx3gtC_Xgw090nTlnvklWg8AVe6-VqBVZp4C-1xT-5K0K2YWxeizKF0KzBWDcf_YlmegwkFv
bDbVwnuMbo9-in18uJsyyxiG4HG6RNps1UGDuk_XPmnyy4lyX85FVXM2SVwr-Lr-H_drv7UKJ-Vps_neWS0r6VuKj982pQ-29WKs_nHKXk3yAcX1Xk3yAcZG
G9j_2fepqEVdlag685y5lS7p-csUVE8DJnZyyx_OReZDBmFC49bVuPQX8WLzysLeQFmmtmr9lb8wwD_4-Kz3a9ytY7zW2FAr3WfZVAs3mZC3F_9LLXd89DyD
F35yv4-AcpTTXX1VLN93aY_33IT8nlXkaEM4dpVmY3_hm16y3OivlXPE1lveEELh7NJ8N2l6TmF09KE8huEc30G1saFyaC53uvyQvdp9zNgZH_p_Ro1kmxm0
wcdyut0C_DEW9_0BlXRkXZyD_1LVPQKP9iQF6n3Xww3VS1a8YXyoo6Byl47yb644CX36Jnl4ZuHk2FArS5HPGV5ZXgOEslXnW_7Z1mtZXmt6pnkS7owhy_E6
tLcc6tZz3G
}

