sprite $Audio_Conferencing_Application [96x97/16z] {
rTSBbfmu38LXovAkn87zhtSmrPGneBYWw9d9dtSu-RWyadJZr-9KGgQFolluBAcjFgK_HwbxkfUx-Pul-7tzw0j_wbF8r_ZeVxgV-dvx-_deY_r6rLUcv_Ej
Bu_7Mr_mUBBrStg-lz6djQCldzJXi_p4VFJHJONgnbgTp8fN8hVzkBvlWC6Usg-_jryZtu0uwVespBaxljXFGQlliMzVtP_gsxtzyjL-Em-6Tr_j7_RvDflx
n5_umE-T0EVt9pEpPAh-S_j9u6k3oQNz7lZqZitRbZzbTiEta_tmO-DcFrg_oxS-cPyrZ6w1t-FR-uFTmNe5WT_Zs_rvTwoUOVBlV5hIq1_7mE_mxNxTyzMV
0h_3jxvOk7_omE_mZK-ennj-cAPnv-VMzwvVKbt5YfV6sSVdlXryUgK6jPFNVvgpm0_uOByQ56LwCxxdjtpePrKjkc79beQfwxTynrSLnNfGvxhx_Qh__dn8
IzRrOxvzlbBvaeXelG1ewwFuFRxTpu4_ceqZSpxwFRxrW_rG6yOnbGv-buUaWy-jh-usJFdCTx_YS-lpZs_8cKSilktyeSE7VjqF9ShPxTJlyTMFdsycekpQ
-jpu4T_w-TGN8b0USyS_weVzjFgovPd0n6EwwXlgVg9CSrfF8FBsoo6Ns8_vwe-3KqhLb-g3SrPBeH_prNUVHi-9TMdBspWomrFWnxmr_ZWERfprLUM7QG0S
AV13tj3i9vzv3AnjvQhCXD9b7pkV68ff4DrausWbJg4VZs_z4cN6D5ZL9rSpSvFO3zPRwzV8f_8Wp8Tn6bHVliQ-0ghGFxNuz8vdUcum_U7TBVHPJcBXfjIM
TQdoRXJuzyfLDozPVjBFehRLtKpfCPz5H6t9rmmgz8XFKghukbyLGj_xB2NrCn_WnXVaUpmxREx00yfTly-BEbkfygiFwCwdN6j-GI7F1b8hRNZ5MkjdhX5n
BGUFLeHTADixh7oDga-Rsbz5ymLEHDpeZM_G7r_obQJUdhai2XMM0mypyE8hccpvPb5OVLTQowUy6QZu-xG9k_JjCwsf1ZxF_iNUAvpM9E3Da19TYgjlVTx0
wLeP8bf00TPJjdphwqMVeILHCUtn9TpnIxpwqkejRw1hlgw9IPqVyWQ-wQ-lvr67FUXpnA_fHH_wIfnA1ntsbS-jp-ZmXci-lNqhliPyxFTl40014UMUVjsd
ugo-T7dJTB6C9LKYwke6JlTEeDBEj_D0wNAanMUYhcxGT2TUVAvu493kHGgcgeSyfRjbrMe_oDUuuqFJTv42iQwv2zm-0wh-PSIAKgNdb2az6F7wlu2gyjx-
1m
}

