sprite $AV_Conferencing_Server_Role [96x115/16z] {
jDK7TiCm30DGaG0Xk_S_S1_TtNXG7dYZpVfGaDK6uu7sN8oImf_Y8KM4n4TqJpqZ2VVhaVndxX-9gVz44cyUdlpZtpYIB_gBVzD87gcl-XBl69xSz2LS7PxO
zHL-QNZWm9TuVdZWqE-IS79uLFpUJuo4HI_wsJ0wVEfrlu_ujWnVznL3FYMub_tK1tn8TA_xCRIFBthT3_K1twXmh_iHlTVzp-7hVlIVg3XDtG_r0Tz3TBEo
dzFK_MLuixeVwWC-99ZLVKe3laiqg_iC3VWUehLMzwcFr7mgl2LVz2aD-MBorVCZDEh3hNf-CgIVL7s7bywFY9C-uEt8J_sbeEAtbXQnwuDnrlUM3Mbi-i3w
Bql9HwSr0nb1N_N1kE1RxvrcXeZV3I_yMa5f_-XTSpOmGeh_FddHTqdpt94Dok37ToxPybNn6wN8aT8DgNVXmtVmrOzXto8MVodm_7Vgy4_zu0bK_2nW-loe
Y3vDymG0gtuC-ysJw1zXDappNFDLyfkbblURvxTk3kZJFoWe-saw647Foux5nsr-njtCMdln2mKb_qit1pvzNFOvlVvylVZ71Ti-jUVZik-AahzTSE3x73i-
hll-DbLyRlawyl5UgtseEQh301JEM5souVtVzieOY1DIxhQJBzFdDuirRCEZNFrV-GNmst3pTE7llggPkVSNtzg_LDFNpQDMwOqFfy-Yvc6czYtUlpHzvCr3
NNE5BtvcwOkPPZQdKsR4K80slp2NmTZI53xvbCauVlrK-dJBXb-S3qPYgKhFFZpxOlehVd4z529MZp36LpuJimrVFfL-F-bq-11n-1dtQFPXtj__wOyllS-d
_2jVkW-y1BttuVTzG1hpQMlGDx-_63u_bwnkCVE-lsNpRqBfP-HhrJS-R3xbYp6VAfoFcLTXpSnDXfyD_sQq4wHr2VtkYoaW8p3JNjeisdFNP_ydv3wVOb73
9Ftol81o6hxvmZswhw32eYBfXtMV-vh3xmluTJwl_ho_V4OP0Z0B0r3w2W_xUyj-RE6h_xZ0aq_2cR8AYn2YAaFFGnvyv5jlpEStFwbpFbLDLImJGKHpWLxi
VaAo-OJZpoI-1Z_wZmlCynFvmkruAc--0Y3WqWGUhpy2umyGa2l8UnyEFwhNiEQHjbkBLCHHmz6TULb5mcU_EARVAr9pYSal3_uupgMcNrlprjAFbWzXTudm
BDQ5lLRXvClkGwNqHuKjmetnweEoHcsJtpnVH2v0wbQhgtbRgrlwvdQ_la6rdwCoWk6N1rzz-9Q-MryWRO_MY3NNL4HUrd3Q_AXnltv6WvD_wvlvUVpkDWxU
tQ9Hoj4K0DV527U_DJ-ldx86N8y_ctqXOj_ys7nFlfT-rYgYh8xO_QxIqdsY3Q5OhSn-kVgCAKn-Dbu3064ixcr50DZsDzly8ZWGhcjG-R--g7XF--inNalu
Mgz-2JokdzQQqUndaw_C4iCNSH4tLr4HXfulBTQ0uMjwiliGVBz-wdPm-DAtStv2jzpogSeP4RTCAJlsT_X9DBrUFylHo_cfhNvgzZE8Il_7Du_XVqjCpUlc
yqReQk_ySlgyxMADg3MUgz7NjNoAxllxC_pxVD8Nd_gBSVpnQW6jdW-iZ_EZSCwdyzNFxiUFhiFtQttDz5tYEFxBVFhIZD_xbafxzcrQGACwXwTleXQx3vNE
-MJBrTqa_QdB_8GTZJMsFDp3nVqwdtAPpqz-JBuDVnJkfcxN-Qo1d_no__cjwVixlmzkMFSrBPtcqrRzxXE0-l3rNl9wbBwfFimFuvZFkkXxlmoV3MI-Fen8
puWWNxwUJscBVVOT0SVykxvEQWnVVcut73u4R25oh5NvdJzVtrnUjz4oxUzrFliEgJpxPVOz_RTT_OADB_FvD_s2rV6BNz9dTBPj_fq_jPz_E7q0N-IxRmpR
_FXhNoQVRzda0xSc7_q2oPy-RV7z9QkwkoeJqTNFK9UcdtrbENz-rPIcpDmyCvVDLoBIz6bRO9zFgMjSv_DitbzbLE6JTwy-gYuqxU-jC1v-HkBRvVExhyh8
IhWb7Yrsl_g3VmF6n1_dyvslveS_6WiGIclL1TDF5Bileh7vjy8q-_byTtw4gT2OJpqY67-jM2hdAussCapxUx_ROVWgX4QlV22JShlHs5yr4yqNQWWPhclT
35ykVePCUFW04ENg8xFrh-RJj-wxIQh3xuIlT_yd_SijIjrl5pzrvFFFFvPBH5_0mjqwYylQi1VfO_fcvdNubrkiJE3H1sOgDvxcvqlp_CmhC6NylB_4d2V-
btox-bb17iq-7hVti6Rs_zg_LBf_MKA4YUtKyMSVWj_fTgamRvEtdtWk_-8snlIX0FLJyoz2PgLyWRT_L24U9_wV1LJ-1lCV
}

