sprite $Bluetooth [96x121/16z] {
jTc7mgew3C1nEh9z_-Sza18nWjz1qV_TwzUI5kwQpbTX-ccL6NxiC_TV-bxxiSzKV-XxM7xeU_1Zdwd-rZ__27Wsuf7mMZtb4pFJkHz68i9CIrXhwp27202z
rRBrw2Ey4ul8__-ISiNt5KxwB4BuJYmZnbE-gCg7qGc_Nl3z4P1u9jHqTfZnsMzNV9dTnswtcsBs--U-xraND4LNVKwRt_c6btoUYmM4zM4uwq_65-RF8_5O
RwQ1FwpoyVtXQDNdsFRXX_UVjuHb35uEVFh8vrISgqMBeWS-gtwWBmrVp5n0c4FvoCyyfNl9ieQmfCy-YRx5arZmsMTVW5KLay_l-CJtUoZiQ-IlaVkGVJdj
4-ccCqdsXOVFJpwVviNMn1Vp1x3ymHPLUlRfd4-wwihE4vdDFiiMuZZex2EVyODN3fxqsMSMOTZvo7_Oz-tVd9UD9p6_G3dS-u2lULNXqU8hF_34PjbN5O83
7-YLhoghhpiUIVS-7lh72x3etIURo_pm4wy2npxG2px6W_betSVigsxxhyy-q36ls_76sVASyoYphsdxGZ3Q-K27VFWSuo6M6MNtMUE21Y-yOcNd0ntmuLFu
HE8ZuU6R-y4luR1exmFoCH_V1kTv_3sBQV5byHCVFhVavmNO-UIh-_xIYecPB3v9N53T-PJyY8FFFethGxvziIL-zYNxt8vyeC5BzE0BhJwWc8q3TZ_AFXtw
W3msD7vuz9d6UAJLqcNrRVYwzxaT-PY_Tk5J-3UPVQ9YWWYhduAxZ-5ddeXun_Fgu_0RcY4CF_Ey-Lp2J_mIF_kIzj-BlVBnmU_XPzxZxEiC4X7oZK1QmLS-
muDFoNSUQVk1ZtoZMagrLpu--fnzHC2jyRezNl_55nF1Kb7CuC0dI7vBFYJUmy67Z-vJQRMG-v9zXkn3zZFlqUOB8SBYpxWK2TyqxJxv-E3Z4G_yuEFmiJJ2
PZlVdUpJvYD0uhFlhzVgrzwnYWa0eDvz9eITpvj_p8VFuRD1aLxR-ATajBcXGvJyIdpt8V4l_TAi5J73HN4_jdwu_nP-wgMFDn9fpSpwtOTKdlySdF0bVF3l
WvX8Xmxy7n-d9NZ3RuiF9aPdV3Zb4v6kznERhCry1rryVkstTtpr_QE9rthuzDgV_kVZyD4XlrdLLXvwn__u-8dl3u2jpz7utI_zUjgt3IfeXhKlyTy-JP_u
lPJIkYT_-_LDds3KEonw0rryXHS-JE_voX1rz_5F7wTtVGtSzTR8VJdsSJhZmv4FwmBoXp_uKNrLHqe-1k_RxyDdEWYcKnLCFc-pxws23dyVbUaZNrqVVAly
mgSsdUxHjmT_higXZwv_wDFGdOVmFyNTf-7hyEK-dLPe-7gtUvtUBlxv9tm8lXOPlf3_duktvUpBwlDzF3ryd2xKCFaglGs-qEepNF7hwdFuEFnIPVMfVyEd
yCNvEb7usAxuPUVJuazDLb-nNk3p2-2-z3gBF7oR_NB91thsPHu8Y5ozFk6Z-wIRBqHoz_cYtp2zO2htp1QVu9fVLr-ox__bC5sVYnU8aw-t9RjuVRnyGSS2
BE4Bbei-qCv7P7FVhy_5UXnm-8GT9Np_-dppW1cXJ2Zcvsk6_QgV3vYnBKkABWjSFbuFQVF5hsCRlbtzEkI_nIm-u_WziYnm_UlWDGm_tbOCtt_xMmUiYz_N
4raMYBVtQkupSUo_3ryj7U_r0uZv0v8laCP_-G2OR8055vyNd-4RVbtzTI0TaOXPBBrTrm_0HOA2u0-Gnd_v03mV4BXFiaxhomTWY020o6en_kkLuRifq060
rDBuBuPqFm2Zte6TZ_5VhoDxjYIkn_Y_EY1B-SlyzG5jOVsQtz83fF7yR404q_S2T5-_Ffxy3U9VZ2SU8FlOfnyi8Dlso_Jj1UZX0H2cRzSGcUL7s_Vw-1zg
Pefz-aK5a3LDvoT3GYpJp-e0vuVp3m
}

