sprite $Branch_Office_Appliance [96x106/16z] {
jD4BRe0m38FXKMmdAVU_xvIzq11lWW_mjVhpSMcDxUEzDShqsWi3PMPkml06FwPE85_06sbIpz7TsAhJo8JVqRto30DI9p1FRk9G5LxwhuDarHaQL_HSoHc6
BJsdfsV8y1BM-Pp2nQ4o_78MBfI6Nyx3D5Q6Nqvn_T2GIEppy-pY6SPBUiuldA4n-HtzqHc6MxeaYp2ssl2pdZi-moXUrwc_xP-XKG_q-OLnC_nJVUSCIFrE
-BKNyWpByDTrQcFUNLY4BzDpvltt34E69qhIp3EB_dq6KAhMqpVlaMS0L_JdV2ucrmY-eoSVvFB_XNedCFkrklT9m8_FyZHzSW1Q-AWB3y0cN_f0IPeWe3wj
-GLwpomnJQi-dgRf6TxxjExd7kcPndhVyt4xJQIkwFl-VLrawWS-xgK99wcf7_cv6vztaHPspaVArBKq5d7QnoZfw0NxIsEIF3PzhVX6AiSpQLBFdU-JFfMp
8zqaYzZrXpK_f-Hj9usRoJnM_Mv_VLhxp__wJ4IoTTxTFskrhyLeSHWAm1kiol_-xxlZeu4OIvx4MqxQtIT51gKm-7ppv-2V_fZ_qRAFo50XwzRZkV_Jv_Dj
ny33lw9cclIGzG_uvBldw-Ukm9FFqMhMuUV-eSy-qbhfYqYCUj9B7_ho-c_Wio_TJ7pXT_xZ_TLI_uAekLlexeC_ygT2_-GpjzPzoojE7HNYSzs_GF_eTvnA
7nL2htrp-vNFr9fb_XvIxTjhDFgJVwb7vYFGd_wb5_k79v-lD2NwhO_pzjEtV6EcWjVIXxxoXIJny9NfbtvaxRVIPn6cYS_-o4_dgxT_13_vB2hC8vzzw6N_
xXO-IsmUphwWmYVV5_Ff2zhuzl43OFRVgF35JxwQh-QF3UgtZnnK-g8cd7peljZ_3dxokGzfzEMEeO8-V7Mlhn_esN_l1OwGyNHRlNqF7lhau_g1Vfx9lzpu
5dJoCIJvziqNrt-i_z8VAwXxlhDCBjzT3SdpXvvz7aADYSHjyXKL7Fhg_ZNmdto4UiHrv15Nj-N-Dyo_zFaP8KHT1nw1NlfOq0kVvn2neOBfqrVNvD_wbezV
7ucZWdxopL5ZmnSYxZUAe8Bg3_wz_iyj7nMO6LxsuVwvUo_xbzANxdl4KA7stL-6-Se_DVnNrZugYAXClgBxrvkRbVvfqlDN4-J12m--uogTV0od9yydue8q
_7CIkVdmRGmg28_xhHlzhTp_qLBy3tIga7sacy8Sle1y3S7Tf_q9tS0F_yDjCG0HyFW2rFIj-sbO-Yp2720aB_f_ztAaHuoeSFdwY8La9gmUFDuypTyDJ2iV
mAf52OvB1f_m5eWQCeWszUy67gF95HI0md-63He_TRV9ZvFYO_s8sdecdwcr9kQk96f-hdpmIP-EuLr0-0grupWQAbo-tL4t6_NyU2GFoSnLvD8FfFMGLFvO
GDFWwmhTfsXzy1kzVRqZmu7aqQoFGV0t_TVNL-LRwPkqdOURzCA3pxvSWV_MQU_XB1yeyDaNDaSm-AqqfbN_oi8HOSU-kGU_NQ7sUVGt1ZyV0xULBmAVt9NI
Q7QEeVPHW8Zftxv4eGcNllGGYoH-DoHKze-Kbyt-CL3mS_-y6ix-CHJpwVYo_VrZcFtsxyIykVdR5w7_u-LN7Fx6iUuUWuXX3VzF8M7U6lp-a7O7_pS
}

