sprite $Cell_Phone [96x229/16z] {
h9g9cYCf38C3Fe2Fzt_VxOAuAI9mKxFHz7tyacL8zfZNHY6ow8-4OtXzNK7q9g7mNJg_kIBcmrzqOCjiHNtL8JPwdEQXDWPzWswavTVZDufVDn6epVM_IZAw
Q_wrub7X_wn1MZfMJGbEF6HuhD1-KTFGPV5Z4kv_h2G9_uBND4kRGvTTXdzSGwEZD5wft-5_ftX-LaLLqb8IWg67ozEpIXOVfSfXCSApDNXurRQ6fbSmcGCT
NYj9QsbtY66XA6SEOQH7_biI5ZfS0pdnXpWiT7HMPPzVxwAmKYl96o5uyIS7MQ_XZotGGVr_bEHs90uUHRizouxljeyIsdGauR1-7Hyi3PPha9r1dFEtXwqe
JluVySRWOBt1NEtq0B-9ZWruujCqrn0OS5mPy5_7PtP6oH0Qg2hxV6rFuYAnhrvS1rwTekWUJxaCcwALX7JV87Xy_a5A5tS70hvdmBXZv9iOro021hXZdyzY
Mgu13N05f_on1a5u4pCl7egE-APWYzuvu0hu2L-uEGJUv6Topf3BnpK0lXb4Q4ZE-BW6pBym4DLum8UIq87V1j2GFENRRGYCyPa91pZbuneOuZD7MF5pFgx1
y630gl417s_37Byr56433_cu1hufXXZjDKGRu14Vry1354F_qrrKvI4Vry2JegavY6huPxvmG0UATv4gF-RZ6WW6CAdgCxv-lB55hmSO6qQ-Bl_StsWkF-8F
0oXepLSLHRpQ6qt5b5l2pG2gkkORQ7erXvPyA8Kn0M51c_n0DwK2-c74OO058H_e5jxeO40TZmMj-MkbNDQoXWWB2iVyb7FP66WVW9h1pAT3VifD6uVG1w3F
0LJvZ6_q_G2DZdnTyp6ycx_q8mG6eXeSFk3TWgWBRe3FDxnl4DTyKYMVtxupqPS6rs_HMx1WZz_m7nEi-SHBlhZyr3NtazVy9bpmp5VZ3pnCKBx5Jn0V1q0-
VJv287_6uuh_cQzJVg231VBn0kpuQJF0SJ_8LuNzmeOFye-NJNuJuC40-CPkV_xAhzk2iiEFH97QwmTVeHzeoEJtywOJVV17F_u0JlxOyfkM-U_uuP31mUTp
pYeJl-46tzz0NkUFPFnS4t_mBz7WmnbAiE9zVgwLMNJY9-1ZVh-V68sljSJ69-Chv3ztmFovfixdNtuo_XQVplFNgfslRlucPu2P7xl1k_wBdrH39oZmaGuJ
RFDBhN775tsy0Sl_ozV1Zsz-slFLNS6QNunFZQ-G_tm0uyV1JpKRdpi_wSFys4yS_UUQ9hvE-T5XPv1_-V6UdtFLnbVZ9xUVxH4jDtuqCNCPV87yQ82FGXO_
B_aqyHl0xqUT1IEVk5HfV53FxnwX10wDFyGC_3JnqS0V0FklRdxOW7S9ikLVyjEc7_7mQOBdn_pr19lym3_fvwyxThVmzWjYo7_oNF-ShoBd1I4VxfT9NY_U
zRzz67h0L-CxbypmNlxxu-Ua-0hYdA1rHS3FmCS5YvuEWFpRymlfPq5HmC7VG5dmo-3Z3JXfoErdVdx_F471uiC0TmUFBxNIcnyMLo0U392Jmx_zyzKB6E7N
GENC0Fbb-kT3QAXNfATFPSZFDT_--HORiX7EdegHdsebbgHA2xuqWnV_SGcyVgHMQVaZy4L597Q7ipk0_5OGYwpuAUduduu7Ts3DbvHroQ-NaeWG_Wzo_7VA
DT-quATQIowrtaho1bZonVui-Bbc4UPkm04Su0uWNto-2ZF5NEKIzJLu4o3VyBpiFrtu64hP_ps5l_DtBVc5Bdm8DKaJpsl00P0l-tuqLRdmhvVMDv_VQrXV
WhJYR_EBIAaD_-e3yCLdQWPXtT3C3y2V9Lfpprjppzyqho7T3TAp_AArzFobqKtpMTtr4uBFxmOr4HVBRxApYXiO_E3t8s_bUaa774iQz7IUNtuTKiuougTI
iWm7_jZ0ER_hzmDkqjfKf9La3kj-3lZQODeDX5bQLPfhJPT1VAzXy4V-uEQNhl93Bpym6w3KVCMArmVCHFHUm-37N_v9_Yiji_O7qXO_T3xbcYu-MKd63z2F
d_y_Ikq3EMuOXW8eEiZ1_U-RGJ6NQHejqxUy3u8IajXM5IQ9fL912las3XKFAt-Q17Q-A6pqHty2LdIRkVejAx3yY9L_49u4ECS0yAe_vy6m7g4QMZwKhv6v
iSQVBSp2VzPljtytY7g4PiMoT_b8v5xTEW5NGlFlwbSDn-J18klVm6jN07F63L_aN-M_yYsqIfEmydycNleQUlX2F_nZVpJzdnGFIr_3HJm0seVUm6gVwLel
wgy_kzliO0j9PFqQ25n-1R35r2zrHz_yG_tZ4zeaxCWb8X8C83Xz5kQmugbVuG--_jMV6h-JuCjxFlXr6MxclTgl0Uwn-LNz_G0W0d05Y9pn2MTHE7cClrM5
UGStVtpJ-lvFduGHKDq6dmQT-YD48_dq-pxVktYw_Fbs-Je-zhyMqAw4jSlE7nXX4bA-H_A46DRbZvzmVV-dpobI7OEEhxK1nLnAoEDBMF4WrQ6FVmVyxRDC
Wfmjh4W_h049fLeUnGE4_rR_lSRNurC5g4eVWzGAIoNM-4AzzYuULX2-zdy2L01mccJP8Gk213nuV8xrfOz8dm3zD6cbFVzAZ20w0I7zoBEliqoWEbG1dM1U
JThd8jLOtVpOIhGYryQNlWi0N046QbJ7iCEAvwZsMxjIKsZHiw_7LtMkBSW4W6XVg-cuQlwSetF7Kh4zbnA-zH4e7vlROFmU6M9HQt6AErH5s2VWhLyTCCNv
egVsHR0EMdBaIKz-Z-G9BVYR-e7Qajd2-3EKhh-v9BI7GzraxtqSonXg5gN_6HccFpxjNJnWs7V-iVBdzcTaz35GBmdjuU3nbNzPYe3fKmVKo10tFjDd_X70
t_XZdMDG1Pg0Cp8wO0Mthz_u7wkEGIpzyw3UJV8m1DZV-8YNnNLdES3ze1AmJvCqQZttNs-V_hJGNH7WUj0OtNIQP3ksu7lV_h0KrCrdwaqeWoFGEGQaPrzk
tySw0JKVPcHKmFXr1Klv-8LFQCPjdVbJLcsi0ih76HbS0Oy-tpx-PlrgvUosv5H2CCe_y_vFV5OhOdsbTdbMckxhZGL2TfAPglspivo9nSnSFlnU6Sldbt7_
C_TaYVN-ALQjZ8slRHcsuFF85pRRMBNW_DW_IjK6ANwFUOH-vTF8rrgMnQhzrWjksznCoJZc8M_vjYzBxJRK_e6LyU7ZcASzy-45EfTbjRJuUh92DQzZxezy
V85WMNegnRxV55Q6NiTSdlZGu6IU_2fZPf7dTSnDd_XZ0oo4PTm4P9a24-tEd9SnPntuUNoAxqE3lP-s_QgSg5bAgUmuvXE_liNl1fXvtFWLEb7j7ucG7dFW
PsHzYyzZWOgbu5VjHBr_6COS-PcLeFXKV3CpZs8f-5KxKUyVz1W2VkGUnUy9C3UBcYpmAs0L__GOcVavyNauGCZ5hnISQDW_SewvoYE_2sHcrM7sdFrAkwKx
7prcmTUTlsNOTpI3No7hmqSdKh9dVXV8h6fUY_VYLzK6_l3dCV_2hmvRHJ2ReL-X4qKAoJJc2xv4XBaT7L0py2jSbfbEbp7_pYSV3o1iPb_zoXd7d6t1tmxG
2KW6lufRlq8dOaL-nScd60xWHhhmgyc9rdo50mWf-9LU_0h6VCsl0y0xjFOhvnhpDHyxu44CVgNtVjLZlkQJmm6S-FGhO-9UIXiVdMZDxmDWWcU_KhDnpDVy
EW0ccFqg3h-QdSXUy3dc1EXN0du5JcInvECxggeMSUTNUUjNkUJF5L9LJvlyoi2l5FngmOSAgUadxDclq8dkwl-7V7o7jCAV_0ez1lb_soV_hdooFO5s0ejd
l-gbPEGd_w-Ydn_2Aq67M3pwLIsbcP_79u8R32tGWIzYUV4h0ISIYe7V4GCV4o1Vr7FsAnsTY2dvBPy44iWU6kXNw4GaJtow2SK45HQZNudgi3B8ufxlj4eW
PrYMN_NyjXE5tVED5Wa4mW-_8XOHjSDZFANvslYCq6zNIHdokmtyuHy9N8auWpiCsxj887DeR7x5_I_LO5SpVtdLbLp3Dh_QCwWmaQJp6JwKnzQtgCtq3xRQ
KA4PF4GCV7bnnvnT-CmIwMsMYETSbwT3Oyx0LMcDp72Fp3J02xmzg-2vI0F8V5jLZ64l7n-BvEVZBo9ElDAhaB58l8gpElv_x-DxWxV2msozRiEQdutNbsny
LnTuRRoz9UExgYyUFnPFlnZeHVLZSNVRkaZ8nDdAVxk9KU9RXip5xNolso1y3SdutHMCJ_ykR3-xkzCLyFxJAp0tMfWMNBqA_xEGk8JIJuDjely-MElF06Lw
ZFy
}

