sprite $Certificate [65x54/16z] {
xPO5jjqm44Cz8saKsFz--mAVuSKkj_yU2EeUsS7wRf3lWRm6gX3VmmyIv2W_K80HNWXQF_-18F9JuliRV4rY_e8XnAVyn3du4WHaIpagqEIILAuS4OGjYJl6
WE38dnIw1VBUVhAB02e-lI7V2dAIP2CID06oiu4ibVSjiFOAVGqcYLFkUL14CliQJA9yvabjArs2C2aT-LF0JuRmWQ0UyyheRD1CqezvHZ3x9b55giwyCaBH
ro1Dekh88mBilXC5W5KI4Lk1Na6OsCcuGVG_JBA0p2sVTEiInCOqkxWPm9fNnEUy56nmdfTbTgayB-lgdd-a7SrRRbLEnyhrlxIJCuU75VR-gPuD7bQMl2Xu
mdiEE0J45Ue5kw3Acy1rZNX6rhokCxDk0ZEkqPwp6Oou2Qms16fnjfgs_AYXegdKXa6rHaKR1wrbJ_uR
}

