sprite $Chat_Room [96x95/16z] {
hTU9kk8w30DWR4aEx__4zxeKJ3evwOPc7xxlLx2Ripn6CQUaY914jySlOr2wU2Tx1FiTBi0pbl4CiX9sNsS8AM-J7GhTR7ZfDixIm1iD7aA7FsoJRF3hXuSN
lKarXAxn4hopnnKEoQxnKxqg_4g1vANl5zpYVr-0oN16QuRaTfotWE_pvgX88Jyx7Tl3tTUxl5RWwF7DfWMMjlN93eKVFFwq082D0Y2uxmUiCZoy3rvPtuEq
nxky-84pqAl2zmkOVf-U7-h72vJ2N_6LdnRmkW_OtC-2i9aV4zzXkxv1kkeV_90TTcq-Zjd5g5C8r_rAWPPwnQ693_bqFFjnnCJtSB_lJnAuwtlunAVkdp-u
y-bb6E2WhnQ1ys_0Z_fKj92VtO33Z_3EJ6iX6_iUyEi3Sd29Mljh3HJywXjm1zVylGPTA2Y-KciuM03uONww1WRSJnUuEolJ1WzXNh1_-bhqO0sc67zl1FUn
Nlmc6g_1fL630wFQuWU9FuQaM2fyGm5TiVj4hpNGXbEI0C-yARpZxXySt4kjeOzJaIM-yFf0IuEvusM3bODhg9YddxnMELNWDHPKM7_fNm3OsbCs-xpihWp9
yalS-lMl3ED__gd7n4_-tV3s0KpyYlBmRSUN7kbNGsN4zgDfnDnF_kEB75UCzTO8J7qFoSgNTBGW_jS5b3-E-LAZamLAdIX_alAFpeWjMWYuvelp1aQq87dT
nwn14I7Uy4depmA6KZ_lawjUFZdG9VOlydd85_7YltsnqvLXvrCyEXy2aaYMZ--6Zru-fJFp9zZxJE9zU7xqUeqdzqlqVYeINhrYdzHF-PJO-nbGYxxXuyhz
vS0da7plA_LpVWakLkh9qRVEytwHGp_PuY_u6ldzawzLF-sJxCzVIFcPY_UN0ZRpqSQlmt_xOZlcYy1cFjgSN_ftCS1XdyHq_dVkByKCiFebiFmRzvUrjXho
Y-RYnxtxMpx1_fCm1SRs-99uqIULgGAmdfyrwxBk-187drdw-qjUz9zDeZZo-_lBY_xp6IJLto-51fz_Z_di_9RHXwc95SyFVy0FRVrggFcWltch_WmyzcBg
6jJUIOVfaw2UsDpVr6MF0t69vKUBQCjlBQ55KtjsFjLIzp8E3qcnfhuALyjWynu3ZnDXY8kWTu2S4P1QxsVpU3JpDH30Ma2uEzG8RdsTrsiDA-BrRVS2va9G
kloyNck0MVBbnnAybjyYyBWS1ItJdVyLKDbKexaKappveNzFhpNyUtwIO4JuumT1q3i_pvq-7x-9CV3jPq6mzde_9lNdhzdyA1xwFh-SzlXj45hzEljFOuh5
hxt-EYvfziZV3tRr_m
}

