sprite $Cloud_Light [96x56/16z] {
jTG7UgD044JXhgvm_oElmNo8SHY2lB-jB3rYKvU1JcBM_w6OtKr7zVSGepwrZJ-Eqs5jK53-VC_Wa0VihggMhQudGCdIMebGBrWviIFACUgkTYoIIiHq3V2f
fUqnNVSuF2ofQuHHjy8FZReeGiqCzOLiNnyDg-R6_8vKeZf3uweUy8EIhZdpSXvZVgMmfl9exRbJL1EusmU6F3a_NwKRVTG6F73gDwqGSsjkqQY3vajOFs8Y
zZo-0se0xfJVnhQdK3DzqhVxF8_jRxU_1BWBwfjEdy2fdfn1rlF-k0Gf4Mh0c0TDSkqLW6ukS4bJ8kYm3fm6ZnfrX6RZ6aa4mAXsCZ2fL-6obeH5XxNfzD3_
LkyxgCQ26Qu9t04r_A5l8e161ri-xEvZVzHtiLV1ztpZkzjvSNr8BJhinI4-uWDhtdsSAn8DDBvgFbs0OrI5FVMulowXorpDyiyfqCa2-1Qh8lu_IY7Yd9xO
--NmtBCyhK9unPCwbQeEBxfRfuEgYgubRkRbg1QA-F9-NlwGcAXFZ7KnpuKupKSaKGTGubVYz_964mxh1oqdYRVE94xDywXVeIFEFS-ltfpbkEOwR-H9g-QG
UVtTVcKsCQU2Eg7eCGTrIl73U5XNz3O8zqIeom0ujcv8tKGvcd1oVD5rd-An6DkIxIJcVj5oqlL4RqbhJPBheoskFSXPkEiflAvxg4V-0G
}

