sprite $Cloud_Dark [96x62/16z] {
jTY9agKW38LXAaLE8E2y_-EEfg8TIks6NlxPcErZkOlsJGiH0yYKVZsYpCm0vymCq2_h01ZCsMFat-GPxC6cy9tGZvRCE8yQEFKz6_icG8dsqdePk8oH5-5y
1Ojf_RWlWftVHsmySWXo15ha8s6unn3nuGyc08ywHu_pc5X-JZHtzczyB6wWU8APvosYVlSvnvWFtgkr2FBqwVDK9LJt13JXNphuYm1nt2kVJv0vy03uwn1v
rVhf1E2mU8k__8R87nDySJokpoUNRXLwrS5nyPPC-tg6LtrSlCmM-TPQeKVUzNLUN7U-rPpkBIu-Lih0jyftdh6--3Y1wvRYQVcZNXOBV5D-Elt8h_lL-PVp
9mowb6M_US_FdyX_ozTBxmqtdp3eKkfgUl6zbTij4cFWfNuZv_TK2sZai-l3yjTtqAscgfA7TpKU-ABh7NxtT0yKhuaSzM_vWT_65p7j_iZNd_ZRjlMsX-JP
xPFhuScsdlEdJ_6EnFaV-SrvzoDl6xYz65SptNt5U4F2SkdrDtp9m_8jcwDQlRVrRyx_i_KNKBXXyCHkmqGWLRNrnPp_r_fH4pQVFy9GNTMTtxfNSk9Hbo5T
mLtVwrT2XA0x7ohRGivl7rCg9-3I8ULMMzAjiA6EH83hG2ah4_GRRnFi0zFTJnbdKfxI_i_RMjNUjuFmDPv_OVaurZWbdBrVLjg1DHt_o2SO-MrCA97hYvUj
TdlUHDu79IVtnQewtQYFl0zxuRGNBrmwMtjO_7XGxRm6PyZL_3lpA-z3k3vEK6Od6Cuc-ET8QBppZnUl7_FRxMim6cuBw-BxZUTZVVugc8WPy2tCwFPBqCyn
ABr5y0kOcl2SJz6kYVnnzHgdzt3eLdkYcyQ7mBez2Bxyrms4-xqUjzzRKttHm-gTVukl2THgL_gY1x-h63ynWLxTdvjF-Z51dVfib22l-l0CqZg-xtUakJAa
r57N0j4MzDuAKEFHTz3InvDoFfDA4O28WAAs1Plkq50-hZ3g_6n4nCm0SoQwNe60TVuH7LCUcwd8wK-Yp9z_1leV
}

