sprite $Conference_Attendant [96x141/16z] {
jDY9pgCm30JWLMBF62jv_zVTcaIBIbW8j9t_FlfDQWvL-NEUb4KKQrH4SlhplMJ1KKJIrt3QMzpT300-hP3D7k9k190_q-qixlQy8LtfVLA0FfcIRFhrSv0V
yRs1aDiyRJfU3F9WzJyhI4SysMCyBCZplk9Gj_v13Wsb03UMpm7lRjU70YyEcP--lQVhPmsb44_7mp4VFG709Wguymlnp2Vj0AVjVKT-ubyll_i5CdryUN5y
nnFq5SESds5YRxcSZuVlIBC38axFK0j-z6yCIFz_3LYy3NpapXagOaEQJ1jIMWpJFaqpz_X_udxJJm1W587DfFFp1rWGeK44dD2V-O15Wu0yqJT-_Wh66bM5
6QD2WTr5HMDV_7C_0WO6AFvbkmOu-39zUA4j8aex2B6s-mC_l_lI1yGEaz0UO7am7y7cIqyMoJbBbfv_1VubFp8MFFUrPUDR1fyV-JBuUUUZtBw-TF3pYUy1
kz-u_-34tnK0i6BhT_uBNm5ZVALPAT1dVZxpeGfpBxNM7_aqV-NbEz8FV9fHig3K2lc2dzzzqcJzhTPg-FxwIKafnU-z-Y_yuDS6-uaVVFCvwUkTyrzJYfCc
2cno_dB3Lsby-5wX7_aZBvB25uHV9i_FV7R_bD5FxZ4bcRs-4YOA-b_p2qP1JCWgSG7thqU-RFYR7mKv-5mTSZdsFFfRWmpZQNxmwUhi0VfMI6_IiQ1dy2DI
pfUlg4My693VNg38ORPoD3vx0KwFgLSfjHO7jFij9pw4NdFEAq-aq-5NUYt5tGbS-TfYNgktMvjVxA30gZJUxAgW-tZfnUBF7FdHTnHl_CxNOzvAhGu5QNQz
HIPmRlnGCF2CnIy0mkV0Zm4GUl1grRlVi-UnwYJu2W1DizkH11Ir-qD1N_nIQd6o-xExkD9DiLggi_bRjj74uAahRoJdTyPavONLLs9N4Ec3foetN-vi7FQ4
uXmAsk3ZcyQRTNywMI80rmQ3Re6r5r4ht_tuWeVRmw4LTr_CbiMzh3zI8urVbbRmTFUSpQmzVrktmoMtGHW8m46xajNtV-4wuGoSPKU4tCxqPpyMeBs3JDfq
Ebzz-UBrVzkRl-QmLRlnvl-E_dYiHQr6JOVOmJUVZyLO7C16lYwGwQel5jBvtjzMUOwmTdwhUjjWBEdrSgBdfmThVEjlYfNkVKCRRqtlzRTN1Nx4TrsvrTG1
lE7TPvqafdLOvGVV1pZsrpX2Nhu6_kFx7M_zCg0omUl8qwhV1mW-Nr5blMxaPrvxI1_yo3U_t-Zv0Q_ONGi3nFfz13EJQPxO4Ms-ZtfV_I7P5CxyhfBZc_oX
zyqzvUr9qj_ygxvKlmtW5OzyFWMUU35tBRZvLA7pboD8UdGeku9IB0vGJuwIRmR0k_hS0-vEAONRc9_Ns-7aJAwHd7YMtUBkYury_HFAfpE8zSNTfUo1RUTO
8DCziEvpM9wh0OmWPWO8zJlFOkuiDS91r-EkYiHNOwZVU9PwUdu2rXyqH2be8P81SEi3TNbYy2kJAuHpVQ6xbHZ1ASJC2Z7uTVb343Cp0RNEjzEFbAyXqXsm
uBjxmlVa4pZp47TB-JY3E05vyWW-t7MQHxR333xTcVFv1CmkVM7ONW6M9Y33yM7prLsI-ka4-W9PyCtz4nxt_UtAB-PRM9sb_lhozUnlRg7-KdyrF2JrWVN-
VE3ArsHralw9xyvGVx6_FPZuWY_ww-3hu6EnVlJbqfUF_7Vz4Nrn_wlwQlpUvrjVcg_DtpfFBjGV_OTPy6tqETq-ycew_kP_-7hmmcVUwKXzH9zZVOAtV5PV
pU9ldzqN7fbVckZ3xCP7uqb67GbV_V3xBHod-jqQYeCvhwRnztEuzFez8DZeP76wp_Frw-cN6eO4ElKHxdVDJw0ftYukaDYg_mtVboSCGDXwVJtvSl4u0rsj
hsTUJszNrMUelyYRXEUhvly5pwjdLGLsNXRrkBbX2fJTf-gN-jtZCPy3Y3wpfcUlPQBM_igYtldy5JJ3P_buadeIFEWcCs_S-ZkPt7NEFnNdYRhCFtNRjte-
Wds06zS-oPZ4yTNNRExf7C_7KBkD1dij0f1KFTYfBoJz1m
}

