sprite $Conference_Announcement_Server_Role [96x98/16z] {
jTa7bkKg30HG8wbAmc7_s_qVMyUf_VoOL9FJnHGqfiyC_o8AcidmZwBSWlAlT5Cr1Yd_H8UgcXd3ENIbMETC1QclOT26ZXX9xTTt7n4iFJC6G6gdVl1WzFmh
hFcs7HIf7pmGRb-A9s7OGjhhiZffLzuO_5QDsU6J-bcFS91g9zuG-APVVK94pRJSTBex3I3Fl1djhNYpcty4iXMe846IsFvUJZXvK3uNR_he-veDREwQNMMS
U7L-hCPKdtptYF0M0dRE_dTstaY-w8z-yYGSchdoaNpJzKFngiz-ycm1ySIJsTPKMHwBX-fdF_dyZIVUsVXO9lAv6ddr3nuWddYQSPu3m5sNfikBxnwU1RI0
kF7k7a1Tnc3wj-BbYvyxq_9F_GVlmMMUwW-_MEfVV18mopy7_GS_ZiioJHLNNydKF_j8V-L5n5RrofCH__jpPVf7yUMBRni0MDE7eGWymgzyyyTbolwFugMK
TzzmjB_wvgOUrNdmf2dTOxdqRuIMykwRxGHMlXIu6-iuEGzUXu5qJYTVju_YLzziDtppoo3Mm75Uuk1bzPn-yecI_4TVmGTVuVHv3dhoMGT9Z2TVfRm-lnht
dFp105O7wHT-C19nyKNBPry1t7nR-ozAg66VrlcrvpTVLPvz1Gv_etB_jAYbd_ophwrCUzh_QjXoBsWRGDDF_l3juiEjb4Pf-ZV-FW7cyP2ykvFby8smQ__k
mL8Ke9vzizt7Zdisb7ppmwd34TpzmSXbeXGbQUcBMil9zuYCmpB88rjEFcbMBtu1Off7YfYxGr8_-ucddyT-3dlrfVbJysdf3m947QTf7I42edgz5SGrpiiR
nrckFZTVXlG7iVKeMMONiGYz-RlRilsawHiVJWuF_WgdFnHLPTHA6KH3hmDuwfdJ7MBxUKeP8v7yoIz5f6pJbBj_utC0foVFSh-fa_kIK6NpoyeNaQjl5v-R
t-BRLt-wHSdnMxIudf_fw-6dToJMrEgU_4jewXTVRxw16tZdvpdo8ltkYqNocT3R1CZp_ibCyrmf9PatNp3AhP_x178EH-h__3nIXXvVREPFNosJjqgU7d-S
MwOktqLKwupqzSa7IC-4q-il-4PHLKmpRy-lkuyMKo13_e8lv8eXvf7wqRVzp0V0Elz2_zv4owtk5gAP1rytFwQ8gR9q-S89cm-GwF49hrFbqE5JHB74aw-7
RpVVm-lIqu_2cXTBu5TyYkZYsk4FRkk_ytaAVlHnzI55TEppXygDWjSQSVRrWx_UY6Lcdp_KK7tiNp_iJnEDedtxlmtW2y_-TG1ilfqUtqHAyS3GuNlRn3hD
VF1heFdx06RfguYDb1vVsW2bs3W7aNuE4B5CVXmGbZnyWbgb3Ls-LjdkpwnZ3RUJttw3wU_XE3izYA7F5vsihCdpSxyaMjIW1ou3rBcwayb_zrL4npZUCEbl
CQBrTWmGJJ_kdBtdloykXt-xHTSfcFeqUbwgfDTNRvR5KlNHLpFKUHh7SPf7Hrvx-fzV49lYurofFtqrCwwT04m-Y6vVC6u807UtpPUBRwVF8MjjFljzmSpB
-V1p0W1JZve-hVIlxpZXvjy_3wFxfgSFaDRZ6vg4UV8dFtNOMdjDFXpRdBIZ7s9JwboTwPy6mChdkYOVdeS58R_mVgVNYAkVl0PM__uf64ZzwekFTbtVJFem
Wwkxt_cSGddraU_tHpzv3HJi0xYT0_BLf_vul-zHotCvj0Xz7S5Xru1uyoLCjmDYz1z-ylHIYi3T2RLxG7tpfIBND_BzVlWRhuwoHahvoHl0Lrz7ryVr5Ki_
j6HqJUS4qXUD6U--x7ocSmBfA-OH3pwm0P6yw9wRBvzyQFDLESr-zpLzy0UldGK9kP-HCOqr_CNNSpeBAZd0jV-hJoJVxnyfeALFEXvzkxUZrhC06IDMtmc4
FVdQV3Nzs3zUZpaX6mGggfnyk_Xczf47jUD_IK47Tb_1F1ue9Jzm7_JqRNYFWkHvVK7kVZx-Xo3zBobAqfshRwILvYDziOns-2yrUOI8SdrhI0w0Bu-V_NUa
61a6vdRJRAWKUUT16VeY8AcNTJSjvHkFeJjgjwqBBVBElp_-UupKyiBtjlzwW01l-X_mHqd07VzRVAxpcZETEag_y_x1Xtj8cWn_AMfiEMWIMeQ_6L6rbGRC
jEV9_mC
}

