sprite $Database_Availability_Group [96x92/16z] {
xTf75jim34LHuXViVycn3j9TY91c-lFyGXw1AkEh0fJjJDiYnbi3dRO-PwSPRzET5hzBJkCzUk7toM-Oe1IVvkGcRnDy6cHjyfYqDO36D7EPZoIcCRSk_-GV
CD68NlNpD_1Zouz6ftsj-phjCwRnyWEaRf703_cSybJMrh5K6yX2t-UCfopngoGx5Lt_rPu2dwIQqFB9cEltET7nAzoD24w2hBPVCsxTu0Y05OW74VM3DVLV
XbdcZezfp5ZtqSWwwzFBFbfb_Au-ez5fdni-3lkCQIW_S1NHzFi3o9ISjHuoqsBq_6hACorzLYGvpMZxH3mFprS3Edw5XUNWLCklS8y7-3exok-5YBPTAQFy
rJ19ZXqVq-mD7uqIPtqhTP07VTZFTJyQ_SO-ev7IopvQliHp0wY4UMm0gHmsrvlmbnyMk_LNmmYo_14fldj2wUMFiCMT8XxYvLyfBMu6NF7gpXzuF47Sglmg
wFjpnhlyAlZTESblzQi8NCMufGF-b_vs_xzFd_KZTTGVyba_hAF-YDHHVy0-we-GTSglO4k7_0hE--UJQlgz8AUlLEl1sVNx0QIaEZ9unv_ttx_wxtlLfzd8
7AkbUayuLgCFNNv_kTbZ9rbyaOhVYAaNV7Bi5iwDxmBwg-7CTmrLdFakuyLt9T_W7m
}

