sprite $Database_Server [96x108/16z] {
jThlSgiw30Hml2kjpJ1-_zUzDqfeVHoS69Bkb_EtFmd1E7NnSYPmB7yNk2HFVwGdaznTuf_m33qA25_N8Rdv8ryVKdAvMUDB_ExWpJh_UqDYwC--F7rhyCU-
nEyCllFL11yEtesTtnNmzD7WoTT-lZmaX7xag_Mp95mRVEZl-ly_5mfOw7E-ybcV4Z7srVhoVDA7P03c-dVbStvoEJ3jvtpEfvmO-JtlEP_pAOK-qN_evto4
FkcxyZa_1fycVVUSp_cywGbJlfloEHyIqoqplabvsc_rgVxD9MND-ybbWS_qRwR8VF-KOrawVUI77hvcVLbQmd_Vlxb-agTz8atsBrtpWRIyxP_kKfipFedN
_TEyy-VxNnRS58pw3prohNzYIOWcZttI_HFVSYmDPkvCptuqFoWmvQUSem9lW1tDvvrl80aW7S_VitAvLv3s2h-wlRi0IJ__P4nFVf9KIZ6a56kNxpxiaQ7l
RcnYvYuHtVD3kHTt0WcMSoww-M3Oumjex3Rc4lxnbpjm7o8ibr84M9FU3tmSaz3wwSSe3i1AAKuU-TxfumgUVlqbqMXURbaj0Hx-y0ACx-D2uwVxmDqjbZlS
V0vyVslVCU7kDyjdIl_hdTyNS68kKK1irlzTH_Y3Eu3fcD8YvePFYBH-Ny0m7_T5TFyjWDJunnU0Cr4I8L_w_iU-dVAT8h1grFzp0PoA-St7MWRzV-nB3Avo
q7zV89tApJS0L2quwf-V-uK0QLlD6FXj0PpsKO2Rf5fNIxtFpkTvtzO7v6kjnSQ-tNoSu14-VDiXLzcsRStyzTdvFE7pxiEhF_nz1JxsxUPpdjzzM5rjvBFt
ESs7Bm3aLlE_Fevy2v-OvCDt0-wFJpxs-UGJQNcT1Ex-KWpn-rphgbyVOx-jCDPtFst-KBpKkfN6Vov0ybs9HBBrbrJrGDnTfQmbV8pzFUXhfC0xVqdRPltp
sVeS-MnkT_l_Mn-t0gNgsSV0dqxu9QxBQjNV-CnBxBzohNdaymCVNXuVyAfrowsFh_Z89Jr2hRMk9NllynCVUKFQ0z0C3n_VyQ7gxNSGUFPvsTUDiRhPtd_h
utC_CvHIDqR_0vzNVHI6OckjGjy_FlUvxL-VjxfbXczFFg_wiEe_wvlAkXKrFZxtOJLtdxz7FY_xu5PzvED3lmHHwkeJVZdlcuAmhQx-sgUAd_UH5SJzspSr
VbV0relpNxLFDz-NjqD_TVAQZtLby_paKdQ_AH3oHHzhzS7psTtXzRHl-_vYuBS5ShxyVDfMonlV2y-ctrzeu8FaQhpcsufcVw6H7pbPOx2_A4y-BjzV0b2_
lnZuHNR9XzVLNliWL4XUysDx-jgFqLpqs_t5kFzhlWDezXT37zUUd-JQVJELMjSyzaqwwo-BEy5sVx6kvSW7NMTzrx8iBlxwPZxetoGkidE-tLzNs-xdx2f-
u5EFd_IUyeNVb_dX5v4kxttk9n6IxEnuseCK7WCkxFpc9zQcUTw4zZNUVWHdCrUnRl0_aK_xYkct5SANrFXizPYGp_B-j37MdcBTuDi2cXkE3mxxv1n-C_Wk
Fd49BWxVf-PIYhM3xmEzhc3-wk0Bf5m4IlRok9UzqB6y2YVEti2FIfYxP9WvS_N-Fy6Z3NTlFZe2Vv-qJ2KXMhxNCJpR_m4
}

