sprite $Device_Update_Service [96x116/16z] {
jTQBikCe30HGWrejiF__VxT4I17YOCnUJ-zZtaUW9bDtkvi0fMBxLm4LW5B-YIvKg0VK-BokXBu38ZognwAt0CHpUW01xIDA-NUwHvwf0QNMSw1ue0QXucUS
Xu3uQwtNQJKygxUq6jPhlHLfDJokjmdhZsR1bxKQX0fP2g34GgsBkjAZ_qpNiY7YLgso5jT1bW4pNfPrg0hoaVT3XOopLuDrNT9X0EmGKYQyh4KLOgwhAexP
4v957WhXaLptP5xxWLXTZUu9eZLfuaFZxOYKMhEwNcDswGVAVTxrb2dGgRz-V86AMAPVuhv_-_YbLjUX2txatTL0D5lHLtnWHO-2HL_brce4ARdkMV8fTtIn
1DUN_S0OBXD5HPWrEb-pv2DUwwYw_4-VAcCUNYkBFXWmzqcD0zvhPGnH_kQJ6F2qfdS35dsg_E9DDzUVyFMq90WRFnemzzi0nAzkROinFk8hcN8oXFOB4Dzz
75rWoLU1cGGXvJqXgDWMFK_ua5IUa2_fxIj2yyy35lrimKDdN_lnzPGyusUuBwgg4ehl_E02wxvbHRr0ML8ih-Vg0ai-a0aV0Ae7GrzMVIk-M58VW3gX-BCB
D3-4aM_L5pFwDs4BB7uQ-FB39ucHp-AN0MOImxP9ywSNg7vAnC0tewhx0eM44BR8Ir_EVZ9Bb9alCSQJFxk0-yb8Ium3tnPz-VAzGdgHOUJN0V4ruBQFbvzO
1YJJWTyMTFBd5qY9DOcuFF-w3_UDRO2CpjyMrFmGvmqxtsACGxzTGAP-6s2DRnsl-kCBCB6BcGvzdFpf1RJZIzl43xyheFdJ2_Hy7I0NlXJVgZ-xGDUjla9Z
cFfi_iK5hEFR00qdlrjGywykq7MhpjUOOUpBosVpHmFqaszwwtZkNrsWwrRx9CPld-vZw9y737cFCPpyTe4xljb8hntVySS3E5X-3SpmzfEPhVfelFuCZEZy
Dg3p1mFIrU4Bv1rN_tI1YJ_ccmvunmCVdNyUmCjk5GgF6jnFAVKlTEwdvbF7CMr-Tu7c3mOqFftG5kB_-YrdN_6ERDLFCpyCVJlvs5e-_JQW-ddWnulpO-ZR
bo_kpozWFV-87qS-BltsGjMi-YqtV8pzTe7gsvKVV_huanzcFlGflms0fS_3Z_t-XMgg_kG2kX_MJZ_pRS6FhkU3GkD7zFm5Bksk7peUTfY0jh-IMOFjfzyj
QEgBs945okJsiH_7GOdbQxFjAsY-NVjjWF3O8KhBUydXVl2S-A1SzZKVJNVSmnhfUFZlMlEH3nKeSzvzGFfArwyo7rwEfQw0WUy3n0wwdlBhzCcCdjz_lz7o
KGQaxW8Sdf_-Q5HJzjFdV1mJFv7P7q2-uqSzakkMNzcFkPzJVSBvOq6_VUGCQNe-F3C_vMoQtgkqiIyldKqloSbAQ2mnnjxtLHfplSB85pkqBhwkfYRnAzY-
p-z_XdN2Qq3rmtj0vC6cfvJVUYObTWdV7zxyIb8h4rBni_if5dyBMXuDwk8_T2EKNv5FFzBA-Uk4tMDKBJwrVC2HFtLBRtqt8gYbFlt-jm1MljIGNaiglagM
BKXE8Wg-zO_58so1xTLv01gsBb7RX5P3DeMeVuWW2gswVInU_PpnvAlxVSINz4wj8MU_W0S_TL_pt6zByWbz3PcYW0AldIMcZrhTcFc36jhdpVpqvlYUQFjd
hUs1MmrhMh-p6bgAtchz12A7dw_h6jg4J7xMAjy7wnEsSKur7BjNsTUwdd4DVjw-rhycAYllYu6UQbtAk8QzJDW_QjMuRerhSDq7Z6fze8RTKsl5OtQhePv_
eTR56jnVgtMzXgLQrsl07_N_
}

