sprite $Director_Array [96x128/16z] {
jTgDagCu30HWMzrg0HNU_tMl8a-8CI5avZQw_zlb4uWkQ_xAfsMEyhsgBidhjtX8xYxnMxhSiu7id-lcaZFzBmofygwJlZKG__7WoRqluH_f9eaS_NyrfEgR
FlZ_P4ZizD6F8Kb_6pnmwaVyho6PvCHRFt98VnyySE77NuV4fb_xaKdwo-3j0r-AJ83zTl0mk_RbsUBtWuVPjP_whtrADFl0TqNletwYe-dNldj4vviaVZHu
iqzyHdI-kPHxuNhmzHEVYjxdjdcylXzyhP_u7dqfzUt1paT3gv_uL0p-_itOsU1B_S2dDFW-9kiu9BPjTEsJTs3GH_yu9BabV-MdtZVGsUQnlK-pw_l7Tlce
7trv7NpOUn_iBc_wkvD9uk03TkwZ2Pr_jNdw8MKl0uaJ7-Fp-qURnpUVRgM2TBpmGTzVxvzkdist2BTQC-6Z3zBx1axxnFVUBugOtQhHdsTSXtG-pJxmNR7p
BPSHhPehmX--xQ_FfxlsqzhxXV880MQMMmzcC0m0OH_ugOz-eVFkPmV5D0MC0v3wfU-ALtxbutIXcMcQrGDC_Shl5zlebmeWzz8yMpN4tgVPjP_wcL_gpxLM
ssSilM0VRHugpltwgDQhyp_TF1vnukyQ9DNvLbkzzqdfr8_Z-Ung1EedcySflV5jiX5fFd9Qb_TFLzQfRuirPVJDFjbiqfMF6nCv-hYQFzolVSDjUdN_Lvk7
-yLmuhkPOLvvz4krEmGxkNzlTU6t3Qdrnj4trfeGx8NlFlWwomyC06DTO-URHR0QNcuUZWtEVIni5sXURvDZyuiY9g_6Ey7UPzRewom_Ysy3ZNcUfHyVePY3
PfGKZeS_RfuBtt2RTtc87x-uSjV1Z8h83ar_ym2ZpvOVlVAhkpys3oEcIQcFlh_pXP_ygFEj-SL8ZxoIPXxJF06yU831By_yJAEV3HXjyz3W9xxBIJ_nwvQV
PRtDiVTh1GmkEKenK-3LX6XPuClzQxSjFxhd9q9ccr_DpDhcQJv6dzm-l01V-CN6_3J_k1X6FsLNbcT-0RtONtNCZvd1mbxxw7rAodzf7G3uY_rLkDuq-ZRN
IvyknsC7knFPeFSjsXRKUekdduMb7lsXWGIIldN81iFvypC7ti-Vw7ppcrtuBhHaQjUWzuqB7diGYZaWFJnVVVJt3QJKtDlVo6n0gJvzungxGNZpOGQkYxtr
7P1h-mZHim4ftvq_our7Nnc7UPsFFZQVwFTOUuJy1JpoyxE_5ew-pOrQreMdVlvhtu2jWLJ7_NNJu7DfbC_hEllEH--3cw_70xXyom-sysS9ThxnnYQvvkMs
p8g3JmEndn3G6bZp3Vlp9zZdHzYT7DFekq7DtHx0GRzRlkNd5dkboyzjsVrAOD_0PLOnD23klikw_7Yl3FdnphUZRwLmU82Sc9ZvoVqLw-AZN-R4V5aNZVxM
G6PMIwc-Um1hL9-VwN3-5EloiyHhtscmt4EUbRvRUm3iyXFBkapg_89zVfQOmeO6xcQmF6YHsVJs0FHymsAciClFCiVc5wx3cp_uT6mV1jUM_Eu1tkGdnrgm
BgD_V03WqS5o0-IcoGliNNwYjjKs-pkVwNSTCZoiEI2youzDkO3HvsUoOmCQidu-aeV3tIlS9JxpCx_SNwNMxB3EZ_mSVKUhxIDvohrQHcdCJwZppHUhhHZB
xRQaV_e0vAC3tAtUVRtAZsBONy_DeDS-RFyVTCVJjo65dMzSPplwDlWSjdBwtFop_E0EBUjaoOz-PuBsz94Dck_fd-Od8R-j2mRVnW71dWT6LlCfDxEV_2on
-SF-MjRRb3VYcpyqs7ntptzfxnUjmNb-zlkBfpxJpseDQlgrc7nx-UunBMD-jZUlR6sl6qHt_qwG5L9kC9EUFZdcfpz_plrPTtzhWEtsMmF--16CfwyxmsMT
1tziWCd9dS-Qju_XMxq-4PZjHNxU-Ogxt2-SkkVp4Lh-1InFd_EslswJ1j-QphcvW3VUKMkbvFRgPnmKyfFyBCiS1tzkly7dXqy7wO-R7ph8VPTFYvQVSVxZ
6vYTwSFlljtzSYoZidn__bpw8Jpc4o8Dmt26XvYcEPFJDW_dDNR-sC03p_dBOHN2s-_bnHm6YHQF_Cod_YC2iVElVjuaTnNx_2p7_6G3Fbx0bJzcgOfclc38
p-XdJPxpyS4_BzhFHxv-uv2Veny1_CxF4j_d9ml6o2RDns_zF7_YZJ-ZyVvNF_Cp3Vuu8ahyhU_PuB6_bj1BFtNN7_m2qUnzVhA1IxG_-0LoFFpJ-R1zmpHz
_CulU6uUXSAFFjhtCfklt_gv5ve_EJ1ZyD7EuS4tgfPFYp-RHmx4u5DYAQCF5txxus-jylw7mOy-ISX__xE7s_iT1p_wJb3bTrMXHyKm-D5tql3f_CTJUvhc
z3q7V-BRd_pCajBdiFv6lwR_Xu8KCGx-w4CgVooU_lIX76m-a_zZcREMjxwJil8lQ_JX-lU-Tpva_zxNDd-hN_2HFZEVzKiluAi-f8Tlt_3BvaEgvGlbwRlB
orUgxNWNovUAWbCeNolaoVh5mc4s_m4
}

