sprite $Director [96x144/16z] {
jDM75Uim34FHi87xJ_mBbDueCHO6kDPvRgTVPY6dVRC0uBjq3I022DkXYmF10HiY6NLkGoIBeP-7OoC9mpyCZ7HWU7_n3ufarFtLFoII1lxZ7tn6-ZMyV_H_
ZUJK2xyToQYNFYCrmvlLFcUTy6RJFa9NmvjD-va0N9R2svBFAzXA-2MV0qAcmbDVznEmkV1DFs5rUDDTFiEhRl8PNhNbe_JFQNf-PkLRKE_vMVddy3q_i_35
6RxfP-4pl6hJponyXfUcdrdu6e3BlxNyBFmHddh7py9dU1bRzK7-YtyEFxRS7vKl0L3dL9PyZ7tnVVpDf7L-LBwT_yRqL_lZjay-maQa5xtsCUMhIUlyUDnd
NzNaXJ_KLrjvVbxhSzzzSvq-VopvSbRSTQh_tzhjH5bn5GW3iFJ6Kb2y_zlUIjE9pJ68UckeRLpu_eHqQypaC7_fFnxcQyAkVfZt0RDFe0awcU3z-Z1_xqiK
U8Hhut3f6xyFc7tI1o5Sy_7UT_fNVZWUvQW9OvPBy6k_3LWSNubHKicw3-Sa_EEJZeqlzpwSBx4cZ4T2pYUwzwzVbFpEV_3v4f4bn6W9ngy22Cyn8kxz8Coi
F1q9WCU3c58aqnS-4Vh1A_y1h066803AuHy9HAk0SrMUCRJo7yXCLq1aJKZ7oCiTCDqYB84N_aCH_o80YVgB03fOGzq-yC8FGExLNF9HF1JNFeiGskFHDnQm
y4D0j8NNTZuYWTI_2o0HtnH4Lp7noWymckhuvqF76ryNXqWNNmUwW8Ml2QRhvgj_6w2RZwIwHUWYkIhQdZ_iVHc-1UXh-bRnlaGNeEF6npy-w_A8-nGQ0Kmw
l8y55_p29pK9aMt8Im1x7ojCVlZ8HqGXeaM0E1-umSwV0-vz6STt17WVOiEV_4Dx2I0DOEz3whnS__i0yydvSu08FNs8FRc0lKzwVCbClmDaAyJ2bwy13HVR
VnT0meXWhFdJ8JYoW_gi4dBhsGLiVT6JLZPLN00W4nEpqF2p-eYvzmJhxPy3MFt70zHytG5zIdtCCdoKrjkHy87F98Yev_KaVsi8mCeMrOVAmqUAhVV2An__
7W14xPkNpmd0yPY7JutD9vBIUyk2MvzrJXZZ_0guTi3oWleWZP_pEPNMUysHKFrb0EgmaX0hIlKne2sG-bh-qqcQf5nghKdU-RRJC19GnhCQ4CBmsNoGNiZv
vs9kVPzW7sswG866SVh0hSMzFmSGwl27WGYF-HHW820iwYFLNlahdnYkPoq1ZynhWOG5XUdihtJKviRt0OhPaox1V5A3X4ECmqSgch3n_PYUnD7xP1Ma0Wk7
HxdwIwi_JJx0km3mpw7sFYBf0H1XyqEJwtsSZ-9Fyg4_FuS8wXDJ2Ew_Ow15zpuv8bh9AGv_lmDp7Btu3-pPzPSrM2bfxoDCJrt_3k6v_aT0QtpVN_0suEyp
vmEU_ME9Ulh1f_aPlWBC9s4P0Q7q9Wj_6Q0WuFpOV9sFmfY77wXfmXU-WhFFYEXy4CQOB22atckyys7jCpcVpnL2zUtphSZWHqBBil0N0VFsZu0GK9TVVMYY
lWwfHqJytMT4l3P_-DYIlm1tDPZwkm3li-s0RJwQ3zGA13_q9tPY-iwtsi0mgfEUvs_OEdlVLFLt0UwHRRpoy_aXrfv_zNq0X9CN77waCJtrdYRU_4s0-X6T
ZyJYV2mscu_-SWa_-KY8B9FFvPmTxGHnslvTmEMZ-W6OHLADbmyvssIYf2U88VpWIsIaSUeMQn9v-b0pN7D4pzuIUdyTu7qzCGp0KhB8v6ChRWfBhgstcYDz
wUlrsLmYp_uHqFZfwv2OKXJprm7cq-LJrDdEj_9FY--ldS-p3tpd0wRU-1S_rbi_NVKJUKoLtlF2NmT8INpZnv9TVw7EjDEtRtmkXNNzPVAb5E6dJrT_SUsz
oDgV0oYLmrMVdNyK43iVKaMhVtU2kFCfraXZp7xLwTw7Kjqrx5nxRoKw_ov0IYR4Ev_vnOVQo9-_fN8qM2jfwQV2vuJ8an_kVAXTyAN-OtJ-742MSnGG8GdZ
UnzBpyl-MfVGMK27pvClmc7ghzYRVEB3JG7HNz-wLtsHCOjRh_oDBpKHtldk_YBjBx9PgVSgMzy2M0i8SVZYV7T_bFfOKIUD3gxf4v-A5f3wFFbsO9qFqd3u
zlEenAsVvDa8paTaONMz3wcvJyHebn-SlouXpeNfyfc8X5vzA8rzVydHOAtLjF6jWBoFBE7LXzmJRkhV3Lz0YBEFWZS-f5xfEzyAI7q-VEKXtFiehQUDxmCe
Mm5v_-1NFbBjBNxgInN46pyiVJjzYn_vmFvRp7nHdzO-KcgzvKzyfulv94m0B1oypnPmrd-oomyR7ovTl4_MNcwW1fZlli1ItFlwKSDo-iHaLuNz00r0zFKV
Swdh_h806dV3FltHl_ousmF4RN_DWzYkmC_RZtPyvpqGyhv44U6tFjeNrEGp4I48tTqEo4zVKemnbhJsqNt6ppw6yEhRJK2d7rDa8cgyyccwFHM5yFGHdB-u
DPiuHOt9TEiJoqo8x7r__pHBF09gGlKN2-yd4ZcV-VsjyJH-NDHAykgxXVSx81lV9GZRiFfPBBmVg3wgZoou_QEG-_h7vVthUFf48h2x9PdCDd-zyFCXG65c
UyikWiNk7nY-wR2U88meBC8xsYUOxnT-7K38BFJL3VcYlkhRcI3yvMtjGNSXkuNV1D0lVmAKRE7_pR2hQFzm4Fs_-Vy1
}

