sprite $Domain_Controller [96x123/16z] {
jTZPOk8m38LXQpb7JWBq_Tzsnj34k8GOK_hVpDfF88SrZQNGz7SfIBhyaIvEHWHfVy9RqKla7on9ISRQnvSaA7oDf7rqyJjzR4d6tJwq90MVPnzOVEtpIt9s
S_dLuj69fBs_UBpGUqkIgdSZ_Ot5Oo3gwE8nKWpv2WB-SiO8wjZY_VKGCUBRcEuHrV-uRemHNp2c8sB05oT7T8yOyOs43SGOyNLSR_t-uWTqZ-ZxxUB7Rlo8
RsEwLhtZryNhwu5xFVV94Tt8KJ_drmUGutvCKmojPjn_QOAJx_dckKmmqUU9ac_wD5FF_mkJPodulkyqFPxWv2zy8t4qGSbV-UeaOvsGJTh0t_eAO9gmEy5v
6FmLtzoPWwxRXFhKT9X9KlHzTVS8marLBPUylZFllBCLxVjgPYJWy6s2TNHey_n-uAy3IX4qLOkS-wkf2KWxz4LLdJcNXxABYkMnD_qAGf_uigKEc4hfmD-L
n438dY-x1VQhgzbzcJs-_PAk7VXrDKycs8C_ZTp-XnlVEmOoOiXlxa3_65W6ZFZp5CSJdFJ6Puu1VvhdYTQROFS-ftd0BsLevnYecmyWdtt0ByNnNL0GKdt4
9O_vKuQaWyH8b-9FA76vXAJQKpzl0wYIkiT08kDQd2-XVT_p5arIvnYC12VSYkLhXdJy9CXhOTAz2uJ73B-5l5nEruk3J_sKXDi0b-SJHAw-kyS9lWL63d_k
bppgW6SJH7NrFSxXJHq_2UCxBxuywgBVFWg7yuBN_P9l0vAK7lJLptvj_feQttlFdnQtQEc1Lws-PRSIbgy9jaRVZUQwARmV8CsDhpxK9xk5wUiKtlFTPHjm
2rfNTFsTogsRhvXjZTFvF0VzqAzt0Ss0bQ_PrLUUt6eEyjXt-p70q_S0CTtnrI_PcZf-tH5MFrrzzGSVrz-SJj3xEdxT4Ke7FYUJKdmjq1ewVXtGypcfb6og
4_f-7I00RFL5vS7dh79Dy_aouMNVRHjGVTdnuxHDjLXEIwPBtwy3rEzzrPy-uuncgblFRrTaTxxwey-7bz--tmwelltqCqlB6SD-7Q1Td_boybHxrNVvwLlh
WnDHudGvKpRVNlHDMl_nySk5k9LFbvawvhkrlZpuu8bOY_cqJE43ljjFNxNrmNEWYN3RZRQJjhvPwvTE2vg6V9CZFwCqN_BxlXtvGPHugXE6VRltLTlpNTdo
xBRn-pux_lxriy1lSRwSChsqv_liR_ZkMEXhpFEoJ7dFds3seczwxplEsN_qzlvBslYbvOJV-7hWPo_bh-a5tsFS9xs4vP9x_WI-vZVdkrunNBvcRhm-89dT
_UnVFzlrYVBka5U--aqq7_RDbxZRyBGiKpprVUPBlkdg5_GqkJKT-FE4lg-DRpQT-OAVIP_-5pxgMrncx_ZCPiKliUjBwvlFNyq4VSXKTVMdy5q_xPrldN3Y
hb_3tVSFB_bAMYsMon9-uDFo5ezzrUAd1DXzY6cUOjytfpDlnP6lzkqBQ0_fdkya28kyvNt_Vw2ld4L4TjtBRjyD6jNh17JzaXFV0vXXbcrNfwrlzvLrmFFz
YwJYbnJq6vFTr4DsLkDfpMY8DJppPVDBnji4ezkCHnsIQW9O7N1uVQOjusrB1jzRV9lJk0rGRVtrjwR5hnbOJrgQnJzaz6r7_k2dwZU9Wp1J4PLcyOyf0Nxd
rI_qZb_JxuEGklZzX7N0wZU9oket6MbQCjR5xoI0yvRj-ac0_Hyawk8F0lt8T-BWUtpIKo_0KThp5IQQdcNDuezMjEyBoFJxXF0TNvpcdZuomFtcf-eRIKsV
ISi0aoHOUGKSbZwLqTmWGffiNvj_CgSP8LI7Yf64f8y665tbkXaIbZwS49HqpLmaVJnZyVym_sC_uOzzUUR_0m
}

