sprite $Domain_Controller [96x125/16z] {
jDdXSg9040HWfdkcXory_-Uzx8Ado0g4QDyb-UNNMpDIYWx7CGvVZBaK-1fFAK8A-ugEKBH8_BnkeN2_5mG-hBFg3__3Gshwsl_Wa11Lt_WAV6xmMp_p8qEY
WcJNhmtyXDxtMnJsfy6JVVzHm3yCta7kdZ-k-rG0-tvSFpyKnBuVogk-HTLt_OZBypUN0_j-rI_whFg-xyghFY9WjkjxP5xpgqwpVTypB_hcglgkxyhBljni
t_UGfCi-Zdmr_heFxFYCaFvuVf3e-spB_QCF0zsnzSdLIzTLFmC6zw2jVNey-tdLzqp1425_yk7kdGBfrxxbJnm6ANtnGU_v2ag_zgd89ZCp0o1GyKs1calf
bxvvH3fPtHn7WTxrtVw_kVYTRtJFcW1yBDpuiNxpPX7ubMyWQuDeGE6sG5g3KDXvlsQvZ0Vh-Bs1KswdVDfpWEgl2_fdDHVF-1uF6kZwiBSlIyS-msU-xtlr
dNq82XpwoDYUdslVlOsnUuzWHpx6iV5ztvilwKs3YtRW8oT_FJytlXpT1eIuuuS3z6dYePy2q6cmlQj1b8DaJbCy_5M1p6O_amRhDJ3U-nYzQL6cAOCzVnWm
--dMQp3JZe-IJOi8vQZ2bm8rpPLpmTomqWzyZ9CllgI2hZ-m5enZAtXgi1RjxrUtilMvzWUe-gtWqM0uy944wUEjwExZnGUMe-h7BoCDDTKt08PztvRzvZIL
NFdyxzyRzEFF1HMzznpuDiMottg-wcFZFmfAAGaGC73sSUJRL5RxxVgSjw0VVmH86EBC-Lj1tdBbhmeMdnXgykxZdCziaootySYV2wnk62G1dl9Hh0RZRShP
NnSy_ANWnoUZukTyJfWReB4aTtnl1Rpx904xzE6JcZzdvNFjpmL-z-E47mHO9d_nqVTR0HOVPtmcGCOqUTVdY-zu-2HE-1n1qZNTHd_oySPtk_ijTkZ3o_pG
g4zjySXtU_9ff_ORN5s_guADpxjFyDWFr89osgzPV9pnAO3CMubN7yS-SEnxWgHdlNnxVlxHHupBViUfBlZXeph1NHyuzA79U_kTJUxwHfpPxosxFZxWUm3q
SiitlcVi-JZUhq3MXgAD3uPprxT37vdpGxDCfUIBNobmpyUHZopixtTM1NU-zS537xhfZGz41jpbV_7fqwI-xsJp9N_ZOz_twfEQfh7dO_5h_C9-4TxyTlbE
9NFhQ_5JVH_OyGUJW__ts_53WTdFLC_dhZzOnEoxbB5v_iiD0P_zrDgtGx-6yfeOoUJAz_dEoYZE_fXR7tRW3mY5kujCFFbyt3v3dFqnDtwDpdqHc8h_FaDS
VytP_99Rdz1m5BXQxdx8xULMtPjVyefVWyVpnxUtj0Qf-KMN_1fAOra6lqqjgFxuwXlZ_CVfOxozuJUfwuTiE9lruBS5pSUpxpAUzYkoroujzozSU8enV2vG
jlCJC9WX5FL0dmldZqWJysXWmuVZcUaCqIZ5LxwL5s46HM3uGamogtzj-4uW6xuQVjd_rnuS20000008yhTUO8Hg00001
}

