sprite $Edge_Array_Server [96x98/16z] {
jTc9RhGm30HWy7Z60UNzd_TNiR8GPGdR_crwNv-lnQgMvV6iZkKFZqkI_PKEYIJbVwARn3mIVbrVNNGop-ytoILtvoM0_sxZtNjVlzSaIttm9VkTnZlmpW_9
r__b3_t6Zv1W_zjuJFm8-Vyr7lWhFni_zQcV-ow7JNtov_b3WjdKvwK_zlt6cqrzHkJnuzTbtskysTJdYvUlBf5o-xpnjZxuyJgIb2LzDWd8iQvJtzNnvETh
swGlVUOxfGjFzzD_Qf8V2sNckqlIHU-d_j2aZ7_lEwZZfAwtMnKJ7vO1tlju6QdZhI-tYG_OZGzFeoctMqFoMtzP0CSR7xWWJrjLiXkVM5OuX-iBVY8_twg2
XtnTdMJlTuXZxlFUNqCHMCqbukLVbDHdFZN9Vu4OefanuXWtB9MN_h1L6J7p5oT506QC4Z3ugHpwn4zzxg_kMIZCj6quVGdFM_NHNrO3Zb_4OjYQGidD7lpu
n5-EH_-w7lkk-PBRTAisVUvx-clgPhObS-ZhB7zNVEAhts-PluJvLgLJqYS-EVYUlpp9trtwq3Tfo5-0JRVskLMVVOjjz0suxJ_9R_bGzTvNYlOk_txrF_io
m6lrtlVLuEuOV7xN9m60jUhgAtmr9vaHHfxA28--XRBkhUv5tlAFs6WWyoBkcZyKy3XV8FzI4Kn_EVuI1YhaxtSRF_IXohOkrNoG8G86HGccVbF0r8-SBr--
7Vw2tBwYUPJBLlNl-V1ZlgerUd-1U_wncySsAM3kBuhNVBUu-Ai186dBOhvXKi3SN_hvddvkxMEhfez90RFzpCjyqsUtFjEV5Z3VpwWxEn-nBil4xmDCVVfN
BzZF5zZMCN_ynBVWaIfAcwz1CA_e_La1KzzAQRc2jFJDK6FmyICVSSarVSA0lNBmSHDWlfzPTtG-ebkgwKyAUDpFgZklFlP3qrvteVbz0MA9vciwtzVr6zvy
G_MywhJj-yRqhmKe647oqRUjzDTlpjThu7NLwVIHlgXFVKH__PxprUYZjIVzLu1RdpbVThuLv7pZhQ_HVvXlr5qltzJ-JLIjjOYzptRIpm1FypqUAYMQlrYR
RtpDDquVJHV9JtpReiqteZH_iLhUpHVYwxHWep-VhubV0VRAqxUHfvWHlZjV4ygvL7i_vIw2EFLzdE-ndvTr_Ogm1wNOR2WWZuwOiyT_UJDVcE-MIvLbtyDF
dsA-9fybTFdR_NnBQRvvvRbKiTbOWAXBauJpAPzXljxFjrs_UESZPRr2I1aX_oiGgTu7M3TsFg9VgdxrTHw-tWEWV5qWGDxvx-SB01wrRap_Me2Khzt922w2
MgzF7U8rtz1blktwtVTTwFrB-fTOp9_q1PWSU3zVePlA460u6I4Bw0CqdzVvrifl-ccBaFTFtXv-0Ogt-TenbAhEVmpGXatPS3E70ZORvwlHzmZfU3rVsZif
DDoHSns91ZdETzktdCePWAu8nONFh_DT1h3nFYCfDTzOsS-tRr1YtPlEaAGqF5FiKaHSvhjpy5k0mwGYmmn7fF3kQVhODZC_vflNxti_d5z-Yp2SB60y9XMN
19GstwBEFxT45D7zBW93kBi_jHxpnMM-e-ybIi1TEWAKUBqlaMSeu5pVD_Fj6WGLEANx2FBPizxmkez-1X2p1WbPyjic5Krz8Eh6jtxJMu9PGpbVItxmEzzX
utpx02vVhuyyHUbFbABr9e1x6hcVjpBuBba_DLqYHBwxBs1nDP-U-LzEQtn_82dLfa_ynTNs3uV-I7xpDrAv7CaUxs4pW0qNlslyknLpuVtv3Zz95Z_zRFmi
gpQ32TylrUnFq_7q9ybhbaTViKHkG-FdleOcpeeespOqVkR7MEQyXjYwni_zUMzkbkgd6K6JnyqaBVz6AhRyuUcJ_mS
}

