sprite $Edge_Server [96x124/16z] {
jD07ZiD034DHZoHoxd_YtOJfdJ9iegRuoVXBUucnxBSWoTfB7o01ahaBNoGqSeT8IUdQzf429Eh-07FZy5KF_eQHKlgBlr6aaFxgQxb5UDcl_WQHXlGFlX79
29-_V3BNXy_yvS-fIElIfEFFsOyqIhhfJvBHuLEwwMlCTdZV9-NxuJCwFZZbs-4ZV5-wxQVqZez6VuKFtvT-yStmqV31wViflU43aY--5zxtfPj-W8Wn6dvn
shx2Zz7mbSRrKth7BzBsWwnncU5Bjts5l_66Nw1c-U3n-uPVHJPy8XRNry3hBBzYoBVw9yYs7ncB-VvuyEdwcM7u2Qpn3-ZHY1z-5jRvn_moyaj_wQy7h3uy
maS4-S7F15RxovowK0MWtlbPXGy771_piFzQxKJdSH060d23FMCZ9Dx_SLSXMBHB-Md-mtjVdnalIa7AkNG5ICo-_inFPdJdsG4aeyEJlccmyHzAqjqqNHtC
AE4drP_x1mWpwv_iD3CtIQSkgji6U_-H09o-Qk_WxXRwZ_tMGDMC90tdQEYUiyY73VR-aLG5PjPNdiH-rpyE4H6QUzz92SFVDjZxuybm74URc9w-_A8VzMZy
6r-_vyl_VelI_1i1rhwdwVFnL_tansFYmx_HOEbB7iFv2p-XBDP_gy7QJwmI3Vx4JwXShF_31XjVK4kBy0U-dxv8hZbDwx_HOEcBDLzOgiiV-0cUBeQb5Ypy
ROErdzo3GQwrKCAF-g6VSfPGGC-bb0miVFs6dtBHhen_b-LUWAzyiUgJdtx7jzCNrCBPdnlGRT5WvGEdB-grSEF3SDz_c5uISYqs-wC1GT0nJMZZFx9s0bvh
CRxtGNpJFmh7_lHIIyas-IJ2NpJuulnMlFlztrZpqpCFT9-t_JD1qNb_3f_4axzeiF2l1buz-E6diVZXuwPlrmLRQkim-x7uuIyQxCuFhDKn-tos096xlkIu
NxFKOiz-YiM7PR7HRlX9IpfwoRazip5y3NvexozysTP-GjMd4v32t4MRduZ_YoeYhpxSoA_F3pxygxeV0UO8G9HbSEstkvoM4X667m4M7OYhCi0lV9SuFyYy
_XPWBeuXPJP-xOitNr2k3iDV1uW8o1belkULVqhZ_C3qlwz4V6aMhf-IQ1skoiRko-GdoysFfwVfYv_O2_4zhf_s8V7KmSjFv37voSfuFiDoATbb-CfrYOWm
4sp-0Ien-ydhc_D3YkAwsf0KtGT5m6FsXJNhqbTo4m7N-QTDZ7XtljLQkVA5t7OmepvQ7F9uyPNN_fpF3zi0KRWYAAy0-k8dek_FNAlF_XnWFQGfG9j_HkpF
Stiwmvy2x2A0fAfINtrvFZzOEzvwywS0kmvi3I90-4bAxZxc-KI0VQ7vY03XjmOLy_w_6O04fm1KjFrfDK_hlnaWwXHq-6U2_lXShZy2s8SDHW1gSkdda5ep
LdxIk4RV2T1yAN64PTkUx_t4Zjks8i0uFsZiJrYfDRjnzfNnJxS-GUhmarQEvpDexjacNxeFtpSuwmY_DSZhvtFuslwfkmhvWQzFlaYfNFfHDBT-EE6d0S8N
hmLBFmAuKrefkFNbnHSjjV3BzGk31qbmrw3vbEwBeZ-Wbxvgt9MGbEG70HBE1i_dXvfjuQVGsQuC8BWFy00b_3P_UYubsyh7EAW9IPg__M9cJea6hQRzCzUf
wtYu7-WD_BzlvavtvwCtmF1fvbZuEhqeaqZGtvHPssmHbDfzSuWutlaods5ZIBCV0QvA8BGLN4MafCaNpFeOaiyL0LxV40CeeddozNdmSmJmRG3ZQz2uZoYc
ptUahrySf4q1t2dJA1VdDzc-P3P7837_DKRbpU2t_y-Ce-xKmjnetV_uNSa3n3E_32rjbhdvEWz-NSy-lrgMafQpnE1l-_FYvwnqnAVeRT_sCqsCXFVzpr9B
3FwcV-jLkFl-7xvUJ3O-_H5_a0JryMV5MFmVbN1U_3y
}

