sprite $Enterprise_Edition_Front_End [96x121/16z] {
jD27ZG1124FH0Ood_uvlaRYSp0ONy41_JMU9zU10alwK7cHcacbFw9x5ryYuNRVM-m3z_ZH0yxT7yjAFvVj8uiOqm3V_faY6rh_xGYGj_Ay-YHl2_-MJVYLy
8k9l_tmaa8ZupzyaurJuqWL_xuuq3HyX-JMIq_0HYlz-O1vU_pydlfVk0p-vTTyhZRlkCmTzh7NDRrttWuJxm4zktVVMPJ-pwFQLDEwotxhg6vXX0p_1BVeT
timdVgcIt-7jcEo3M_Gxl3Kl-I1btq26zIGVoPhaT_Y13v2wN_fQkj-wxiDN-qh_IBvFzDtK_wFwp7rtwxdzwMUDxnFzelx_Fx8tzDSg2l5t_y1BhVQYvIWC
WW6u4k1FeiVtVzmzWhIiJUDqBzdxZduaaDASiQE3oK_y8_raKwIFyoz5v8zzy35pstmVyk-JdmIOvWUm28wKWS_yLpu3skI8OFT6XCJF0jpx2rHhypM8QaH8
-j_v3_OtQTj2RBVmwLFQ-hC0StyH4SQvWnO6WCfqwZ7-mZy2i0VWiX0nKAj5-EJBT_w3cCy0dXkfjRMI_Ea2xlrbEJ3OQErOWvW_MS2N_cBr501IZZS4qbQ-
Mi3SFqOqKlj_zoSB-DhtuVf2oRzTmDpNxCSwll41riEd3pw77thoxmC0uliEAZJogPRaqrT-wETnJdaP-DHfClzP043p_mAgPU2NZHF_Sp_fFb8Pia-ywNZ-
iorgkbnsRIf3ygbiAztxEO1g93wDGHcKvV1BstNiZnSmqdEIoij7EVoYkoM9vZxFz0YDA4FiJpAbxXleCl_X0gw97snRBuFxPGsbRdkNkS-cyrIF2BoOJx8-
5MthlbRXy5E0O6_q742B-IIR1685ggqfHdxMvtmaoNoI7U77TIF_TlBN05ML2n4LtZQv-kCJz3VwsbIv-bcaxLtkVVv2xwlv1399rYF2s8y0LFX7F8x9h-u_
k98JkkuRvZuH_rWF_w4r2AdhlhQHNyAdmdgN6gnhx_tfFsfFvzWZSRqTFeryEwrZghT3p_u3cxplJtfVG27olmAJrFJgVd_w3zaxl_lqvfT2_ZS1XZhMjJNt
p_q3FxzjcqvzOtEjjKBU-BwsPdvhaHyHFw1Wtt3nBmieJEUVDWGLadMjXsv-U-MVue12sBSwyGjpfD-7QAr9X-i-_-HJbpYWoBflJUNp_Fq_NgL2gn9wRt2z
NloofhTtgSVchUp-PG6K5-0hhTqYjDvgXUdd_DVUtJy2l1-1z9DFrvrSE-hQW5fX-kctS_wcz9qJdtmQpR-uhyzIDS3yMgE-xPaVjPjqx-NabvdlUedqd2k0
-K3Kz-2VljXTlEwD1lEdaUzy90Zkevx-fRueRiYsTylIP__rydtc7w_vLxX-hU_APrAbxrlbo_mf-ymnVNNU8bHLzqrF_I7s9p-NhMtRrYfbx1yZ9Jy2L5ph
swE-v_aMEQqAGF7qwUAdpNa6UFc3-f85w7pPrKEVJjqNu2FNTzGVs8I-O-pd05peJ8v40AW2m_f6_w_50EoRtlk-3MnmP3_bn_bSttI-RVi6kV5jkFygBwe2
r_xGdlalFPzlTU1JzlEBQrpVtF_VphVRlbRS-Npwo3vIV-ZP9zautQYr-VaXZUp71lBSvFb_wFz4EZhVZlqyVOyG_hZ_n_bsvPbFl_U7N5z0exx3_j_yxhwt
EvySlxvyWOf9_oznljts9Xzz6lbGSN_M_qdI-NR5rAVJv_JY0cxwFzNN-TQsvz2dmtyjW5DvCUx_QpzzQlbyY-Rdsw7FqGPJUQ4LcFL_ehRnR7_wSDyZlCfh
yA3_jxp_2_R6F_KbyezuUZhj3xvssJQzz-CAHYxllF_7xgxxfbEVV7-AZufdUJ7h3n9-uRvlTUwBbDDdrce-e9ZqVrP9XpBuzfpu8Xu0JHa-flt_iQZaKx6W
hzlQwsTVB4NelQe0kRwjrNRj3uy7gPJat-Gd8i0SrPT_p3ht__0VYshoRNpmIthZgZu0TVymMwglyte-_-Nm0M7kFFBBuSRwmczMO3sIutpg3r1E3sd3FtvN
VlT5bJaTsdpOT57FkaP_yBqZItw4BUQB-PMk_Y4lTXsIhqMSjraVmvTWEbqVmMkSYjSYl_j5dvUJ66sPybS-n5SHUhE-MIOV_ulwfiHJdea2obBe-Us2PZle
z3tneq6iCP8lUhsyABGioviFqrFYno5izMWvyPUnY3sqV_dmahJ-dlZ1lMfBpOaVVs8Y-TOpT93uyRrgVf79vKMr95zLeDV4J-v5YyHFFx6IVE2QoNcIzFPo
4fMdFte2Cx-NVlOfjgXl-LyV-1LKA2__GuzK2Zt-tw29_Wi
}

