sprite $Enterprise_Pool [96x109/16z] {
jDG7pgHG30DWOZlEjlkVT_NqDshULAjDWGzXa9Tva5pUbqZR6U_YPMUchRVejFCZDbwkmqvzy6yeAMHBA_-r9NteMz_cwugN3lwhIe8jdlfbwmN59tdXLzbu
kdWsVjKp9V53xtrRZnSFz7vMcUHZnGle_NHL-S7Ya-ZzeJ_eqnRG-rdrumVkMs4XMd_eArzsnZt5HxH-kbO-xDjNMywXjtxMAhPlNstOZEXzkRP-ViREcEcA
fVULzeRFpMDNvtzSl_CbZ_pmUNXjsVX4xylU-9OElZCQ7xZs-KrufU_zijNu9CvzQZVD8a_zAfkN_GGb7droRTX3l_JheYGppIMarCwdSeCasVbLrgdFAZD2
wLpva3P-4hsVL_wIzYyZa2v_-g1MVWuThU-iInzEMq8Wgsf8s28feFM7VkqlI5dIKFphTv7Q8BVCTkilaEpH4e7wBKe_odosNJD_2P9fZo-mLZSmd-siki7_
oBBiVCvcMww9hw5-yOEolfJvR6VLrAyF_uDP-PpEjkmRVDQ9JzuospVvqEyu-fZuN4z3xoF_uEW3VJ--tOV-rTwFPhRNg-sf_xzMUqrk7GQX05mZE82g_Q_t
5WlRsDKqkIz-zDqFXHCpcTOQl-a33_-3mgA5BxFUzHdnc-p3M_NHDieBxExBtSShdw3pOMiVhdBugk1jrrhnwrPzroVqSwnGrUcpgclRMZ1y-1prspx9qCC7
b6cVFw06RiGXSFWSjNW0h_FbFl3qj_YCEJgecfQjkl85-q2_-uqbF1b3Jv_2FxOsmCJgkRRN3m3nvVtzOd_Ap5Ty3DVYnpDKO5_5H59yllaA75zUl4o9pzMF
VA6Mimv_FZFd2xpctDhIH_aQL25qz-FDa9flgDEF3lDjzMk3gaSzOm3BrzisNEw-KDsgwRU73yYTZz9R362qE2f6H_L9jxLVmAhNgZ60oNW_gdZ4U_hastU_
5HzOw_cC0Xq-kUGcRb1bfC-Z_UIlTMJcUiImQrxF2Zx8uG__R93w-l2bG_X2r33quKiBS-3os-NBI_qSKkHB-tesgZufqRogxtuBzOLU7mAOyfbXesjB_mJt
grgv-jdWYIzuiuwPRrw_wbxpvQd1lRiKF_2NXuVPv-VqMtU-Nx_PG5jQ0CBF1etVqBL_JZyQwC3bjy0bHZI659yEFzu0F-cgzjdxz7NFjm-z-Pj5lXX35twK
P0Ui-D0FdyuWNQSVpwEFp5TZQQTFrMyCO7ru3VpqhzK8_ofD_uDx87lgtVtXvtS0-Qx7ZsU3p3U2BFFVjl0_UA3ak_0PK3pBFjrtt_kLhmzv-B5XQVJYHogN
pr5WKKKj_N9tty_vw0ooo-L70yJMrk72wRVqMpa_iy1AX-vcmLkTlzEUrXY6qzz8i6_jo1UdJtS_Utjsi6u8t-msV_OpoCWtVLARMxjfF6If_j40mZAdel76
BVpeSC-NXzHyqoSTzVNpzEdkC_89QXxwz3tzdC_Sz4y_DCcjlVPR-Ca3Pfh-cM_nMmPPV26AhOtJfrbb_Wro-QhH0j_obJnKhEVY4n1VbZwSLpvdlf3JLxNC
jyoVea5EquUxdVdQzRAzkvm-nTVI1tZo2eCUyxSw__WBNsjjbQzxgzTlzRC0bFFVvj_zy3y4UHw5g9HyTQ3usze7vExRRVxvzriEoE9D-XnZap6K-PlVYf-b
jtoj-56RG3WWnk4JE6BHCUoxd-Dad1rglbRpFVz72eHp-UJO7R7HtHI-7GtuV1a1IEQh9L-_vvj5ZAYIxx0ZTcZro_c3N-VhrSyYn24yzZD7lZQ2EUU_RTMF
Wc3jr_dNQe2v40F2UxukF_bI_QYoFujVYw4014tRpBVZyhVqENr04eSgr1RxS_d_QYAqusKTV7JJXy-p0-hnd_bwFNyjYYGQKPSZNrLx-fp-k_dMIh-vt_AD
olbNN_StY_tvogUcmrO-7xxWwA3t_Hb-r0k_iG-Nwc-xVtHG2EhrzJhVh0tH85-s3zUddwL87lR3_bmMeuK_fs1kXxyz_1o_tdsh-QwBmTFFrx35pw-osZd-
7_VdkXfabw3CngU_4VFqXHbwN5ulzkUpwjOEdweVCeTlaBs3selz-U862oYVFXrd3xyRe577_Esyllob7qK2e3x_6GX_jWZBWCll_NPzzOwtRkE0GdQ_0OAf
HrkrA5LW-jtxbM-Kuir_FQixxVeMiOI--xDSzn1Y95xpLRJtxrbmPe2EMEw-creEvihNmBzvbn6NHtIMD6fgejFMWtVmzZuV93yVaG8Y-P9Hr6rFEOUZeB-_
YqIbRTlfQrJuEVY_BW9k_bnqEVX_Kemo7zqNLHdyl-d0zVnHzAzlN-FJryNW_qKCF7q5_wzxvCB_dtVX_UF1lt-FuYy
}

