sprite $Exchange_UM_IP_Gateway [96x105/16z] {
jPc9cgIg4eJ7N291yFrVzqfYVeDKtx6qFN4MdEsFD8AkHkVFLoA5ojAltnS1mgAG_uQk429cOWMzJby4miGYqXReomuCPMB7kuD0bbU3P_BXGqJlrR0SmSke
zsgGHYUU-FfE3HwyqsU-gX09vBTxCkWplsceuNdmWP_vhY6any7_WnyEowFWoV4N_4SrUF1El-H73Nm_UE9B_gCQFFXRVBY3V5K3GPdkyW7r6huC_W4Vy1he
Y-1lyt7eQgzAHFDWVfUoXtGH_7E-rw2GY-2Vyxq6Llsi0HBun_c7v8SQsBDvONxNLCFhV5Dc1KtbliWtq-aZ0nd2x-JlV8ESJXb8AIdpI_Exq4AIWP-Jy5jy
bn13Wj-KJVX5lX8nbk2xClYT_7tyngU1xo4flpA_SYFeD7_Ky5k-ny22El3LKjTgOV2G3u-6jTIH3oIRQdYMlv0FdxTQru5lwyeyXVHWVkrqgwxE9y-_R4Ki
JI7TvNlmZEeAlgepwxRbaYqS8gGRV8_6Wp_puT2yrb9K_5xQ3xEwmmN_CtWdktBd2_IOEPTagyVZFqn2JL_Dhpm4Vvv_0TIEObDUqnOXvQZXagz3y1FVRy2y
WqCbrRZCHmtyB_uS_Cpt1Y08w5eqbxPwL573_-5_1Z_b7tTWa8XbsrfKplV0vEoWPqNmixQjWeOZYfcAET5sWrmsnmyry0_yCVYPNZDmUj0rY7h-PTtvI3M7
GTGmyuVWjnEzuOj2pqV4gA6OvP9w3UwIeuOJNteqoUdpy3Lzl0vPUaZOUNL7RrkxbTnYoZcNTE1a3jvvCpshmX3aiGRq6WhILjTKIyqxFkMq5kEEd88FkYyz
chLDQRvz9d7Kq2QtdGyj9UKchw5ZZqLNvytq0b4pw2S-Qj1UG-EdQcYtq3hF9QkZdIxfBtrOYZdzbFrS0w1iQOUcYhhbcjUIMqpxceHT4NnPoqYlIGHc_tuW
8-mIINuFgRQszqoFa4g2Ab8fExTcY8Zc6j5aTVhb0wKW778nARca7TBvkqFJkXQdkpGvFMcFXhzvAUOXmJ-76d_BMdj4xP-c1DqbNIYrY215yDSY3OS6D0y3
TWW6fuyE99RBnwwvhi7w9yHMeI4H7ULyPUIQz9Bw-P4X_lMR1vYYwMIWG5vDxxy7wbyDEID8WJzRgE_AHoyGlGQRXl_1uDxmyqV6FFnimCzVZ0g0m6EMXwz2
o_ByZTmoPMExWkvYMfhewOjHwdmDUXWeSyCJBTJ_4-WJ1mdym3U0cGN2v5BbF-uWovDy77_YApDRhThfULVoUxXV0pbUCHg0YMIjHHoVSfSr0rRmBJxFXrb_
FYIhDNaud78ewOCQvAVJCkTQqRD99_5ojuOVNeUHbheAkT8aeyL3ag_nSZ8uiZ4cOZTGcwH73L-591XFLOxdjHRrtQcywmS7NeZvkneW7yUsjMRX9aq9xi2p
Wp8nVtCB11aD6XSL7BAoXiEaXVqEh_dAuWey9_LGH9omhZugB_o9PyLr_0tRvVWG4OjV2D7IQ3GuiED9BlcAF1uK0kvN5EloPo7oYnYUk4dqYgzMg_DLHX4T
TdGiHE8fBkJ3-q-Aw2KVQWNG3mSc7jOccFfFBCj2WR_cDonCHmTYEIxau1m_jWm9iUEl-Una2tw4ewVPOqKfEF0I-0l-0kTg2hoECySQJfes6xAvuBk0Jkvh
wrEF2r-5E4vqWLIH0I-Nsp-s3tSk-wf473znE1whyeY_FXIfsMag3X99lo2AFTyCPSGdq2MVa0h2G6BaxX2pgwSbn_21j-JyAos2DSSji08Gp-Qum2vTM7mT
yIa5_qgaLeuD50vABFq2K42fySKLsQHaXgyFeMD8wAFt2n0BNFmNBxR3Rvse1IbZl0KmCOvmj2qdlDCXzvu5rjGDmW5on7za4tWu_VP1Zc2h7GxH9xD4De4N
fpywY38immt2WVqET9pUwU2dpm8fXG5h8vcDsGWQ_7T_DPzCmm4sutlZ3-5HGq8OoFZTNzJn4VnZ2SoEcfdaBnw_YkRpLLSJZNZVaw-853ruFl2Yy3tvcXYm
OL_YOay-VMwDxuKNmJ-j0ThnlYVV5m5mUWJ_kcGA_dKjyk_W_mS
}

