sprite $Exchange_Edge_Transport_Server_Role [96x113/16z] {
jDI7qUm020FX0wHr_nM_uEFFmJYfW6-OTNZiMRWUzoq4a7Vn1RR1SOUUu7N0zP72OFUkZoIm_3h0SMruwOD_OQJqgd_nhuaKhN_rBubK8FtWdu-KeAhVVCXJ
uQis_CEHelKDVpaOIQ2Q-Ci2FXP-w2zm9FpGnplz4AxCeU-zznSeS-XxRvziVUJRoxBB3-FCgT_ws0-rFlBDiiylg9pvhS_z3XynyplyrE_m4KDVyD7_SOgL
L-inwIC3cWtY6Jvw6txhg7AqGWcAcFfYNULmUlw_XxxCEjTmAQYCzZVwIt38pvpS_xTMEr6INWMX03pXm55JNNd_nxrNCObbOwV_ZLbxoOUe8xF1x7TzG1x6
N_NVyA5jxpJiq_YXrk8tV9__fiZ21-Q3K-5nJInwpBUhhwq4LJMLo8VTCVdRTG1Cjtjw7tzAdg42xxxgqbVthWJtpREQwlymCQMQeLq_-Hhw7islqr75Tckx
RjNelf3CsMg61k3ovUtaVFCtLTKwKfL-GquVcpJ_HwlV3-XsDgBv0ltILuN-xuXEFjpV_485H0HCEMSLrsVVHj-7VEKIlNpFYTFV_EGoeq44APUIW311D7vN
vVfiSr-ndVvMaUnHC-IbRwDVztjdjxiGv-xrRGa0e6LeUrNIwAl6lYT06_J5otaNxlbl8VsWytQSi2x0z2q1fBx1_QiElSP_HxqfiwyBtndqND8-nVW0gJRo
NeRxom9Cnt3rh4R6ohRg9vdmoDUbxofk5DVmtPSYeRykm4PRQWdItfy99X-xFFiQ-SvTdtVNKzw-w0ih7nzzTCnX6Uzh7DmNFVZeQ-2B3FjUCDo9qQyLx8Xz
VEcBo7Ydt7uM4I0THNx7budtEx7TlhBwiFqecFmWGUnNKY4uxvHjm-bBeZJ7zcFdh_fNNBUS5zz8rPV2xbZQZrSsnBv-ydNo8VV-bBsSZXbJAONfzX7ucFtf
vYOoxX_iByL9iCRaJmc0JJ22SprRuqMgtnAa8ozzN3oxxuE3Bi8NjyyFV7_QwqXht_6Kk--NYyGPSF6elkJg0poEOg6FnW--OkiHfTZE4EzVAE88zsDFxBvW
z6bMVUsyZYVYk4IGyRJl_TVsXlW6VRtsaYRVQADliicD01Vd-OO4xl_mfHZtJ_El15hrxckV_o14_7Lu4DtVz2YZp-wFlANRLtcZem3Cg5RxEru7PzyJL7ts
JKLLq7_q4JdVfX-0L2dKXDRWq_7Ykw-qmUVmDSPlGdweaiMBpCShZRu8NE--0Z3tfnooYBgqAdBrNzRZhVipNpK0UFCB-RCAz_72lQDIsVS27x_xKmaw9h3A
F_c28ry9FDZyaOfBACP7tmzG1BxGvg0D9HGQ7tq_t_9HvDrtA9YazaaouxFV-w_M_ZlvNa0yIIn-utbz6VPVcGk89obbkY-8_R7_wj1_PIeWN6UUwxifkKL-
s7-pfYHJ0M49DFU51cBfIz1_vNC1nfwX-KR06Fkz_vQ5hrm7071llW94w2_whvonvhq48yLeYmAeY_uhGG7h3FG2Gb_7_fiv-yBFqHCOG8Q-SEw_sVsfW8SI
J9K8VU6X2FUF1v_2gazLClR5ZlB1r-S4naK1L8e8zFNYqXUcfs1zYmgWKaK01Ftt2arVHRqORxuK-Fufnv5ZtmlWaz-cwTt7ZXhzU2kHhpuy_de1td_jEjzO
zdqlrPyBy6toK039Tr_qoC7-d0h8oKfMycC2aeZxhttqXIadAW3bWy_8h_tNFlbQnuyQIdvE887l_TVMlZ2VV8sl2w11vEg_hxJqLRjkMqtnRG6R4Tq_DsWA
VUa_Q8XV56N8TOsOfnMe2J3qN-PIOj_kpI4rGOuYvKoP4kZbgwao7h-IEbob92EVzMt-OxkTVavcHGCVR_yf84RokO1UhRfV4e2Yi-yJFmT8XdwswFy5QbZr
Tvby9R7wkoMV2l3Ob3HL_vvRtOydVgwS3FnjyUzLqzVNFF5pnElirGOPuFZWmpZL-Zn9D5i_6TLEpExxZdyAa2DFRW__XPPBgRxwNuYVGtdhHdt-_urKSZJn
ppv9-QhW53ppqMUyq-99mi_NOJOF_Zd3zlEhlW_-NuHP7_o_ytsh_IlV1__FGjQ3_my
}

