sprite $Exchange_UM_Auto_Attendant [96x96/16z] {
tTQ7jgCw38LXg-mjU_7-xtj5YHDcSXX8p6t_gQjz8hGbNWrQhaILIwd1B_bIhYK6kzClQjGx_GAXtUcRA-r6Nr6KTfylo1_QRNvXwGFkyQKFkCyl0hlFxmDk
z8l0x_FxWF4-fEm63FTDrUPK17w3_v8xXlj5-ZzgxZxOtoT6EUNBrkK1RgTyaoMpSZ4xwPVKrUJ_uVjBoFXIHFZdlfTC_1cTl_UDVp5pEUFxuki7Fad0v0y-
V8aNV756RMkLC1dw_7ga-gXbGHldQtJyEI8mohUklzIcm1XVEnyrelivm8RuiVdng9yYoW1Vad_lJs63_CvpvpVyu9kPPoVNihh_03KU_aHvxwShStx6T_Qh
s_Ki-IbinFidyFR-pAgVyT-_clkr90E8N_JaiuRJ_l5BEWWmukbF9_qJWIJ8gFqJ1KVwp03Fm6mzY-tOboKxvNVUCiy0CWxzj5NLJBxnMtxxzyzlzsrfyrdp
UwhslI_lVTRv-76R7pIh4syxFr0rdoWt-H0HjP77lxz_JDG54zxxijsWfmRYZUygDR-h3NY-ZCk07a3wBDX4-UhzuArvAVh61rMrXPSpllpK_9AX2dS30B1E
pQnMdDsVto_caNwhf2y-dlmq1QC6v9HVRCxDj-zdR2sXfimmj-XjQX51kdo_dnimJKGV0DIfCLYFzq-xi9-B9BaDO5rEJKIjntvsOJ-t-KAtDlyE9i-QFeRk
vxMsLXDV-LPh3FMBC-lyx5D6-k8FFbfRVSWmNm54B7njcmyGEiHNp2MzsDtF2FdUDsHULx_pTCpHl_G5QvLHiusl0NV7alxkcsSWxInlTLiFMtvbuMlz97sw
dplc7DKy8kfMmBUm95-yV-OiGenz0FqbP9JJ-pCozh3aLY7YZAn6-3xC7VXoi9cllAEgY9YJTBCtFksZysEhRmpfsTAxCtJTNtctYZsVkUq7-Az-fd_mfVlU
-PxlVRxwecgPomdVPzyw_ynjvrltJwVTbpMrrxo7kUk-RRu_V3lm-RcFwFoklI-NVN_ux6VduFpOvpvapevzl-nZvwiVyTbdnmztk6G9xlZlVNtu9bdoRZst
x_s2fTL_U1t_ZR_k2zOqVVyfz06cLpCi9My_yZsx7hf_ukZBzGG4u3yVFfwLZp829l97dLe-Iq0JGtQWWrO-pjYf7Jw2xrVXE2tV9NumWLvwmoUG9cL8OY1_
iUbQHYPcli38JAMyzXS
}

