sprite $Exchange_Client_Access_Server_Role [96x109/16z] {
jTYBTfim40HGx-nBCkR_VxU2nLuUii5DCcsJu9np1vP4gBvz4HAv_M74r1H_fQFXgcPAVwL7pEJNTPBGe-3NXpJf8fi6-jtHY6py5lbbVU-RyYyDNgJh_yQG
kEdSzIFoqz48ytlVtPH_eYlpPz__UqWaeP_uxlytfAOBd_eHa_yR_3NVllOfzLFVrDE_FdZWcgzVpuTD1RZcgtdwbmSFNFDLlxs_5FerF_JmBmyUkEYhUVhQ
8WAS3Pw9plr8wgMbrbBSp0IV1azqqPSNNYSvKblSbDuEdYxwOgcNRQO6xW-Uw9el-kHBwFk6mztcr4zzaTUwyDHzoRDWCDtmQj9cTiaNKNlwDVLjmJ1iho1k
-XMVD-jQ-fk2UdyCnckV0RhavtDnEdtpD-V_U5JR-SodFcyNjllZSGzyF__cFqpsFlD7dsNxOFVoY0mfFyVJKdNjj-bZKl363tthjuAXbd9lPtlFXbfhj1fM
lYZTYAK5NPyramLUj4Mq37DJwFT7n7Zbixk2Q3vBfeClqlTzzbkqDd6uDtruB75PpySz6XfanZjVv4s1BJmpJnUnIT6rpsvMey7CNLQ-o9dF4VNYsL8t_atd
fuKo2Eej4Zv2xnViV1OHzQ5x_ZTIrSbd1gQ6KXGCbZC_-FIrLFVxqRz1HLodp0sbbChCdmjwlfRYVhY_BH1XzJaAGF_JzzAo__cCvIrkKgtLS2Fmx7FFrqz-
dVt1QEr70QOGnNUmy-MgtmhswqFmaU09dtnz-RhnDVpxF9xqHRS5Q0b_Mz3tPUtxvE_NPt7SzlhtleHVoh1_lWWARXt_j21yoLN4M-xnmx_n-Oxah_jP4Bow
DhrD1piV_93E-L-zW4YCvn7JsVdWqPF_njSDt_pOFMny1fY71-_E_tf1yYNvzClaiuzt_jwFXbXwlBJexU2pOtRgU9UjVrwGYGUzyT67UJXQnh78Dxwj-Jhv
ql7XvUdOzFjHJD8_MULUkjVPLwQZ3nyadxJcxjhp-y-Pu6iDlqLmyDb7Ixyb_PCBK8-jIVXky-j2Qzy0PXq7FVTbxSVxYUcNvZy1Jf-DmIrblEjtVWkhFmjA
I-SznbPLGj4w3fx-MK64muzubfkcJuCiY0_ZKBxmuL3tFPzN4FuDe-OYMEv3zV1F2-347WKvd2p8_ScZyFxd1nzyIv_Keq5tCKFur3xIC6h7Fxi0CIAeJs7T
ntHPtoQVRBphriTRtpJIJ6e1CvCUOpBxOh4_gUDW6__q0jY4bd3FDvfygCVp5sKSgwMFwpwq5vFPHocqHBojRzMt_hvcvJCYslVrjRw1Ne68OFQnc7mfqYd0
QttJ_VugVG2C-1XVzDCfC7ckRp8E73ojV8H_CHrVc-yyCtMidEUVVWRSJtoZwnkPeF0SgUEW8Ehxvq7t1ZIV1rwjRyuh7p_r9VPlc_NjNfH_ozV9Xun-NDyY
pC8NyyQF_Tke9tvk3137U1v_zdF_fciVpnnzIdxLX_xyD_itw_fBmey24Sv3bYcWdi_x_PjzzD52JPnvYeF5fuvlkj-_rSSuLFStFZtFL5vlwQGFEV26v_h6
-_tRUp_OuDEVW0Clx_PlPpu5dtuBfCDtzszz7-4dl_MPPAilptVntB_r_UC548wl0UclDg4cwEpVkhuG1Ooy3qIqwCII-AH73kjRUUjd0OimqVmHho8HMoBO
__zqlt_h-i44E1TWrsog8g3REltrhU-7kXuEvvT4Oibk_LZVpdqE2gbYvVCR_snzazq9y_I1DhUNpix_V7qBBR_EbvRJHzTNPU1aVKkU9S8v6D1o-Xp-Fc8C
FblVabhu_0h4d7wtG9Wlh6_0q-TyDRPTbFFf5wGVT-2DZvSfmkatE_rEO2gBNuorojvFDlayQ3WZvzC9gQc4hyogslEHuSqH4GG4XDyFea7Lc6lVv-rBQvzp
FXyRvhZlvWFU-Fj311_pEMcmm--NI0nW-rQjv348Cmzg_ac8GzUdpseQksgMDma-vtCIn5iMzQch2cWA-XK8FkTp6hRMK1beEj-MDJd2Xmgc5v_-IKZCYaey
_-SvF_tSKmipnn55aEldUP0FQ57GAWWrgfBF-LzkG7mXAhGD41_Y4v8F_yl0X064-Zu0iyhjFo8c6URO2SO_sKIDlhNpPfpdpTd_0m
}

