sprite $Exchange_UM_Server_Role [96x104/16z] {
jTe9hgiw48HXkghSnWZslzsd1amWXi3BpVarPDHdf-KCT-YUnsJTtqLtT_wLZkIUahlZBtHJw95xihyOJL9Q-lsG4Bggd_otGx8K-j7_uP0KUkkxyqU3byxy
dmm9LM_z7mmf1azU-Fy-98R-sS_V3udkugsVixk-73pvnC_ktmnUv2C_UVPl1ezxVviGthlHdS0ZFyzv6ozrSnVmqRVRyI9TB60A_Nk_HiV5u86V-72SdKdQ
RtmJd6zwSfhzoEzI1-VxuEsN_c41UWhzYIz_w7VcV0s-iqU-aZ_swm9fkNZWI-xF_Rg04oj_uuV-tDyMS08Fzi_a_joVavWq-yJD_XdJV-vRr9cH2KwRjGy-
cLBZFmifPcJXyCgdKkF3321kVNDdIjOPfIHOuuTUs_kT0ORkDdSoPy5iTXgVaivzMtp3AsvXvrlENbAi4CBncOfIxTsFyqsjxOVeslcTtBtl1SFyCAiFwSfd
zUyAlqkU-bw2nGevPo9qIkq2rJU0UkeZfGK239xxU36GBlocMx_ROG2yxukeimM-z6C1gfzB1deH-KlV32Jbxh8uSzLl5lZQDmDWjXw_yFb3FnQek06Rtowm
Ri00aFU-N3dC6gBLvmS_Tc7ixdCcNVlj0XVlt-DlnwoTZwmBdmzyR17Smjv7IOtFTr-d_dtEuCgvpqlV0FAnppBfiV__SZb0-bJO-Cq2t_Xq8g0IA_o5ls9A
PHhzWwzlVGvQfJnCOv-uy_a37noTN8dvuzzFVRry0A1mprluq5Z4LV0e_7Q1Byw_kGIGPV9xNoV--JRuyfd3fq-Zd_hyx8EHg4DxttgGfF8qzJU-6lykE3kM
bV4uFetFCzyCu4E_qrYLv7qPIj_wM_ZKXTzfyb3syyUBv_Fin8_xE0sD_rKdVX-NLgPozF4Jdqwby8t3LD9V-72V5p2ME3wRZr_vA3duI7aOXfBrMn_z0Di2
YF2_MK3hX7NqcQUqyT7N_XggBvS7bAPHjlJoSJp_i3NMR0sRt_v-emiasK-3Ad_kMrTxlyDOE_6t7slzD6L-s7-tPHj_zAtnanFOlX-zZ6DnRJwQ_LUmkHdX
mkUO-VhyoJcdWryBS5t895GsVCsPwTG7Xq6R7rKVxxxcG35uHJiVZUykXT9F-Oblknic7NsI9pupGqdZb4zyNFZeZ8qlO-jllwzyd8hV-9sMQ4OrFizz3UJC
f39E9Hzzl7nQbOJky5R5idsOxCXR-D2exVpalfI-zUi21aM6xRxAYpJ8cq9ApVVZgI-QBHWODx2iISt1Z7GqlyyPnZYcMpyosxRE08yFKQtF7c0Sq98U-8Bj
PXFa_eRnn6SEdohJuBT-HTlh21ydFZolvwUln-VA9xYeY8jr0TIbhdpamdf--Z8CpVavdGUiJXqldwS-ygYxyrC9rNRxnZQU2vzfwkzzEswVhrLHjt_bnm7r
9_wBn-5ktFYaJsF-x0EeFc3SV00okvgFS_6rVi0zyPUx-V9fXdE_atFru_WCOnoV6ny0jX657pPHvzCkG79tVdA-zBUEDuEUVOJVBg2zdznlVKhYdZUYdlys
U5hzFakztdpotN-_e_8uzpjBhZdFYWNsFaXRmFObRJvM7ewR_qGXzNxmwyvq6Gsq9OP_kO8lltuFys7YzXDJvs7Z4VvbaDUgJ_SasXfullqNN_shaDopfxJw
oPCI2QknUHN4uT7MRyUK-txsvSwE2QJj29W1dCEIlGh_BhhtHQ0xurQYxGCh2ZG-mh_Dv7dxxnzmmeujudhlteVaTky7wjj6N3G2TXj0ohjdOJSkxOCaG1BM
otsftVvza3zDBVyV
}

