sprite $Exchange_Mailbox_Server_Role [96x107/16z] {
jD1NRWGn30JHOUZI_K_iG6Tl8XUQ1lJx8DOnMSYEynO0SPRkGXB8pz1De1h8paYZh-sFvA3C7tzl9DEx_jVV5ycoz0j_KwGe_TBV4yb5yPV-ZaWLFgxx6o8b
YeYx_WBvy-7ZWR_Uzbma5wK_-l_xu9dm4KsVnJnDUDElDzUzvIzK5mp3kpTzhHgZyEvTVtqEtLfSf75_x2kxGnVX7_lAQ8_u4zuQ_eIFrA_mPljzYe_IUpvZ
to7CcdvEVLVfFJ_5q1Uoe-bdmjGd_UZvfS_zUAt5NfGSrM4WW4RTicmN1V__kVVI11Su9kDzzRxmLFP8iHNO7TYKpnITZ_Qn7twX-I1-zEafEj_jrNdz6dZx
9BxxJAdvVaR-4NDtscMfcEs-ohdpsQUdFRsFNTeZa7QkEjzX1ZKvzAK_-Zp-8lHkf7ZpQTXzvjXb3Q1z-kAFZFsseFS-TzzoFYhiW7U-MfhnhLqstod_vJcY
9fXH3wMBZ-xE_E2BXt_w9j-EPv4V5NAEju_MtDYdDOdYMrMu0iX_CLBAsPsxctCkGH1mx_qa_rh0S4ZcPrfHkl6SpvHIzZsgK4h9e5yozZNJUXqeK9KCvtIQ
7_vBByfA8k2bL2S7VhhxGj2AwP8ybyqtCv1CEUTQgnlWixxw7LtBXtmLqEJJdVeuOlU71NfVRO-kRG_F_XMyFzulpFhasNPt8CxcenKGRmR87nUGt_TBNTzF
N9f7i0nk_yz-klWui3RirmBokFiUO__f3NGds1QyRX7b-UuZvSPF-6dOFcy72yV5HouJ_Vitdxgw-ARmy54MZFlddC-TlFeqmyL7tf8AVFFzqITsdk3R1ypC
txu70APruSZdLn-6FMRGyhrIxnJ726O29CjM-TtttczHvqHBEs7jJo4arMsD3v-VFjdxr9eNd-8fdyi9vMLRiildeq_2AE_2tmk8F_S7y3MHF8GeTQdPAnyB
d1_Dnr07hBXy-9h94uWzttpQ7f0Flhflyw_juBAcpdyie4bHm77xFFdTPmQWyKbpFfrs1YGx7MZbgVrd0CVurBZuU2f0y5O01W4aO63Zs_Ch0b9ItTOIF_eE
kuP02_NBMYZ_LSkfH5tNMh9yZ7pN-NRH5zxijJZfQVUjLbxc9vTyztdtdQ1c480z1e1xy7Y-vpMw-NpoTG9qfn-_T4qwbS_l3mJzVz_ILdl_wGsSYPRq4CVh
5Ipw_nVgLjECxv_-wqk2AAPmqO0sV_eDZCFcizeHbdMhCV0De_1B_E8ZBMqE67LPQgRyHjZhQ-mplFf8Q-eUy7_NXwyLfjnzpFZsrVSifcvP-gJVwyy-KnAJ
rYt3UX-7FyLhp45sFagIuh5iDStxFI_SFQBtKPDyzrJq0Bxw-ERRFGTVFdmivV3zkBtLx5E-zRxuWSzbyUx-TlLXSmTByGKtttr7ofOVVCYVuKryxxF8IEkQ
PttfGxyCV9JT8FEwbf6FWM_30ZhUp_b9LRxl0xgKcF3jQteVKNdEJwxBijHo-2qsqkTznEhivcVWp_F0tKVQYi_vDiDVVGy0z6MD6NzEl_eC1qZcROsV_0vH
25A_51Xw7yMF-T7JyS7lUTxZfEi7yEbpSP8y__cMdtnx2Wmj0nzSul3zkBqDvzCcyk23Q_rfFdjfc2SVh6jyy_l07_BaCxObvlsMsVv9hzkIf_q-ZtuA7ZvT
0vfZmf_SVuN1qtUFignBBVbNzp-buVwt0kHrVdB-U_shGBhvwPVs_xkl8DBfbt2l_0L_ed-TSlB3Tz8ZTJxczB6luAYGKf0v_EudJFAztrTGSlQu-Xw1HtxU
LuNuk3zpN-5Hd_SLIa_fz9aYMMh-V1vylObSIZdy50aw_5iYnKJaZyA8BD_VBvhWfdt58vV427_zevXEsbx_BaZuEz1_
}

