sprite $Exchange_UM_Dial_Plan [96x129/16z] {
xTW7SkCm38LXr2VT_yIxSk3AeJCZyst5dpRrWzD8sF87rtMn8fDfM9FF_V1F2m0vzLNUlNsVchi3CVS_JiC0u_cYwO3nV0a7O3pVqce0nvVq-WvOVaeDuFW1
gG4Stt5yIi1vVWsW-0Qz3w3vDO3WQparWERN089lCWnWFFuQ43o_1l3y6i3pQy1Ats1wP7hvAfP0hlGJJwKxaEjyZQ_yKaHa6X3b4p9F0xHypeH047qnGpxx
QcRNd-2A0S2pRwRNjWM-3hwAgAgPwIuB6ltYdUahpVVnyMj4vEKZxo7nslOpdF0jdq8ru6TzZSVoUCzPSSAd_FoTvt-bml6tRQyM-fJQ7sk_VRt6y2qZwend
tO_rFGZDPvx_V7-y7oStxrRjstvhE-zNI61wnmDdV7VphyBZc_w0_Otfy_VRi7hw51I_7hmTK_woyxFzzjkl_zuZplbpU_c6k3zexmypV_hy7TNR_G5d_75z
MBm_c5SH7j7xmv79pjl_axN_Lthfxpe_ss-_VOt8hDESuPl9DUxpBzU_rH_lnwVYUBlt_79wV72_8wSl_5UVxGyLtiQ-V_znl_w_L5HafvqFIJWVJjT--wpQ
Rx_z90PwFm
}

