sprite $Fax [96x82/16z] {
jD655KGn24JHprZ_7Q-x2qm1bvoyfMd2CZdOdhnWaNPDyRGbAfgvK96r6HHE-9AjxKWFN41yyid-qDQbtnuQzfKFz8RsdTzwWOzyj8MkFFI1fj3s4x-WXWl8
Kx-ALi_p7_jGwk-uBzvFyyE6zJpkqKU1rpxbZt0bUH9Api5NROPB7p8-_u3e4P-JZzeDPv_ofxesMzTY9agJWZ0G7fBk09Q-_-kkKKmX8-xzxI5xVHrwyTSQ
Ha0IISULn1MlwIByCFbbkqF6RzAe7pL2LH7jtFqnq0oXtG-6rocjYUCF0Lm9aXfo-Vb-DbDlXphGr1MXNJ98oBr_l9zDjIyz2wrPcehe4g17wkMd_TRmmbeB
9TqGiDiT84akFz_65nlrh3kGa-G_pei2VO9gyolvrireBwLMaqUqVp3YylFbR7BGC-_sh3AZtqBpW_obwdsaN9PrmNN7FA53mDlPJBmFRxckIzFQjYtyXGI1
OQeVXg_BMhJf5sTI5DW5s7JyOVYoh1Knf1KdCnvFaotGz6ty-7jHJJXuW4CFGteeoVMS7_p-s2nhrWcISjdH9De1n_LpVsORtdAjS9FSnOSnIJcnb7H8CAQf
FrdEFBifsQ-kmlVmA066BPZ9vyNlCwcY56eR7iIejzAHXv9UtzjiyN-HFQCD3yLTa3GF32M1yuQur9sCONWGKxypb4JE_5gNN3WC3mKz9FgXZJ1f3sLwW2hH
EAS-BexYGbFYbnuzrEbNPjpmFJI_2Be4jGuPz9ZCJs90GSHQEeia1Zx4h_Z3rSEe9gvHqe5-50EJrreJnJEYuBY2ViI7J_Y2ptwg29vHxLQCs4zw69waFTSF
aQSjyBvIlCAfNzbUItiGlw62jeA23uH-TdynRl23owkOH4tqKpyqIPTmIVmIA-1OgEB17fCz-uKfdGc8UST6Bl6BVlebEfauwc3G2l2rqiTkBDjd0ZKUfGWp
kkkmolbx-9pdVa0RS6BU48VPYhdBHdrs_TGlLCqs1A2RF9R-6Fgktehhv_vaW6rhTnlHTbn2Sw2marAgNuXEdvlUFZD8mBXMueA76E9H3HuPEVHXRtg-lQ00
UMShxRWxXqWr0ZGsqUcjXFx53p8xLhPy930IW9YVjB6RtEcdVY4HacNDJNRv38YGkzxAJS-fdTQnBf7m4024ljpqpq_VH0DiOAjvvqhm9M3PwVIvkltGy-J1
3WDe8omjuUHOdebXjrhltL2Ux0IVMRPZyn4m35y6lUdZMuboYgthaC3GvthN6zAJ7U0RUJlV6bi052TMRtepolFmlRxTihnH8y5o35zk-h0_b0z5eEh-LaB0
PLjswkxI6Fwkry-CH8PSWSDVQY5wR3qIIcx3BsuFVHG_lN6RNW6U_hfatCZRwWdcowNfpnCRrSnH8_GW_BiBseEwhUkwv5n3Vq3zjKy94Him3rWATC1MPxdf
9yLFIbBLqvypT8JBvlJwIV7pXCD3euw0PJjPBtt9a-BV_nj4LEK6xA2ibz_rfVocFRuKoHqreugaFRsU_k9CYtydyR05IgD4UlOjxFAQtuf_HsYCJzXEUo0i
kxzwDN-1Mlia4j_tlTfItVvNk1X97-_x1FtyFK8pOzZ_0n8j_0q_
}

