sprite $File_Server [96x118/16z] {
jDQ7RGD144FHdK1U_ntR13JEWLhiJG5Fn5UwzUm5QjruHH9vbvxIGI9kqINhI9wF5DBdpaSgwNC4pqPAwTt077LrCdptD_zCf1Yz-mj_95AD_dt_WKWflSR_
mXkHZF1LzTV-_KZnqEkl_VkHQlJ_zbyNoThKZVtNwv5uDdnBjlRho8tmzdwERwV9B7i_gVr-6kcPzdvC7pDDINVtI_Vz9bkslH-yV5_X9TlxfTl-XBVtGsai
Vy97c3vclELF-B3zqKrVuQNx-yMxVcBqICzlajx-2Jzd-D9zN-5Z-JuQV9pZF_xU8im-tTJvFZBaU_kxm0_d-HckNqrk-5cn3ByAuETp_Qhyjty1Mtwi4DNv
v_vgGBVXrreXelCNN_VBWudZNqozGZTGBvNQwtBZ80m5uAAZ8p3CyFwFkoliHXCAJgm_Uw7v3XOgcLusll9LpttcF6vEHqmZ8NJbphSlVEHiPIICL-kxBvWk
jiV-ZvdPaLKymL_2yE7wdMzV-79z63nX_DKkNrOtysF_1wJcJ0BkMiwb60G2w4VVFliHG594OEL_PK7uKy1JFpcKhu88SYa7W0SFSEjVdyBPwwYQF27yJS0Z
FoM1Y7D88uzV-_QDxoNYDyJFAFVl0vxxwLTF8azyk_LBMhu_kZy7NF0p7ySJFudZVE2BbbiVmPCsbcokMr-if5Vj_LCLBpppfTIx_UFYYU6FqYdWtfVSyNV_
Claf9LgiF_75UWb-zd7wukj9rWbxFu-EQk-CW8q_RG5V-IWYJXLFaDcF0CDqIDCnx7oXYGpaw3tV-BgOCk5dNuh9fUJMMyR6Pre5u9L0R7mvogz2vjfQEp8i
_6if_FKnq0nhNsgxaBYz_leM-EeO8A1HbZvAjriVmzy4O1m3084Pq-JR-OozyPClQPFWCW4WYPhXtLSF0BJsohsF6D0v0G81tC1uutjBC2QZ38gjLtlWHy2h
aWUy7OFtww2S18_U3tlvKu0nBKi0cHBCcC9FpM98ZjRRKVB29zCs84ey8OvX1ALMtkSp3tyAeALDuQqSXD0Ox--fTaxp-SGNJ0c914o7hnwJSZ_qhozR_pu0
944Rlfq1wFtW1r_IjZ2LAc3YlfJh2tZpXCaNHAbXRKkIU8Jt3RalLPpt1By-jpvCDxxN8a5euZuwhe24xEEPmnT46JV-RyBaAqZtHNkyKWIqdC6_FhdKBzuJ
v4rNq8Olw7M-izoV0cZxpKV2xEj0QcVmMt_FH_tgqDFF7W1ORxhSlzmDg2m2PEfFWSZvzjueIJR-Pa1bMO1wdRvKd8PVdmLx7uQFkuy0l7njhpTPgxrNmvil
-m6LVSN-ntp6_Mcvr5hK5Zwvt_vS25-4FMDrVrwr6I2vhV374pG-zIKIxloC8HpzuCwNrO3Av_thEPydmDOFtljgikNtFeuB6DTd-EblWE5x7x--MCKeLPRM
MxdnDNpvsXTh6lEPZzhgCVboyiQlTn--1tHEyxdqGNwvVJWNlh1NtVeHGDi5xFryDglr_Da7pH01jxmCFxx-ijxpHx_aAq7IFH--C5_FKte_RESB01u0b4QH
k_tZtPTSv9fFQnwnzQzICzxnio-bnXTPTjGMyxaAo0KqmqwFZSJy74tlvpDyrl6X-mGiVCczVFG5W5OYcXHxZiBI1tlZP_-mkAgDD7sjpFpi0wKtk_U5k4hF
BxB43F45sCpBwO-5ixEzvLiVeUlFA8m4dBNoQNozKbbwhzd2NmQy_NvKEW6iolqVnFeOMB-XQybRN-TVE16QRWBSzm1ulStFnfUhyL7Hf9t_8yOtNybT_wFn
YuGBcNqFC4P_ZAowygFnKM_7W4W8VnID2Zrz02pwru_6Hyt7uBX3ipyUOVZC2h3AxCEcng-R120IPFYnIfxzrqODVzFuVOBl4nhxloh1p3XgFjz5u_V7uEwP
0Gm_2WuFFFnju_V70EYP47uyn3NzpExVD_w-IL20jjo1vLAA-z7u9wLNWeO_xy3--vl6Fpa6scxTyW4k6l_e6C9VDUb1utTN1cs_FhNcSIMr-rygc_Jd9SJF
Fm
}

