sprite $Firewall [96x136/16z] {
j9Hjsfmw3CLUOX-TSFU_tzkMnp-W2VC1L0kGFFQGdmDD43_FCThXNnKMGRRM0cZFwmFKDY91oyEh0KKhVqH2FBpuQ4Mq-0tF5HQLlOYD1BK75py4dZd3Ch5N
u94b1MHRXlcBlFrV5VcRqLxatJC8B6MS539JeEMMtuT2j3W64eXx_gqmdNz3GBldDwf27CWgG5pqkvWMCWiCMgxw2r2qcFZbrG1nsLyWZVkHU-VQzrR-UQ7q
zEwy-hq93oXt0RoM_TAZ9Dp_Ob_O5Xy7WBZkhmBQXXtjjQIux2-CiiuwtFkRHqdqEVRQoQd-cqT9xYUuMtDx1OYBynV_PUuB6LbyyoZ9vtvPSixr-iC7PmXy
wiUsSDPg1ht4spCiyD9loqpanTipDC0l_KRMtbx-0gENzmNH-pherys_0TOuV85V_GO08VTrdVeBR9tOUmUWdVbhWYhi_Tw3qQYtEwhlhPtFRmF7mBhvzm2Z
lHQdio-QubUhzg7cAWv30VYsO5NU_t4tEcI4YH0p7rbDsNh_8mGslWL39jwBPF838aHK7PMFKkC77WcGySaYPpltSXZyyPd2Ykxy9JGC2PL-IHYGOl1rIM18
ZH_TqtX-azRFXDIpklKMxAiYGEEVHNeV2SInyLKU0SU4uBD8T9jK9AYqExVW3TgjwGNFQkSF9B1AxvFGyypIRKbB1EHjgFxOLjkr7nlhqWIWmMr8rT_l1QJU
FswiX_OHW8JMHn5V-JHjh8yQi1rOUn_5vmbAW_29ZRM-4b2Omk_UHv6SH73uMqBTMD5-1ZmkVPnIQW8hKrRTM9Dd7ilHrzb_uX042Rn_f3ybr1jCeZeMlDzp
tAfXlZxniVKhF5NwMTM77dxSOA9DWr-dpKIYdPy96H5yw564i2Kf-6S9h5hy9W6hFmhzHpsmx_S-XIdxaAJwZ8GHVEheVzaJUfzO30cxdwyXX1F-YR3irKmF
_O_jEmbV-GEDIVfHq3C98n1xrh5_x3SHpNBjuw4G-6tPmNz__eLwF-QBsIBaPpwbdn6DxuCPwqGq8cxrts-Qh3Omu6sHczBD_WDWRdqaR4EYU_rZANFh8u6m
FE_D_xLP21zgzd5v6DAD_lCMi_G-4lWqGNf_3WX1EXz5704ct_WF-AK8WahncuJ6f-Kl_5e4GLHw7vpQF2Gv-ARB0zi_Qk1hAZ4CMLe_GMN9sdrpNVwaNqjy
v8wJVgbDhBwvcIxBdzPdSSmEbz3xx4g1oLPgKwcCn-EgVyfDKusQ_bsUWhhRkw-wlT-R00wVSjFKtgUn49kxma_TuFzwTBx29y9wkFAPUU0IN4Kt6phyFyj0
GEFdeoL8aF81Fn9m2QdRbn_jnrti_4nWLQOZ7P_mKJ5HNxzus_S7910tFXyIMDuhVQn7XtxqCM5i-yLdofCX_XKIYfzNj2teueV-sfJR_X73hAPSV45XOEhL
Jn9dvSclMneQb3b1uU_L-hoVbSCvzL-NO3FuGvzHiQnaSzAlfQOJgBEllO-IF8ttlh1Q9kZFV7wLZRW4bUhNbyXN__9pNop-aLbLH9suALTaAC3l_9qN4OkZ
A1uJLUjySLw8iIkZVzthtNyKdx0TCiT_xNsYI71NlVGN-3iF7ykDiHPwdpcMYxdtFhRFKtzB457QSkJmJJR_Ay64JtrpmVit-VHHhxiGCQMSNpL8rDrOgk_k
lFpj_6r7Oy51jlEHmAo-6gU_yoPZ-RsCdOVFUs4ws3AhBr_5969htWLF7VVtxsCPawyswdw3XDON8HBnrTCFFkPlzlHnG0a-_L8I2JElyATYbXXI-YyzVFpk
_aZ_V4tXgDpx261RLrE3hueG-FWb-d7fbqsv-960s-2-wwRXHyKXwD8N79Mx_b6AXR66lg-1bnz36goN_KU0xhw-boYsErL_rhk_3KbKklxLH1INlFcYacuM
DbtmNdmCAHQLb1DKLFXV2Gg_AKTLVniIxlHPmLSHCpTLbszyy-9ZI3ZjTdwWef7mhUzdFXAm6ixzJ70t-ixtwkytcaBAZ_Zsyj6tH03p7JzNmziDdFhNl0Hf
_GmeVjveUkjly_Uy0BZozWC_jup6Hqb8oiLVvm3jVuCLMyRHJpuJLXTH-_h0bhckap-Mty3Q8KdlcwdwkXgheRQ8sNVAzliXJRxE1LLqVIQ8sbxh7h3IKinc
IDMt3PLeMENCNvsMHpNha3QljezIYABfxm5kqiv_Nj13qY-yumY7XEfxUNxQ8S4lF0945RT1qrzRlqyOKeUVHmN5b10BtNg_7rBf7WNCr30aLKkzyRk4usBO
zHTdYjPnENx3noLmuiKF5mbkViVFDpI6l_i6FnDYIBVyV4FhhAFIpx-zv-SnPcg-elVxpo7ft7xrr_j-3YdRhpxuktuE2NpZhn_u-QogUUD_E9ySahN--h6F
FnV3TkvFyydz-UQGplqCo1VO_I6PzVEXJ_zqC3PkhVqZGCTdV1vNnSvy-l_-U3QfJJxgNlFzoySE_WVDzvlIxklIDV_vQjYQxnxxprT3r_pd2LWDryr__YHT
Dl_va6hp_m4
}

