sprite $Forefront_Exchange [96x106/16z] {
jDK7Skim30HGO1l__K_yJSf3JQ8KfUsKL3y8grRtqsBzOPWag3EDtzLjE-uwGlltze7Z8yb4ePZD_8xUYgKz88gDDQL_gnfjtrdwJ9C_rt7ef-_p92i_hiPB
F_tdpyIiXiHFYy-ojv-Ws5KDaW3pm-B55tx6R7oVLlna0KoTBtqFOmzeL2C_A9wy-1uP4OKguDZWMxmE_UedQ8v7h7MAE_sjuictVISiLe7E6B5eM-ol5t_r
VMvGCx3fCQTODj4thqaH-CXFPssfuYH17QlOd-_1cC0dVjJLuQJh21slHSB-k1e2d_eECL2F-AbZdHED4LbuJtS4VExF77nbwZatWSUmrUyK3zppfy9UFkpv
ZJV9DU6juj7tV7l46J4HXNkHbUF2LN0fllkMRuynZ6hwV2EJgm8wHBiqOfvwE-g-vojZ-jol_5LskchYgofKTOQuYv_wFLzECdqjteHZjGn7prLSCnhIMVmz
NqfEdswZ2bxPHpkwLZZ4NVmTV-dF0M59LLwYxVFooUuTmwYewvvFv_HDiOgh9TlQ0-pQWLCX-fwVd1aE9zP5YqR1nYv_Xr88u7EVzYj_DG-xovhMsW1F7fHZ
ImwdXOzzoY_zE67Pndd8ShKdxJ6MBA8hh5xO-_xINmrmEqT7SEysx2IMShuCGdRrP8Ihls9VVACwcOstdn3ePRzwcOKQwcvA5lhgI_PrG26ngyfOk0xRspvz
Z37StRBZYwz7Bhv16vM3XnDJ4UgQi3poxv_GKBBVBwT-NS0nn2erCN6XTqrl-4WU0q8qd8p1fmyTkIxWddp1oVEeE_MkNumzOatNun411BLoNS2ioJUphvEF
_PRbs381PFnxrBNBkInWbL7mCAkxgfVlZ_oUraYo3XsFjWR9TnOm38uXL2t_6AB-o6-GykEu_xTgBxgIWa0GGAMgQ30Q__zpDzAnyIgIVTM-PiRaW5o1PZDr
BGbW-CFYGQM8pOEhAM7cnzIbV3nXpUVRRvkNKIcX-OldDtoFt_3RL-SDhHXfDq3Nqyo7-n40bqz5Wh_g_yIh_vZtl_waCVRLU5zp82yM_8JXTwpbosS9VkvR
eKzJnV4KWBz4_lIHwsV_UVCjBqlpgSL3CYtkmxvzb3NuYU-hCTeVtw98m1LCVTZEZ_upUEzfLgiR4YK_g0BkQ-R3ZkBys0z-OMOc9VeJv7PQ27xvAW2exR1X
_-byL4-MOnCXBWJafyyiWAGTkttwvdWhWQ8fNIy04fy-gj2WiXzLBv-IJXCoCJ7teQBhI0kavTl7ckbEhjknbSoNBudNQLSPIspiy6M2DlEnLNVaQq2rSlEf
VbXej1yfn0LNgI1gwdFRvBulmG_VGJVFq9IGbMDsYVZq9G0iH_tfWpqoltt4JpGAyXOeBvy-2m1Isr4cViCkXTdiNkg8clYfec6s7wjr7pTVRTrKweTOmm9T
wrmM9lw2ZQxaTT_NylQz0Q2DX1-n5FCA2sJBp5-uwtf-hDHjhSt7tLShsgv-yWOcPdBk9-t6n_CJVc_0qaNsLoHILfhvQKa9-wOVlk5v0r8i3PdHyxOTQ9dv
jUs_zQWJdshnQX2dXtZyip3rSqvdk1rhdlYURAOCYc4c6ID8Rn-MKmlhiTVmXmr46zsNSeyPH-kR9GzKztshnUpjyvxMI6xLsEE2yUsZhlSIXOBx07lmpk1p
oWO-wg7k0szV70Hy1IzV9yLyR0o--vZw_1sVVW9MFIgZWPVFl_THsPYy7bj6-7_PmC3djRwfdDkZ_hSFxZdsHojrBGh_tG0yh_SJ7zhhOttxz6E2qXFJ-CkN
Ry1x7lhHWCA_qldk8_7fipR3ZYt_jXzYUlbw-IpDK3ssCl4zVd9fSkflJj-l3dpa2XVAVgp5dZwUlbE-cw6zxZu6FcozX5pMhUsFSz_3nhllhoYEV9HTu-V7
y-6dYmzVIXpvo4VzJH_XCtY6ZoGRr__xRfy-mcz4_2nVzqICrhTU_y_zQC1bK3wgJ0dN5SgczRyDVNJVlIGFdAPcFhQh_hUw7rijSpyQwAQdRL4Zdrkvr_-r
ldo44IfUBtdwjD-e_wS-4neBYRmtW4yVh4UP--F1mVqEqXcDVURjg7E_yuZNL3JWtSVB5n3rVvtxtOgdtTFWT8PFdwQOeROUUxNVzOd4cyyqxF-IJ9SlPQlh
jjQPZyi741-U2V_T02__DyO7phBzww_bF0Rponkmy8lbcWU-mkzXl7E_ZTtmf2sJ-wLGMlNqQVdjy_wkqVxypxv4aKz_mq-VhLO6V_ZFjmdlv_FTGivPjV27
BpCmWwcH3DuJFXiFskpxFTS1fljiHmPcd_pKE4X8djbP5JAF-wuhBQTF1u2XdvWydFa-JAKKg-xxrudSluG4ldZqQvpwFaobDj__L-3onK3kEm89eFl9_LcI
hDG2F-w6xqJq4gVLfXIwtv-VUP2jj86Fm9H-n7LlvUvhxdVFy5n34l3mto6pbhy9JPJyjpYANyoM_leRPByJFVbV
}

