sprite $Forefront_Lync_Server [96x105/16z] {
j9PdWlCu34C14Y0bt__0-rbsrjF7qzwVz0UAGGg-3HtuEy9buu-Woiam_spq8435Rqe3bnsBD7u9scbpsIjnyciBIcT4f5DLbZAun4pzpceo3jGbY6HaPl1N
tc5QyS0b03gaHynFxN9SQDEwxmemVs7n5zvcAo89S5KqyqUBLp2UuI6FETeIrn7C7tGoICRB0C9IZt-KCrNE-4v6BlihVsWm182X7elk-d98EdaGRmJqMQnC
XghF52lkTv9yptz-GMG7Q2n2OymvHvVYNYVvWJ-h31K151RPgbJFRPjToHkh-T2VNJxCnMKlOgrClMtRA7sG4Cl-YT_TWHqJh0g0ZGKrzuHylvFav_xihb8G
3fNMvCO3RTlMZdSw2TpmkvMgAbUPsEd3HzNicdERbM_O4xZXLtVhaDMvw-nrksSBQ47x4Lvt4ZVygZxzIDkrobf2zZZkrTmbuta0PGAV-zEzyAvN2k4ggwlx
CTwMsAapu5hy3R_wn824J60bzBNkqJZGLhewYHl-h7uWA05pBRQgZ9EQn1KGPoU16txtXNOzjHRhahiEXsPS9iqYv01k-DLFMI_AO5gq07KJGCoyFA7HSW8t
_5dz32T0xtR8sCrT08VMTLNFROxkaeCt_Exdb6tAvlKdY6sqg1hRhdxy93Z-yObV_H8ZRUUpVz4SlNzBZr5bdLClVwRY0tzMloB1Gmyb5k4Uu_-nBxmR92NV
zeVxDSMmqmyzSptfclkPNsJ8TlArFrHL_Gf9IeZ81CErE0Ml_DKYqwuIN_Yp5g_6TwI0oCZG4jF_rMeVsdAhEXY0rILSvlqVzyQIMSES67R9kl-fQPzi46KN
XkSeYdkpVDAgqF5wiASAYXTVIwlw3vccFhgtSyyA-MTxnCQCFCZ5ivfA7rFcgG_YVfpd9ZbD4NMuitxovZq6Ae2IBui0-AMFPd7kMvWGM_o94Odz7Q-GCVSD
4w62jF2pm1wgiUbTGKjyg13vAgMFlgnyKZM_YfnxLL3Lvm9n9KUm-E_vYF8dwbip12GBlVB4jmW1980V-aZCH9IFXUK_56WjBeSmxUxZoXzk94HObTBF_9Ul
0ubInLvZFR_AyBaPb_zGOJDYhCTFi_9L_rFGojTtxn1W_y0eK_gNlkoqydi50IYVwDPfz6dgi-wyygi29IC4n8MdtYkWuDndFMpjgn5ac97hGpxiROIu_31F
cQy26wry4wYGy9_GtJF3WQGmYPeoYsoleC4NaP6tphD8uRsDCakVch28sF5gFFXZ1UDQei8imb0P7h-Mrxn_9EFxwmWPVEcy8KaThKBO2n0LZlbUFFTP3otD
OZ-ElRc7tBdzFYWi07S1p7VgCw48Y_crqzFgctoaNqc_BoYfVpFctP1IBnzMlkYvwuDVKNFkUs5nB4JLHHLYWLN_YCZ-QZDVpAj_X01w0M4SBx8qzx4mFrwR
F_jgBlcKNHCM7fwVI67XqrxArJ_D7tpHkX2c9SfKsm7INO9OLZxmeJMzrJzxT7yS8HPC7CTBPsr3hBJqGKxlxVFq_3L4-bwwu_CYCIkiVU1ZruLV1OmwgGYL
R54MNlcM1-JsQZRw_5H1gu9IsPmlX6AOcVWSkOrBza_tcVdl2ddlmLh4xusED3A64rytpEZGF_nt0MlDJSpKokuHjIiHDF75-W59jXt7leMNFrRGvenNcFNZ
umXYpEZS5py4UuYOhVoXWhLYAiGigYf2X89V-s9dZ2Tm-Zr_y-EZC7tbUowk_RH7lmeapnLyoChdBSStpiFfqMS9lOHeLm9-wkj-7ox7QrDwyBNXl_ZYnxtv
-tQSUvXOCD7RT_qtN-BqSNVm2BhI_Njo_TU--6kpz3FTf-wNm7ozWV_KTwtRINpwbUvNVkNBbjCRhxFvuFUi_VTR-indsslpR-ThZ-uF6VmO_E41rhvuRVxL
FyVUOkgtxXEncUdeh_jdF5o-ykcArSMH-2jVgd_AhwnzkYAgYAhMUV5L_wWTPtpjL_zVkfaAm5KW8mjVjfpUDlRFsXVJAvG5AhRmxPxUxQl-eVB7JoLXlWQh
sjoNsE_sYJtxvzadAX_D1A37kChemfSuFFrL_z3bRziMc2H9Hitg9ghcFFKrNgtysVWJTR-X0Q1zHEfdvhxwUORFVHfz1B3AM43CSUwRRQyZPZxTsVPzt-GE
iLVCpH1uCa2gqW-NL_NFoXzYvLSOq5tWAQBQ3vVOp_FOuXU-p7qGwtucMdpJZollvu-93soPnBVjk-CJ6j7Z07mLcOGwtqBqcFjgPgsvIEHAUuS1B1nX5jJo
8vYtzkcpDHfYBG308ze7pn46Yv3U1UAC3r_jq-TeNfyoRy4P0W2gAj-fy37-OWoVFabhDHAXq2CHBGY-27AMABzqGVYFpwojDHVM5lKD1ApHcdltbq5zxs-i
ci_vuTTPrIgHrVyaJCl_EcHUlXe3FFhCah-f2dXhfbh-jy8UGTBrJvzxwivT1IR-Qf1C4HxyKUy59luoH50fNtgqOceLRosyDLzyVBTE-T_AhtsMHSpTL388
_uyGhzt_0G
}

