sprite $Globe [96x96/16z] {
h99TZlCu4CI-cAngvFuNtdLiOnnZ4imVeMTIKlU_ht5RD4dQ9j7bzk_FM4mVp4uxRUDVD9OSuYjhnELNyfiN-PMstdvpzPDePwuqo-_ixPLhuFk5syN-hX1C
llTBNkpl2m7hTowVsUWRdlpmzK-oaXd0zYi5D_yNdv146pA2REYx006Qv4j_4n49431pRoDjMKaF0cRr5u5yOSotca0R321jSlyVTxdWdZ1r2uY0iU-7iDGa
C0DGbRITI8Ga2j2LP68pAo52t0BlzS6fh1H8sCrgLWx_f2Rpe2X9tWLkcpvs2a7bGHCFajADDCvvYx87tkkPAO2G4N7J0rk0f3lJpaubM-35a6CUW06XLPBD
ouOca3njQNHcG9F4VAu_G12Ptkz3aiZ9Ro3dmCY1M-6pWDbHIS0FVrXPbWNGO9u2Q5JHFU2hrKbS0S7E_VxXNrOsFtaAx6BW27HvzJlkiEBSXuiVnPm3mGU8
Ho0lVaSF4EdzRXBFViIS0mOtS2E9bz-vw8zXJKd2nK_EWOY27oHvNjBqyZbkTAhFVXMpqmqKBu6yl3veK4qxe-9fVv3aAP2h_phYr0-zoP59xHpH3Ozpyhlv
Lpvzm3BdrKpRg4YwDtC4_clLNDGhLq4e_8so5cZU_trFWAJKO-jS_vbUj_bHKEFkbofX1U1pNGzUFsi0qC_PeTw8v5HCN_AXXr179KXwleZimpQ07slsnMxm
DCNpEpp-mA3Agi0Jkm6Bd-yK4YszjzGvPtQbbZE06WjeXXU9_cVhLW5Gztj-zgSrX-f9heB5XSMh1mZlVM_k3r84SAzkUE4ofzN2z4WhhrvoWRM--zjUtSLV
NSxgRNv7o7njkQhsQNBrPw7s0CdY5q3Tpxp_jsgKYvpRv0__GRy4S9IISxHufZ4b4YHBUbgclIZz5Y2kYYL8ICiDgYUXKr3Mz7lae9es7Fpndym6BNYQi4k8
FVsxloNfA_qMGFBuGBRr6fAPFjwBT-b_wPsqdVrGPNQ_hicJQIpXfaJvfG7LbJZaviwuKFx8FPS-vGJvsAJ5MFhEJbPJHEvAl_blnFNbhmgaNsIiwMcz6f8W
1-JWhwMUwlnKVi5S_IAz_E8H56S_FcUVBeTdDlt0X9H_cJmjxo-d_YTvKGTQYxMf7kFiHsxwoT4ly0eqeK8L3Nhx5PeJLC6l_1uNZ_xi5-HoRrGLkDW_dFIJ
r-ftlK2gA6S_tbTLbL1sLzE3P7xSZzNVaPHVDdtvdzNXoWoHeB_-oStFt_QtKBQMGIGRFVMbwphwgq7wdRF_QP9wD4UTvctAVxcE7G9l6MCw9aZsvQNQ4hZ_
QQJosIyIRGNS_8VxYwF-QkhNNJ7lRkEYG9XqOR3vPT5loxVyjV_qZ6tXrw3yUm0f-xPwlzxVwFwcbxdVdDr_006xVErtoFQ3bnU08u2Y_ES0rM3rz_93xoCY
hnZ0DA4w6U1N_TpzfQVnlh_Fww842Ygv3U2ahz9lVW2A-tnYrnC0PWhY463LqspVr_lY5pzVtVxf0PXWzUFGUnEKl_JkhnCwhvl1V6C1AdzUOXJfJnPz-EDy
Eo80f8VSB8U0uZizor-KFzAV2He-WYvKCZw8Gm1yHfpDNsyXCq5pt1yGeMheez2hPhSJktzFJyuWpv7srm-p7C12kWjT1h3xLTBlIzWy1Zer0oGuSF1BKE_l
OedD-qD58ltuRRzyMzstmZOl3z2XqbYBx0Iv1DYwxzLDu7Bp0EeDxmyo1GS8SlS_-XxTNmRW0URK_X8rvg7pBBzJUiUxNs2uUvJV6VW-HxpHIb1ITbcwdrDe
p36lz3_ejm4OAChVbMckdVyp4YKUu-9IAdkoiDlN051Lgib3pVsbn3R6uF__sAEXs-KLW4gzCSMMdQB5BZ5C9QbKAW-eVoIcfS_YRXaQLesAaxumKvM4dfqD
c6yJsZU_ugGll-btsQb9QgHiGC_wj1ljfFT9wZNMpUxeIU-OwgIthgcvqJB0ha_qO3UEQG9i-Zt0qA_qwLpi2sCCz-VKEGUOYbsVwFVsOGHWgJy46BcDbdtp
wmhL4adzcHymtwkjxAM7RZqdxK4LL6JkZo0ENBRhkRb3_dmte3KnZmZZThFvmJBZTKTKwZNKAEKuqg1B03xOi9YBOrZWueWmhpctt9mGZWomwEVDSCeUlyxp
vIOvbrd7DJxqq5iudT8xrEdsG-TFIHfJmI0crT9z9LFkzZz-Wi3CvO2fOnPoTOQx7IFQNpnV4HkN3MVwluSh6Vh7prVK8DH2czvYcXBjNptVyWHvgc1AGlw1
V7y-1x_tVCv_
}

