sprite $Group_Chat_Channel_Server [96x113/16z] {
hTe7bkCy30FW22GWwJalzp_kHhGdSHIvpGx-kks3oRXjkLr8WhbJBQGRqkqF0r_W9MfnfB_3wVOCvjWpCGln_pebDZbzfhLGalsVBj437oKg_gCXKJJhy7uA
_dfBaFobt_gy6tuvWek6pXvrn0ZfCi_WEtrS0RzUGBbr-dO3J4fNUVJwVW6lyDRnVrm0yN0v_QViakEal_3fM0PWBO0v9NawjHr3-4Vu-igE9fvg42qT-GqV
NywouyDFwQ3WhR_7ENkraPRs2zAiRrvjmjxaSgJT0koTkp72Ne7BqZe3VgHt1MdxUK9BNRexveaJIzowuylDqavWKNXOuCCpHmxi-tRgdZhQ42GQW8Cdrg6V
Mam-M3nmv9-uyYBu722vv9XZTd3uaNq-mOHkyQyS-v4r-87t2uB4XJvQ4DBP6Fa-9osbSxwTBW0LkeV-wTkV-R7uZeTjApZj6pKlFitvUv-n-9uFt_2_Famk
ufO61RPJOETzoF4gm4aVEBz-UTF6ns_uBnycc_sGkkF_tuBb2IE_fMHcRjtnxnOOJlWkkxNZz_O3_1by-uQXXEE2vVabJrdUsfpqBz_TVbM0uCE_AUUYb41I
xFRlhG130BkyYsdnJIgFkv10ILhx7hdQ01Y3d_qRfVkZDG2IicpsuND8jn46RFIQInRwx2TIZsV1H01jMzbWCFy9dp4BhlD7NsTE4RUr3rBt-pHDnG5JgRMi
UESSDtk1ymfTylxhgD0__3Xx6b-A3B1SgrbViCGGb4lABPgBKu8vAScRtlbnYR7nCYJ0Dtn9uGSlXTzYI3193BptFxSPxyORFeCAFXB-pM9eAUoX_qxm27zS
O0Y-ysthTLREbmyiS-pxCBqIFcIRh-Do-U3kN6shmCpK-KaCVkmZMrUmwzErJlDl9WO_zb5jVFpZ0dtvVNhV9dO5V-l3fZhmXmNg2mvz2-_kdpv6lfGBUV7u
Ym5cUamsy6tbIsBpUUtuKO06rSV4FL_qt_a-O-xb_gZU-VRYtNzyNlF1wGTIdUvJbN_vQhpdt_dWtMU8BPBuwLDq__NnHq7r3T-MWryVFw_u0c0-tRNbYxv4
l_5TQ9WUTwrzB3pVl6VIn9OB_aqCoylzNhzyoT_93i1qqRzLXU-k-gp8Yu_WwUj81i15Nl7JLEnr_kHQQrxv7t5AU4QN_5kga_VdvrmGvkllY0Z0pllsz9CU
PUYR-1qv03_hPppzXEbHUZy661R80F2SZveYl3_AjsyYnmq6-_9X0zycB0tJOogzJt4OCThBsdSfVVlmLX01wpHDLLwnDq14SZDpYOi9YVA13xzhyPVOodTn
ju6IHuC8IEdBZuAAu3k_6s2y99VKJaB9OFBUBy7KHqPAGz-q5_ep4f7KsgJK-PQ3uVHi-F9nw4kjW18bcRcyyy4SYcjwJ1pvfdCDom3eVEGIlZlBio8p_7w0
CqkIt5piVPJfVNzJBd5-zWESN9AxXDv7lhE_lrqP819-5F33PpFug3l-kG9Iahe1v68pl3ugXtuKK6SJmDf7yI3QtKTRlkb2WMHh7vCtmPtnU1pxbAISpnPq
x_zwdJ-vJbCy7xk2Dvtt_-e6a3VWNcnm_dG3j0fA-I2AfBKFgtVsVb_GO94kdIcmxlwM7nFtVUQOtZrddIX8W_T_hVo-GBMfaYgTElRzw_sVzN6lsl0P6oev
orkaWuAizED3DVpb1MwgEVokOF5z3YMT6I1yQFt-BstvETDU-dv1-oSjVXJa_lpyAl3APSmulqsITds-VVFxn7s_wU6_dkSkINi5UFjnWchFXqNMl_oLA4bR
Vea1H0i_Jj1xsVHdtYMX-vClZVhwAwkK6C2a7z_Z2LorxSVYFsCnGXaqb7c09DcFxwHoNUvlVJP-Opsv99Mln02fpIZPswTlxCTZyQCaZXfoplBvsoN_yOjK
Hhx5uhU2PKaVaRHwx_N5frIizmUB7tqCFO_r0R3nbEGYFtsFnUyd-KT1Rb1t0AJp6LKJQx_uus3bQx1EamRtPplzvxUIjE8v61XKvEqROynhVju-f6HItELd
t-CuBlhQ_q4cvLfhj_ZplYG_F1DAjMxn9_sySvtqduEdsrLV9nTgfnU_zdb-v8HhUFZTRluwDlfW_m4
}

