sprite $Group_Chat_Client [96x98/16z] {
xTY9Ukiw24NXm8Ojv_rV-4QElYfECPQjt3ElCm_zeNJExJrHc7FDeNBxQ68axH40U-IawSTqL1kgyfK2HffyHdVhT4_X7vYWT3Gzd80vtcXDtsugpzJe4xgu
OsD_dm6dNEPfslMT2MgN1sHyQsQ0UyBF3r3YW1Tz1YSXvwyZcQyAgEew0p2ddvi0LrcBDuVAQtK4xVpwyO2krrctDiBElAeALVO6g8f8yAeAeuxwC9NUHeB6
Hpirm4tY6XzrvbMLUxwgxFi2yq4VEpmaymNKAH_9AsrxBPgw3wGLwJLmBDEzw-U1qBUWUCqUaNxLTzDDrMigO3LKdxZcQ-wt-e4czyUU3oBoSUB-_VQ1B_4p
SEGhU9nNtmWDV3tmpUKeu-exSVf02XgEQhun7A3v-Zok-H2FJWHDUPN3ZBxw_TEtmG4wzjwj-pUbVUU0M5Vh_9Yl08C92Wru9BpYgrVVp9th17t7jd-ZLNU9
MrUk-IFR-CwMrHdQB0NCWFOtpp_IDJt9iy3lkQsS-TUV3I8my_wrp8nFQkNPSmYCz8hBRjttGx_nzEStmEXcnwyovHcP-mgsdExqoW_vzqTBBVK1Thqz2yrF
xZFkj-Fq2NGVtdyfor9Avczlqpgt_vlFaiLdFdZ_xfFDB_Tjotjrp9Y_B6Kf9VRp2JvodxP-vEVyyVxZ_dAFxiEX_PV4dxz_-x-Xd_F7Vjy_zvUG7tpvBWF-
FU0dxvCVPzxFNtU6xxFrI_Sp_kJ-XUrrEVOZVdx_b3z__-vhzxFZZFkbteSC_7JzyVkKMk0d_EZ-kRya_F3-rQvkvDyJVlp-jSXFjf_tyzUTyVjKcaxtxtx2
3--lh7GDMp_Xku_RYRP-pdS_lyysMxe_mFDe_v_ZU_TpVjhF-Ij-wVuH_q6__7YVtPVTSZ_dB--FxgVyl9_ptPUzRoD-IVtv_HF-yEMR-Za-ltysODxlZmKu
VI-xV1-rE6pJY_jFzFDz_ap_dsz_WYz0JpP_qf_i__pxqFwdkFf6EeygzNjvQIdBGDL_pL-ZvuFRo3J-t_q7
}

