sprite $Headset [96x123/16z] {
j5PNsYGW31eLY2Nk_O-xlsvlOvbPteKGOhuyDX11IY8Hm-FTY5-fmIaYn7Uo9uafVY0D092az2RoW55k-W4CK1B2Usf7IjGt45C1d0el5qynSROdV20cS4hC
85xlKf30tqdYr9i6J69uZRuO_n4uA3DxnOA4QlhtID46n4jw2YthN_uX0Pe22dUJWzgK5jdRWE9DysdTddgF4c2Mirs40A6tHM61Go0F0PoNNthMkWeEWMB2
UVc-OJjAi5nAFXGOvLTjVX8hfm9Hw8jqNnA0sFlkL70Ar1C1iNPNU1mAfEtfWS_sxmlaKgifRhV_KoywsYMb3e4zov1wDvojsYd0lNAO9_-PGFs0iCTVv_WS
88gijPMjLsBhhdYwRwsskT6N4FoO_m6XjER6Q_xr4DNc6n44eL_m1v7DlIZUygyZoEvkkkPVHr3Tcx1U3-utbuT47nqA_ua_2iLzEKEJtt1trBXxLLpzhql-
XsZkdhLQ_-wPjsVJihbaMTImY7ZncCDakUEF6mOW_YkaDJWUzwBdJVHMBq_l85P_VZp5oM-uFhozFpSWr5PDZsi3_Ra1yNDfPhiOhGu2uHg68Lzw_vTxec5R
jw_cPEtyjezq82p4MFBWfs9YUbf7zGrbpedXyJzGnWrIYCOtF5vzk0xdouL8ZS-7_71aE7FOHb8oBezNGrk74mYevv4uW4qg7tIXnaywREGfkeEoim4eAHyC
oCC9cR0K3uC2gG9BfTOSgVCJvd04LDM-js6dnzAKebaqOZx3YSDPm8nKGYoNaWso2qgTot0Q6hGGjlCfVJ1s-YvY-WoR30o2cQgWqPFJkvHXSeFRnXLaYWDl
JcUCfW2c72BpkfNX4SC93qtrK58ebnc3RDrMXi43PtoZkx8gPSwWRJCC7X19ZjTIVvIKc6gYTHibW2envoXDh6_YP0BIDaW0AEgLm_gkI4vLg6rRvN9ht-xE
ZjVwIvcSN7Bl4wmKw-QZ_bQn6VuoId0WqDr16V27EX8SzIxycBEAIAp_odI6hqnt1RJqyBlv5_7ZQpR1cJV5u-7dApvbZi-zW6vg_pRywSbKg3S56exQfmWk
mlV9UhP0h_YWrxxM-Y2zhkMMhohbw0pfaa-PvEjD1oMqP1N19NxwOkkE7oXMCaHuRG-c-NMr2xvGKiaYkB4dJFDj2TVyNE9TzKGTLur0cz2mnF8b5_d5pZSH
V1o-A4cBAIKZPUVZYgzI2mMN_CZHWOsvkd8aPLd0o_AlLGMNlUSs_42csfMqZmIDpsj-sVdyv6m9xKM7m8vNDVxrzo79pfzk3NW5NtPwpkNWXs2uR3-f4j3B
pZR69n5D3UzykKmNOTLmaL_YpXp7cuYbb7lyIO9UpkWWQWAG9yqFx_XN_1I9M-RrUbS0s6HkQIyyB1xy56Ek4AdN3Gx4FmaelCEhVNjl1rzbbudSJX1APa3j
L3ct-C3kOnPXuqTA5qJIUlSBhpI3gXKl7D-BHkv0r1eVGOBpKNV-xITCgfAMSah6-wuZ_36_2U6GDC7MniySV7UdxHf-gcOykTFmBe40G_vNK7PX-2jUNkwm
urq2IdN-dPOW4hp1Zeid2fIcZRli2W4maUBvVQw5-HM-ajBmNG4KEUAF-0jVwAKFLQBXNQ8IEj_c-6DxiFExEytEZc_yrGU8vsBsue4gEhxneKU6jV4h_sP_
yTg7gdJ-0gZiAHRp5VkvGhTVTZwwFH9X6Wv-yJkKvn9xsGEL7d-rPD9BTFKhZkU2UV5_ysMjjdmT_3Y-fPpdgw39uq_uwdYfupkuUJwSx_Nf9zZyXkdlnqlU
-8wNUhxb3e249_LJJlp-0kUdyoszqgBnmL5ZmvHlleIcWnvutaJKwfPWHZpe3oT--1RE0m6uRghDhaI61mau-2fCIn37v_DtDkRDT5q7lxEZ1k5yDgHR9CZb
z9rGR2jITtp9EVAp4wUfrsVQ_toHGveRlvX-FxAfrOvFAHh3XmRHsmIagO-tvNG9mhpA3_xJEcAkEVVDGm6epv_sOuEc8ZkzHs_6wnUCv_waVTY8wU2VJO1b
zE0xNlKY1-Eb9IlE_6Hl01fwy8xFarS0YthmEU7CJx_YMqXBZbV_Y3vtmPFxQDhqmuz6N3ng7ZoiJxFX_urFtwDf89r_KnwBaXsFx7TiM4R6AwC_fujFt0U1
b5ipTxppFQw1ySLhyXNiWXs0C4mNgSfiLjnNBDUnk_56-QoRYFexlAZjTqIBW4wVx5NZPJn78wdOfTtZr0TcD_wfG7jjp3b5EnHJBhKhUfKyr-9lk52ENYL_
VWCjvNTsIKRgd-dd3uFzqFVppHt-mFVX3kEPLGN20_P_
}

