sprite $Hybrid_VoIP_Gateway [96x78/16z] {
jTc9Sk8-imLmt6TfBRp_yrvBCWv_2Bdv0dEgXcMI_5fkKMsNkRoLZRpymy2IyQ_qiBN7slw5licYPipFyxJ8vNiFFjrua_V-HviKCldW-sDDscZYsKyR7sey
y9sV-O4cOUel_BJvTkFnof_nkut73xxUycb6n6jVpZVyi10_-NgdFviyzPU-SiL_RNp43pwTR_WmOzjU-rBct_smTlq7dyw_-vkCeR_qAUVV_J2toya_-wJt
lE4hflzg_VRRViGh7_AHjtmWlkiFAEa3_awJU5m_e14V-RkFvBQ1ukFwDVEslpbJiL7MwGVu2NyBK1VOQKJGgUbF_R707tnwZ_PdQSrEPKb4WE_xvyKPvpNc
L1ZXKW3oXmB-_SMPRlxeapDhRe44yBQ_SUgdlyN8jksl_UJBAx_tOUlqR-DXwW7ZvmFmRnj_3lP3FpwRniy7uD-tHhB4AC_-MU1_zkbxlWuVFNxb2w1t7-9l
6k-odYBO-UW_5n0GUwPWlheuqrroFN8Kw77pyrjVnFAtZIoL_s_ZcqQQH76eruh3rpS5IDpyO6cE7nj_Xcj_ERXoxOdXyzddbqyxl-7ZMMURZoMYUN8glLS_
-fHu-fH4StlP-ESm0hrEVuzF7oT_-Y35iGFcGsjUsSsY0oZNVE7hovzFwqmgnwblpjhrCaG6e7uj3_xqv9jFe1H488iZODqggBPQMjMB-E8ScDgr5my_ldpv
vXFgZH4g8umujy6zzrPABzHpvlmizS1AhVdbW_RDH-p0NFnAObQOVgkjzrfgJtxlR-Mgh_r515QSDp_GkcBuPuo0ZEcF0crKC9_zl6mRhqrFllFcXte5903C
Cm9eRSElhVKsjg4z-yXjJrvx_jTd7Zx1dhDWNKzd0g3Sol17WR4DzT4FrMs4jRUIqu_fQ_a4B00YM0tClaYM483iMjO1zEkeyBWDZ72Fumn0CNtubcIR90Zo
-FnlbvWLzWG8Jh-KhArVhzTUrpRS-uZGrUSPe7W-8PkrXoiBXuuws1CSlApXkzLs7MdrOHje1D2kcZvK3vzEZKnyF9uFIdDayd9uVdvSU-lNtdjjhTvjGqJ1
7hLhcPsjZ15GoZo70xLMJym2NKEVlCVWRtt0EPzMXThBq848j05GzLhrvUCu1J46GnmFfAWz1ozhpiz9kzLLOJHfh-1ZgBCR92rz-J5z3WHd0Ss7RPQPlDFR
CV_Be3DxNHNc8N3uSq1tBLw63X_feu2mS5fQgyV1b-BB4NWilfrDQhtM7Buu1tJJYWaS1NZqtnwiJTa6VUEpbDJz-RUsrahBsbQM7qK0MAgE6CJq0HLhM1wc
RSBdVJbdfXt_lQQjk-rijPu-8te2f7tmyge0m7Bgg639bhrqVNixAvHrnFk_wRFaQ7_Z7jz585POKjpZj91vupE_lnq7bo-_Pwtf26JtuPyX1mudkGeCydWb
_t2dZ3jUzkp-jUu-7G1RJ_cfWgZxGpZvFTn-kCAjXrzAAZmDbTxz4De4BDBYBQ9jnGlyt8OonaLQYiW2p7MbdoBd-g55hj_wpStYSEdNdevGH6I_jTLF9SJX
UuHxVdsp6vpBc3xOgwXZt_8-je_Vn9zkrYyVoDwyV2aVAt2HjEpulJr3O_YawvWUcGmyLlZwPE0lTpq1d0Chr_dNUHzStWdDvQTIpfZ1mm6yax2unmPo-ZFA
if8byOdlGYJOEdtwB33zjxBHriZP7rlsugtB1nAqBIrVvhoodpm_zeNK0F5rxJtUslZe5sg5FAUNrodaay7zzBBDouUpJNs5lva6_mS
}

