sprite $IP_PBX [96x68/16z] {
jPY9RgGw44MdSTMjpHB__xVFDYL4h8QnNfWpQxPJpht6fFcpm8Tv-_FF-128m9z_Po_RLXZq-GVs0YxRW1ZbRNspqtP2UBU6ZNiq5mg_MCDdidVUg-536VmC
0TihTjg-Ktw_LmkcQDuCAOD_X7B26y7FC6L8swl19oIDSbF3Ml1FYA0XKZfJI6l1DxQRNsa7c8LB8u-CPJkN9_ZKTwGl9MjO3Vuvcawt9vba7Xc_23w1DIGN
RmsKmTYh2mVP4hbwALS8AC_1YppvwTQV7tlSgmI0279h5-5xlmW_xrLYeG5mk-FbmGy8FTK0AEX0kCom05U_pFxBnx-Vt91QvPn0SpJeIEFGY0sua2HZmq9k
Qu24HO0pfEk4j8CJ-NQnvKV1Do51GjMhe-kPM2GDFDdJV_jHb7F2x3SrhmhYyKlukdgU30bF-ZmmyiYOyka3BAg0gG-1KlyyEx9TNBz8IOYpXjFVK3EBo0bv
0CE41tOWJNjGIh43IRjnskUGXbzjuDM4mMZeCK7mO-4a1zE65SlevYCZ_HtD2IeuK3w4F_qOlwx-czCbQqX_aY4TIDOWF_o3gr_qftsgOVQRLqyBL6ZKW7j_
1dytWVumgjk5QqW2nVnDztvOoXg4Ke2uJY3qa7A2Y2YVEv9x-GCH5gQL0Vo7m5BZz8iYzsgYcQ-0Vo1Oq1EE6xkU4-1LrMhrS4bKikYBlRU_vC_x8pn3acRl
_Ztw83am8IfqcI36LEYHRk_-GG4Zeaz0H5y_M7UFo0cYpTU0uR23g2pOqz_uKDRWCjQFFL2zJv03K-g802RqDz9UJl-r1cb-sVTTmjp3Se9wJbYsKytr9nlu
gC6jMkoxXlKQHaZQSL2oe1SnBOJvrQYC6kgkUrMtwZ5gICnvTV4kqDb_rj34eTBzuZJsgYPkItOn2N2T_Lc3LVjmRLxlFQZ6g25n-Riz61NYsUz40U31HTA_
3x-7vWZxImtGiKMKIldcpv32gPbgbSE_Znei1pZVBpw0Ab3fTWBT_hIkjI-xzUpTNsaVDLZJDznkzoJ444mFBmwo1bZpIbNrxg-YktkSTxfG-eew9FBqBv_d
PnlYKJQjTVZtAiS5xJRmm8qVIwyAiWOZSX_-_TYtuJdXUmsrHxFqF2gFZ51j_bs7t_TUWmqofFAbYULd55lMu7jVT_SJzl0pfC0N_MqqzpKuMTLQcrzsUFMi
mQlInA9zha4BHQr7Jg7c7jxBZib_4_nA3KAZ1_GBshgy_pNxyV-UqMq03k6--yK_hVztJrN4ZmiwTFO_szSdQ8IKY5hJ7r5r8VZr6g0X6oR_Gl2B540yGEQJ
_ysdYkATQFwc7_wNduhs6iQ4zBzYdu-CyFJ_ClZx8oEywry8_lO6MltTQEOQRcv_hzLGLXR_7m
}

