sprite $Laptop [96x109/16z] {
jPYBhjqg34I3iKqC9l__kJUCXJQDcjkTDcT9JT_BC4CuZ-tFf2oIjn-3LKLKwQVqGfcPHINzY5yfRIacy8_u4yM4pABv9zO_I1lbd5ab_uIVyp8XlUxdmmiH
dI6TYFBRVkczkqGD6JMyxHyOBo7HotvWeuP4cL33-_xkXJ2123MyxKSDouJyld_MC2QWXdVzQmsOmEbzVtTTQtZP3vpN6jxtpv1c3I_x0Sxg03MyxfzdTK2Y
-MK_C9uJiaX-tnyrp90alU_lhciDB_k1Bo5fVjbVf3X2mWJAAlGNVlSxlvoOTwMJ-JQavtwxN__0bdkLHFcnNs_3by2xFRuoLlzzGC6d1dfuPOI_tFbDFXDm
La76bV70h_x_0SqQcC3NDpVyx7g_0PKF6Y45h4hVhr_zJm7D2OM2F4BwUlrgVmu8cBjy1j2t_liD5BbWtVCS8D_xxQk0PWrp0z_xrRyAQ9vL3FZ6dwVVlWm8
k3tswyLxt0Q4cf_xxIQWj_obNpbEUjUN_EfNVM1l-SjLtyElgg_urI_-m7Nm3_vUDB2hFfZZ_zflq-1NFS3uuBc_v6mp8BLh-C1qvQ7Vh6JHYL-NFmjOUUAN
tSoK-BA1uzuFpB-ytqZ7W9qIAxZgmL_xCQ2OcJ0HKh8P_Xj-a4JDb8LJLjK2_GNxQt-Yj6siPMTXoIcZuQE_v8z8U2DL4HOHIbocVC6V-oCO6QWoSKmODTXB
VbQPgE87O18_hZptP-Y2OGSIaFP_zDDm1bFz6L2gv4j8vP4_VUngfWinmQens-gt1_x4AWmvJBNRTK2fjLeM_oj__jZtuJ7hlkkW5CHGH6fjjPMb1l_MJwBJ
hdRAgpS_chS2VOaHiWz_QvBjaH_1im0zpNKCw8UF6RLCngZJFYPyQlZAlmRVsgbjfxcVp-wjTIkJUlJM0jJmbNyDlWntyvFkMFru7huN48dC2L53-PEVH3CH
HpIjEkX-OFNpqSQ4lHsW1L63_Ry_iJ81rXt9z2CUv_COVn2Fm_OJGoIVa2hdtwwVfp-hq2JtI6O8yUYZ13I0FSI4SKVZzu4HoUtwIIJJ0lVJXrgnUknchDx1
WGbMZ-w3kOMSyk_Ndn3yGg9KZeYZ3XzMlzRGcmtQiGx0nuRV-17yQWTqcll85rk0na57QhtQm0FuSNCdkVfPBlP9xjZ2yCB-2QpZjpQetRkRrTPSvOGJoQz-
pR_QbmdiCnW8vqdoIArxX6IWUX4GDOIVXvyJJM1VAP4mhFswXTQdssgrVHU06bQ_yBhuAnPliA_l0ORXtFOAkzKJAqK5e8R5ppajYxz07N5u3Ii2Yyvd3NMo
Qq58g67wSQNnhJsdnCs6_9UJj9we683RjEYSa9E4VykgcFWxf9H2AMcpuHpsUPb6OF5eqz_ghbgYYAB3h_5-nSGhN82E6ePx7Y8iF6ge7ZMqYUd9hYAxD-7g
6hUFHl4hfCCzA98smkgXxXvpOWiUqSq98oCMBQKupe9iWAyX8HgTbBnjx22iyHRFplqOGm4ooiHQsjYZPkWHaefANbUlG5JqXBPDkmVp4E7Xiuib8nxtlTgk
TFrKLYZqD6z30Qf5qvRim8W3rizxqEhvm6yYBrCPGivfMmaZGcBEb1Z-ODRWn-6GOGlNapIFR5M1-a8On-uICSTj67PG2fyrZ8zR4CsJrEkSTXnpGYjo__b-
KJedvFKs37tP2PSI5XlNqSmUDHmYHuy1Dfkzac6IT4xWKKzUzEMSEp0uMby-1E5FOlsWxdcxWU7YRO3x0VRuenHGEoAVzJhg1nOFQhlt8wHIDCSPo7WNi2Ne
0tRaWxle91O_xStwSU-Fa4hPSGQoC6-aECbfHOzZkiSPXJsmSrRNwRyFQTzvIEFccFA54lbuzpKQgsCdAd_-ebVtVLmCYIIdtv8T1wSlqLGxV-VxPVLtDPJT
S5PloJZsd-0HZNtxlVcikfj9keUYXZMQgaBRboJMOhRpTZ-0IDPeMhcBvZuaiq8tgoUmZsZsXk1vUqXMjPkGQ9BDR0R_78HaVBDu87uD_c58-pKaMiZcDy4_
2QcQNjSUbDRQJV3FGge8wMAN2dlQ_f4akjUwvqGhRAtPNV3FQx1MbT8lqLG4_mvPIsrLvW2TmRz6OjrRCuGa5T4imRyLql2MUWt-rP3QIy7VttfbEPFlJn3v
qluV
}

