sprite $Live_Meeting_Console [96x99/16z] {
jTW9qgku3ePXhCc2aEn_kJTV8IVHYStlMqtUxffwU6GZEDE2I9MNdrL4cUHd4yGuxa0_qDbqYLYbB9Td7-Tcur_uyZwtAF_2br2lNmDy5KpuqHhWgw3VhC4K
YQ3oyKLSx_zc3MRWDvCZkdWDuU-F_Ty9HOoly-_tnwOYYDkvIPGly4tX8vSquP8rs3FuHtRutDJ2AfVvQDTZ01Fqvr_q7zTWwELZ3V0HmN-6DLpc8uy1N29M
fSjyP360oX6nocK-seNJ1C8QBlInXlS4AlHCbI_paRS1BQpXAX_j-Zr1hlBHOvVivpNC-vhyj8RiumhAb_d8Oa1QmsL-h85IOdALxseth85IBCPN-Qg-tpqD
I6kOyzU1VrCz9XZbM5HftlVRQBsARBtlygapCOl9lEy3VrL5MCF6dpmIurdVpYyGQw0MHweywVznWRo6yfeWgkNKh-7RVP2-i_KHQoY5E18zzsluw_0LHMaD
y5yJrEZKnm3ujfzV8A-Xn0Gn-ykt2d_k0Z51Zm4BgPdDdjzElx7ya7OkY6p6h-6Vlw9vmjtf__PzyW4XtttIT_YheTla0qBhHlFd3z-d7z2yxt7-pWKUzyVZ
aHvGzcdEzxVlIN_ogF-0_EdJtFaz_FoDWSS4P9tpJ_l-uNj-E2qti-7vv_sA2_Gch8Q-py-6k7JA_ktGhQuPZsuMAJBauG-JylQttLfxUlZHRg_KFgfMF_EK
SVDTxnx_kQrn-fnrgpb7UG1yP0exBj2PKAsbN7Bq4RyIzTKL_b5bgSSLRe6dF72p4podlXelKg6BkpB73UBXfrQB66H6S_AguW95snCIEIRKMxRp2qHbbXU5
lonivaX4cBYQUUVvx1QLCil3j_YJZ7fSG9X9Qhr1dF7xVFOHgLMlxNVkve_lUZuZMXRgyIe6Fs8rbpQ0js-_9Z_npS_yfu_4xF2HzLxGx7FmpxgyQlRn9caR
OEBt2V-KppuYRGDmcVoGjkppcoyHnRy1t_CHcyO5p5Jsz05q_BBqekPlA_oS71CKbdoiOKy-3trKPEpZ8IakWDvhk1z-FNnkVNyBLC9GhSbFpqXm0QIonGGp
LE6VVxK4O-WpBWRN8jLZG3NmbSeVl680ZNnvmm1HhC73V_7qRy6hF9s1ByeYQgbOG_AxgoNmwF3jso_WaLfEPT-IFtelptqLr9qWtFp65yfnusNaa-PLvG74
Xvz-KCkhHR7VdY-vF45nnF3FUKXTtrY-IZuTFeJ6CwMO0972zt_y0dyy8VabUEakMb7zroVulRJloy1dHVRqjnaV4dnEpoTuuS5RPDz-iQwES0KX-Dpscoxu
bIK_Cktp28OSVbpWbE_wOZpW4GPKPyxV5tycZU_xR4CUYQh3RmF6g-tvI8qpdvFcYt0P-pRqsKvuTFZT5sTvLe9F_kW2FFAxRmudVkGNQmDuu4_msS_nUy38
d-EpdmVqZqyK_YGV_cX0noTAlhOayr7oym1XwU3P5tsN-5CViPhr-EphHyB1J_X8pEGFNrCzFlcTAqZN5vxYuQ_RfiiejcTVVdNZMRvkcmkeaplW5lJoMTrT
9LyWkAzmVEFbB99y93FpTQqzrglddlhcklmLySSCPJPVZpO0vxcLPQf2gCJlPDi1yVUA-kFSDF6piQXDfCBBi_y1
}

