sprite $Load_Balancer_2D [96x25/16z] {
jPO9ZXqX30N1opCsizp_jkbvy9Ffh-m99SbIoL8reArR4ySXN5fhYiX31BG9CiSXCY4-Cd28oE780Jy4HW8PE51UCyxqpH2V-lw_KVWwywEFEVq9qmtj8RUL
tLOqOgZ2-DmVOmHVZODeKzB79TQ42OhtpesiOfDbuG-qgl9R7u_p8v79mVuxsVrNYgn-KCRkJvf_huy42kQRC60DT-tVwUkl-kFMDzIjdnx1mVuhuP5jo-w3
ilkzQAl_Yk_saNobz4p_6EohlxwQxRxQbLZYNQokkgu-Lp1btxv__X4HQsiSx7Uj4jdzBbMwnALt54Hsl_TH9XAqx_NLUUGx9XTwCPx5THlyWzlgtbSKCA7-
FV3Wvt8tOgZorP-h_vzHCyJNlgl_Ts8zfBCl1_Bm2s4VueSGJ7XMbqFqIXVCWXy1DI5DaVCG2Msd_t--
}

