sprite $Lync [96x96/16z] {
lTQ9egCg3CPno4AWVV_tlGJHJulOUjex_owpsLyYivrm6edQeMnvMfcKPhQDTdlQ6LxvoGIBOOmxcbHLbhW-xcV5QA8hXU_JqQSquB_q1NhyjXDVAq_0V-n7
Nnxwxtpm3FqdVjxv0_zRFvaH-9_xEcp_Kv_Cz2Sy-RCz3hvP-fBlBjhxOaQTftn8FviA-jGtsnnw73BuDspuw_hnhpwXYO_rR_hO_DgdTNtuvIEVhegRhvQW
KAbwUHGF_WryzCrux_SUFWJ-JHq-ZWS-IkS-VUG_cY-69GV_T7-YExwQ0hdO7_ezFtKV7-Shd-xwPlAAJ7peztn-HMO-qJS-ogC_yimqn6iY19zUzn_yWPVa
gS1r4qtz-Vx0grGvjLJhyDZr_Zd3V-M5jvimlmUvwyVH7tcFazamGEj3zDxvZpm6c0wsllNpqGSeGdk_3-ZeyjPUUcV_LQjfMzy_jn-05bnk-LtoH8dO-JQ0
_P5iLqf9b-1dklxxk-cYoQIA74EhpzIrwcVp3dwsQn-wDfnfzGFr7oDTHgGR-w-wmA6m3HXJopw3B_RFWw-CvWCmeLZ2_XU-DKA4-Su0iPnDxUt-ZyLNi1HZ
yCSI1b2i166OPakv-_FpRr-VWAU0qE5NuZf2uTlexx--qgcE6mWehWCkzdU-hFwWN_luQt7fO_zB7kSpte9DVEB1d_3ODfuCa7Bc4uq--4WyZUXbW9xuvFxZ
nSUkbmaM8HOMIODFH_zPVTpycTYU_bZUSAtK53xqvZ_zKND_NGhG6ijOlpfA2pvuueu_5XyRSJSnvdm0RY3kV8BVS2-7WEi_R7S3Il1fxtlTZxZyi_eDIslp
QURVMz-B-mFgFbtxKMv4mQFca_kDH_n4PUcnIzzDuxuIV1hzUHh2Hx_3l_4Ltsf_I5nyhVtLr_rZU_gZzhM_M9xqrpu9bpw_zME708_-Sb7wmf_6pIVrVk-x
wV74vwzz7F__uXEEN-NKBuzzht-5DP1U9077apY6Sl2P666V6YjwpuVjixdi_SeZIUg59Rx3OxSo-0X_tZmIVHCkLSyuLZ_FVKau8Kourd4wgSgN-ujp6D0Y
MeS8qw68YwJYggMCFXzzIHY02CkUrlHapz7dsO2ZfhMf7hNYjG9_SZnUMqLL9GOacgO-E-wlFDz_790E4xGASQgtxKtp-_txW6KXLU45bVR3mOuacfOifw1l
V0omPO2dNl8mG7GfRLd9ElZ3-jtNljMGuhWEMQuD_ZX1UbgpZmUOvS6_Ffus89bT3p1_T7tcC-tvRK3FUerPmEE0PBcKac_jh_vOSyN360pm7xtr9_l3rzJ2
XDq0dt3jCytE_pZ0q3Q0pBjrFjWV9S_M2Ga38lnxvpFoJKVwTlz8Q7Odc8Nw88rrVUs-BV7U_tDihRIDmfzO-49_puxb32ntVzAZF2Oz7qzKR5VnNq7mvu6T
32ex7ZJyIFnTOZtbboY6Mlmo8j6KL9aelXH-KoGFsZ_jFm
}

