sprite $Lync_WebApp_Client [96x96/16z] {
jTQ7bk8m38NXIBgIx9Hz_yTTB0SJS2397FYtJliSIsVAy2OnqF2ps0pusGcaGHDCVk93kPx3Qlm3No4qH2Icz0EVcUydn1f-u4ivWUe9ydr_UqAiuSj-zACr
D9z5Vh66y67IXZHyTmqA4R5_iqd4zCtFXkOlop92eg-kWQ0IVYb9zCKrY0bLFsf3-iuQE9wl-QNfUsjWBVgBtw-1_xO6WZ8DdLzAtQ91r_Nuy5s_hK7-kWQn
fdT-juPIhE7Qu6dFxzV0LzT006zV5EpvRGsuj8QsLcgFbHH0xySQ47LhE3bu6aXJslNR6X2rDU3p6bYPAMOVlv5ArloTHaNKrl1nI8oyP13LUNewygTfNXAY
KsiGPDEKcMBmVlkL_EDyRbrPWqZAITF2hDxwv4Tdrn3-abDEC7_rfpr_dgAvNuFk3Wd5pul1DdL-Tu7dDL1RmoN_mmNEhg7vUiQFfjRShq6nuzywwxSBxA-1
pNfVSbxKjFSFBr3Ne8Zgv_wEJwGBNdqD__02iGPNH2dj-oO4WpuN_hJyk_rwVu7ssH0ViUl3oONalTyTqFcnXay-YhzfzKl_Mdi3QYtsnjS3FmOKlpP7_C5t
R7luy-Fvu-_hlbLVzloum6lTWAxxPbRykVpwrxVi-6PN_JduUVdNDr_nsS6yvq_rW3t_rXkVTdrvyjLk5QGmUnTOWf_t_6twmSU_m4ix_7Wge_U-OfpNkksE
sGs7MVLztq-6UiBhXgVHGMV2dj_scvEfQ3UWPSoXd_K1bwJouaEjh4eX7XVOyCxq1N_TWIeaRI_G-8i-NdnXMGzGmTWkC6McgtxgVM46HDGq4ftkqocpnzgb
vpTvqLcW1bLJAqCAVtAwbSVQXUSFl-a2CCS2oXaHC9Rfus--FUOZTpruKTDsmZnNCaTZlkIRR4SJA0GXgzMGlVcbKxuW8Hd2RuFVw3B8UeBxQ5Jol_anU5a7
hoBn3zSVArTVgSHivtskljhBuCDiF_J55iAFtlkywTb7DtWCaPX61tvZXTVqsO_1gm1rDA0x3q1BzjOFzbxxN_YauST8Ok906to9BVOI9znyZbzRVwNDtVMk
S_mEVp1BuQkgmTPaMAF2Xu3YSwtws-TsAxbigpwhvUGP6XCHQwE906u8UhzHPbh-yjuVs025tYT23I-PL3yQZMjU_SR3hL3b02tXuPS4GEXTTCA7keTV3YZ5
Aj3yJx4U-aKllhO38jSplhpnnrlXe-0gH5GfTIMYM8NRiS-suuk4Fn87hzlHigCELjrJvv-QlmZkVl33DhINrJqV-eFXoGyTpTUL5xMQHohh0IP7FaosVkWF
_sPHpE8rBQykQp_osV3aO-jBVNppFbilmCD1QlBm7JMVRetbkRcCV2_K2yYHJwRI-NcA0rfEtZKCGnnpb1ZauMly2d-J3xrFCJWT3eD1xhvUyZNsSFQ0yA6b
atvyTfmwGEz-2Nj-IibJmmEccF-Pn0oh7_dud5DQQyVmC8Wda-5KRARDVtJ3olLI7-Bp8XaD9uEPThvNIFn5Twd7EeRJ4QppzMPnt0_bBefQVPMdR3nSQCUt
b98CaSP_Mf9I6eqk-_s4ad7riTrN-eOV1vIiZOhQAys_uQkcdEvnt2DorI_vQfvIBhK3Ylurl-Kvtm-m7_Zj04hPV-2t0oJ_sJygjf1lVYbTze_BjJ6wwAkT
oRFRFHqkHISIDHMgbQV_3m
}

