sprite $Lync_Phone_Edition [96x97/16z] {
jPY9cgCg48L7eKujaFT_tKkHYaXwp7LQyy_I-t_mK1Y__dEATVdpHLO8hz_J9rPJ-fgUMDKaVwUPJ11H5Lg-KGmweaBVM3i1r05m-_Ok18G_vqoWswiPVWVv
riKpp_v4k7Fn_Euduni7dZT_14XztELVmUz-bCVZmRJSr8sy-RKsVGMGhkipYyn-MDUpltlv4eZbpI-ryQYW1cIzEfOo-w7LAL6KvajwiEhaPokbwOsUbAfO
B-bdlrXnluOUxVqYb79UVgKNdVrYPat910gavPaQ8__cDL0dFslJLzTp8oAWflu-iFwptcQ_gfM-ip0pLGgmlLt_hHoR_TBr1WAncJ40cW1e-HVzv7VzSt14
XVcvy_mZ8PtNJtxHhbS2rB_WRyOrn4iEdTu64flyeHTY1jYYCF4l8lGHG6TAocp3F_JSTrO4x5yJOcjWqs-NaF-t7PlypxaiQ4XlnGFqkGaK-e3Eb9IbxFoX
Du0ROFP8XgYfHZcK1oTcbUo5EkP-HRJItnWJr4neukoiKgqxVod5J81e1O1e7rc0FW2aO__ZKL_-udv68C-nLsiS-iSpsB7V4xpXMglh6K6KmwP3_uybPMv-
fvPI6mRqCKBdDVQX_moGVoIiNDtVwVeOImN1YGz0Py3FRI0fTPUWwCHjwFM1w_62yBcaTQv7r6fZqnFHgtdTESUcyElzKzkmnetU4we0RE4HcvuZ-A-CbCEI
e1e9XMFi9RHcfZQku120nf_tMILHnwenjXtjOmzMCqP0n9_01cKFe7r17SQ65kk7Dpe_bJ0okX_Bk03xaS3DNufWC4hwJEY5D__2LY90He8ql-4T8XOMwV_6
cm4BCXfIPGpHGbBibJ1SicziIZWcz5h37wpGCfNq4nRUIlgW9pIiXd-GsOfD9Ss8yHYbmqiWrxFLsHybiGSS9QXPuLr97_IbEhB-vH7kGqaoGezASZl4zSC_
aM0V4bWwV50IK-piWJzAsitgaqtFr67UbQGR73iR60wUS_UpoWCmA03lIjh6EdOsK1o-tgVzh0xYniH4nDWWrWvYPmCZrn-mJBEwyulVO_46YQeIGXze-ln4
zvUIGc3T54H9Ot22nu7_u41tkZI6XoVGzJhiZmF_qO7M4T0O-ZrMXtzU__cICEp7-eTpnZyVQE5Fb9q-rd-AD9LqX9HzDurwrZyVw2DzdSff6JLUl7vTafeL
URq_xQn750O5Kyxv0rsOHJHsjhoZ6v9FbVHZLaMbXx1_GP0EGFX_CQl5JFrDqRGSCldF7sWPWrDaNQxvZmyqQotQzAjprHybZLbrVRLMJbBd1lyygsgr5caI
CkS6_tY53dqjlhV9r6vQVpp6b9VVkb_kwcT-XIxDltODt-WV1zg6NqI6T1tmh_nnr-l-q8XiMih3Z_3_hgIzNyDFmipfslh7WGw_gBxymfcOqpL_a37xKo8M
wh_3vWQbAtvdy_lvQlQkNJt04Sct-bcOcjmXyXrYaJlyAQdxMRZRmzz8V8C_vPoxNtXfIkem4wqz0DVyoVLPIocBf5xy8BUF1UibV-vOysT9AqJ0WzKl85_o
K_WtY4I4XPss2InqrKy__07p3NwYJFHtlwlbylezGCnHKJFi_Ar_aNJDlz6R8DcHlHuiD_b9n2UUM8GwgyTvw4r-ZYv68tJz_a1p0DAQ-fBzjY5ohvzupCrJ
JhVv0zu74Dtj3te0lkTd4Rff_GT8GwrnpKyuW4KOdVNFDrY8Dl5_
}

