sprite $Management_Console [96x137/16z] {
j9FHZjim30GZShca__-7AyWKY0WsNEEKQU_kRIRWAfz10o6Vdm4I97zKK5Bx7o7HjijJMw7DI1x-LmNIqZ-7fcps6oxkjT7VqMLlxFK3aAMWE_s6pkuPof-1
xJEiVkZc8wK_0rT7qbr-mqL1GCeUVmMqBJDiyIkIhJEKlsLWzmpbrzk2W90D_YgiCoY93VvE-RzcQ4hg1dyLjBFE83ly5UZyUGPcGCBMWWxc3EtJMitmsj_W
lXQq2gt_xxn_g-paVIpu7T14XlqCICxmtjzXS0bKeKs4XBpoi_Pbs391qefNCt1GxmVkI7q6biBB6PY1UZyMXE8Y82cl6LxuMtxmd27jPdPNK1Bjl_tyUZzW
MEeV2Y_yzNu0MBZ19fS16KVID_xnmNDS1YqXBmlIgHcU_RckpzlF0jc19j8vF_tWQGOcGbtMxMRNzC_234pxB3pxsrptF4rkA-eiPc05f3xwvtSN7VCOUeZm
Y0hOJK11oeC_lxk9XNU_YXZZS0wyOvV-dE5vNmkcttZGH0Ka8voa3uZhW834e_-yVHxVGw32ZXz1Ju8t0RsSWOauylWCcuX3E8WZKj-XoYLAKkxV3r6t7wZG
nJZmin0dTbz0kty__FvcYPA2cDiUKJXk0Y1nun-doUEFmjXCud3cRQeG1_N2tbbc8BtyTHgZXucH9kP7-0mSKz-fGajxaZCiVloZp4mJ7Lj18Dnne0GqsVzk
Nn1EDEVwUgYU_drb2WGxzpRMo6jh9b7T00UUkTMFmSFneU9b23ucvkTOovcR3GNoQ0mV1dofvOj_SFZmOUUFwXePvc2bfSQeYMxXyv88OjwT7FBEzwiLqJJC
vAtnaIh-pq1C50QctI0RrVamVeorSE0MLmkvq0f_uINm8bo3VtUmgUTy67_rppnupiwlEUMwmb_uuAjgos5mTw12SFsAy0daV4ep9PzffVqCNpZmfhPl_dL-
K_1JBZ4K6fdsng-5sobyll3QbS9WVOIwuV78AKs3b6epXv9Yh4s-SI-yU3WXnxybvR6Kul2BNqgQ7s5EScuqu_V6DtxSh7Nu49hXNPoNGQKxVwv3S_63MtSY
nbejv-n5XS2Y_LABa7xzv5UJqRtlQy8QQrJQtM0wg391PJFez7_dhwvSA1NdhvL2XGyNYqMr4RJhns3qmMT-8kSJeLZofMmhfPOLlinmGWg2SJyEOunoupS_
lu-rYCR6vZOJQlaUQm5NOS3uuJ3nW-xyDla-riX7CWS_76evL5VV4W1NDgfz_8OVOyrKCjNy2PytlbodP-Sp1Amz9DgF_1RyQeq_0w9IjdtEUFE_pXxLLK0W
Af_gYew1EtyQ9EVxQotNNFTj2-9sm-jC2AoGcNs4h_9_V3AygJMKdEi-yIiTmsU6T4XKTxYK3lo6X4OXC79UuN_p8vgftepFqJ-N0QK3lwLAxUFGSbahPV75
yA7Wgw3T-WTptH_u17O7e6BVv-ly5noO1dPs82wMLtSy_uT_FJDfN-VX0FfUAG88IrVBdY4wyTEXFusVZlnmmC_75AXzhHG0gYA2DrcmPJzK1vAfrZEVhh7c
qKG9YE3uwH2tLXlwvA_intCe7VaF2iLAMU4tvd2G422pAz54ksAcephnR-78fqZi-DG9XnPJ3JpvVhK4UcK_yQyplo7d3n_jv01230Mpi6IqJvULlV7RWHyV
8Ji-mbzuYV1141M8pcWOtGJMhRgl_-5tmzMOoYlxsy9bcDIYxnetgubAZ_27werVoFcIuhyb5FppFbV6xFVsPlja7Yppu1x-g-jt_WyYvzS8AMV3X-xxt6J_
TeR5FySQynR-M_J5__M8YDY90ALomEzZJKN5-3xMXAFnrV3t_FtBw-t806gYXPTzh7tUQemPKHzTkGrFlqlV-TNvfh8xuAsSqDffdulpku8XiL9mXVzK7GT-
V7dzPK0vj-_i8toMZJzCsbJwqyDNwvzyvvlITjEcQgeV_lvIZcM81XKrVczUNSEp3aL-6-GxVoy3BWTiwV0LlXiqS1_U-Aq_lRg3cL-lCpz2mcOG8QrzFldX
m7CiT5Ndl-7QHGQFLyiv7_WH4Y7uuL1OLlYYtIN2q6ici3wVEYoT_k8--Vd8No45tdir-57T4ACFLsTvTkOnM4rd_jrX6L1DBV0HZKj4OwK8wopFE_iX_EBV
ygCCkm7bpAeh_BNFk-6VAZQ3cCVhRS3Iplnx6NO3obK27nyXiXUxMChAGxM_JAou-3Nu1-MxGKrmVZYCRQSeyvizT1XVXN_F3vND8HxLt3U7jS-rCpydsXmw
jnF_zo7HL2uI-6ZyyJHrONsvL5_ZN_YbVXbGge6FrzfpQh2EC1Zwj-SlHbyBV_sOm_Wk7skErLTey7-jceTowq0C0oK2nDcf__-rhp0ovpoIXRITahvx8jDS
1hm_LFPYzjSQIhxDVZhuzjgBl1yIfQO23NZRxVPhRVFUMdu-8OBCL7CNIEX3Nx_Mwe_MjjtF-LSHBEQ2Ybx3fk-3Ty7x9R39umBnNFhM5lL3Tcr_7leXS2PJ
1oIoZjtRxJLSZ5_jRuuBCTwcGjSkFFL7wrqXCwxlJQ_XUkxNv7TZIg87qskuagV-RB-zYCn4ljsjeVm47_b3F27tWOpnFg-X_7pen-ptXTBWQHxIJ_m0c3j_
ag_lpUNxVXJrjVU1HBRVdJ_FxFj2RiHbxy-Z_IREzKLseGEiDJZ_Ai7f-nAo_Rq6vryaM7sHHGMQaFLJ2MilU11WAC_z8S7eTvUGCppsDrB2-9kRvYj-QC3h
Ex0l6FyY2LxVWJt67vBJppZ_7aemVXEO_MP2HXuHoDsF0lFKltQWzJv0gGkjnt98TE1SZV87QY93k0kezNiW2KPVvYX0iduPJuNp9tPK08GBH0SaRhVUokwU
c09fqAeRQcp2K8754D98fsymf2y-fNELnk0d_Ntyhq1foFXRp-NhXAhW_51FvwkW2kTwZY6jopUXf37oeHyoUiVAAYWF_63PQHGEg193oScEhFT9OGMMe2fH
g5yrFqbVOWMr0x7y9ck0L44Y_5R_0W
}

