sprite $Microphone [96x105/16z] {
xTc9TlCg30HWWyH80Xto_czx3KuvwP-GtCJah9tksoSysDsylPt0321n3DiN4W4v0l3o2I6XoQBIitX2O8W0cikUR6q8uZgUq40jVarf4q0hYuUKveg8PZzU
0oqh7cYeWcECb63N0V6i7O_YsNRTnfw69EKO4CvkQjTRyIRf1YFaFe3FRQgLBDogAVzs4L6yw8c68iHoAPwFukbkkhXdaVGPJWdQz9vU_5rOFpo0GC1ryIsb
5t-VWD8EWD_VL7J_ohiUmlG0mWSw83BAeTddmjtUkiXY6hg8ZUfdIJOhQBxqmQkEit8MKYyYUEN6I9m09EPRtieuA-S55Nkw0I6X9INUyHjUTtvKCm-Aco0-
uHDHY4HyrKKXFxnWUnNEppSW9UmOGlCJMimwRwRWyDgtfpwZyMP6TELXhfs_F-tc6vocssDUIZRBXUcdUiyxh_sIVPqepquW4Y-vnvsuwxllEbdynDUfdspd
RS_kUpXuTN_ZaWzuvcFthQUu2tTUlO2tRP7Vbg_Q3w36fgiLn6sHdxJnqWRilg3nqlX5FadtfHz0TUfdVTYM-G5surSoCyHjdRz1Rdqs4zvM-X5stT_cmmJR
KdzBOZsvx7vIXCL-W7Q--mpQ5lkjePmRxxM0j-N-5iUlEO9jjTyI4hHjCX3M-psHc9d2u1Vx8t_-mlpvV_wV7x_gCo3VymD4pRxcHuYf7dxypkfLScw-2OVL
VkgyjlwjPasBUUgy0CttRBAu8koyAU3TDnDUlNoH35WzV1LUtRwO07xuAiBBwyb0kVgos0ymDGFynyVQ_OqmpGBxyG64nRuLWNlfVW7MrX-wB-xvnm-hhrvp
5I-7dzVjxlL_BGcQJKksmqTOGdD2I-eHDxFkA-9vd1AGc9c8c7gic6brLyDPFIQWqRTXoyNDz-3atH82qi07BsQvNlPa8WPI_BGOu0vlegXvusl_A2U0mliw
T_q-W4XkkjsC18TtQqyJdO766zs64pYSr2F56DKjxNnf7_vmGWJIFt8S8V5oSOujamadzAugOi_z30RePJCymIUPJ9ZtFkT3U-XvFY5-e8T_Cnymcy3gi-B3
mpmUmCIFEqhPYH_nOPhP07xamvqc_9i36A_zrthFUpxsC3yTiBqQmCmfFUo_NAwfdWtyWDzwxdb6lt5RQxsqP9wSF-xjCyOKvT_-5Zh_Um2XrCj8hTFRPX4z
ekPrVBfnk4t7RyFbPZscWfxuzDS41YIF4Px2DCa7dWLWYk5__-ZIyRKskxxoM8E-_JCiCEHdWiU7_FYmVFPJdiO4ZtFUJzphPuXF1iGordxkDhpL1tiGWnod
LslcL48w3e7Zhr3jYqzXEns2xfZ_zlE-U1t5dpw4VG1kUTxvjlX5OV5BfL_BT-5jNLZgHOWY7U5BRVpQ0PL6hF5ha-o2uLTBs-94LAThf29iguDo4HpnWcrv
s2uZnb_mvNgtffGiN_0ZSqhOan9pt9xdFm
}

