sprite $Monitor__LCD [96x137/16z] {
jPa7aXix34H5XEPKpKhtF-x_43KznO8vOQbzJXLV0sZQtl1uKnmkZp_30Fkx10Ni_p_4uUNRRcePz6MaEui1-bs_q_ytHGFkLjAzlkftrzJtL_tcngFa6kRz
WPLn3VD-2uvgc9_VpRvT0_rSeNkhgOQv-NE2i8PPVs0DxMe0QvZp0ws2GFkt2ll6_A-rRP1hSDOmvN--bZr0Kmtp_kVhPw6_gw4eQvZnHmAs0DKkWJNC-2DX
zJr0tkhuKGfhcF97ma9_ImXz9B26AJzhq4RX0eKrpFaZmVS0BJkiOSBF6dH3oeuu87D-rg2Z19SRVYJ_TgIgEO4rNFSZ-rd3O8MeOShF6apdQa0mz4SDeoCv
l5pqO-YF8q69j0I97s9HmvIVRvN-I10cNAW1ZUGVr22Y8IxIEAy17pf_3c0DJTlc3rZ3XB-hGNfOmwIVHvAC0phjvrkLZ3fSHlvwnSz_kNF0NiFC_4nm-bCD
DZd_YcMD6kIVQAiX--jLFznzUR_LOO9BzgDUzWThr21a_5OvV_Elf_x5to0IN4vhe3z--civ3LZzmxi6FQs1yrU4VxcwmBW65LLb3VIt-N5r0TPGDszfzYs0
DVJ-vMB3UmshCo0YbFXM0seZ_3SMo3MKKbg0l7zkDG2x_zu2h65R81AKj1fwFvvt5c0Du0PzWW7ItGVhlGLOWtqM28GdKeNty-Fg4-rhQ6-L0RBFZyv_PG4d
gORI9pZrkt-vlm1hS2b4OlZil_T4Sms5kF_BV_E9vXhao3-n06j0zY_qNrl0nyIHfFVNfIxqSu7R3RE6pmREW8NpNrnWzGEMrzBxwn8Bq7zb0Jy0sHy1z5zP
OBdhx-V7p872BydF-ISEH7_efVVN9Vpa-4FrvnF7Vad-fVUl1_fWmR5VJlprm1y9Am0SpI_7VgpZyOCdtepdF_Cl1_e06qT-x_qhpXQWlflbgl-9mmLu_615
nmM_lPuSgW9rFHgVVdBgh_Qp3XVWon_vWsF_KXrrcnurDq0t2ywC_G74AZRgCZn-K35Wv5zZ1HLlqrS01-Fp0MLgxuTXQLZyKX5sl8oE7wnN_GNO_QwgelNJ
mM3wU_v7yRs2ga6ncXhcz7Vy7lx7Gy44rq0-DUJnoVEoF_0j0TeGuG8yVi_b-xmH_zHW6hGQwa9zfbwPtyFVaBQ2AmEArPN7JonNxqCi4gef4S6Buz_mguXe
ziTBGZNJ7R6V5u_VizxqimQF06AWyRfVDp_lJnI0wGvSb_j-pVCJwrQmMjtML-PvwDSqVr-3Cm2rmlmd1_pApnfu9A__urfd_1dTZrJVv1hgBV_uIDu2ODhN
i4puUIGka6jO9_q6mCts1Igw6jRv-tX4gD8Fi8P9ltpiWNjj860DFnD-WPk3S870zLF3nFk7gvcdXBebr2b_2VsRFO8B1As6-bk_GutyEy5Dr-MNVjtr_HBz
2gR-Ep-lavS8FmEqw3r_7ZyliVlTH8hTy_FwuuJA11EHKZpxBVc7vybdsdqkGH5FVbEraLzWGzJS7Kv_esZoszYlz0yIWiulfTXrls7irc1Fa0tMGB_zPlwm
Cm602c4D5_m-7hvBQ7xoq4j-6RmVxV600QpXt5y07KsVLZ3AMSF8J-WVJyyLSeAS-XskfzDpXNma-B5VyW8wmZqdk9kF_LmWJpyEiDxlTkXNL3sRdXWJ-lcT
_em3cgS_3d3T_U-40xy0fjV6Ln7rFi63mVnSeEg5yOK1JE3yOty01fpChg5KoZpyPEmN0Chn3mDa3m00w-u3sECuu82cba3VZLOO00z6Ug8HS31-4nFTZh4d
EB-7EWgevtQYCRxp0-zM1cMZ01y69CBVXE88z76230D4CbhX7CtTpkpyUi750CJuTp6WujBuuFYt4Cz74jLvFJ6a7NAtjGBblfije5OV1YXgXLD_dsAHm0Zf
iB337rCKzHO1Dzq3r5733dbC8uQWzeJSTKARj-W_aN6JnpSfekR-DhkRdBVw7m
}

