sprite $PC [96x103/16z] {
jTdfOgiw30HWB8r69Wll_xWt1XKxmQ6Kovcp_lh6aixQ3Zj98D9mUQgk0ke_udLvUx9_qs3sincXoVNBeI6zZNAz3srFyGzy81OJPxZUHoocdk5g7_hJaE8C
L_bHSFqPmgy5zGnYr2jz8j8ioUGgtp0-s9mX3UcgCoHozf_JM0zT2af0lSn_lXeGaPI6-QiOvV_nMFtIuEi8Fr5QEiyhJIpyEN46Q6t0wJE8ySMGgr-Nf5eR
vDmPaX4fLRzfY09P6upwzyL3qkAp-lKC6WqdpX2BJqj8Cloru675_rZIyJC8o-8RtrQ_BgdefvQKBFIElzkWf1nS_AuVURX-D4Wzm_xYz_rwXdK4ANh9_Xc4
fkazkl5xIohqKg16tLcyVEXcrUysUFWrIihUuYMbQ16pFJ-MnC-2_Xa8bIIXpp-3bVY-7sUGj-Zs36g9EXHs-Pf0BdufsF5ljzSPseB-6HISfj7Iqb3qWxwP
lHgy5jGboRi_Ufx6cLSkMNpVzTtC_3Ozk2b0UmQ5ZrCUfob9wDLtZhVxDpzRYT-d4Iqkgg9Mpu3YbmR2dOnKF-yjg2INCxmLb1ZrpP_S-xu_zmU8Conu4j48
uWpGFFlPrPk2wdyTuBxeSGPR2juRKlMzxz_TTozS4cVGuh-o5gWHrS_gRK7rR_i3D6U8WgQ1W8xx_g41wXbIsm3ITBJH4NvJKFsl0zn2hajw84LauOiFS9fy
_EBl3M0rzGmf0dBruRRZ__9xxECC7ZjYzKS0uNlhU_6F3X2vJPFzrRyVkd3ztU0xldVyt93JzFt2aTkZ-ZpY-xto9RMYw-TTFmfow-VAHqDK-7a_Dxw_lxzM
t4xutl77LPyRQaNVboD-RdolstaFsVKboNVVmy-DV-lpKoR92tmlVYSZvsnysVDzzPzU1-WzVxgJaK_V3lW-vJh0rCkJJGxxllZPcWNTfsu3t_CtFxlnbm6S
7_dmqVLzySUSeLm7w2Lpa_68xyi1iaFWStBN7y_vJb_Uxu2AVH_Wlk_RwkF39tsvCKe3lmtmFEXdv8-2Q73C1Vhjmh_v-QiFp0KeKHNuUDJNhlzMG8FHQSoC
0XNh3U0zNqNDLZzlVGASEzmvytE1FhP-xleQFf1jzVDMfmw8w2lWnX_tVMlzgiVtI8FEFuPlX9_ohVXBWS52jpG80CkPjXJ0dNW_y_sWRujF6Dq1SygG08Ld
9yYbmDpTh3t3SzTNSyw-M-49C2RGOL0ew9w9OL0o1l1ITyftgukVTRMPq_YFla6LNjAUuQ2FJB0kFc5zx317Z3QlQmvjFOFl-bnzqcE2M3nd9oqyYELWZ0B2
7iTzEjRzg2YmE9Jw-G16V0aPPnY_-QL06fzcxjbHKXS_nqm1uvBLfy5_zUdXivYbW4RFxcm-WrJuagXO2mYC7H-hFn2Pis_5BBJdd6FnaSJWQyLQGAXjVIZ2
LzgBOoQN5mkNiyfGOwXf6e93agqFX3-0LaIiBnQ5XbwVtsk80XD9sds_5NzGaaOop6qq_4r5H5v9wBy_NgmQUYymz6AjBqbiurlulwJo_GQLQFZqUT0tx3Qe
H9AUyubkz1MO4R8M99pO3wXzFWeCMXl4_ln-uJUzDaZJyDVt9zf6N_qwGWsRzvzRKCZz1iNHzqU4jiT7WK5F-eEnpzTWoKa_aThTVGqYf_n1tmew2HKqFUCF
g0MgEmKa3HO-gSFHs5hGjMFlS1CZRVP9ESpNWgt-umjWr7cPzV770peKsEerSARuzEw9JwygtNJZjo4np4bIzUCHqh73cpFOim6TwFd1o_0_8qPtz7pruAze
83vykBFmLqH0Ukc84fWN7R7xgoheQqXgw9SbYSACD0FaA_uV
}

