sprite $Phone__PBX [96x79/16z] {
jPE9OgKg44I1Mk2f__-zBt1j8qPd9jkP9PZbL5jDqcSeb2sMz2kWkz-GLNx97bWvxPJoa_P0vilkDyfFs0TJ0bAYILUdRr72Vaam9T2rDQIlasLDyC02rDhw
7JzjwIaW3_tc_DrgxXC4rMNTAdzi-3d0h6rPZAyF7zm5o7PhLlxoy1CNlOQ-Adzl-Fi4gcCPwOl0DuITHunB-XBoBRjrXpdZI_LdFt4QNiWTcD_efWvEVdQw
dIM_AFpa5ZZPfmJkI2ZveEWp2Jhfvm210N8kuy_u-9ars4z-ul2NKhes9I2dtCyq__7MwzulTDYMIfH1JlxlZPfJwT3u1xtqv2S0hTksxFgKstyld4O2zBS4
MFT-anJPjcshPTTZw0UDAOy4A_z5VnlWKKrz6txbqKqB_ckjrH8byQzwNLSie83Bs_0jkYdjohu6q7ZK1vuGWTARtrmA2aOtDpZbWbZ3e_uQ87H_RtubNYIt
MofIGSSgp_evWALGO_Y68E76_VfRNWaqF-YfcuJHjxStZ7TITdt0EQ4pbrHCKXTiTVtePi60HqAfJo3bFQ6amE9DWD3fzwRk-bg55oNXEI5AKevsEBZHz-bN
0H7GMXILdnDS4ivh40EzGtJgljX0oxBeM8Fg0yWOY7izmKMFTJCc-9Rudb3aMy9FxtumcFHQY4u1YHsjuvNAlWP_H3bZzalWEG4xXxMS4ofGEliQT049EvIF
tos2mJWEs-i3mH7m-aFsfvnIxfb4ofh82I0uzDrFBz79IHy04JSI07PAITrVm6i2KZaaafnLrqqxmAmVMk0K1aP0xdfmK18EFSvwMNNRjkbMSWQzXY2Ny-k0
1paXXZ_hPKjjQveuTNDzXN8A0rYhkPCwEEpKm5sdfUak0T4LJkU2E7RSMXLFp7ePxZQlzQeFrNoE1mPgozBqf9UBXr1rkUcdNAg_QubQjwrgibE1atUbMZlf
CTsUE1Flv_S7jNv5hlhmqs4zhG4augJZVL_Dep-m5407SSKvqDbV_3wsLsfG4DBB0yfnvl7V0JxeaP9rxaM3lU6RX-Dy21NmgdVN9tXAEAG0TPeQEdzX9qV0
RJULgSFQpW5Wd0Km4Z36YmJjC1VoePlQAb8dUzbyEqIKCLSVlWZka5TzQyC_eDTDruG8k7_W77RLkuL_KDIsvHGmhG4AfkeB-QHdRU4FuBQrSq9O-m7lSTIf
l6aWJjrqNC8U9Nb-1R_GACO7e7pmKU_MgRKwJMJLRPr72k4KG91wrBE6tJbTA57IDM7iDfoZ-iWAfdlJiQxwM4ETMuq4sjIHvewkUhhLWOrq3xsiKm0TH5p0
3_hwP9_NiBRR10wUzGexqnDHqbhF0T0KyDJDRbT9C_S9FYTGjJCIud3NZQTgdidoqgQ064-tUcgtC_qZnNKaC01he0zw3_bq9_-bfCMd1E1Kqgol7fJqEUXs
UGNNggkUyW3fqsID10O0-K7l0TENW6ipTHjm31ztyii9foNSwf6-GPPhfQx-lHj5DT-WoDMS0oID22kdxmExAlmdlLtIpy1823kx7Ud7oB8z3y_qenJR8dQz
LT9F0xkxVxYQkIJfr-nHafb-4Noc-Fy1
}

