sprite $Phone__traditional [96x90/16z] {
jPc9ifjA44Ddf9Rm_VyV3jD35yR0NPtpriHLHz1IzdPB1oLBHFiFzB2jWMsXj_T2Ez0JCAFGtWTafRr0s69_vyCd7Rt-fjxr4hAmGJmJRqcW0xWE0FNd15X8
yYuWJWdctwupvHiatfe0H-eBa7Xd0htf2vAuJ43x3TAB7nNmbgQxkVlRdJ_XRzPAytoV31ZXEC2msN_gHtBoz-7ddsk0SGm09sqbWYTazH_v2JnztpFr4HYV
NVdpI3_t5zEmB34kbVupil0JFuUszA7LddwK_o-laFuLv5Kqv0bt_vzU8Vr5o8itFv21mJ--WWLkzB0BfTyhTpVwvf1eRg2rBhjGoCbDmZU_BNIvzBtt1lc2
OF3uz_TlrEsOUh7trkWB55TyxqPT8w4rKS98Y4yJ64zyxqQqMrC0a7ecw88OpDtkVEj6CXe51a4pQxXBw2jylL7xd2Zz2X5RmcN0-0W_B85cWy6O05iDr1ci
_aY-NG8ShQU-sWDd3PrNViIF0c2rBY8IZElkDVGuK9-7Nl-oxyPvqBElG0eYX5dqWRxvJznr8FSMKPPX1omf05N2sH-r9nLXuxDbJgR-GuC05SWQJlS9Ie41
DpseYm0QpzFHWu0-BA6755K360Mt_oUn4TgoP7owJ32qs1-Bn5c3iWPW9Bo2OXmHYVN5T13IOv4YQyOY2z1bmhEyOqBpNizKXWPRpG-l1EW0qFg5lnSpGkw7
xpPRVvtEmrfPYD73OZDc0e7U-gs-0ip3CZjLUd5EnneyZ4Xzxv3Dqv5AVtg1ksN6OjHq8FdnyR1d3-7d6bOOCVMd01hNqybc7pMTJdcbUbXi2rK3ADNptnu8
HtqgvPpET2RerOCN1y8Z87TR-fi3mMfucGurODzw63mCS1ngMJ52GwgLk_k7j7-dzZgTHIjsFJ8WBmzF_VetEVHDWtF1673pvp9LUXar7OvcfMqwdVRZCUrB
8AyJ6fmMMdehzUXqwKUpcdfaiyi-7Ipsl8vW0erA25P0_fL4AFqq6f-wXRHyr7G0UR1_4ru6Xb8VAZz8OcVOb7wUfeCCLlNWWP0z3FNK1z0Gk_z0n9PimT6W
c7vnEXSDKDFnQ5Q8ZyTg7spJYNj_bDzg0AHvByn7VaZPBE2SJZRxiUedvAOlV-3etlsqq3f02mmjgkc0ESUQ3i9BFNrDP_Vhh8_Kkqbadma4jJnKqy6SexSU
Dla-dRBS1AGUpVbHpoEP22txTEW1Kk_HxM4wYOeuFx_Djlc9rW1c3LhPfZFdhgE-fdFqst48y6AXfN-orv2pgkd4E59ewxQcWpZv1r8zUJv9U_BNaM8UwS6Q
JX_D7gU37jV-P4dE_aoe8uqvrdJWfGXMjxV-nNV-Y9X7sjPfH_NmCXr-_VmFkn_zCSW4XWDq-e_TcaJZb_vnKBCT_57q1Z9hyAZXE1sYuTvV-jLkjOC_TfW9
Cg3ncljq9BA3j_xIUuNju8y3R4CZWLuUJzCXqVcfF-qYMc4x62VGEhE6sATJnx_pbptbXRmiFkcbs8v4gAQJ-bl_sPxCSUjeJzXR7McR3Xlk_LFFzegzl2Ge
DE4yaX268lLt_cbNRoUm1VYedw2sMjEvzb-UfkZLZIFHWQs6eU-yz9SUN_n9qKpG2uxDYyvh_-dmrp3lTDAlP0rekFQV3dz7dwzmj6U0qD1mvPVFXxy7fmHl
2BZodqxplIEvv3kwy6lQU_i1NNk2vPsJVp_Dpq0bEBdpd-m_Fj8d_ZfD-nqzCk7M7_bXzFPRwaYN_Z-SvlpTqjcl_4gqlz8v4ux-E1t-JKTAV_ZqdS6RZfJ-
ElpxwF8o4q3D_xQtWkaltDkRaP_rQky6zfE-jxVJvOBjlz19IKHll-0V
}

