sprite $Presence_Icon__available [96x96/16z] {
jTe7RcGX40RXDVtttl_8rcCIpgKIj7FwO4hEl7_t6UF_nXbZei-PU6-RkSJ20rmiiMo-3ypp9jpuL8rDKvNR0WjVRrkddWkCYyzuspmZrmBZllt9ZsqpjNa3
RjilhlCLQjw0om_WnGBJl_8yjr_Vt_qngQpJkVjr1RhdcJgQV9vEVvvBctvFVs0_2V4p_R7ua0VRdsFzC3xEJm5T-_bkclkc_RxzfqXxxnVGeU_RUv-qztv8
U--dW0vyqLxuehtmINll-_QJ1xveBtpHljCfuEls7R1_tNxo1NpT7lYwVQU1xzlF0RvhtsdWw_P9X_Z-ypx4zv_tmFVjEyJtxODy_taFVDy-7UJxxpd0H-sz
xzidnFVjgI_q_ax_mK_Ajr-dVl3tj4y1txTF8T-tHxvlZtpV7lc-FV9zU-JxziZtxP7lsoFVjqU-RuzytnxvlZtoVNlgfsFQCt_YfZtrqwezz9EEQKzz-Nal
VD5U-A8zy4LxuHC-AU6BtP_nKy8Ndpd2LvyvtYVjlP_lfZRw3NQFVDtU-m7jgS_ufAGVmXVbLx-cFuYVudvDVpaV_EHLWFJTgzRpmTFdcwVFPm-VBvy-7pz-
llzSeAl6ZrFhtVtHp_TLlV07hwyuVdt8-UjRJb-Vymu
}

