sprite $Registrar [96x94/16z] {
tTQ7rh983CRn94znx_-AzmWv0lQLcMt_hxwMtsXG60-ESSpvHVKG3l6M7lruMJvKMOT04ltNN_OpFl8d_C-l7jZvVEc3toPgbsNvBZtnByIev6T-SLXFVNfK
p_qO5lxZFb_uG4KK7ej8tCfdZxdTLczUV-RpBrGURdtocBwjrdBAVB9G7IZbM3_bQoAg042kHvz41FWG8fAtyjbZ5bph2aiKnxt-iWKkIRq2pM6-JRI-hK1p
a4yRN659vBR0a_aN7_imVncaRDAM99AzG0rv_JR0lgRZk40EyCi29A4fzG8afP--lta89c09VQyaiJE_c3y-pDy4H2vezJi0rrodvmDZyH4TTmj80-PFG02Z
myMI05upRdvLHcGzTBmrxXy3is3AGbMklYMkllJn_5-7ytyyFCOgmDU8zhSt8AFzdvCB5R0jrUfJlO0ad_Nf0hAFAtFnmnBRhvFpeVl2c7rwkFgGLBNuYd3z
T7mxgO3ixx8acn6MkFXohlxFKOLU86c9LEpV04_w9IojMtcA938aOVMr-b_lJt0VLLZAQoMIW2GMrW6vtfpVukF-10Aw_fa09MLIaclnJqJMOOMY04jOVPpr
GNGaAhEgI5DCI39Tx_SdzNv_WkqDa2Jg6amoIvAr-6SgOlDx1P3CfDp-a2F0DQ30d_rd5z1UWCSgwTK_iJ_ivs7pzSG_6_Q-Y9tF4NuyytFnOPpw_lPjUr_4
vgSnOFxapky5icGh5lzy3tucRDSKNmGoPIl2U7_zYdVNh-rvHrzOfgzi7wod-yEwdt_XhbfluyudAZEnykFcmxNUxT96n4XVPli0RMQqVs9_id-U16Bngw3M
Fn_V_FRuIg2z-6BZu-RJlWnKARRCKRv1IwWi7lnJ-vFgszxu8yvlUV0dpEV_xFyn882N5_v3wdpiuilhNljZUkddaFJWZqtyEtt_jtsCzxdva7EYJtAUBqc4
DDvN-nG1p_2n-2AgPlgepCb-JVKJvaIVTCNmSFL9YQ8qpQSamXZlktsAeEVv8f7EqNvjFcg27sBxh4oDzylbcNx8Ex_6-tdp8SQ4KgjF8wP4WP9SCIcHjZAc
9OenCpxEvay
}

