sprite $Response_Group [96x95/16z] {
jTY9TgGi40NWKCkjOdd_v_qjGT7GRV-JaznpPX-_AqWJmzSbYHM0SlhwYv3Y2Fq1Bp0pG2Ffztc5knk0lKHYjdwNp-7t0BergFmUpyZX7nLUMwkEtok0braG
UYGZ_H8lLaxV3xvLaz_X4t8jEJBvYEl_k9Q8AQKFjx_vlI3uwUFP9W5mh0YXfzclPHJKDfCVVORvcLpS8A-7mU6FWj9QRNNyv0z-clgiUBtYrApKCOBDtT9g
v6d-6Ruc5zENqsDvuqgaywtjFxzVFtJXpMUghmK4s_m-GxLjFuSVFvVt-voU-CXPOBok7ZElaL82Bi67_txwoIP_BoXbkGXc5W-uJ_o-XE99jmf-v_FY7mMv
VHz0sdsVVazTjuVLjnT-qNNwBVwX-ySu7su_vcSjcDUbRoiDPlksSF5pQ_QqEU1xmMNlClgs-c7cew2rtE-YETBZZc8wrwVvXMz-7pUwlq_vlZ9pYHhmyvSZ
cAhvFNrpoVB6Dokjfthm3m6WPb2OpP9nzVq1fuiFzDsp6EYHJu16x8oRMNxbqyLN1ZoxuTCB17LV8de6TVVppMVWy6FtexWizCVmnMS-Qxojyy_Gq-S5-kpp
biEtLcDRkVbYX--WV_Tvp_3XqN5Vdthnqx_vilZgo_r_z5EY86vVm-MDRs3E3QjlRtmIH5JtdoLzkdyYqhkF1vztMdes982d-TSKW_s_Vj90XZyeXQRLb-5p
IfoqwalV3UjdT2bW1VT_cnCaXq-fK7Bd_-KhTFgtWgrX-f712yNyLAH_yTS6BQRTrs--KA8yb-Uppz2beCUBenVSUAjExBahY-zkzu4bw3g4ZkN3rujVcWFk
7La-NwiV4uHmrWOtS-YUG_TMBABTUFHdmHvTviciLOVEMArcC5jso4S_XHrNwRVqzn3J4PJcQZ0tqEBBwQ_x9oiHoTA0d0rMMirklkzegZ2uc_4xFngMqKdu
wNi3Oh615LxYfTLDEv_TJ1UVyTvN2Jybal4z2e3-bJQ3ul7CIbWE7ujFmF3NxmuG_1x2vIKgVECas7BmdhjFwwk07NwCRhDMFx8FGLbstxDtsW04a8EF-O7o
EzyCaRdHf-b7YE97_4U4FrzGFE-9YUjV15wzNvbRJw_XuQTxYDJSutv35m_zu7TVHFJ-UgEdx-C_8QBqsYTcj-uBt7h1v2EgaEaBTd_-hoXGZOPNliHwt_oW
N2-FFQwRsz4S0e_jhGJVVKD_WYzyTaDjtOSJR8zRH6Lc3Y5rl-n-B-XlgjLqzS54sdrsIm8xWWwl1RkVotd2ORdr-EehnHYwhoufiNPSURXhWOPVoZc0qaPC
-PjF4Z_BxhCvZJaZIi4l1Uby05vFFnzyLPLl0n1A9Wbry_VfEHBy6jNp0UJXvyctegftdpPVKghnz4LS9z-p383d-SDHK8EktOSjFgM4y4tWFFaZBmV0w7uK
n054wz-h5fZHhO0i4scrCVsJdtdr15BufHV4lNkhnKijPlSLnAL2hUHzUkRqqtjVPKnGhlKytwY-yOPIROFc0CYRaOvFEYu-ttBtzJXjgP7mewIwQMqj98m2
GelbQDuZcwyBl_f8Om2b5yJvGypHy7EsHD4WjV36IzUpJf-UVJeE4A_d6_sWhBPQitvj0ahT7mHRzo7XotBxgwzy7e2suNlUqvh3QulKh1Gy3LubulpCTtzk
GhVpZKqkO1cdtRpht3SpwF0fV97tVFWw_0Hl-_d6mLV8vGLkP_gCOXJuiI-i_Ef7WTNmQtOl-nDEmFI3sIz09FviuNTdwWkFwulAF5oT_2oGwKS3bctjoOy8
h7I-N7bT_Dwv-HzvlP-bI49jTJ-7bOE1zW4CVeOIV-PbULqSxmu7lnVe4LppFtYa5-VjwUZfhYam_Mk7FlDpUjReoSlqbs5yuf7Uy0aHxI6yAz07VVBFFZWT
axKMFEgJNp95iVuTWF2h4QY-q-Frv7tau9KzzIp-7DHYpxVeZxvOvqaNlqVNuEC1eSvBXxyYFS9wAm4WzFKfc3uwZtV-_fdfUsliT2ajsBElmTFRZu0-Eiy-
Jbz_sTUxp-k3n94V-JHNXyJjBpv-xFUSGFYCFIl_SpzTVHnP-3d_FoqGIOoPWS_mrm-JzBX_nKE-VXv1X0aFeH_QSmYiVyH72Cf_nqSUU4rVlv0aVwZti2uu
X_wB8HRLiM4m_GF-7m
}

