sprite $Response_Group_Server [96x98/16z] {
jTcBUgEw3WLWhCkIREZxl-v1jfZ6n4ddT6VMzDxoYosp1Vwo_PJ2eb3bilsJ2Cxe6VmBlQYvXGye_GCUxcu6Cw1NA9_jadeDFm9ORSr07-JPMlM8dMb7nFM3
FbghMS3tOmJqCLwyHO6eSF9VaUDm-PYFElpQ-VIhVgxxuVSAxSXyqbUlROy2mU_x7kyVx0_1QXj9Ue-FXiyKO9Xvs_VmZprgz8yxFl9_CYba-9sE6aV_s13H
yX-d3fJPpCBVXvyV32Fo7tW9dIKR59sl8zVfmm3zVUEL8mY_vaNJKtltqyTl6wz25Bw5x-q8ltfaFpnzKSKl6t_gaxyVfx-xMTslxcW4lsiyzNptfzKnsU93
I_sNFaEPPjzghQf-H7RlklpI9qqzVUb-grL4jEtDeQFnl_2pyUNHr_Gz_2H5z7U-GAcKoKVutghzyH_qsIyiEdh7jD8fzEHlVltsKt_oIM5cVgQwGtdL-3Bo
ncVHfLyKtSxKQaeJhv2olV4HlaHMVb7pERLYAW2cxIUVN_eNRpsZG4EPVKgVbdxgIxyWzOn7cklDPtf__fbddspoSvbtb0V_j9cPNlYk_xz_E3_wKZPY4VxH
bqL_iEZFKVNHLnCg9AhoV_kR0dPVtvYpZpuPtAYGAlIzBmi_ufdaZro0z3S5ZWDK26TctnrlVPmnH2mIpOdCVe7Qlk-WmZ03HuNXsysNv_wZVsCzKFZ2tqZ5
QjjtEztJD2R-Ev-6By8yVWcqXR-H26eyGZaJcmk_ykMbpsD2mPkt7TlibnAYj-Qo5O8miwPl_1S-H_8_05uNVg4pvwVuvfqlay-Jhzrts9VHjyz1ZlGb8-g-
NBxmJxvCvyz4rHzymJm_q-VBrvl_lZ_A9-EFFgkaJna8fUzsfXU2geoyNryX4Se9dJwPb96bdqK2clmYgdzyOP7qkN3JUJuxxZwbdwDbKG3gjMBu3p-NQB_H
x9CtUl8r_CwF6eY7wQf_V9pV-aC1ZVWkx3RTNpGqV1bDFZ4ZPUzLSWFSBWdmLYtz35e3BFaCs0AJUbQO_Mozrt7JEFhsz0XECkWWBhqsXnjuctroZcZzglhj
4wFxNcjDFWfOTYE3kZjIZsw5lzrzRk6B27nl3avVB59RFNFjhtL4fWgjrcijt1tbxfCSsltHLmoVk9z-Qotuesy3cYuAX8gHw2LezYMelScpZzElOt-zv_vQ
dmie8ic7BzjYVVtBxpxnwT_srwxF5KmlFNXNdIg0H8dx1LHnyyrzt-VzjQb2CwBfstWmJ3yCVl0tOAolxKUrz7ja-Bc_xfLgFrmVOsO8V_2c8gfG-lOtTyxr
XRb_-sm-zjTn1UrzdPM9PAxW5U5dL2BPfFGt73fVF-cp7xVzjPp-L0487vwHJ5Yb-nAzaYzV-CIw7m_xwsCN6VSv4kjnTw2QZ0AO7yPGmcShSOFnhwhFFblt
s-0Ff7-6rKn5G_LA9Ah2TByJvNpe6mmwAPlzAA3X7wq_bvc897_DS-i-Zs_bveDpFkGXRArMrybdjlqOCNdsLHrMfN_7Psu5ka-yQnxGy-2FOtg1fd4mttrl
RbMJZqm-vNnebLxv4LJNF7RssL2Fy9E_5z3JHoZsvRJoYQyiVINYxXClVMnWGVnI_AlAZxxgv4kSK_Vv8LE3m7JD1xIZWjDV5H1NpGL8lu1uzoh4lEuF1sZr
OJwOll35b2UVc8cBkLVYLxw4JzWNys4kuDMP9RSubn_jRwXE8Yi-CfuVzAZlVQz7G_YUVl3UMAjRHMWNppUVmK5OpeUrx_3c1eUvKWODOdqmopB9CNcszzWT
wSynOHP03-3Kc2BIZ8fs7czyxVD1SdsjjUetF-zl31EhaV0bFXMsyEqTBsC-W9VhcudgnZcBzfDiLOaAmSyOlU51EH-QlFLD1gyimBN5L9YP57x3_vaF-Ahw
qaTs2CmiYAWAiwW24DMLdlp3V3WQbZwZwn8wQzSHPlSrgztnvCCdMCw7UZHF_xb3FFY8G8CCOaHq4SWsV48BVnnWllAp_m9a3pM3p1CEAT_xYwVdXpaAueWE
HoOFSuaipqDFd-Le-ifdoqlqGkH-mkbdbuGfyCcF-T2mz3EitoeZybHWMqMLky-2_N2alz25BnD4kYf0soe27hw8MctL5xv0QPCa1TIZTr-tLmKkNoNF_rdV
xhxeZmtAC3Hz0qnlFYjuT7BsKtxRe4nHbGXC5Gp8f4jU3RXyJVx9vtUlNUZeJqr_QatwMI1ymJCFsLw7nx5G3N_ICthvyMkiVFtfDS6Cp8tFy31K92e3A_zz
2WDcS9aRVoMHy37xV_-YeS0y_Dn1JQ5KX0IHEm_-krTw39Bwga3uo4mwK7xcSntuPV4pB5Y6jxyCbzU_2WVBoFQH2FJDsNyWPUKhRPyB2UP8wfyBiQZgU51v
Y_yF
}

