sprite $Response_Group_Application [96x78/16z] {
nTW9ckCg34LX8tIliCd-r_iiX8iuHP6UyhtJy_GB9SxK_7II5icoV4_ZotCWqxRirwUwdFFulerwuwVjL_aiDpbww_-wBg8B_zTFFzVz-EFyMVEJB_gBGR6C
trAGIP4_5D5y_PIFxkDZXIyVwlAt3_L_-Icbp_b9wUclZ4YY2gXAcllyxYlDYBFjxH82cbUA4Pf-oOSL8ziCMKz8e9Mhup3cN_3L3-FrOydF_AMF2NZh9nx5
CxFZSLRueu_E-q6YQlcTZt8S_Iy_MYRRFB7GUx41t_Z2enwTZufky_JLZmNMFkpqVOFZySxF4_znOEadbbfzGF1BFv7EboV-U5GkVJ4xcbyVjJxERpLk_saq
ienYPwQL3_TzmACUxX-rnZyGoPf5Nixl4zhHxUiUCrdvD2lLU_WAFgTWInaaWVRz-EV2CzZeHrykFx5Tzkxxkdua4tNxUcU0CK4OVn3l5q2Mjtwsi_EldISf
dXyVHF2QDP-1rrzsFyPcLO3c_uuhNzsFI_De_C5CUAgNb9M8lnn-zc81OwbC2n_X-u2u0oX2z05Z1FNLp-6RhMyVXb-iFBp3boN8CQ1vHfdwAc95V_OJBIut
jeUnuMBk4nI6sUsZAGbBNlaqzmsR0Avxw2y6OmHsYblt-nTPA8V9Yy_XY-7odwEcZ9WGsMuqeb-Vr_6H9Sc1xPr_5DFxupITFKqmsqivgZ4MY42OI35P-3dE
F_6zR5uy6-n7hQNvkFXI3RxvmjUfBqWzDQEY5BFTZi9Yrm30wcvcnFOtVhJlxfCQA-2CJI-prtUR-NdbgnRR2q3QKVTYfTGQrpNrN_YbFawVyUwdbBqu4VSB
_iJ7tQVckeU_2RtWT_VJh_cwZUJkgoHX-0a46c2-Xlk4BFmyy_7Yfon-M6n2U5QyxWD4-j6N5rzKqqRmsS-YgTfkw7mnSxpp7lDR7_sNnQ24vIS-IyB9cR9h
PltqXL2Whp3tUVDnr4SXpMpuTWYgbRthkMIO5SzK5TedfAcV6cR5k7aezMX-IJsj1jjBsOrzW2LHcXdxo_0OCF4t6gsOsTWTzR2JIrxUIqhcD_RNyGt9aoJj
nVbfXQaFUuvdyCTeytFPit_V7b7WTVEabkJUrm8ozsaMRvPY2q8HxxXgKHzYSKTA-5e6tzDhmipF_VMzyMQqOfHC3zbFhsnhGOE73VvrWJJyZEuBpUnmtmUq
Dto529_eRx1QtMVoycWia2V-HhCIVh7ZqJ9--PhrxXETdoo0xbltn_lRy9qVFfhlV1ymBX_v3J_RjyyNtG8PbnwltC-puuVFcPzejRO15tyun71nrGUeoUJu
w7wQ-1l27vylIh3KSJiHkFoVZm_Ap1U-VBvWzyK7D1jV0vGfYRxmQt_3_VD53LuX7aQnJ4fEdcxWNL_SFfjOVVvyqNseytdeuMiI7Gr_Vlr4iDldY-jIZEE_
tCKvAUOuA3_u2MLylgWCdyw7VlC5hIzTnuBR3_uOK1_LdlnyuwFEOpJuYHybJNXurS897_m-0CGivctkzz8cxTANhJFmuvyDFT8qcK2aRULx2V7_KJaSYDmE
p9xujY27JUJGb_v8kvyPzMkp5rIIhF0qoy27hmj_a_0vIxTrQx-NsjASXEtN_LK2pFb_u4TveilsR_meOwclVOQ_BecYfNcAh_qFrNt3XxBcA-wH10dEijyh
_1wMSPuPb_p7-my
}

