sprite $RoundTable [96x129/16z] {
rDO7SlGe54LXzDwz1z3-5po_LBJKPLUQ0YOSv_GHRNVvEnqf6x2LHrbS2C2IR0CeLke6PKJabIGRl6m4uOnNlxD1QtZGq1_ULy0AtkGlVV1udjVBIpP-TLPi
4NecJskr0ezUOPOFSkYghLxyC_lw9tBI5qENwvYyb1vyHIjyNVcZAtFejItnTUT73zN1pyy_6BE_k_Nqq5ipKIRZnus7H-zLbDc4zEXywnUlCXr8F_HwwSs2
iY1mQkZFv1iv-Fb4TShmqIjALLHM-VIEnY_2_PRUMUMRTfvdxxt1NUkz__bCmojuwETL_sfy1kPvSzxryviV0yol8EcVoRzlthVaf0zZSuRuuoEOuuFwWAr_
-FOCq8WfN_JNRttmhRqRf3dVxUEtjw_vUzB7xzry-SStStuGNvV_5ty6CUahnm1lBozD-WSEdNU_zLDXZZ8LE69muzv_z1vXA7C9MqM3_Agho4PbCh2T9To-
SKT9sr1cEy2s5KU9b6rbb1BopHzbpG3levD8QNm8KLOayCyaoRWiwH3mct-FTxuqV2U_1x2e8tINSHpF02vRIXWBYB8buJieUpB3ppt-0NiN86nZKDaJ6BDl
0G7cAhSTyMZR0aQnUG7UlO1ZymAqUm5bKxitIF_t3ThjQ_ElM6m-W6Fu_hyVmB79JwvCRZq0ewq7ODZbUxClmDvxm7-LQYRQaUem4BMaacJ1___l6sFgj0FT
P7bt9kdzbgncSy3TG_yg45N3WgdAzJ32_xG0gS7Z0mwJzK0ky4itd2R75poN46tjzFilEcBJJR4TF_OF613fXWCkEhyx3ZLVt7OdGc3QnEPKZrEd-Ds9Bhhl
15hq4bMRmATVVc1tokqpW0xLShvg-l6jdQNRCu2P2ktqVtV6JJmEQ7z4bNRgSIJ8Dwivr1tsKquv_QD0VDxA0b11K-0lUi1dWdpOXfXPQxsoDRkWDwZ7h7hw
qJzD-10P61vfraJrqKrOljUq0_DU1ExwSwbHQKr47kM4zKSw0uQV0LVzudoM4_RVom7w0GQiUW0FFN_qmpqgflRKcp7WKlsJNlx1twy09lH_PE3K6pAiJJGo
W6VxuLnUOuOnWL0FJowcyQOxry9rFccKsdYIzo_o0SoukKRq9ptjUW0mOarW1Yrp3tfsA38Uz3BrmnErMz_slS8ExVfLs8AxZSw8PSop7mn-rETURcRXdZrW
bu1N22BG8aj4ZW549lNadRvsjxvlicskwhtq6a2_HxW0rfeWeqbq1nxqehFM-Q19G-tPznm-bRS1ZlF3FUJQdjTIGEKiVxFSvyx3SjzYtmxTrNz2OONDfOTx
wHN_1yncUxOTVKzfAcxYjVZl0GJ8W6TYcgzsWk6FlNkPXRUi3Hfxi3-F_lJ8lAjNlUDSVBfYstVPzXebiVn7VsIyyOi8tHZC08TNppJlsxxvxDlV_9kBJhl3
p1XWoDftZqeC5VLF_Xp-7X7Ci2RciUrR3RixNek3Bj3-w0VGXxyYaW4fSjGUXztVhHas9BG_buyw_U4mrTaR7VvPF8Tmon3oxFVJxsZm50nnrXQdtRdtNinq
F-hfpyhmh0AQXujCcyCdz3D19rVzGtig7L7bgiSK2AlzKCEPQGousZ-MFym1YwfI4RLJHFs0DqpubHvL5IRHHmojQ-t7BMyoNTNqOd_IPrKFQP4ZvsNFJ0mo
P_zvu_RHJVsrEvNHsd6d_2JIbze7Hu8dNkhM7kpK-x06Mfi3gDbWiDfSRf1VxJU_lTNFyZc0EjTLJu15i_QqLN_rq-cELS_oEG06u6l_Sx6Rmjh1lVR83CLm
WFgCTg0pO0imuVoc7LyRdo8A-XSv3mTTnM26sAPUsmJdvIe9sC6h_w6itQHX2_ZfjmjXBQfBCzKuhuH18tu6bBES4U1hQuxI9IhRm6x0CIScg5FlxKMCW3c4
LyBQ6YqR0ITYTm2CZkMm3tsq5MV0bfnvcX03p6ghR2TgRncjeTuROK2U0HiFBscV-vdHetRoOHuPswbFwXSGMKpeU6qfuSU4J2bdUoxozIgL3BGx6Xp28C3g
8TMZoU9_8-_RWAtNzXRd41YX8WvjQcZloiU1K_wvUAB1X9CAJbaN322HTDFEuZ-0cS08Xgm9vx5gzjfU5EruiZEXC-7AmzFLQVyE2qPGzaHDyZSdEHMCUCWe
kgldRwyMPyJ88DUYwQRyruXvp91UR-XJ7MxI_emOF2QvSFa3xlz5rC0P52_nrP-P_mC
}

