sprite $Server__generic [96x151/16z] {
jDG7SiCm34HHekh-Duwn6emR3PE8lAdJdg6VCluvCHg_6vkxoozrYm_-2Q_k5dDtkruN1uyXqlLfr79-RII2hkddAz25uJLc3_Eh8eadho_y5P7OKf_SZqWN
X9_wERaWVEMxSJ-yojnFlXy9uKMalByTYKxzi-y6jnb98ZpufVinsmmlSt_E7uYq5LwsxZ-EjKZqeE_qFsvRY2IfRz-FkNyFpqk-Jto7NuPNOMxURrxVZ_3C
yFVxkzLz97KMRjnlTN-auNED_kP7uKCtq9txeLV-exxT7saAFyFl-dO_ll2H1lgkVzSBdnxIDFfRf2by3Ps8M_URgH-LZ_0tlUT3Bto4fnXJmzVeC_VluGTX
ZVuQ-cTVeGyQrEa37Plx23y6_DYchvRwr4VuWIM_uwlwmzxz24_93yBM-wlOepxnaGPhz4yzD_MPWNVw-zkcFdFwE_t5p5PzuOUVxq9_w3FVF_WYl7E_g9rR
yIc9y6FVV97KgmT8FzB0K9N4Arz4BRVa2vslW0VdR_z_7lMwKFfwA5v1OwRyhSz4Bts-VQEe5FvjXQ-Q_aAXxE_n7Vw1dW_lDlTP5DlrDRxvAzLiT1t7GIYS
Oh0HbdZ_nrsHE3rHnLm7xTd_dV811vEuLsFAzFbysWffYV_1BZI0ytF-JnsZNHbw21bMyVzwhyks_gFTro9kvpQiJwqCi2PlO5__8Ls27x4NSds8Bpx1ctq3
I03-HqJuugyC7B-igYj3meVs_8D4c7ciy7Pbq5FjKiBVxW3uSVQHO1d36kAWbneO2JyIjCOOZTmPUDz0wX3ubpu1MHdKjDCH3ue1_dk7HiAF5Xg5MWnWvQJ-
vRVAX7l2_qJ1eSy7AS6l7D6HyO_F4kW4Vhs1nMyVD03-wWNyQWFWsnUVNAx0hpUm-4DWqCe0WLzi07motjTVtm7moTkk_keEXC1lpkNwzms0J-nzMtzzmk2J
k4Nvc_gh3O1FxCwx-kiDW4zjkjAc_iA4mHUzI6su3qhhhpS0ISCxSBhtJrv_lG7uCrkGGZBTjINrlsj0qlgfHO8LtAVxx6dzUGDxVuYwD_e6Yxhx72sflpO1
y6auFsDbs7HtKzdo-Gq_4emdFxGM7Fno0-170lk6FZwwv_CxFebxH_sXcqyDgX-X-_j4dFufIVqxFc_g9xluvmAR9FNJItvUFv4jVcDrjmvymY-_nuGEKReP
v-7Nd_fB3IJyGusmNoCsMFk3NsiWuHzcppWPTcxN0B_IGC8_flE37-f3rNJnQnD8-8TwHnZgUCVdJVsXuSRv_bAnWP_wUIKGzv7Kd_1BTpdSFydSUrf_VG9F
VXz1NotuIEklJm1yKbnm8uDczTSR09-cNFIumR75UY41-FK6SF_ipn_WzdEz1lX8KBZBYSx5ZmHwDn0YQZ9iJbC2ltP4fS_d-uLzKlO3Il1h3OYfW7zsu3qQ
G0Bmwmse2VPh1QlFXYjqdOy4Oufqy7K5TtSZNA71Xzuqq6UN4EwVia9PtPMI-YiDcF9D7tf_lxjZpyClYVyl9y1giCdccczpZb2y84UhyA4-vJ64BejFx4m8
EDTB1VoN2MGEbgK-n_DyTk_FpqjNkzx21Ruf1nv303yIA3uloVDpbq3j6ybg2m0-YKz6_S2_uhS-vJlYCFw77s9ttTMVhq2JET8XNETJneepzvxMlsd0j3s7
WFDfw_tOLfouUq_g_pE16aQiK-vWrdaXfBNv3HlkFb3_djzdRpZz_Quj_brkFl7Z-rraiFwoVfa3TwQfy7Og2_WqPiD-tM-l9pzFO8ypROQ7XDb91v_KVzPh
HWxLb0_Zxw2cKvv3M0AVrAKb5r1T_2o1_7C82PzqBN1olqhv44-DA0pXYPURJzrTK7ystpo1hMihXW1wRqSNkG1Dt8sV_hpXAvug6CAt-Cznn7xTCUgkc-V3
4ep_ZZYCP_3NnJpuh7S8cxiAyvw_Z4-7mCkQO_5fA0w5kS_nXpz8OFOS0aCHoSS1FfdU_FNZ4njv_L1OScjCGV6tyKy-eTFp8x5UqtJymSyU4g5b_0-_-Npm
-TekiwaxFeQmwClu7pwrwR9vFsuU4Z0-urCpj_PYlw1b_5SCunC-jU7U2_n6b_6Wm_YKtyHzfj_lSfasw6byxa-eHuRN_a0CurC-LbBJxtUv_Z0UajxRyzCy
vbelUSc7yQdQIl2xNZfsV4gCJqIH0Cs611VGl_YvyNa7u6_d2pwCttN0u0S-_hxZm_YjIBe0ppn67yEw_C7V69yS8qRzEgA3AVnFFeol_GvjNdmEJGA_Q4tU
Wl0b6Jt-uIJW9_IYWYPhll4lFjBw4-DB6QuhDikGbiot9SONC_Jy_P9RKrSm8F0tz89EK1_H2FWRuujgaM1eY77YfGRPP_ZoMzzOKzT7hWIy7WO5Uk4m3Uqr
u-ic5OolIwh6rqtwNzRy1m
}

