sprite $Session_Border_Controller [96x83/16z] {
jPYBSgiu44IHPhgbaIZ__-Uk1m6pgb0RapNdthoJqz3jzt8J1I7BKmW9W7mc8PCO4FdhzWGY8D9tzKhN1wH-lVWPKfwenldg34b9N4Dg-dBn3hytG_vfH-dj
IpCaN5PJormIqWFL1FpR3CgVbDxEJrib0xrT_1MeXGV37-HxnTy7wNzKWzRBpsfGxNv9makC5_xMEQ4tYxzFlbVyV92mneEp6gWgFfj1UKMnoJ-dGdRmQqd2
sm0WiMVmHAwA1w-ugiOg1ye2A0ZeV0h85yL_w8zhCGf55V0tHC353Cg_W2Ag2iTJvW3gxUAZ6gUmg2XA8IE01_xj7CL_GbJZj8wInm7NHa3L0pJyfMm1Ga3v
1-hcnxX27m6gXzs1xsgrhmJlKEY0MQ3WO0IeWYm7JAnMtwmTDn9QhuTV1Om0yG2MyAlrtZp1LjEF4uen_2Z7EG7Y0GY_7ygRLj-qjIfluNv4NGM0w7G2P3Th
aK2mV0fRPPQKjw3Y70sXXB-PMNF632lmiTyQHFAu07e2FM0iVkhTFmAE6PgYV8hhqh8anKWeW6Qy6VQoXZyIV8ORVWzOCg0Aaa0IptBMr-6tDZXd-3G1yYQd
9QKCzU81JSFVNg_DNoq2R9-XVpg38e-4Dm8L1R2rPI_dz4T3xTOCTF-Pe2eO1V4L_YcW-sStPb0T0RebP2WWgG2hwrtHQWIuV-trdA7yca0S_ZTlVnOVW9j_
RTHbzlVLQVN36VX6Hu0wadDM807eQoz8o_1Ngopc-a6ldyn0l25KJhzk7trWjZhkND2gKq1hrjQ3LYrkzdXjFz0SVXt-k7FKQYF0rbQihoVcCzW-muKzKCdk
Zu3DdvO1YblSt53Q6dJp6QoQ_PY1cD3mYxXVI2u7mjg6rmSrizM96PorAoxj0_T7W2JrUW9bFQVbL5AB15DUsfspVq15KyAe9r1QwnjaQJtOxXssX3QkRxZa
yAj_wlNeCfF0DhoqJJebj3s1UW6iy_13DQN4q0SPnHESvYK5pSwIgdjcgX-JgAZZzdoXZw7tacmwXtQKz5ATONSeEEVzhrTkb74xpM9jeli9OBBZ64rq9qai
Uq7oX06FpuBPhx2si_b1Y0X-VM9Qsg1Qi-aS-kolxQ1YyqDpaa-UtzMsKu-ImYywODY9M_unj7lDKCnt_RVVKOITcZ94CVpv5tyClL6hMIcs4VueteYyBBVy
CVGEMIQ_LZieb6MvxO-XXmGb_1QvLhdBqbr_3BsNv7Jtly8UrwFx_XXwqrT_D_dhLlpartl-6BewfxywNdoGA0ePVYptI3WImbz6yPEVuRz9Hh79xyL_oHyp
RFtqrokAl_8BvQuyxj_Qo_KXcFp5_QgCyBi9hCseonMx7ogAvQyaKKtBB_w4vG66t_NF-dEIH_q2f6VyilaLM1xqGmNowF6By3a_LNDwnAyOVadF-1S-x5Vk
Vk7oK83xLP6MPw08GLsUGfX9MPu3H5gUvBgRVm
}

