sprite $SharePoint_Server [96x95/16z] {
jD27aGL120FH1QGc_uZFUyVU_5a5y4hLnycLuxXk1L1NwGcsZVCAFOpbny45aGfBpxxtHqgGFlgG6tLZVVLnR0olxpxKll3V_JsH4glg5xzlZPH6LR_xtRT4
YcVzJxyROZbyrUmtjHY-CaSVB_bfAdFslVG_Z39dtoprAPmv-tYfVxxgW-_kLtyX_EIBNl13A6FsxUu5lt16pBww5_nyraTVz88VfY9cNmR-xukAunXz2Jxx
dFCV-TalyxnNt1K-vsUE_qlSrsOdF9QZC120SPNBv2dA__-xAmn3fz4BobxUdPa-lmBZTqI9koyXT_xI1x7pwLBCgY6tqLczygrXUFIvl38sFGiUhtoK0hhp
gy_bcIUS6076m1jV0JEwYrzyrwYX6mlWJi0AfJU-jqasenI--Eup87csLVV5erNWXL-YnaSmysRy-73_xNik5ndG8wGtFdFi18D7hT5zq7q940dBWDIj608l
_EBoAf50QzPHyuEifK44d7Gt0zwDKFes5G0wZYD8VmWeHh8Vi1Mp_9fj_HmrfseMWJXg6gi_0XfdoFxbJuslsyut46o3v5OCIlynW2KBu4p94CUJNymCW5ak
8ls73OHewHkj83-O8Jb-gnzClbV_yUa_101ZY6PFhFyyNH6qtxx7232CsllXPE5O-j3HjcB8YEMjTL2U_E9l0kWSC5AdbNuc8qBtX22gMw-Nlhl3Xc-WzOz6
MK_WpSSdlgwVgpyta0KpWXt6z8l1tJraFpu-7op-la6vxgoXSDWWaGD5XNNVcrWlVV7vUC9pQ90ACF7-36lk7aYV5G1rNhB5tupeyD6tOBI1j-fxuWW8UW0a
uxhguZzkeFcW9SqPquieMN0Fw_DJaPG-rtbu-jXlWCdRsgPaEG_Q5UcZVZebHJq-HqHWlm5cnu44qvyexVwcMUcZdk8W8WlSRe19quPk90VPasPOZ8iANSTl
Vxi1JmN88xOHa-9ltkWHoFdnptKy-Ml0y0aIVqZB0A330CUpjWTGKzFd-iIFZusVFG5JngqpGAUTtXmvKGB5FnrIFQ_pgDD_2X17soUVHJ3BrMZOp-kBpkue
1wWbOBS1nspu71S3fasihrz-LIxdkpbXbfBBdxpTR5jVlvHTF4yj_kC674Ompv9sn_drzPT7-o6hrnat_ta3Ji2OJsEmn64MUdp_G1nMp3BXcFxp1aWp_fnd
kjPwzkZxQRtyECzF3X0UD-0idKV3qH6JRtpuISjgfeiAF6s0BE1y8Id5ka_jVFXLHq2M1vusG0CAnYiyqcuVR7nvWyvBauSUVOA0TttunMphix91SPq2blMl
0QIt3s5tFxiLppu-H2FYl0vFLGy-iq56AxJtFdXw9rJR_8WU-1R0ffTnlic-wW_0AxW-Fs3roT5sj_5C31iXUp-Fz_J5NmASvEtwAmDQ17gZ_DcNcd9SnzOd
KNAHvhYz_RVnyUxnbHsYdzTnyzS0jz9z_f6iHOw2k9iVH-x-kCuZ7lnIkW_7V4O6CA8WR7oS6lCJumdexeCSBMcAU-FSOJb6FG6ChS-pFiqFWEIpvDHy-7A4
8drxzBqVhpP-6KL96gxv98oCykmtZ75zzDrd30Kk2JEBayVMfvGzFgupllbg42Yn1SpfSIkpFvGsFWuXpxUUrwUkFWFmtXJ88ByjVvmlFB3pyQaSvrkFTNxy
vu9JQ1bkFQgv65bXMn-VZp_DZ-RQkcPv1kwtiNAFilTHhtZmFNnvOqyvfAaNS_dM7zT7yU27fQAR9qrzjd_la_MwZYy-8bBMm26vn5p_Y_OK1hll7ktwwCly
jmunEKX4iRPwetCSIB1ioeB0_VeevsS90FD97fPR-UCXb-PXPHyWSlZkMjUV0G4IytpBJm6IohvCCVnQfQflVl1dEJPnqao1jxTALOEiNFglo4rfCEDVWpjo
D_7wLgyKvEUtht0h1Sezj8yy5pxd9vV_BY6arXxTV9_BxWcYR1p5_79vMSQODHlVfMbbEUn--wEyBtX4thaSEijIeAANd2rcBFzrMLxXDLzFjwWD_3StoX5n
rAQZRCk0F8c_Nnph-j_AnF_C-Wi
}

