sprite $Smart_Phone [96x220/16z] {
x9cBbeEi3eL79I61php_unu8Z1l5hjBY-UzRLqkThkyZYNF_GXP7AMvRlkuCwBo7rjiTMm4J57VILo2NPQiITrSHYm7NviBgKCGTZSTceIXLRDDuqAydFda_
9GAvRLiNO63OfWUH2CJUGbsFlfPf0p4dl8Yt60Zun3V3n1oOoVj7JWob2lHxIGNC6C0FeY4cHsYBg7GOre_vwdCqAQ8jAHk0Xs6ANnN13Akr1obtAoqpV4j8
HOWPbcDMV29-oeT1BmraXWa-scG6FXisCwnp_ES6Z66M3mEjbsEOvRU60pu5JPhWcw5EsW5lGPFUu0S1-7YtYko6jJMuSNuX-JwIheTis0o_1tVI83y-KiAL
8HO3hp0qJHhdMxJdInvqDX3WC6pZV4kK4zudidrAYthNuhVI95g6-Pua6qu2YnbK_NOKOCuZV4hHqnYaHlCOae6E0fGmo2VEAqLtTa78Or0L1teAIXZXMtp4
67Qwg6fkKa2Jjg9mA660Rv5zqE9RWJKf1AMTZXAsD_Z4DeP3UoobII68Mu6l9RYNV2R4BWJW6u4PED7NIj-SinAM0JuYcQJOVi5ho0Oh8RDXG8y6-ULUZTW-
1BM42Yy5OCp3VE9GctJ0Xr-3kaQ07etoCOOp7YLaki5tmJhEnxsghG266DLX-xL7spWVzse4_IW8LE4Gk3Vu64Fi1SNW7VPVf_mM7sC0_Y08vDf0CCudjZ64
8puBpC2Weu8t-1Z32H_Heww2Apu_OTlfRRVN0kqhkEPpVnhTLc86q2rs3KF0NTJpCwCUMDQphD6a24CP0W5lWhNd6yU2LK7ZAVmQOXCJCF2vN5xEV109Yovr
336TlG06PkhuWv572jWd0Uq5h6_o4RqIF22W8lYOppvq1YkAzlrR0H_pkTohpmIr07VaUtuhQi0Z_n4CNmkWAJvx623mnYvydk7ZNWNUEaJkDZx6087_RF-U
VKrQTMCmUX748RxH94MHBY9IVqipUCqBViRgcucjWP_p4ri_Yv5VyKK_pm1VPnB_ptpzQ_3_ut__UNoPEFGN_vmleld4qPvOucnNuFldV7ihedYihBB0IxmO
sJ_WKE2fS-BIuFvd0ZxVpX_P_tzyW_yP_70N_xlbyoNVfxCUU6hYcmTyE2t0Vxv_RyJ-GEnLUS1XByvyxldbdIdrMN3Ym5kEBpJXN-p_TuilWhV0qF5vxx-0
FvEM3y7_Z___tJ_VkF_X_kkT-x_Wnpd-D_ZDh-Q5Bm5__9_dz_iNgRzytBV_4r_n7v9fFdVpBV-ZWE7U_HiU9KIPuxVZPV0RG_Y_x5zK54sQsp-rV148qAIP
_ICx7x-N5iDt_8p_K-x_Cz_RMYtXybvbBFlBtF8P0PzMOZO1IaW6l34ToEao-3y_cE-HR_zVzu9_KfGni0VQupXUvfR_FqRj1D5n50O2w5W88OD_-lwt7Qgi
16B7SJJxqg-4u1DwCTRPxwLc1G6ePqAnsphw-SfVH36akau17D9j-UJdY_vPagsGdnDky1_dOyQ4RAU4vZ_vZ-_zcnUbZuHdmElA-7K-RdFvyCNmL-c-SXkc
WFiXhRU-q7U5FxQXzO1VXkISprT_qJ9yVZKuljHOjsTrlVTb4ItXiynHTGhuMykN_XytFig6BxpmtCSIU6LSz_-udFzAFtM_kqzVmIE02HVRSDl_olvN-5OK
2RCV0P6mNM_3klNsh_nE5EFvGSBJpnmFVGRCs_2f_yVN_Yt5-PIt_bFsg7KEsBgInsytFY3BHp_J5s52EIQy3IdRUkUxPT7oz2NwTq5bvmULUoKVLKj-bkNH
VpdxAyhDL6ptHNf23hzd9KE0SGdRgDLez_eo7_eL2SKWqyS2TFX8GCL3SfJdgEy-3jsUa1DzB23ZN95dQRnd_2sWbNiVBUs_VgLw9yPyw1EF14eHC0_fti-s
_z8C97GVfUxqHqacvI7_FQ-CdFDwutUlz2MWYcK6vDcFNr2PfXNmleyXMRlnmQIw1s0RPfzy18Yg5ZTlz9aGTUylqbfjJ33B5tvIpQvc5Jxh9n_6ik3lNjj0
FnrzBC1rKIiDEEid7y0AFXAAyMFXmbyaJmbdlvpx3z-qna_mThuK_Uptol6fo8lvf_dJJxBajc4dLWPOMaRDlkBUh160tsU_bCb7mmWG-4mgFQ0nmB3L5tvi
0sZMyAcZLlZSrZBvs6a6qBUiWnTDm-Ss-4RxtF_ietAYpvtm3VLQGKulFwKq_5u9GphtF_daoRKtlxOzWHUCSe3qTVRvDsMRVV87FowjDlkM2jyBUu8gz4F_
8l7ctcxwLocn07vR-YgBU0mfQwz4VlQjn9kx39_wiN-XrIgs0HtHfzAsnY4n81tz-DMjOeq1d-RJwBEBVGTQslrzJyiMsu0bG1Tzyvt_P7No2-heevwVtwlI
vqvOx3qwXVxMltxoEtton_qGt9jVCJSCAR7cyry--7F_bVvqlpaibhxy8Zc6X2MeI_ZyIpdDnyw-lFfNMXWKZmPzt10M2QO-V9Ryq7z-tMz2YmDodepm5wdn
5UsMK_Z67cR_7-P_y2kj-VwHU0XQ-3JoDjw6MNRVYvvzrkm_hRVxXzLAsVt_9lyF2PhZV1PvzuiT_5h3ydhoMPFVIZmSgjcdy_-l-wpPRqEQVIzdtoLv960R
fFpePplVRrd4ztzNN_CtF4pZxS1jq3ByVzT-eeLDBTFzHekvEdp-L_XCKB7T1t_joqAhqPhljsN_briLeS_LATw6_0vTDV9tyvbF9Qtv_ebQBVp_bhID9ubR
bfl-p_TFNSy-AtmiCrSkuS5j6FDVB_pnlZhVFsktMB4xAGQ6LoqIEjIwVkMVtrUCqVd-wHQgoTDVyNS50KXeQF_AFx-lw3UP_4NAQqABXeypzOZwt7yDlyxl
AtvKnZIc-uS1JDjzh5XuafxyXLy_lAyGGCjEzy_M2dnk6Nqa_EDyBloBznMjbJwiFE_-xEFJz6O-dzvNhPtldvgS_SP4wJUHLB64Bxw7DVi55ilc-oVnLSxG
y96Ksz-bV_M-eiNIuTE2pnNGZpFxRJwoMoqiyHdTBGcV_n81M67uM7Bxwi_lAnd-E9MkutxZ_SDo-DpfUt-yh_pqlaBLz_kjRYpsV-VVlwzGet-k4jSF1xMW
vCO_lw_IuNs5fjTbt3_yR_YkdG__ll-yM-VtLVTfpVUFr3y4RFcZduUlx--hxUFx2Zui2P_d_y5_-tyhvw4iEml3u2qf92vv_wVzYo0CE2RUcxcUUjedm1oD
jfacXp_zxv_4sNwwVFKbzl9L5g1vwlq1HLV-1y_3OmE0UFbgSVoDgUSdHbtuBpI0JW5QtNpL-rjo_EsBJAJ7XO-d-RE3qX_cAwR6t_0mok6_wmQ8Y2n_1Wjh
lUOhF8ng_MVbA_yrvGumPOLnllhs-KfKS8K-XU_V__m9yeJ7qQN0ClaAjTLyXVilKenax0_WVyuJEWkit_8LAk3d4o8ZmDil-Og0l_7dyqFgYN12dKB7tmhB
vAk568suEN_C2B02WFNv2cOfqkKhP29Hx6hCHmis8m09awyIYxZvAjlFa8_n4hiLoATjybMnijxVc0L6ul9HqqK0zWPMbwzaaAz6_dCZ4EGhiVcAMGw7RmMA
GW6DyvNq-MhQNN-x4wWbu3VvQi-tSWhprSi8R5MWNRvu-KgZV0M-5KW4XNxv8aw-Kf4uNxr60eQVizgVvojd4CeAWRO4vUGh2ltD7ITY1EGie9hr4tBCRRvw
kGAxFVvQJRuItZx_sm_i8KLysuG1Nay3dS37IofoZFFLQDRDIWvVHRNcA_3BhTHXlXgFkzaxlb6W6VmuNzrCl4bNlg842k27-Ufs7X3r0YfwAk2xNRwQDfOR
__7lKGA6-_MZq6bwn_bgN1FQZ3jvqaNROc23V1LDDIgFHCtwwocbA5_5euVg5lHICAKeNuLRI0m58u0dCoJqdwYQBR3TmN4SAb6-YgS_jNtkDm053V9LM5_q
MLGR1R3roAMmZ80VzrcpGXK07XNagryFgLN0ugi26htF0JyyfCHMuUWKEE37XxH9LJXCwKs--lsGohF0mc8sWEFo-SyLhXNput_eXQf2m9-VJehRDVTKH8Vy
U3vDh81DgCjVWkM7fxG9WDcOB7ynioOUAIJAJ87BbPxW-VzmF52iCETZaYoXS5XqNFBYFtzhvE3EVOUJk_Zdcy11YHOwUME7dXT6RXMHj67fuT4ybuWcnJtN
-4nvvC3Kh_rV
}

