sprite $Speech_Server [96x98/16z] {
jThhTfyW40HmsDsP1VJ__g_Re79GesZRP3xrvF9R60ozsF0cPk4Ne_oA_feE0W0Xlw5746j8-tdU23Ei-VcIjEfx_qTB4X1syd-kfDZqxc_H7ol-mdVtSqcY
1f04JELzyQfdlmtmNb9KSByI4XfV56-g0z-taXI4gSGUKGEXu-AhFl9hkEYcyNlK21aLh_BWayww38dN4IDkYrUH1n_B26YyZu9oMNpLnpwyPhVuOxijHhqe
NkJ11ts9TVoScm56Y3puW3_nVO9H3iLB7Fe4uQ_uFY2sub5FQ-p3s7WC-LuHq8gt61zzznQDutgQhvIbU5i_8WFVs7d4eRz_YB0Ktpvownl8_V9xXdnKHbge
6QtVZDpvZ8TSu3rGYjGF3zVF9RsUzp5ZzGRzAt3oxMzyK6Fbv7hzQa3p-Iy-gHg2c9byzrMnvhzykeQe1aWy-ceu-FotVjGzsV9BwiuNCqFB__Y1xfzI9z3T
Db_KQgus07dD2vGQX2ZJl4nmTqXDnOyRy9ItkBxrbP4QWWAvJe08F2M8sldkoJdrv9piPJsX-a7Cl9JvCzK9AUl9zuRl9cHvveMw-a5KpSiq9GaYgzy7fCxl
9-2HDuJDNvxzxJAflkxyflkMDg2a1zyOkx_X8Sh9x_nvm9o7l2uq3PNj5_J9RvplildJx4FUAao5DhxxVK1ft9cl_cpttLT-ySKjX5l_2yd9dPxEV9xdkTpp
6felcUVrzm5fNbEwlF5J_R1Twq0CtPTKPE_BphSyJpcNYcNt7L_ccdIfKqCBOIBAZvzzxIUC9NdwchJXZPyd4zdROiQgTrzTHDNon-NQDzGiaofQSiqqRt72
JANYQWRI9En3tSuJwLEuztNlsnha-PHaQc3rbJ2jjPzzBRPYJAKarrj_-PYdklpkQmXIVUsrd7oncRf1_4hpzSBNxIFbvD_nWH0HBTF1bvFVUMqBcKlAE_-Q
x-VhdunllWvy_qeTu58HeuKxNxrobZwJ_wMVldpM4nNJSEi7souqrXybz-hBivzIzITswiuFBAQj_uElGpzz-Hal_60V7izNvCbFKwe7xFha0xN0QUALhzzy
QtvAFi-5uSbV_v8HCS_U_ViDTBylV-nBqkN-j_mfVlQr-xl0uTxRV_2b8CGbofHSLb_kVLG_ruT7NlbIShzWvUZhwkFem-UvjpFqeIBg7p_vWmq0llW9Ztg_
_yk7tHzk08jV7lb-_qjLK3xPfFld3U30Uya8BtqhgmBFKtQUVTrye5yzoHFbhIysutZ_NsoWnnqfkJEyyqtgW3pmwm0U-B_olJhfamQ-EgtnG5fzYwzy1QjJ
VthP_SC0ibTKzSK72NtZY_lQWPUv9F_cmnVS-fyDLnyW8IzyyTmEaL_2wlS1xI_PZU_-Ck65BpwZd-_PLzJemNSth25bx0CYYhdWqXTja64tm84MKeU-KaLL
_LDuwME9kbJVEzyp6j3_V6W-pTcxV-0XAQelIUwEOoXFz_zslfvBJWU_4UenmhVOsUVOrodfzVbg8umn2hm6YdDeGryqpRpq6w10_8eQJ0NVGndxYddYo2TY
2wvytFfOV3LEdyIJZ-vRunNucmr4OFNDuDDKab_wtdm1NcsW1r3LVhuFFcx2S1lGDj_fuD3NMryVtzEP4yZQVVtMl-3Mn_FBD10eSkbZzN4VFhuCh3dqWvxL
bv4lOPXeNDDy8tUyzUMF3s2y2NTVVIMny_NPHuU64rBrGOk1FFhwptwFqfDjRyEr-uA-_E41FyT8QXksNx-C-RT-4DtjXltvKVnBF-D4R1FqiHxzzzVaYo-_
iFnUaZxL8-7VOoJYhxJJZy56-d_m_HXuoqF2_qUl1_075j-FWR-XzoXuZ4duuOWQWDV_c-8F
}

