sprite $Standard_Edition [96x97/16z] {
jD67ZSKm30FGi5dxRtpGzPx4zYUAK1y8whWUXSVZeeWE7gGp9ad5Zz0HypMEjkiEFyNXzk6_H34s3Yz-ZnpjqatyzAKj8y4cyAil9LWUdi2V_kf8Ye1__BMH
sFg9FpyIOk2Axw49tI4k-QdIv5lF_TRl-ug0Axv7tVVP-YM_zRi-OlGvzrDrttVO1sT-w_TzjTxyMN-FkkypwdFUNwtVz5-7VmsEV_nKtVRXj7wXl-j7T7Nu
y_uQTT-7tEUylr8rurl4XVwjp_eI_-7RzwXfdvHiuk_-QdtUFq3R4NxVdncrvDk0dCJusPyUdIM_oe2ICS9l_VNKcNrWnwh301Z6wd9ysFzo7pB6Cqey3-xy
jvTyCg2JAYELh_sYQaq0A1Y6V6jcAb_VVrPjUvyGXk3hrkI-zOk8xNjpxgy1p9I29vQ_VULl8EAjgYe3iDeH8JClUFdABy1ihaHQ3O7jY7kow1i_1h36SzvR
NCFqRwxXgN-4X4XyRYX8-BUNyDoF011YEPD_E-7UZmKQ0K3_QVht4-vzjFoQEFbtZq4U-9G7JF_s4XxwABu-__s4PpvgW-NvxoSyyr5tlZr_z8rFVV7tXldy
3mSGVgwC_Jby8jyTtyzF_pF1p9_4fyzE4TUzoPjF7tppwYRtQHq-QYNgdBUz6UFmbnF4NR0y2QUFrdXWOhMrQch1BoPO5PZ2Ovzqr-6VMVYB2Uxpx8zz8YII
lSdApnCiyGzziFbqrpxTy7S-U4Sa7kxAdoCgbM_yZUifIEoFsy9dYkDRwO6EdlgRD2QEfEzFi-xdNiS7hsUF_SAx3Z_TdvGuVELZsKh1lScDRrOkl_VK9zlA
aSM4Dn-HSYxJ7pqyFrk9qDF-uEy1JfUl-ay-lHOZzaU77wtyI3_uwLE0qoURjnBOQgqgXgEdFimmoZxPFY--nuQpbI_JJ_RIx-dUjm-oF_heJvn4HMZosOzT
P6wxmUhyqSVx0sSaV2IK-EcpXy_Qziem_Tpo_DCNvY249azlFfaJHrBttGMddrgUVnwVjWsOHIWQkprzydRw8kgjDHVfVkw3JoBCuSS0lXnAFbb__ICpCmJu
xCFqG-_X-u2WNZuVttLlyii_-k33uTV--eTKH1ZXQ0kCcUEIpWcNVpxUjjViznO-75cDEi_brwVm8enzkNpnFb3JsoyOPJ_qv2jkxytF5yUL-6j_E1Aj-p52
XvydY5VgVFOxXyGzaYCcB7s0g9IqFnAmjoCBFqqG8wVWiz_NHlHA-W-Hywz5SVZikuO_6tww1YU8abyEHnV501ALiJ_CjZV9VcxfzwNHPN0EXl3xuvNOd-Jd
K6hoV-hFJ-mOMKyq9-TaFFU78ylxaoFNz_FxpqyCUBM9vieMVyNmsXyHQsb_ae-G_TJ2XzFdr_x8Sdzc_-YNVdyOm-U-F-ldEyCRtoArTFyDj-xVxm-mrtj_
5fkF_IgwF_P7F_kiwVnTyrfDHBpMwgJ9Z-DB_39zbhG_w_kV8tSz70WwH_5Amynml2QAvDgVnpwOksn1aOGg8oenDVwYRD7q0wvt-vCl80P4nIomMPpUUJkZ
u4Ugw_CZrpy-nW33RfY_-UVpgJod2G_TtAilVEQ_FYAInGGXKdVj4X69-f5A-ACoVILgzjidmUsFZr70LngGUi-4kp_3Qt6cd_HjxVS9zcU02lFqymIrslJT
nzY7XO-plk4YzXeWFFmSi8oc__eABsL_uaWZZW7bKDnrvKS5MVJeyfbXY-RvbwVF0sZfpq3KZguRFwCgoSmnXHWFDkx__Fp9CfJkaz3s5dkzpyzgB_nbXSH8
kFoQ-YJhkpcYxLCbRlmt0J6cS_q7
}

