sprite $Start_IM [96x96/16z] {
hTaBakeW48LX-ZmwplutVBq9LMt4Hw3y5_0r8JemPRjSWBATQLj4j1yMTAPrZ_TqpvdYZsRGQH40uWZ_evp63_IqYeuAeDByXHvl0cHZNGyF-ZWX7SkBBtqq
Qa9YYLSAepsEW98Bl4sK_ca2k310dMzVMXp0P1H_OG2cU6Ij_j80PSpu5cB63yWJF8sOymCpho0PlQjyG9vRVk-g7p3cThztGPzyW4Z4On_vYddHXn7dFk0L
4jTy2R4Gp6k-5ttnubcxwklQMGlyr1_FsbMVryxQLT-yUjQk-OaBP-so3-PxNab4VPU01L_-VjP6twmLttZF0wMlFG2Kr_aM-DsdXpdmumEixpwInQyE03E-
_JLhwmF0vEUpSFJZ-W30QczATMPz06XTESgZBMqHcBfubem3y5M7aij7UG3uejjnuQPJJKm0wEJyKRwx5LwE0A3ILu_omceAqBD_ULKu1dJ-ueKXYPW8fyCJ
qkzz82PyQyullkzFWDGz8dxX0r71Tlf_afrf3Zvd_QX0szksvP4jf-BimtF-ewu3joif7Uil-AJdNRSb4W0fkK_W-WietjkM5d5A_LL4-KXWdjV_jPTUoRgN
M7o0ujEb3nEOM7c0uclnOtmQOE4dVBKFY3fYX6LUVZV0mmNeMdZaURlTNW-WL5_YYG7mbhKvkjqZXcZIc1jGkqES_9im994-_tTnpS-3BtzxFQ0UO0yfuDBo
KpZvjstRRZdu5E5MXKtWwlBBxmF6jsp26Fu3msSUMmfdVpiQtZ85gZqM_Zm1W6hv9p-tRNW91hATWzDyUzk1xCqu-riVaBaFu16wFzu7cIdXgEWTJ-UMUlRt
SXzm8yk71BADWKvB8d3eb9nf1hnvy7lZ01hWXzz2ajXvfKMqU_HcOlHl1vzv-wi1k-_sFX--wZIIS_HlzxgVpZ_LWD4VJsOeEzzzFFcFV7eVK7xavwjNyM_y
FFZk-t_r3XpV_9sl_EIJ-RHyEylF27_sbMWFIIUVP0vylM7wioyVV4MdMVgJls_EZPVzHiRuzTOZpom-dtawe3OJRAluyZl_bsGb1TccIjjdl_FrsQ-CSCpv
LlTP_ZkU6P5jBjO6FVckhQ_jWIRzg0q2kfzx0y-CCDfaKZt0uUVUN_8frQTpeaWvYQFo_yHn-KriqrcrGy3XRoDFguNRV95IVSTslxQ-abipsaAqb4JFjzTy
HeFRKbOD86z_EUfCjCXOyoDP0q2EAL6xipf0wBtXsPP3KhBV3B2Z-EKd8EiHpejNQr7yMc4T5lk4qgCrrDulnzmzM-BXIxOYMjZBwd2V1oWVYV4_6UqteVuI
HG_-bLu_nTKrrUOlzRgfxX7Hnlu1
}

