sprite $Storage_Group [96x178/16z] {
jDZhakGW20NWo3c0fdp_vzrgaanQOsBsvf-z-WaC1Jspl3n9kVp7GpCp-LywR3jC_qCNDJDLDJF3FzSJGuzZPYh_biUfxodm7-ho0PKy_NzPfAIRtlkcwL_m
tFNU_pT5mgaFV3FyVK-ITxx_NP5IwC2zxpufqhJmmBCVB_nnuO6vxsP_LdWb_fCVmu0YSr__nCUcptqrFtqQNWy3XSnzrQ_wmCwfD-tuq6T-wBiVjwARtnL-
xglvSJRvU1VJmgUvh-hdiT3dgo4ABodDVRetlYgdgo55uLFmppxDMv-ShuOe_4UVnK-rrbVs_g18eIzBciLFnlKk-FbgsFXb4Z-vt-_q-Mem4v5f_BHsyX1t
ldjR9BC0d-Fl9fi2ztwt6io03oUtyQDDF_H7FrxWwQSa-3Z3-C7sVkXJtxzznPA4L4NlXzxSfynzizQd-oTsgYfR7pnz3LtcllRn9tVBI0b1dBuqzzLKPEwh
UUylY8ma2U9z129WwqDU-Ef-zHUg-ZP0wPwp0I8D4FhC3tteBsIC8HCHUivPmGO8VUQh-PsVI6wzHH7cRCreeCn6TnptMtz90iJuLKc2R5_0Hv_xD7_oG_X0
iM_yovVfQ0tT_CaFOzC_bDiX8BrO3LHxy2dTV3vzn6QOn4-QFVdGTED3tgm6jUtS-c937uG8qZH-c_gIqwqFo5FytwFxtfUCWGya2KbkueVgIn-UXtvAcoIZ
-BLVlJS-HG1MawllJ0aXeVVrlO-ufDNH-OkvgoH-Z6P-xhNl7nZxeliTNQkXySKj5nMXchdnyBcTjxuOVsAoxCOVV_cu0VEOVeS-ykt6Zu3F3o9--cdRYwG8
_PpSqmHEFx86AuV-8gJ58KGzvw9Fljts3zPrvCS36bUA0PgBOk3haozR_t2jogkV4X3LLra4slXyvIzW-AJNOXg-XDzlXXJ-F87hViVvzNMpmm-pcJwTptV-
WhNhdssoiP_SuKyJQFtudLGT-A9fudFkmw8ALhNnvUEBfwi_Jw3rmQqALfszZoBFFkU-W7iLa6is_VO5AxzzXZzDeFK57lpcW0XVDXzvbIUVBtn1bUyw7puW
7wiMTFK17dnh_MtDhjxvSRXPLglYZ7-MGEj3FpwqsjKNtotDTJK2htnhVJ696reBKkTB8R0ZKTZmfrzXQtonuuAjHT7uoBxxSNlaS-fZ1JObZXq-H02j-lD1
nxqGBnBeVC6g_Vo9i_LFgNh6F_3vw3EYz7NWBuTKgZV-D85h_x2kLtzHxf2jjVXP_ra2e_vXhjxxYojm2EQU2sMUGEkVNKxrajtior-QpMy-zldiI_JFgMJV
VCJtCzLRVvh0rKVnBz_3tn-8mPq325-7FkzzjbtU-jWcjzRgkqzvJY3qmUSVv6eNNvHfEz2obkpXJn9GpyFvGwl5Eb-qtP0CNvvypG_zOpbdjoyVh7Blu-fd
jSvlfcGJFqAgHLh_FW6wwSY7hYDV693MmXzVvJO1ciShjdhlWpKFV6ZtdOSMtldK7BfclyOVKMRjVO4VXkKrkuO_V42BXMwkslW6aJtAydcYyONhHXnFt_dP
oGYUslb8kn-AzVs3Qjty6JpWMQFxLZygTFeYNpvLB_sJguQlTxuMtUgVDKvnQtt8xhjRral_SAtUnD-sQ376tH9uvF3j8_JDpqQk3B_zV9BhwaEVsKEtU4Nt
78O_7ux_HbPy-SX7vTJpFd-Q1p81ybVjTgBh9Wn4OHXcpZasbj__UQiB8sGSnzdeTD7QZwIP0FUNuAw3yHwkFX5z-FWKUTaVhnZiJ_S9v8o_KL7mgVMzwSEW
TFMzv3RHXzyUG5jy0M95sVTX9Ms8FhmpuVlnqQZ6FnpwiJn8yJBu-FENIId9emyhvTrtd6KYrwtrsmDiHqfJ78LwqOTt_Sy7u6OvzaUbPd7WNzu3-A8FU_HX
EGxVo-N-DlpnYeBF-wS3IdqVFkuSrUvF-Eq1KewNe5TzcD67BSiTuNkkCvyRuYJnSHyEtr6tPxuvVHygJVrX7mxVmLgV-VjWseSz-44V3dzF7oMrVdi0plig
rwVzTZtz-DeFVBpkm-lpFcnjBTIZ_tCV3f-PsjZx_cuVngGF7vC195vzlDs7LQPz622eWekFJ_gmrpJgmxJemm____vs7_RempK_z66c95kTf8ZMzs_wC79D
cFHXfPGE_yC-J9nRhfJ4ftquvJ_VF-x3Ik_suGo_kmzJVyCV-t2kh_kmVTU7uovjc_HXIhHbTSpxyBYl6i-hR7dHX_5L7tRzvpvimpxi_d3cnXTzU7-LLGF_
pZxCgZVwCBxemnPzc8C-R5qVnbTzc4j4WDJqOOi-pBlxi5lhUwh-l_gmUPGpR_pl-l2sJVemR-Z3gB997qwr9kB7Fboyzosp-UQzsOTxtrBJXzNtuHm--NOV
LkVRMtrOuT_PXzjonbaVxW_1lW_NMH_EDNT-dtxWvyGLpxk-Log_xCFc3nC9vNKVbje-a_f-EzRZ25px_S6i3xFlmpFUt2K-wSD9R_TX6qsideJmFUVH_iIP
cy_xi4r7MYNWw7iS-8vv7_QvJq7d_gIg1z_0zHXZ_kl3klhsOgHsVrYBEj-GPttujT_j3rFiJzE7FGumyjVfXD-T9PKkvnylPT27F_ETfVVRlbSBJjzRt-S-
Jj-zve5lEikhV7V3ZmF0PhoTVbJirk_xCDEMwEXyj-Nfc4Dg-d2S9Y---RKFg_5ZrgUyGreWULi1KhS_NjNvVJsqaRww7_u22U7lqCF-fCfdFZpMgCFD_VGN
I0m--d2_FxaAlMz-7LjjfyDk_CKauV0554-FzoUgHNFVSVxL-Ss3Han0RNqx-p2ed5hVV3hXTy-GKObiVIjj7_xQZoE8KhUVdhEFVNlNZp4SU4fPqHZY_ZRT
uiURI7dlmqxHU1Yg6GFVFl5ZNFiH399ebg8mnLVx9py6af9q-9QxllUx7v-qs-xRnj7-n7pgnxYmB8Vlhdgl7tFwxgNy9_yySvTwlx-gFNEhb4JUvyScUTk7
gNlzXHB2_vlR_VRIa8cCtiUF_cBd4w8PW73ndR_vxQM1b0hO-4xfTx-zD5ps4z8zVXn12l_KUOCVipfrdBbttod95jxYjsyYvms7xijodzzU6eZpGNA8Sv_X
lpkuFgDchpu0oRvuSDURxpVdBv_BfsDOBwT0pdZPxy-N4yzvl-K1TcAio-zxXlsAW_SynDxU-14nPEpORRD2tI3qssOr1tcyZyjF6_y
}

