sprite $Storage [96x144/16z] {
xTk7akiw30DGcmBu_v_ydctC5asYgqJ6hSJsTa1vThgupIG20CayGf808hR5I3vLkSh7jvPQH5_ZjYxNWLJo3axHRHYLC5x3SU9eKy5PCNyAC5FsTC3PGo2J
d6NxKs16Htip-553VEWB3V6Kf_J51ZuVljsG9qV0ENmyUkc_FVwL01EFdaqifdsyPtB4hwSlO2B2LI3ULu1at1ucnCV96mhYyiKR2lHquF6HqFYcC7tZwm0Q
ttU0yFg135-GeDEF9Edrq-ep_sX_F_pTbzCF7nzc7uSFizzyVZlzSF5n-SqsllnmZI-_cSR_y9k9__2RXPTlAMYTtmoyVCN0orVkvdk_nRvlDxn4w_sFxDl_
sPVUDFm3NmqhaJxmrR2iz_vwW_InhyJ-CXwjpVggMC0xVwb2-Bm_No9wnLSYzYCdUYGaB_WBAN-Gyiill_pooo-__FBBBx_yyiill_pooo-__FBBpqHQVI3X
uv68fFFnn-RrjytuWAuBQadd-CO3CA7xWPO2P7xSRtJzyrn1qlHq5DvVq5zWfOzNWO_lxsvRxd3ZjW9aOdovtNJ5dPbSvGzZU3-Vdk4Lh3JCRZ0ayTxeYTdL
51AluThlyE-dp5TS7HZIfotypVqWBGZXktl8-Z5YURz9FKhcqdxJU3-BEi-a_1y
}

