sprite $Switch [96x75/16z] {
jPU7akew44IHUfA2o___jyyZO_ck40zCmTc5ocTmzpZTtW0iZDkl22mEXz_eoTqRlva0SRtSeTz4yyyCV3UQ2VXYD2DVB3hASoXyB_Wv-7eq8_YbtU7ujMY-
M7GWkG1zFPeHNBIh_6n2PD4D4Rt2kpK4xcBHIxnrlb6tVpG1huDtVZCXJY8tqMiyFTy2Qqf_tJlN9uJfZy-EQSUE0NgLsVd6AUVjFoSRx9RsmxBX_-dVl0Qn
TLrItYUSzcIfeVQ0MaF7VySdZFwqh6kzJt1ElMDgbnYB5kDWwxgMVS9WT-mYHz7TVxkXR27jDQH1x-Zb2VJ7lq7LQsWJPboVW7_zZfurJB2h74MBqSq9Hkci
uO7yOGtT3-267b8UxCu7nq1tlqDX6oUpaBpuSqB_UlRnBoULR1AwFo3uTrh72VcWb6AMtcEpEqQ7l-ExkkPc7UnEjhVjJfQUFt4xYWrUUWrErxyxmQoKqOyG
8TZyFe6jrp3QdJVievzL068D3INalgkZlTHQth2FVXKcLWsEt12u7fUCKU-KP_QSftx81hCQt0yWXAXd3OFTIHDE--WFB1imIs4dRk3SrT7kJEnF_RT0lA6f
k9iHzm5KUmrk7ndj9PUftmaC9iwBnnCWS7q4T3bhg0-Kqzue3mWRnRRsb13gkeOe340umX6rjTKm7r3_siS1jGXC2S4B8FQj3r0L8XRT_G6KUmtJ2MvtoiEc
UJutjYI80UIBdn7wAZ4S2e3KViduervgpNLvTfhi-VjkcZ6Y488JMJP8BU74bbb8RdVIOxVLzRlV9oGbDBtNoWtBEF6GXWcBstVgl5j7-ZEY8cxwDi0d89Nc
9O5p3wdQ4PBRJt_nlsT-9uebHjnXXQy-0MY7qmQ1T3bgA9lTzTq_oaV_7fAHsm7Zv843f48Wzl28o2IT8UtwCvyNVeSaATml4Roi2M1LPM8rSZI0Iml99zJb
ttoUa7XyL6T4Q20qwDXLTJyZ4BUGV2NBqgdFz2PXV94nem36dRwhr00nyt7LU-bFipS2U4W11yHEAjJWXeTaB_r9PsyqVLSFlyBzosvNtj5gh_8nmVDNLKiS
uzrV4VAwUZWXuXX0Elf7EpspzrqDxhUMnheGYOeNhXF_w-3dDKH0so6ivduLZyWc_fV1psjeFxWtUz_LzF_-h8BNzlEI0NQx-uzRjF76u7yh-7aD03NxFWEM
yjpVWxy2QV86kA543CrruhyG_Bo6vamfXcLTvlxi6t-Pu_Rc0nA9NtpgrF-X_RozCLiWJikg4_yO_FMGF7mXtXdzG_3NYMp9xJD__JoQiGQQ-DCNxBs61t_H
QV2Vr_37N-rgyAyl6TBzTOZcIo7PtP-5RZ-0MaWfJuB_NWt9e_aPaFVj_m4
}

