sprite $Tablet [96x142/16z] {
jTc9rk8y3mFW9hRb1BZ_wntIkEZq3PIMaz6_VjjZJSJiIqGC9ij_IX803Y3_3tt5QmjWQJglW8gj_gq0ccQtbzJ22pAv_hf0IXbrZS-T0Rgak22bSeQfVXn8
Eda6-Yt339Dzpb0ummn_Tw3FK3Z3H9ypb59YXXd-fd06NfZXym1dQ0VgpG6Px7E6KdoOuKS_Y646zrlb37DyFfAr0yuPVlR70sdzqzchknVECAb_QjbcSFTQ
dJFyjA_jtpWnMejpXb_xIvAyUnqcMtNEyAkVqvBpt_evhP4s0vmp_E8tInBzDNcxK8exweqpNFORjSG5-i_q_sap09pXgX_IaeL-atd1gWFW33_vgS-myzUt
Q__hrS4PhlivK4b_3eZ48vK2s3f3_jMF2_Ipj0FIJsbrm3Z3DJ-J5HwGdlP8mmnNVQPvBL6V5yGBOE0C5tmUu2DbON9_fE8mAvpX9p_78z7d1QjkPfKpdFNp
_gkMj0koJsuHgp3hGr_psRv3alBUrxZW1MRhq7B1p-GZsevGVoOkgBkPUHiwd_LvO8jaCM5uGR8CCvprSnktyor09XwHzIzo1atVV1x8xK9VCbItuOBqhnXU
x9bx0V8fNsHx7U73cvbhw4m_e6MRGSxvilaye6O6ttn6riGZ5GnFbEYJbnnHZce0u8W3mmNKTc1y8OMbqPVHLwmf47rxmTpiCJuGD45NdpnzsNq1ueAAClRC
Ua5By_MDdpGFlcm-3oWYLfHylo3FLDNxMrzKwClUV_C5a2N1PUDjZHxr5zFHbyrNVgtj_l9CxZEOqfTwnYVMFvhqDVmGf9Y6_gCVVsH_3l2JLrNrTp--ReeQ
lzgoVaj2kVW-v5iaV7lzAOFlVv1ThldonfV-wUY1BVku_kA7nY-0IlZfl9zLDGy-UVhWrzZbf9yKQpBzF_Lvm60QIKS-yF8LSAWQRFI3fwy0wv_nSzEjnK6V
zPdD1-j_zPC2RWe03XrzwjPzUVdBaFBoDVoywgfUQt4a-ZBwSS3YG3xXA-2gxggb5iX2V-J3LmLWh7_ah-MjL5U5GvSllhryiFwXx-lBcAet_kNdz9QFhxe6
m7Jvxh_AM-ay--jRtru-vCZNrQ-ggCKQ7ty_--jR7he6S4-7lcfrg7c5gde1qdBAjystvPjlYkBAj-c-qN_30zrtpmS-L0sgAAPycnv5y_Dx7vjlZkMmFqmZ
llyLX8GsOlXZ_Us0ou4FG2Cs_AmIbZI_zq4Vou7lB5-0lFprKqxD7-lpW7psmVBLeMaP_1pzX_hqbuy-Na-F-k3RZFwd-Z3L_D7dPzYBN_Bn2kk_ym4tLVER
7_bPFzM7ctpYpG2uEnnwx2VzMD-Htki9mNinrPFzn_fk7tYpqDtqgW_Gpnzu10zSyCVwUCldu0km-UNC-u_rvICVUlZboC_NwgV-z5BrWd-XFk2b_PNplbsg
x_6XlUgFzNKvIhNDjpF-MD_JN7-iFy-_Nf--sQtMR_vOtvPplkaPVwoVp_fsx0jz31_EMVvON-RuGd-eFwM_DF-W_WGVOtrV9ldI_B4-vlkWtw9JV97N-v2F
w2HVicFaM-Ixxr_z5dMpltvvnkMKVp_m8-O6aEU5VEZxDv-13_LBgQKYVVTljtU-hJxZFjGlzHcaJxvt__RUL-nzqG8CUgst6z87_x1_XcHXL5Ii8lXueCRN
6o_iV3_s5s3uxHNniglV-HQxxYT0KgRVKmhxhmUsw1_VHtyyO993Psfnre_m0dqj7tn60Cr_BmZgRjwU--r-hthHNvB61Tt5An_dTQ2b2dtpqH-Jh5q8dwdr
zK3i_xW_7bKstt7aCnam6IuOTTP_j9JCVSrmv7C64_dZA-xDP_tcztWwyVaPPn0bRi-etyatdS6D_H-3_sq6KxKMrNhdyxJdPwwy3sVO3cnHtEzDZtLtldKV
f_fp1lPVe_wuSzsTNoxud45wVqRBW_hR_dVwPsQGy9dwU3qFVI3y-ncVCumNO23CVVsopnbqfmFcxtrSzJa33wonEiNd3AhqU-vJVCwWcxxz3wRud46rouw8
ENqhl_gSeLq03t26dV-W_yCCV7y7t85x-1x-uqUVCo1Yy6S0VltwtUSCKEry0U0jvXNkFiEF6GnOSNWFVFFzTvypn0LtPav_pc3syajrdzQVCvZ5WQhqVOOV
C-1reDB719ypn8M9_SSPfllZ3FFzSORv_ZY3-UhV8TDyFX9zHrfcHlk5y6zW_RapmDmBO6m_UGPpwhCZMAEpNKRCv5FvVm
}

