sprite $TCM_PBX [96x90/16z] {
jPY9bkEi3WR_1EdJXj__TQ-DC0aPDyVJDrEzRuMxH3Wd_kyM3s9-_lUlU1Hm-NSh5ERot27Gu_lsvs5F2gCylfo6mSyN9IDzDVoGZnM-dcPUu4jZU33JhFxc
61uqfVbkf0p_uhc_zDT2vO2O7_zN-A5E-NXJqVnPZk6tuSirKEmevGfSVXl-6bP18gNnYp6K7-rqsda7oE_XxyRm_3cD2jBF2NeabCVzyE3oO_c3RXUHRBGO
ms9FNa40MC4DPGPGafidT-6qhr1EK0PZ3ByEJqi_bJ66NuM7QXdWJxygbdirmmiCF-t9DxzS-07brP7nA2nWPd6wtl6wldxi25qV6Pb6E36vEWmW2R0B947h
bW1W1iOOFlp4mYTmlZWCfekcWtouoVHpuUkzogXL-KIDBWw3pjHlMhqXboSt41O1xi2qPqtuqd_z2xtHF0R0pQmwTo0jakYd_TBFRq1ejEKo-yrx931mH2A8
W1leoEnlY62axHCOOvZybf6wpRKK4ksJG-UOIWDqH4Yan-_s0JC_Xf_OHYJiP2GMvHrv7sgd32JJWCfC7Xdffr8u8ncZOqw5M737hrEwALBpFv-F0jOMIHY9
j4ZGoOzaycVuApyndkalvV44rCoFI4Wq8wtzd6ckz3lCwJShvLbODNTIjqYBH2i_qSA-WyDVdhPLtHSWjbSaWOYull--Sg94ftXXd_pR5bo8ePQHpfDDdUbW
FeeEbAv9--GlLhVznPXOLQr7aiIybHJmEr1Ps6S_xVv62wDsHf94NMa72Xw8OAsV_Lexpf1SmCDV_q8SaLZahdtsCsaCb7MNdm-tzAjwZoIfvtjsufU_5ufm
m3pU8-b1jDuGw7sx8Fsisw266wT_HDA3Z4HWkkB23kb-TFzOGGw_suYaYHibD-t3lrEtD_JmA-S2HoHDBEIk7SsTVW44MbyqlnLzYpHMu1lXaGp_0TW-_6eT
Zr2MSm6_iMbclvuhUFTd_w7VUKMoATBQtlqMOSm2CEBbLtHzqYFb_yDtxUat3pOL02mn_ANhJNA1C5RDQk7txDpyRghmJTe2P17PHxjVYxcVaSRCiRJFVbT1
rB2s0h4tVumwalwC9Fsx4HzsngMV_SWlYB28R5HAL3D1YWOZahTlLopiaxzM4n45B3o_tVpFKw_p2eAyVdtNNtFwgxSqECASVaFNI-dc8cUasS-yzcyreiU7
HaZwVTJX_WcuBoJM_MixqXzrg-4HYi80p3Zzuf_Ox5_RMItzUvvjg-BXK72ZPl-kCnyCVpJ_mYw6x1D7wDXsfSCTGFSRVVIlHMR_Aer9JqIH3-1jguwe2g3v
VM1d_qApVv56pwVvJv2s5IBgvhMs7SfrwyV2ZDxpgur0QC_Syx4QTSSzb7dR_Q_-e_lexmi_32CG8UzhSEGAsovMI__8mgE_3d-q_XV0ZcyVWOYO2FqvC277
iEtKvezNbJBwB_t3IsBSbaf_tjx8CRXlIVNzzGFJjNzuSInbGisVb3O6RrCuzFmikiMy_yCN_jdBcZ_bwVOIZqWgO9Pjxi-sygkqzpO2xQ1yt9T4-27P7033
MoBh_MFqn-6lIij0zETzhMT6Ek03tx9AHx7sftUauJB4KwGqIc6Ewhx55bF_6FuoSNXB8L5QtTvz40WfQdcKdnHRzgVUwTelXnV6ozlJEOOYSLul1CIslVf7
NFaJDYpkbLsDmGK0Iyr1I-Pf_lg7drJftWtHHm6nlmODtpo9ngM_XwSRDtGp4le2n3W6NRSjF7w-_cwVmgyZ5OsMXRqUxv-yrSNrZ_1tAJZ74E4EuSAnHJM_
yjy8VxLN2_lxeB65F-Jmrzt_V6STVhrNnw0bDYzqvL-7NuyX8nan8sgu_-bVXR-nLwb52YbU8pm-_SlmT_VgIOt3Nz_yg_3t8qb4s_nLRFANHVY_tQjj2P50
fFyNuLTxbRoju2__b-mZ4gBH_RyElpuokZz0NxMFlPf-uI_Rnrvbvp2Khxj7f3mC_XMFlzgJ_mC
}

