sprite $Topology_Builder [96x95/16z] {
h9Jhkfim30HZQtTbC3dl_xX5e1HolyxvMSrODlbw-4y1xV0PXkUcoGfOFwWNeKBFJc2qAr7UxY_tBkHZKrpQ9hpVFvdbSP-8HI1xiv_cuzr4ZWAMHs9zi-_2
uzqAH1wFdK0fnTxv32PoE1uPkvLAbfipA7D_PW2ibFBoPoYaBVtZ-Dyir_LQeh_Wi5fAXUo5EZGtenyqM9m0uNA3CYCT4rgSO4y_GovMg25DsTLkiK5Gevzq
M9qneJolPp-1MPXacW2MEhdqascm6a1uyF9h7jJIJyOqSpTeRBLIv_tcNJMm-v_1q5ij9cO_ynwzpOIcYP98rpZzdoAzntfc8EkT_jHTeSg7yV_DmsIjnSme
Ep3xelkuhU4assYbL3EetknpcjnNS_3jwc7sasbKc-ZPtwP6pcXiowUHtUwtjQ_ezzq5I0r3dKsG5CcS6dqydX037rcAxlN3yUotxUffAanI0jsplx_col1Y
t_VVRi4PVKdGrbylyBTDjNgl3pBwdlrsCezfIeNPNwPQz7sT-lixIjclB_N3JDLrtcVsM_UymD-CPjO-7_TTtg8_dCnXDQLAaTbtjUP130LD2yqUzzDiEtFK
Wb_qlJL2tkUXt28OdlJJTCY7DBkINJ_V4ORsjpAU-iP7lvyq6mpA_l5cNum_m5fkyLA_XSge0EQvcX8xzPixHG8n1Z_c5g_r5QenJFLztwEFPNzfdN69a7oR
6l2ehnQ63Aj9ANRpM_rb1gV_BjgBVVSm6UfYUkmsNFQNCHUh4QIMPGP_qgzB8pIvh6Wpz_qQxQXxL8I02Wnh7tVwHJgPA0ViJ63jW-B19A4KiqN12YcX6X_r
5vErc9L3RfP7i5PAQY0PrPpFVaBKMaq3x_I3igbxas5k_Orjoim8gxKmzty6ToOO9dJT1tCeMAvWVArlkZGhh_lvG9QGoFvpn0kpChYrXYNL895IUQ5VbVsT
UMCp4tCa84t22_aqDnKoYVNMc70QolDVex1rdamJyeTv3IG21dgV7EN5EZHFhwP1aRzF1IN1sAQ-dpJUEyuqJerrDXMykfLfc4PPdaenrNjZxvEBBG-GuEhX
FQ_v0VcmW7ROzR-Np-hRVkVOrVs-e4hUNFi_iQprbW__1P2xjzPyZuIoFVnNg8_Zd1-6mTiEAH_-MuGuOPWPXxOnj3x83jypHz3wk3BiQOxVzEl1bWFwp5Pl
lQlyeWzw0NlhA-j5Mk-_wXU0PjRwsFiqJRtFzR7_gaytD8Y4pUKyeFUVzGjTjS968pJDvN-js8UIf30CXE6HrTqsuUxz7_Tg4FO2UnWcLDwW7qyKzOtp_CL-
V4n1KYn0cSUvzKVTZoJIErV8xi08KgNr1o6-ugw_y0rCFPyqAWC5ahJsXtM_GHwur-sB7Zvv_YrT1995ooiyjFr68lpqfa_QsPPn5RB4-KLhYwl28zEhFdbS
Vr3XKqHA-nzed4LMUBHUVmgVF1p4jblUa4iUebv_eymy0brZ3PzSb37epSxMN-AX0P7bYNjminC1HVZaGHclrryW7BZWWyxWCQ1ENEN4tUFVhkyxmXx1Se17
Etokp5g_AQDJ5-lFLdk4IiEz61LiTuAZJuOoOiezT8UGridIHakxlRtfazPvRfOykUtF4uCF6LTWyycywJ-jwSed4wQH2Lhw6xqg4-9ioyl06pxfP_uvbzKd
oquUXo6bu4DiVL97dvpwFedvfx_djpncMqQ9layEFPz4cLQ4okKeZtc2cGKE_DSdkL76ixwK5J9OVijZ6PDHqcS-gUQJMo4Etokjt_79mLA_V_J3IhDazBF0
ZayEwReVVZZLqQ9zdrhxrISRGkcoNtqo_316nqQRjL-LKRzzSaY9b_qOdMAo-M7hN_jatm-VVKSk1p-ClaH-x9CgX6lj_ztscKM-xPEHhpw9F_k-Kzhwf4EX
ZFTzCavFW9bmnTdoiR_y0WUVlDSFsSII0BE6UEbQVnKOXNw2lEsJgVRzsMNrIKw7_iOddI_uf2clJr0EdmGP5snlFKeUlrBMRv_iznyR_NnKdsGyqz47fOVh
MJPFEp-aX9JwFcbOjCDI-DxE9xtsBttoLJy4oENcuDcdzYVQ-IHVyKcmJbO-J8h-TtmogKtMip7wN_99S3i9qabIN_D94m4qGBplatUDmIZyJ48dDsTfvvFs
S7i1SWW_t1-UkJi0IVQofOa4AFcbJn9lu8ivoEtaFm
}

