sprite $UCMA_App_on_Server [96x98/16z] {
xTI7bkew38LXhArYuFtVzrh152UW29Pp-t_wcQnln9voEYA8u7HOf9uSf1THDRDgSeZEYswrLiLy7ifWRRodquSN1W7GkgIOFBo8CG1cgvxnJ9wLpvVBHS7C
KfSc-b2KGkhluE4R9WvFZIVuEs0MCUTrtl0W3q2Ro4Jy1QYKQTCGoEy7kBs0CmEcGhDqHejA2ypSV40KywRfUlVF5sFbMRh2Apto-yygPVOqFMxD7XuF7IhC
CuSVTL6LQSEpClYLPzVV3L--ptLlr4LGtgJVjzOXAgAVAfazXk0ylUZA8ApYM_j-sUWoJkCwTRB30AVzaISUXeQgW43urIzRVJKDjR3sUV2puq1Q67HqVVJv
rOVcOjTNd_4xYVlC9H79UXf1ukl4VV1kaEqq-tMVzr_ce9FuD8cwZn87ztWO7YNJtJz5-RKgu_2dN0c_kBuQFgcxBzt7XrXRx9iNkWtF9IJ1z_3gCyisNdIX
6rx8fw7eExgVB2gtUF15jx7he9vF8ub9bZ8-orqlNMTE-fdxvHR8OrNfVhXF_dxn_Czb6jSbTR-PwLBiTrsDRzDuAV_SgbxeTzvC5tsUF_AjfvxsgzLg5lYk
TxwQoht4n_Tv_yhNkjGyi-lrHNzDylki_Nf-TBrUwyBNrwobARzV-Sc_UbRzkJ7tK_lKLkYVlVh1ZuhziGsVkx_pMp_cy_ltPxT-p6VzyNuT_91Fx1FuDlA1
7yVzwUzyc-17_1m_vlE-gJ-xyXEyoSx7DtL_3Vnlzx64Rz_wvlkeRlsOp-zZtjeF-FJzaH_p-VkxhazVdduD_Fp-tjEdmBTvVipdzz6MU2i_vFFtqq9x6Fq4
R_valfLVatwyJzwtkVSdU9tessm_mN_lrozy_T77u0VyBxwDVintltmizkFn9zmVySVwEi6F-1b-p4_u-0RujFljJLDyqJ5v5_-y3_7dyEpN-zFzu_p_VTPT
_t-_uAKo_8l-0Vwn-oWVb2u-optTpyQgrIXpVqZUf54MfeVt1m
}

