sprite $User_1_Right [96x147/16z] {
jTkBjiAs3WJGupMMPF__3xSX2bC3HbPmvxvlspsI2EUv-ZTF0Q3F02X_kr88Zm5-nv-sIFrlvEhuQNBI7wD7RbyARbEVLPGVzRZY5Yz7YC-JVnsUkf3ViGBv
4sU5R5m1gk89t5i5nQVtVugiTImNg9ukDzXReEhkSuUwL2AB1L1Xl6Xf0rF5-ilByr_FZ-mfA7nysE9waBRqFg3l2omtM5VDFF_4-JwB5a1g0Mvnwa65jUm2
vXNN6jyRX0ii5TZnZ-6b9YuV_SMNc1lOl_7nsJ1TeRMkM2ymiRD0X0rLvWiqBh2sWPq5GyEuXOptwQf853Z_qk0LRF0IQrmWBgYb5DJd2ZRYH-hG8hMTVbdp
onbKyumstzqdBkVuVUqLBW_VCpPm3xOySlYh1uAYC6oWoGNylvhPEV_A0kh-R8VAznpVA3pG-laPiVSAdeP-Kytu3CmOqYVh1JnGokUHFEtu1pFuNP5wVCOL
PXNc1Pq7YXwV-Gh4cSjl_HU_G8mL5GNoulUkMcxxV4TBHNc41Jv_LoJyC7LOeFC5sEHZz8_vDV7sZTCyulFlzgsT3nFdrxBJbmf0Bl-8OgSFL5JOUQ3Uzlld
LqVkxv-_jiVReJNp-TjUNzf1ymK8_PBts-XhC7xExpaVgZNdzvIlMcj9-KV1Wi_n9UFRmxVOv_Y2h6_Ddy_e-K7QR_GNth_wy6l6Tzxd3_rQgqZ6R-tfDvy_
E4_6X_Fk-oVWmBVKvqTnVk7pbuzlMFVDMgFVGryElwO-_0ppj---VrMP-FH8lxNWyIbf7-qAltuhWNziMc-Tf_7ySzyUkNMUrbiBVEVRhVE4dzrLdM-ovDUH
vzCV-ctpUUZxA3KpVlDtMVJj4LJTxptnz30SV-xx9UC5q9XeV1x8-TwH7N_fQ__UBhyjNfzHHVozuyNtfbzvs8VphFpyxV9LaHt_BuvglyR_Mb0jUnqkq7r-
LMpaMU3p0zE2AiscZsPSeEtmTRf1VHrVoI_-zkuOwH5vQy23jq7Nalqb65FnoeizTJl7c5knBrAl2W0LzH7ntFXzfuuPVv64UaKgVKszlcEclmtZ_453nCjd
lZhFbDNRyBgAh_FhIqBUTGQJ-KKgVGP9Nln_HkTdIeg7FdG9pn-l0F8Ckh1Wv9df2Z6lVNAVytPCk0BvmNUU3NnrcVU6wFWyZtd1T7pcIq6PZE--5qp6PwO5
ElFDX0N3inCLnECBkffn0H7dp_630aGFZy1zBk0zJ50GdWTYB3ZnzOBmFDfBfJ_OAmK8pzCBZ0MhULj0PxxwBrzk-XgUlnHOlY3XdmN20j540QBpy_SMznO8
VJRuCvJpyVKyMfu1W0gKx09BFYDRVRpoIFkW_tv-1FpQ0cNg1zTPzF7PL_haytwP-nfV9_QnxCjllWR-xOznkkHZluzW_3M_BFcuxMF5X_pkwnTV_byVl_YO
-J-D7omm-D1V_B_GbzzyBl3PXwhcUVf_WI-_-bpWamyzakVfSm4oz6NTrubVtWhqwKFFfCVdP-1F5mBS5_MaUVeieEC-z9aap_Ey5z2N3JuBI2dKnsVky6Nu
BePnNtH8KkVuN84-nsVky4m9VStncF-0J0vVcR11OtviuFX10_NvTPZ2-NMQ2EVqynKAD9kOPmFATfwvRVDz5GGRXuyRzkjisAypsA3lQm3rJ935yod01Zjk
OStotzFs3m
}

