sprite $User_2_Right [96x141/16z] {
hPkBSXmh34HDYHPJvV__t-j1urCBGxX0eYH--wZL4YoBuwzff6IIFo5PIkdhNqKo-IXawL_00tOryVtzVKMEz7TqzUntZdHE5_1f2Zl36_HvYiCQ5FI53DT1
2GdnAndSjSbtBpsct7_hYr49-djyqEFLEu7jjRP3rrTFy97MehGZ_-LC6yCnsf3VqS4JsFIHmBRbqzL138ReX0z-M40vAI0r-k6_2oXd7KXU6loOZtZutvxM
-7D_2COKldPN5zEpC43h1icB3-PpFZvx1arRWFhIysrvG5KcAvWFWezmhK-e74hvXOLm-jhXToRKooK10SektUCZhaM--GrtwpBmOenVRx1SagxB9U_xWFdW
z_dkHJL3SKdUJ-Exi_1jqNv5bEj9uTxEV85-n5UHI77d84fDnVvsn3TN4mZ_BE5ny8IlJ_tAobaI_fHI9EAGhuQl_1dr8yG1ttq9VywVws_v1_FltjcV9mMK
3_orn4_kC_Lz1GVyj_vfWwzupVwvhfy4imOK4hc-TlNd6Pue9VXsedzaVvCXLjtDJwlygVwMhkSCflV3oxb-vTVkL6Zlblv9V-5_nzxdjiT7_ZG1-jtJAh-i
wMS1rmgmPsF_WJwP_nzwDGXxTlSVpTof6rpuamxqI_FnAUXVV_uYrrG_UFH_Oy_-u-ySByLu8d-JZ_wnFSyv-1lvUmi0_MheMV13F_9F6ZnvV2oF_ekrjTjW
2k2Vz26_g6vkuBSRG0-2ZldmLOg3Fsg011q-zgYSt93vi82H_59uK3mpY0nYT90VVDGV5p1MhwjEvub-9gXFebv-D_cd7IPw-OLzyw20II1_pZyle3poQV1n
0NFvqmQV5t35yCJcS7h_F7Mdw8g0V-3G15yFFeK1Ed9eXbSSgtXaF4jGngqDyoF3X7zG0Ug3VfN909rKW3defy4dUEzBgFHo7ta8FskmFV2F4Whq7tpzMtlX
Pp_1G7fHf2Y5PxmtdIiXEHaEw3bkA5MYW1jUvJEVHThCO9-sUtiNVDEHptr7P4ZBuaNOzNkN_OWEUBmNzkGiPJ9iuilrkYoF55olYqENkojjxMjPN7jMBFh9
KJYYwicmWPVz47JhxwzKKOzyCdXQLb_bgvHN2-xNaKAVJxinQUsvgT8FmlJWIwSVyy6B3BQ2ptRBJu_-ZmfOMwXlIn0bp0_EwIOaQVGJXTBZUvFInFnebztT
JIcLS2YWICUS9ZZ13ppgt57ow_AKeW0gu1NqTuW4dNpWTzJkffGi4Y0yNlcVs5aacCWFUqgwGrq5Y9-ag0dIMpxgSzXJ8vCWvCloDDYHnlAh0En9MFJK80C_
TqWkyAcHp_GGLckGigLaNO99ZzDeE6l-9Epfmh9bktFOh8Ad1VtQgknV-pN2Lp9_LeSK-Vc9LB2_nIC-wXYpMSWEltskQmdxUtE8QGrg2aYzVhEX_KRC4_24
-Id0l74V_XnFYa6e6I6zx1VjdUCd2MAHgRUVyR7_nq_dL540VEG__BJ2_-CKAKfmJ_2HNyUpJF1h5LIawncVtEYdlLCy7PYluOH-lVZWZ_I7GToOC9uxVFIF
1yZjS_mpV7NupGB46ZR6NwH8tNZQhdxyaUlcmqQ_DVYy9Hzxei7-qc_j-ESJ-HnLah_yXtycdmq8Flf7_1jnAb_kXlwRhk2N7f__n9ziRpNWAt_ezqJa79or
nKle2Qz_smtwas_r0tdFdT3wy9lJYO8l-Bb6e5RL2_cYmHG07_bKa44_VsT7EFY_2_ZfIkLR8vyAB5vF1mThu5C0-k73Q6h8I9_9X_ybHZGAiAkJJuAd4699
FmK4VSGdfd2Qs-edGNuyiW9-DuGxp7__1427VDmXECFHWaU_TzqzbSyHg-an_1Eym6DFV_6JJU2FnIE_lvp94lm3xpjtclj5FIMOxRilp1dBfmJuKV16ICFX
8UW2yhMZNj31Q_nVpqE-z5Izs5WolCtlJL9AndwdBUFdwZ79f6SQeee96_eI7fES7tk1KWC6FgIxhTpYygqzDaBiwZtTq-f5RY0Z-ariF3Q8NypGPUdVVzEL
Tdu9uqM5d0_fVGRNKlWTjap7fOW5DjBFVyrcJExXvpd68QKEVXGfcKbgm6R_X_uF
}

