sprite $User_6_Right [96x96/16z] {
pPW9Zkmu34DJ2aCByFtlEuQ92Ag6EsDbrlVtfHyfnQdjU8aPG0h0hFZ5Xeajlz10QKy1_T7st23Pt4LBNvZ-7IOIvqw4OQYxPthtHbYodpRu_CG68F5ap_9C
TtsTaKZkHSJva83OoZB13iZ-n4omTNb_elT6VikFpp7GJpa1nAfy3rSBt9j70isIUK4aaFRRRffBh9-K41D8_i3dk4UmXNwwaZtDe00F-tF0vsS0qsvoWdyF
qDlnvoZWp05mIX7oXCQIlsCx84_0tXaN836dIVq7p-lF0MJsz-4YjOwy8yd3lxaX1I3xXKBI1SZzym0xfoWsPAqd6gErv_g26tvXY07W_OiMYyzwiQUF0UBs
xKuEN2RN344FFdlwk0B2sAOU0qP4s1FOi-icE0AJdb34RGjzm1szCDfFlpYLiCG_dnrtNb3kB_ivWFSbdsqC23z2F-quvn1qT_fh_ybll-muRp0XN_bjuVzE
q0mWSu3lsZ-sxeze7_sfWoJ_-_uW6EKZWPpNuPw2VsN_KvZyWhhEz8hVbkSdzAa_v7Vvp_twHaj-sH_wwm9yNlj9y5prpnVOT-Mn_kHVz-UWU_VwUd1idHyT
dVfwL5zOkd-nwD-r7jRhPp-L4EtFT7nAzUFc3NW7dF4D0-Bslp-SuSTDrDTwwD9xVJlB6mmowt1EfhvRGKzf5qzWif-n8IVxv2phCwglInnkaE7dUtqiYCXG
zUMdRTgNUYq8-XQeFdNqpMnB3-9OmKagpz2teTSxqvtoTYongOzlkRxtPeSfuL5kLFabo1EelVHqX_u3OOFVv2UVtyDBho5I-m4jPkHfa-oU8DcV1-04eQSt
V7y0eGp9vGxvLa1SMzMV_a0wmgJNJYNV2X1gtzMVN7mMOjA7kXmmzDqdY_51K_k2tV3JFhxD_XS7ziClVKb-NQIBtgF-y0-KaFmLlP5JOerqHUX9Lzkv9Zd1
MD7ZLiJJrJId-e94-FVrDksgZ-WV6Gp_8AGWAdfXRYHbJ_KpQKTrFPen3P3Qlmz80ciqHa1k_pu0IM0EKu0I6ErV1rZMcvlyd6wrNq0MjoC0jpj0_N6j8Mhr
XN7wZJTs_GQjk7tvcqt00IpqxpT4PdzhbhaUe9NMK_UpiXvXpWrzPG0--AzdoC9wQdv1U-rVw-lt01R-3RqWo_wsuQyiYB_whms8_vkVtDGB_jD-A_h13Nt1
3_c3gX-r--koef_L6u2XB_lNa5L_XjKd6DRqBBpqVED7yVNRXRg_D08g-ekLznRoL-iNtr-yEfsL9LNqLl8hmQoiBoq9HNqzWKLzVKaRTXICrGGIXVB59V71
NlsWOE7Us7ib8hFHl8WP08a1U-F-0m
}

