sprite $User_1_Left [96x147/16z] {
jPlTRYGj5WG77I9Kx__2-uFMgIsCgs3SN_Hza2U1xX4Z_pcdLG4eWwhsvsCqS05yOf720VJ_HnnGlqkkAdqDgj9-PQS_ylSh4Fa3DPRmV8KQzlYVbr0v3mzz
5vJ3vW4omCu8d7N3e6-plm2nquyMQ0VwymMK8_rfGvSSwSEcVijVqPzLv7LflViLE5x1wpzesz3ByG9U0zbjPt-5sFVgKJXQW64_Zx_cf-pxxJ_hwKpse9mS
_OsQk0xqYI_lfFWpVIcxU6th0uviR73zXRwvwpTcUhNgklkzEQhT3KzlRR3drwyJlXMUQbzWswod3yxihR3U_MpulPpjWxt37xsuapsK7DG3Y7fJgrvwUTdR
h6-uTxaINqGCmpxAeIt0pSkL-AWISpwzhS2sNJ_cunoVjWPhy_9sab-gLIVH9U7F_HM_Y19RTLJfrNwaNlt8y9FyzhRFWJ_vQyExVG7ydhyT83lRorTyG0xq
VTi_w8DFvY_Z5thzztEWhqq_v1Rq-cH-51Wu_De_cHzZ9_wFvYVuD_bjctv7_ivXVjdFV-xlQFsJ-UcwdP-nm97VZhLrFlsR-rlqBbj-n6D_etTi6_SN0Kxz
dGpmvWUHGx_3xzltPmOO3TM-7tXvtb2YLppEJzVQEg22o47-4g7BbXz4b6r_5m1zts3pEV0h89iR3A9Yt_SBihN16K7ShaU1Ppyf2574NR-N6l_6Bx28Qctf
wxeKutyho3JaPlpBoy76JxoG_lVyrtzGUV6NplctJb0V_ikBZT_8ARyxyGUgyMzUCR7lnCy2zMThWDZrgXtz8FNl322YlZPKHuyeQFfHKQ_dXZXzVnF1xORq
y0LhidlfGpiQV_GxMw3ftyi7FMwtamMI7WUNjVPhuURRRIZJaJujW8eEU_GRDDHx_klxAQhKTnt_xvU1ByTblzcx6gWJUqLwnzxhV_8kgg6TszL9hvc8oIzd
tQ_pH_RTB-tGhixsW80JzQh7Eu_nkthKKJcpj8iCrFirbBrgdlF7Z-nFW2iMzkZjAYQxgco53m_fkyNYDB7LV5gDtakDl_y7wGA3vvl6KZrOnwVJkyOEA3yD
u0f4qTdFq0yi49mcu2azEhtTtkj1ux_ea0batP1hKgot_3Zi0_qotoVW9VszM8nV4I3-Wcc2UO0swLMvnGBlzIS_5vtL5jGwlWdebEfMJ_nr0Tucc0jYBaV0
UG3yyj_qxKf1qm3jUpkeiTzJWIxgRqsht-DpBuYfchcPh7MF7_z5_DnopF4LrPYd-A2947tZ8WXc0PUREyTVT4lyDVxfR2ton-zyyE_csDCHGjAtUGFc6r3U
YMv61gR_QeDv0mortbqUbwWsFaCUFpzliFFc6lkQDiDbtIA8yTSYlYmH1FgZFtRLrUcHDshorsNrLJzEzQ0FvPFgseJNv2S7g2tYonlV_5EBnZ_N_uOWr8F_
_XMD0PN30UAlMtmcVy2j0MJo6__q8t-N2o3lM5i7bBQyNVYI7rdxOuz_plziHmRQrtv13UKDt6i7fUuNZA1eX1uT8450bPLVG0CumHQALlobjOxFtCvEV74Q
OEJ7x_NZJ4GFgAWLloQ_Q6ZStRfrDfq7k2X8-aZzuyJMLuHVP02fHVlMv4Sq5YPS3v3ypdhdNnSLtOvl1d0HNclXLqpQLNGq7eaVS8B5hwEe4lFtOSJl0qZF
yA5Dl-xpANBPlOg1-9NLEyJAhaOx5pLhAdvN-lK6yFsRMiZuE0zWeSXDFsZh_A840T1PdW6i7n-oS2OEZHjl-UO1vET79XUWJBvL_0nWTwu-b66bmnJFIY_n
J-6V6hhPOb-JVX9-Pu68ULkXjyRponBwLj8JyQUQ6VmDrVhRwstv6rf7sNtoF8Ufca-FCDi_lGjJyHzUWVD7-S_RptSwH_AS1eVoSrfX-FWVV6MHOg020dLa
_ZS
}

