sprite $User_5_Right [96x141/16z] {
jPk9ZYOf38Cd2d6GwltVTxVCpqI9gccAwVRSrsVZvBzOxP-bHDGC7vcfYlpvCSaaEu2GwKzug97SiwxUQMRo0ydxiwwB7dgEjmH_jZXtaA2l72u0SX8-jxu-
WvxW-wQkos5lyG_XVNnvFC9B0wtfRwo7ppyQIC4Jw5FXbIhIVNx6Cp31_4RH8Ha0iX_VQpj5f7lPKzrlFwTdwgg7XkIW7Y_fynIE3X3yMSCZlWxWSfpbVww7
yHF_Whpcv_XrmfLlUtn3zrIGz-VudlaTs_jZQS1z9_z-GGBa4V1B3b_hfw3R1PKPP8D9zy1JiFqDCai5vQUsftRURQXtA1A3iJrCCfxghmRWQcaADNd5xmzO
0V08PWXUiCjeN_FnKRyT3F1gaV4Xw2O_77nOe3nbUj1VyoNuZTaTIVunS_zt_l_wr9EUaQUdd_0ruOU0MO-xymz0zH_XguR2aZhWsvglFyKFV5BEVx3_MFDp
VlmxNuk-743_3Nw_EjUfFd-UypNp7UCnSbtu3JxQ7F8lyU7zQBw1N_DxxswgkFdsytptRgfAWuvVoEyg8gggBEZd-x_nDEY_mZSPKlLVuSjVVj_itzuyVbMc
zBfmn6zVyys8Df2_-_gonyTV_jLllkq-lcJx-R_PNGyk3g5VZZLNPF8N1haUvVBBHZs3gdc1fX8--4e-nVYon8_h7Aa3fX8zwW--VHF_nXiTzEaDn71egfKF
qPtb5E9l0SZyS6WbFiolIrM9p-rK6Iw_XXoXP93qzxs3g2eFljnzz4_yydOpGpEUVnrcvjzVCS4lVFZk-DxW4tvUNWBs_KSwXW_yYW-MoPEwTmTqup7xAOVH
rWRud1HaZwNUC73YMUpg1ACQ7_pkiErFNPJriaK5__bZ7_Y-V-yZIhnvtjDiC8e7Fl5l5tr_LGvImg7IWO5d_bTNXwfcPk2241KEtkS3_1E_zx6RVzvBkKL3
wPEY3tp4vm3UItY6K1oduCa_aP34v36CmACFSS1dGbN5inuE-4YonbEd0wPaYRzcVfpY3LLEeFV1fzoXv-7DBDCZFELZy7f4jsOttttY7QINwsEZm-jcRAZD
Qtdcfov-Ym6qbmvA-jJDpwhvcxNsme7XfxGpFr7CFhyEEUFpIxpGB2KfV0Ex2VJKHVg8tvhTNvbBtk1RKqOi1vWsn3l3qs0ulC2RedUu1xlAVP0_9jncMUFR
f8_ulQK3N742_YOQHPCvQ9Dr-i1xxpRuvDNT2JmTOWpwpC_fZV75d2eEZ9_mgQJ78sXEtzY-g5D1Z_WPFqlwQWeoyRDAwRsh2C8WllIKlXwXFNMKqj_jM-yk
CWzGwtTxnCU3GR-8F_-MUEycmWCCHVuysMf1HZKm_4qVzSWj3OCfCFpImG1vYZ-7zAad348BUWp1ie42WMTyi9wXvY6eVeldz-d98hKVspEb1l3gMKK2lxB8
8v28F-nLPprP-tWsbEi9FBSJ1_YmI0Uml_KCVAe_utLg0OyHf_fRv1Td_LLjikcpFm54FLHiVv8cDTMz2SHusnolFDMlLMrP4laIussHN_M1hqzQJQ2PmGRV
el-vFhR0RnWGzYd8aF7awnQ_wSQJH7focElvWDzt88W6HdxWWx_6XvQF0I2jV_1zWT-SmE0BrxEiltTa_a4zriZNjFxFV3tERz2D_FekVzJF0MXvSkRJW-t6
N_MJ-DOYVrx_zhf-eiW4nChwL_uDULt_D0X-xaT2hRMNyGcV-TMGNdihdmXjs-cpWK5d_r_aRzJBylc5WfMdV_8zn-S9zj97_ipF-H7nGrlXSprSqFpcBVCJ
vOQkuPQM_yFNQK1NyYtY7uXDJE5FEO2j-H5-tKxaJmSWeclKyrQvdZPU0TA8BVWlkNatAV8bJq1xn3zC7toh7x_k_FyKFqqNMjz2HtuzIP_m3P3yyPhzkr07
U2ljiFviq9hY83xH4JxYLmER_EFqDNwzkr8xY9_Ir_XnXFWlSt7YtUmPN-ywegIcZ4_oBhxPGthxug8Zujk6GVozaXvVNL3QZ6_HqRgM6jvQnjUIjDaCzNGC
oqEjTAQtxsz1Wnr6KNNENl6wTujBG82oNxHUwP2jM-XuuO-lzHn5-xUvEXtgCKXEoNDsO_XzXr2aVr93qFSaT81jwIKz9lszHqE27rbGpyjo3e-Y30kP1lnS
lCeoWy48tViValu3
}

