sprite $User_3_Left [96x147/16z] {
jPiBpjmyhuEF0OMcaVtlzo0s8SH2FB_qjMNIU_kGeZsPJ5xq_-fgpSmCWC6UixLMHPpPPlYIMViRS3pY22BnA5YKuO4Tn6XHfqTu58D3ZJuoudznS7hMeOmV
5G5MwuQZf9i50uFmPODyDtK1hOAl2vR4t_-5Vj-mVudFyTj_nnEMmf_vdESN_L5cVGsyZ_0ZVGcMBhzYSKjCnRz_y8_qV7oAdvFewVQ1M_myNM8k_h_2r-FV
DRpYPmtkY6yP_lteN-4RkFXtdaw0GEx2R1Yt1hXJ-84b0W5rMbqfHIVWUAJhYHESwHTmwG0iNO_qF-dNS_e0LgX7qWW1BleKWFMDi58zqUJUXCkkvuGSfbBr
PCGPtMP-iLCRr92X3vZPGv_I4gVuG2gyJMa022v-jVu1W2E4bu4xoCCIrxOWOebpWGSNtVdx05Ql7okSKERoYdm7_LV-9GSJFmvWk1G2Lb_UTtoB_BZ4LbxU
0LnoU61HxmMuYdnU5q0ihPnspA_-2zjdNF1iroc_UNwa-6ClNhhWzPyt4Au4VrzOajlsiU_yfkj3aS_5Lq5U_ta1gldv2FYTVr-0bkS_y34uqsVo0xXX-PSN
7loTpty1Ds69_95_uVV-yVUOfzGqVv3ZtlEVzpymysk05F_6mn_nyXdnsl_Nod_3qk--iv_nocyV_6q0VJpAy3N06EfVEkJ7pCzR0sIkRre1vJzT_z_viK8X
pRyvo9yN84sb0VppuvcFUnD9SF6_hj2wnOAaLgtm_ZX0B6c0AzBz3Yx31-uemYyH2nZQCT618JvAzoUtvtU97cuG5Is_m188Q09x7Ukxo-1N7n-uLGiAhm5z
vwzTASCtVDqVwbrcXsztRuelVhsWQ-9XqSBR3_ngGLfYnFoueFmC_591M1J4_X5tZ_PFgI0De992Va3vmmEWyWgle3Eo11sAd-L_hp0LT67rFIHlt-il3o0w
u72_hGtnKVqCenMWEs0hNkN7Uke6RwGtlrHw_jPmV15Vxh2x8Jp1gXiGe91-Nd0bsv4C-DNG9GUN8TsE6up36iFbDcQeu6N0--kzajuFN1gNmgVKeeC8tDA3
lMFT-PI_-cK0m4y7Zz-di6JrBpdsJf0SKt8W99AzIr3w6fsT01yjlZG6duDKVdUeqFiAHqpyCd3-UEZYkpH2ZkwQ_8XN_6W0M97k-UNW_2bOBneOX0_vkLPu
BBhdjnu4M2ey40QGmJnV-L4nUD7nFO14nGSq0891Ahoa-C5W2ZJqvrZVkK4gVDn13F59W6QUtns0zXFV8vxO9bXq4AiWT03OA_h0dyBt3cW5NeVoWmRfPqCM
myEFvzpfbB0AWYiq5F0nFFnxK1ewX_T3lFbXW3DUmVruqvMTG2ZeD42BU2LtgI7Xbx0EsmhwNW7RyLZvWzp0unC08jyZMcZ7yKuFcb39sxVc2n07QDwEy7Wr
_oMw0uG7h34E40ko5r_2jxmOFwxMGFiUm8xnSH9Z_DQQdVY8xVlQ7jLNR3UmoSVEnxu0eHrqdBNm7j_Q8vvsQ0lrnAKzMpZT-N40Ns2hn9-DsrHpdHSuhcuc
FbgK4Hb-BZvWNtmxRI0xniyRa6T-ARwKvhTY_PAb-U75bSpVBSctS6LEvk-XeSDxP8VugEOF1hRpfyG7Ej_rv_YX8H27_0t_CJ-EBp2dKtnsbFlltGB_8pu1
-u_vE_gHtrs0ePVxLqJypAz-3C9x_9wClpNa_0KIVl4xzzzFnjS0aTzV-H7o9mVm9EPyclDT3xU5_Aa1F282tqVp_DlBApb0xowB_Bx7D_737oNYBs7dptJl
-2rStZ83zBVC-QPDjST_-EnUa2kJNWCu7vl3n0T-Oe8UP8VyrDrF0xXMe0TzqvNVXIs_56xUs0CVtoE8l75eukFpCxmAOXS_A3IZ_9iG-F4XHzC0OJeT-wr5
PCzajlW1FykPCgr0_v9NWXEUSm287v-J-G3yHCCjLluWJWldXswYGRHmg5jznITD_1ZUPJyD8ZdYsHy-H0US7Wpaa9FA8JM0XMe-37hQGDadN0DOg2RAu1sb
-QBF0H3fKMqPv1oKnFbePe1b7gXEZqHsqILJ-9yoP4gYXtUXyjGM7l2R7iFpi6lg3WpxHl3gKtE3FFnOfxuBy43F3o4FByKD5hgZ38zJI5fKVITmXDVLvF4j
ivQ09qoQcHdU_rtDMWNz_m
}

