sprite $User_4_Right [96x141/16z] {
jTk9SZCf30JW4MaQ_Full37JbFw9bWnoxCvHL-fJ8yPxv3X-ZHa0AW3Cx7XNRCWnWBq3dnYLzftUEqTWRz2zVdk-ALr3x6yw08Bm0V_wZySV9aY7yutN_cD2
zmdPyW18N1PqndsT0Mb-bAVUVFiC_3a1QHvNFcxV3v0VCCex7lZc-l2J0y28htcTm5BRaRrgBrthEGSawZkEQ_cu_FuuTzJtDyHBrlo0bSI6xAVjUEHxE43I
RsjT_RCtOBuKjmElc_N-ZqxRzOCST7SznFRzhd5VpgL_Pa4WkT3ZWwba5yJVxA67_fa5DJBOb-SczC_uHZQ2WVP_8bpxvvzGe3MGKPUvwBzv0I0AMYV09dfe
9nlwfo-OBAM0lHCQCVUow9_tdy4tsWW0f6xwYOoCkzV0h6z4EOFHl97u6PAQa7s0v2lWQOpEodo66jjBFgRl8qBw-JNugw_u5PpRAZFj1Pyisy67_T9Jpq_U
vmi-4ZxIlgNySihd-Z_XzqT3GS7mZ_VxZOC7CY_V_GoRZH_pXyv6w7hVxfDjl7L-n2_au9_-yPd-ymJub3ycQ3qVs8zu7dl9-F3-nAxFb0zgX7tAL_zZCqZw
ce1z7_lys0yIwya-G02W-Wa_jnv0st_p1SClm18-jdqCdma-Sy4ORma-UG72YICPSdlzYMyYPXUavU18nyZj-kIH3uYz-gszvDkcpwTldpY0wYVyn0745muV
n_iFeFhFlEORULk_zU7pUFi1CEhtu6T2ujVswFBzWhCRmg_BJ_Yf0T3ovUk2tpV0UVNdySO1E9VpwDwVh_CaebxG7-xpnGi0IQ3MYl0lhCktKHfUcM3Idpun
_VdjYEv-8p6glA2Bvp3Ewgq_rDxzMfCJCBpfTzA_bVZGcw-7imPfYVBIQ-cTuSSAr_fQu-O46_eSyCMk_l8LhqzK0D04s1u_I-79-m6YFuuwtg09zwlt_eMz
Op50smSge27GaZQMWrcV1hOue4s-ghz6Q4bhFjGtFq3xwLSe4zS4k-5rkQE-V6NOtbwHh6jO7O7EU_tJ9ri84JF6B8u00ZEZVkczstTo_2Y7EC12_NCzEa3Z
3kzx8h6eNp5ub3xMOs53VhFh2V44bsT7ww6T8Tlb2CGD3sX0g5-r7L-FJj3qtXZuvOeirA-pFlJqAA1_ew50kLqH_7RfTnlMCu8pPXky6D3Sz-N4zNYsUPnN
uEl7t8txU8ttfY1y_RuRV_7Uy5_F_3Q2zFMuhQUVArwsv_QAZSx7w_L4NRav0FPyvqEM1x3WBw_to_cOrG5mNc-zysFxE23shsJqzVZ4knM_IEm_5sH4zBbV
NrayGJT-v5C78BVyalQhFq5mV_NoGl2thlZguryVMJuUO5u0AFUTllfNyjv7rXSld__dXyjziJzeTpwmDo3MN_lC-v6F_PMBZxol0QUFb8_KUeQFjHzvxF4-
W30YuMFxuPHF8uCFVpZhpW0iwki5jlOZ3spmG7NVo9LVi3C0Y_ho3v0_V5FqjI5HZ_NTjvLVgkiX0L_r3mCAvQDMQ4GgpbVYEBIXwDSQx2GFsg41qTTBC7-2
UlKr8FZwaYmktjS_1z1zhvyzG0N2UaQCf7oSzHKa-UhyhEz7SB_K6MHESDsEnUzAJhzwvbftR3WFGl3r2BE-1rjBgWXyY86SzUE4ckAv_XwVrx_USbtIAd3B
Qqce8QYpOjHZUL_EOaar1794eeRoExmlgSPC2Vwf8kh-OEOdg7jihY2KJro38dMbM-RF9EfcX4lFJC0kBZqJC_9-1WAU6W5g28000sJ0ip4fYy0Yde-PgMxc
3vB-0m
}

