sprite $User_Store [96x111/16z] {
vTe7ZgKm48HXNj5Tj3Jtl-yQZ5vfF22CWzB-czDN1ZPDMAu3O4QUcG5OHeK3zb_b6VJREEZLrp_b5NJf92LVvHrNWHt7GyS46dK0Qn9mzm5vlcNXq4z1ujsE
qruUtd70sNvgnVhg4em6GEvwymdw34wyuTzdjGCGFtX0_CI12_vpyKdfMywQcu_sY9hZD_QfkG0GdyOFQU7v2PYtyf_zuwDF-xIL1ymU_Qxp6yUVN_qFldVv
FjUt2XyT_bhXhxFzjPslyz7Ar_cj0skjdshXQ_tN0qlwXFMDd-_HKlaX7xxUrq9bMD_vMbYUa_xMpy-X2fU_Pq2LhoTnQHUunxUDD3px2lYalh1esMKaAloA
f1VHnlXnqyz6zFiw_9OB3GJHwxlqE3zinK2FBpwvPx5z_JJGvoTBn_yc_sTZbvyEU6hIGtwAwF9JEytYyFA3FVv1v14c-SJ5fuWcNmEQAFZSPWs-uWyznIWc
T6LiyfNdpFE4-BCnlks5L4Lq-Iu_nKc-AQPYlEzQyDISyykF_L5Fz3s2Z56-NVbn-iiiFtO_9lkR3V3zsj_Q_tvJbpvT_u8DFh_Br_57djzJf9xk2DzlV6AK
xxzvRlh7fS_N1SWFrp--_Rwkm7NyWySONrVWHq66-1vV0-RVI4ResOxnjS58VEZPzleQqDs9sBZq-ghan_eQ41-SulFWis_eznKFdempxc7O_RSCAz9T2rr-
Fddf-nuvvjyNi1pmCz9wVC-P5JvT0spqnME3aoMlXLRVpn0m-UBB0VENlCuFQi3BQDa7stmZO2J55n6wGGt79m4uKq7QbNyEW4t-Pa1US8DVHRw-02_zd5_t
lG1lyAF2vwA1r_ujhuXt0txf-ssqHGCpV2vd8BtHTtLxWr96R_9TtTuWNKAzlrNvpBOM_ANl5Rw2QUB1f_ow1w29OyClSBgY-Be7e03ZdYlcN5cTp-Kc06Pv
nyvt_q4nqEZVPzG0J7odhvoSuIkGrRwURzCziXgUQ7iVfzISusjXvE-UCYDf67vt58p4F5wFuJQAdx10qfRkZEITZadlIKXA7n589NnaW5cM3N_iVm
}

