sprite $Virtual_Machine_1 [96x151/16z] {
j9MBYkim34JNaXZe___mnHCv8unlRKWgPz_b76bakd_FgWNQt-_A0I1-PMW0FFgdzYDwk3aDxNKw-_REb-7jvjtoE6HuCngoMV7UeblSTB--X8U_jUZcdMDk
vhN_OMXlH4EwgNyU6HxJUQRy-Oa2j4TtqYvoCOJpktYmQ0NFau_wlzYsMVG-6ZEbqxzNLA6CBiE3jIPN_UT0acZHny7RA2yUKrP1TEGtMlHPy0GdNSTh_adF
bBJeWsYiZIeAJg6eGkcC0-24xarLFUfVNz8HF0xiWu_sjTAZ2VAmW6tm8XrvJFtl-8qBEYwh2_9j_wHRgIE5fSV4tztubi-HY8AaYx--yJckolFXeMWT4Vye
_kR6QtQ9TEQHZ7HNFeStNbKKH6MDaVAtwdzpuxSYeiEjUFWi-UN6drTw8lb506o3FwynWH8INy4_m5lXk_hNdOmdTErQgmTgym_en8a_RC1RqSm2_eByl9EF
zZe9R1n0RmQcC-eq6YK-RG0OqOYLYhIelaKZoSJl5QHhW351gyzQLi7YIz3nDtlKYdTBMkbM71rRyQqj-b-sx_c9vPu_La-Myd6tgNzh_-zVQGkq3EZkdpyf
8twewmobIcWGPmfeqVymY3u6a44M8cij1SR3_6qOrBzmQhrygNGjUnfWz6zwPrN_10bPN4bG9NovOlBzDWGDALYrhzxd0Mmv0Fc1e26YFtK2fQ_T-bgmt43s
3nbwpVjL2RzViF9fG60ojBfXhS2NDRzBsCJlT7m-g0RYH1TyFu46IBuX49zF6k8g5vdVQFJb1XOHwNv6__fP6dGjlvODy9BV4Cd_82P3fu_-DWEuoSEw-OQ8
8G339nyHnYfWsmp0C_ERWoFW-Y2LV7wVtEq0F1A8RrqGaGOWqa01sUBgXuChLFv_yM8c717kD210dF8_laBYqq015SI76okWrALPYAujQS_Yi_roQ_Bb_3tv
6k1RQG15fFmfw8P_jPg9RjnC38En8qA0t_-1_sFb3s5Knl-Hr2skDY4v5AKPpswfgkxSt_XW7_iR5_21_uj-64eQl7bC_m9Dsu0leC0lJW_G3F_TMbDVb8MS
HWBNN_qweE-P_4B_O3jkDiZbuyySp2c3WUCF4yAOJc9m_Px_5gUVGVKDKar70c_89rIOLNZ-BzcfnFJZZnrY4PdZYZshV-iI_aDX-grlLXasG_9_9lurDG0R
4l1no0PrxZO85lwfgmVMTopq-uqgyeXgzcVZ_qrmAPrvr8EvvnVGoQ6jVm3xQi3jyEF-h2M44hjyyDLOSLszyeC_QxYmbB0Av7j_5QURXW6FTdtX03jNUE4V
LDVHtmm51VvyoFTEfiY1e3xxNzSDLwVU35GwwlSAvnxR-A--_6Ag_wOOZkN_FD25FiZw_oQGZutISBHgzA_7q1yVy0ddmLbksQNkmTf_SXDaV2FWght4a_JN
sUuyuz_f5mPnYOp-azRmR_MhNgI_TOexyANVry2uEFzEVzDDxsXEn4m_o5kzhoC_tbylPr19jVpVHOXpElkl_aZTP3_eJnUtUGY5_feLZ28D1VBT7nx7pWox
lsm5TJxQQ_nnSDGpHV-D_lU48DFyC8VfLL_N7xiuzzSz8T2ZAWN_dSS259zzFk-hNGyHwjP6XyG6qHC-rqkpVTMnzlrIF-d1qUV-ujwA1Xxxep-x56mqJ_Xg
Jc_gg_j1_wwoJVlprB_YzFaICq9LqVzo6YhzxC-RW4FRYmwMzE0FJ9Gtq-Z6hy_7Gz5TuB--gi3p0eJ-Dm5N9Pohta-D_iLGYodkzSAVco1VARNx_yhoArcZ
CdpEdtvn2txTm4PVQL9lTF2PNzF0wnb_bluqwW8w-3Wp3MpgQ_IZFjV0SWhyxb-nayxvS-aNmZTyeJvPu_diYJCCSZpokMyKVL93jj79Prst21ZmlAWlzkS2
p6f03_dKvLNITB3h1pfQnLQZbgDxFdM9El4rc27n_1j56AJR6iFdvOZ_aZG_OVF7MmE6Cltgh_8vFwsh_PiUFjyUFkQXkcgn5u1k-3HmZt70v_dvWiScQMkW
Opubed9TWa6E_x206lJ7V38XtWsiMQBx4pyeyHT0zeEDZZ-yMX3-p_gr06qP64-9DIq4ElXgbbhpylMh_-pGdqDQWpxoGG_vxAPBYlPo_VwX91Jq7kWIPxET
JtuI1fMVFxcV6mftI7Pov2rpvLFMNpfcdcWkyErwY4U0KuJQCqYYlwQ1YtIMrHTyFC8XpoS12kYtVj9lPpVtdyUI2Wb58FsiuurUhsxLxU4qSD9lZpSo-QJ4
RG7YsrtTftbtwM40VEDxYZPwJHiJ8BwTziQlzhUlliTFPVqM_xfZ3VgOvEY3J_pBmbz9lvUOJDF6e6Fym0y-18SPSNNmXmVlL_hPPJ3UyUjgVnkalIB-dg55
FfVnZd_ErNp69E-zplhj6jb64DO0xVX5-YUXahtVXMzAhUjTvkTOi_0PXLTpa6U3IVW-XSWdrXZwqZy4R5-5Ul0pGxMWSkCpVaq3JuDl_R40zfl9UFU7Sy2q
rzeV1UwQGkJJ4X_nMMGn8ZhudylxUh86_AuFU3P8FVbF2mVZyrS1xG1ixVM0Z_PjV6Q0mAzanIUfoN-qXyIdfxf5z4d__AsiFrhpl0BPuRFkP3puaz2V2PhD
WJfBRuQiFnl_J20wwuq_1uIOVyGluv-V6WPcz5Xmalv7QvwNC9cy2Qfq3lZVHNU6qfIXW_vZm-3_CsYk1b-r_5_6_r-65W_wlskDCnGK2x_gs-XGgE40_tl6
vxZE16e5utzk3TtrGyRdKdTh6V_J3FevutEMJFpFC_n6T1ZgEx_-9m
}

