sprite $Virtual_Machine_4 [96x182/16z] {
jDVjhgCw38NXe_NQ3fhxl-2ZGjebAuMolxp_eiV6f5ap_zql9V_zNIchAlLN_Ax_MGSUCh1t-9FL9C3imE_h0RX3yikBPo-nL-JlVGQowrvIwlSMh_STVcdn
whQNLFp2cRIijKFomyLh_bbtXJ_qznOlINWxUjkWlg-xZFSAghwr-D2xMlI8B_ju-ALGz-FBlgm3Yuz0t_MjUzRf2OIMwUtVF_7gzT9PzEOhYq-Bjtww6Ei4
zfMrptPdDUSTXFas_qFth-r4BtHH2DHuWjtNlbPVgpSNlyuleKDtKUKRV7Quk_XUiEZiVcMibzxznNi_4XngdnyGlODw_EbpWNNiaxHQEbph2F3XZEXw07xc
RNvMSSthgLlkVDENTAiAFXzByPfyxyFKcK-SfrjLH71zQdPz-YwGKPrzXYf419mT6iIwby1Fd8TFP6KLI9oy16BL_UnblWN4xbV5QGVWMdUnpd_uKUSTtkdd
uQREJrzLzM_4nBZMWpRj-Gk4_QWQ_nuTQA__OJNqYOLwTDhVN-3V64U7gaEvrdkN9NwwJrMDROnHY9ZN-GVTzLR7lcQ3CQhgsI6M-d1tB-66VOcegBq2YLZy
6-4cytt-lThfesxhVK7Xik_J26_zE-6WfcCV-Y8VrVR3_VYXfyFXfvQAkgsV_bWyVvxxt0etl7fMNr6d_ftmGU3mSGUUld98Blf-kERxQaxEJswSpN_n3ktK
-7bMNx6LNDW_pvu35z6gyJu_K5ls-PbFNwURhUlp0uojQFiX25sasobFyvKvNxQsaVJvLLMZd3qtzFNxLWeGGDKO5S_v8yGZVBPOErZ_DBzK0pdsUVWG1373
vvcV5TmRlllABTlFi88028azdiTMUuUgmFejFoI9RKJt8OXd-3p2RLJi3QeWxliJ8RUHpGyWD1iSuJOxV7JfvmS981zBi0y1hqzvyD72uUx-HmWXu4ZXYBai
GautcEq--WJDrqXw_XVTbvWTct_x_DGmRpzOi-7h_hi3Ec0EdD_oiK_EID-g-tifygVpgwHdXuhfnzDNvazzXk_DCQhQ_4wtR_l2yIM8nBvwkl4zdorb0km_
qurrVcxw27fyOP-OwLPqd-VlY4z-md7znEgZ38aZUu9ZGxN-GoGuztczmfRO5u9T4-YudaQ1F7yGM3_pvTjW1gJdz-MXr_-PPtWIUFvBN-brHsPbn43-lCFf
vl3ndvkS-RnkXvWrTje7jEW-1BJjS7r-fc1VGZmRCEO0GVJvmTEV-2aGjLLqNqYlyCbjo_3yVe7F-oS1s3lO5pfQ38JG_l7BFd3845pwoaJp18xo_DENlsvK
ZQhTTmS-xL_Aubbv2FObHeByVUs_tYCWBi_Fe9yV-_E0qdsNVsON_ZoWzklfv_-bcudI8pa8WwUGmAbz__VT8rPrwyVkU6V2tCV_cM1YZ4XRWbh-DD_1K_ue
0rV_I-kyYXl_gPy_nPygj3CzqFXGTT6_j_X_te1KVGIk-rKkyUS86RA6vm_CUO1uhey9cGZE1ruCCw3nYGRlV5z0hzJvgcwNYTzI5FZ0Hxre2MZyjEecYTxu
RH-U-L06BdnLDxvU-TF_MF5Oy8f_O9POhlo0GfTg__3c1xgf8LdyDsTqWBNyoO9ezUunWC70Wv7rav_bGZALFixtmmDa5WUVHwe4LZw0y0hfVAjkb0rAT-ZR
mCdgxo_8hYfkV4O0Qiv8Y1yHwqXFzEx_H0XF0eoR7yZ0J2_1nGUQiitoLJm_MVSAH0H1ZWXP9iAE9_5nHs-Qman_4PZ-ewfAKda0gC35HqGbj49fYMAO6Tqs
eElRVqbZaA9ZVDJLsUXsD1OTOXSYAFu8J7sxRZ57VDrkgrMtGXDfUeYQVZu5TCdFDOgieRQNQtKJlo-nqY__8wQ-_MwFOhvD8ovz2J6reLRSsf2ZXQRtf__P
A4qonXZWj53mgTv-vtzSWI-Zc_zIb2vzEpWeYnXA7zslcl-8dgF2e-dF2aVNdrLyVF0dlbcZk_wP1tqx8j2qeGq_m5hfHDUtPSxtwaPYpqTj2Wpcz1dvcGyr
Pn_yPm-y37CWKX_uKfZd2WzyxVzYyZymFl4HSHN8x7oPEuyRZwhMltU-jXn-EzhnhxXWzN-co9xVRvhx-BIeE5_vW-4IHCkVkAiFWSRl-DN_35rVuVwh-Gyh
Fcgvn7-YWsZ-Pzm2fSU7cFgpyWF125GO_oIqplYpPXsL0l3couav_1nyW-RFpiT1_rJ-y4SBLzAt9rB3JqmM5Fy3tVpNV8JMmNaBhU9Zurln3N_qFmAlmiB7
cpyZfEh6CQe6H3-QvK-zSkz_n3MzBLKtdEaG_-TyXCP_uw_YCukRwYVFT8-_pqTgfsy7IUsvbZlXU_z-JMzp_6pXGcR5pVXd_LRveo8hezsK-iS33lpJVAJh
sqIu_Od_QVEHLNzE7FX7_qNGVAJpe_0DFmiN8STheszZmDX_4dyCDWN0_O_Ul_-s_u6H3W2ChyFZY_X70CE2W30-eGwlJv-XKdBsd-hVtwHLV-x3LV6NWexd
_57_df23paSfPE_D5vzm_t7C7y0aSl4322X_D5iThr74vVyD_wpFODAW0jdtbo-x0Z6BSqe3YKfd_mClQpzI-Ha8TRdiXqTrQVWy7wckJsgd9JyFDZu0LQ1Z
_a0Aqg9_0i1zEsBpt_4WmVDy1CvNEjhjg8mlEd2EFmhG5JnNVgHkH-hVBJwY7-SNA0HsBHnqx26y0MCLH3Syy9m_780JgWP2vhSZ8MlH0KxwyvM1IujhjwF6
ftwI0dt8dzVe-hblRoYzd2yxwzkNWhJrFtaDLxdoQQiy-fy8pKTozJ-AJU0MlzEt_D9yn3IgvhyN7sHMfVXTWDxpSpSVAVSV62FSGEEx0ltalm_mrlW0oBi2
m_bzbRt_hY01FJuC0BJc3E8VNeBvZwaWvTR_HDZu5bTyek4V1MxQvkxYCt0Bt5pYtrTP_PyEXWWh7mFm_ZrXccypBln8oOz6AESl-e_oNrlVw3gv_Uc6kK2u
2usFCHhVLB40q1JAzUc9VDAtWqhGtF2rngflWp2-Bx3Hju6hEJC-lEjurhVB7_LIEm70-2YWDsS5Fxp3GrF4ojV3cP9ZAj3ofss--5syxJAh-Bv2wjLTVEXs
T4Sso_a-0LX5t1B_Nk7dV13KxIYN_763XSRfsHvM2QG-AIO9eBAetSsF_6WX4bruiz0A0m5cgRhfVlNCNmSC_LcUliAaQ_e_h--lUk07khvTQVHkAIbT9qqM
R3Ws-Gx7hMyx7Hsxx3H-HV_q25YLZTysGA4vFSZs_X-XwdRd3-H_itFWkyMlYzy_FRBoTu4_c_ZQtVhWF-Hy3_oPh_pN-7RZFnIVVU3FV2krgVJPnX-7m3zd
aXSHtQzM_Zdmpsy6mipyR_J2RyDRyL5bQlnpQCuBK7m463_vO7r3roPaWfHSu7pBoI_igZq1qlcW0l-jNRK7jhyM-EyjtwmgyR_8oS_7wXZZpSSQ-EyjjK0e
DDyJzzNj4FXlLpW4_aj37GB_hKN-_y3_0m
}

