sprite $Virtual_Machine_2 [96x121/16z] {
jPc9Rjn03uCBaUB0UV_t_O-HGSYhk6wsM_O-yb6cjKC3_lNdYenV_qwH_rVyApep2ThXyyCJ0C1Cnh-Ys-7ZmQEB7ms97huRP7mwckdmQVfq-6pmqu4V3duw
nDz44m7hWo6PRjtXjyDxmSSG49XIlXCyuZjDFibyEvgfIQVoRRev7-FFuD4Lm3J8lmyUT-hpHsQy5xmzee5jaAtT-3RzoYS9rc-KRZT_dX-3dnfyOclpVGpU
ET3qD_YcZnDZHFFCdmQptUpm78s5U9c_12ZvsuCxlPCFWeyqs07F1tVo2TjLH3xnGJiayTjKegyyRJ7nqo2Z-C331PZ7SZWlu4_Af_Xt3kZu0hAVUiyET0l-
PdvsdHRp4cFojmEt0ucOmiJV3OEv2jXyI8oeG6DEpo7yfDsI8Mcf78W7Ekxec7oUV4hhwx33m_1ZN1lUyKFIrzTNNOD4_0bz8k_va7GSnrhxznGvy8C-JMxp
BuFrV-bq4y2X-66xcLzJhoLLEf0uX3VQmVowjP9EZZZfx_Fju6NGZ-Y1sJw37z6sRU2VDFZq2SIOqa_evhk0M3hvZA4_eMD-TE7Ss_oH_7v-3FnZk_7QdiMF
zMgmoRUdJPyx-XCNqUiJviVIxVmFxHQztLxhdpZviHOkSnNPUgXdzlOiXyRV1dbamuVCztRVEO0MQ8jJcryRl-mGWJQ-SDwF2P_bIVQ4SFPB3Sbr2CxVqKWw
ftnkDzHDSq35nwf9iCyuOl3NmcExMOx8_C2YDvcIXCR7Rf_JWNp0W-JW1rUQlzNu8Udu-Zgq7IJYbkur8g_ym5f4QV2tmR7MsWwY2EFlP93FjpnKU0n-kDtA
GU83_SAFhElLKTJ9XoXLkx4SVWidNvzFDX_8jSJ1ztagdXj4FOxV-S7bSohtd8q_sksPJu0NVkGYkYRVH_4z7_qtLtxmKAEpyJE6dlWaEhy8Nb1U-Q4t-6HX
sFgHvJ3sX_gM3vys67pu9_VZwR2vLxuD1jyO-upnN_fnRwXquTTwDQ7uMzq1Co-VRthftWi_UF1rVlXXmMmCkFbG7n5eV9x9sG4ddt3TSl99zyiseBi5vZS3
vB5uCxyV6aRJU7y0GEv7HC-7F2_fM8JvXiw7XYAtV0G0rO-iLkty43VVzTRuw3Qp1U1-F9K5kF9ZAKoY94gOchEt_MbnfvHNVYmFG92SVDzVzFJXymTBsEBe
HrJvP9zoyicRAyYijlFnOtv4bEEve7dwO_9xey_v4m60noB0pWSY45bEN4jj_aa7k-R-r0BsV6fNmqz7EfPEFc5rEiO5L3-szL7Bf_Yn6EuTtUmFEQ-WzMFR
lxCV8yp7oWjeykTnTzqVNfz-sFak7o_OuFUqkio7-n6l_8nhVtBm-vK1xQo6-n50BI077wfVTOZm_FoEFZgi-62jntOO-RY-KAVF3T_UHFV8wiTsmCtykU8K
ptgJCEdcl_PxXBmVjJwDF_fnOue_vSL_kRzQRT76_e17TeDxFdYpFrfiBTJvFEy-d_bsc7mlwCY_xhxx4O5uvilrwxUCq7OWnlxGXqUYB3j_wcN-XEllMCJS
7n7e_VZ0foxFLv49z7xCSN-bjXvvsS-f6i3ANysW6FDyqxLyViCdMmjYywylmIE0kJyyTDakLQP3xK8zVndqnwIuy1drqSu-_zbkSKVtAEbNuJpv0KRF9zlX
0VChk6uWpYueVbr2EH20BdoilZx5zu41DvlygrrelXts-43d1vQpGvxzUF9z2NgD2EtjOND8NlSVbwSZ4Cx7mcr4P6RZrslAbCm7CpT1YoT-y14Z8jE_VrUe
jRJvs1TqFXrTFZTz_hZI8KUJ6IT-EZ2Wt0EaZoVEVEnWUXi-xbzZBzL_o0puIzVIdB_m8_YdTyqg-yp-TDJwSRmu6j7SqllBz4m_7LapdsXqDFgpCkVJqU0Z
Pl0_uWFhig1pVWbRC_XdVdrXEV1cVtuOZUNwt0u-uCRyxz7T3Us0qtVpXuF_iRe1DaOp_n7ycmPLE9HUyNflU9VFzTYLFaNtJI1xkwdJ-NVqQty2kl17yEyf
s0gKqeZcGmvRvZkQpoZSRlfODFD6Q4cA03v7d_qvWl-m0mVzemw3_bd53_3_1G
}

