sprite $Virtual_Machine_3 [96x105/16z] {
jPg7Zjm-3yI3AIAGzt_VhyWQmTpOMx1tyo_fF_A6ubZmviyBmVhpUuA7RVmMNiC4FNwd0coH85FXnwq1CFcKXtuMF-dXfyBF6Xy-I56qZPyp7biaDIl8m_Wf
uyzyp0gKVi8a3Q6994Mj4lQNT3Tu6u5cWPynlek7z5N_SAovvkixlfxIGKedFhusFjhmy7F6FZCUjoBP-9EkLFZ2-6ZI7VvQRif3trZJyP4zB1189drZpHH3
pZUdjNkTIRRUmqUdhHFvSWm3JoLr_aLiFAymn6UzTpvxQimIByOmoDiAo_JeBlOaUU2MFzkyRFwUdlwLtB1k-LMJzNoiV19Ar5E-gmfuO52MVDjyz-Wv7-M_
VmkGhUlcSISIHEFZudogwdy5JXNwN7d3Nf9EV8sXV-VhSbML0TkccbxtlldmZhs-Nwegbqk0worwp3_nuM62x1K6b-5nebxJms-fv66I_yJUs2CbqVbyFrKd
FKlHAep7BiD_D_PyJbLcxNQm3lY2_v9ENgxVfECSUuEeZ_cwNsvExUlad6_voXz--4G87nIrWtKGGDL5_tSL9Fa-EhWDeaID8GDm-P6lINelLUzpRumLdQvI
urSv5JvArKoPqi5V3tYwgcoMPc6uwgy1MMnuw_M0sFYeEcNjzd_6ga7RVDEQi16ynj2oF_VNaZWzOzNVgbL1m9kn5tZuD2RBJA0SBG1QiQfPuJK-1JeVyehG
0r5Y7lcqgrmY84kV1bFyLnq_xIfxyaNkiyvLIleec1p-x9s8QvD_lhFmABJvV8rl_Kztojksug7UflmXlSyNBkVyhFcw5U0xV4fyvE_yz1fm-B0R_xK_Qchp
ZGbsPZ4hNlLFyTOQgua77oeZOX4aaBLxv6kIRbBrgdzf1ZGtV_PEJ7IL7-Rh5NkyITNR-PR3n-HhfvwRF-LvsPDvVsgw_uVZgYg7l-qdITkMDx_guJf9-IaV
9P2KCjybxv-NlFaepznB1IgwvQCgzs25h-bLSHSWatjLLUkoP-kfCb-Nmqd_Uomy-gV2Xvq2lE7pFD_LgYLP2XzxxSgJJuKFxWDKkXUNFzD5QfBipSSnQKAs
BJx4tYi-J_CruhDTs2fZFzRCgPlRtWsT-_aenh9gzfjauyFly5CY-wKgySmFfygjVqBr9Z_-oDdJnaTX3tZvFqtl1VoiUshVVqXgFH-R_P5Cv7ooVDC_B_gV
BP9az-VXMYg3FC_bnX_-qt_cgCwN6aVcghhNmk_DLvbZvw-j24TU-BqMnyIU-yCytt6uV-9dAxJ6uikrK5smUVhX-6CJw_VxSRvauj6BJm6eqjv7vHt7ZJz_
_dXeNqYeyDN7iljNBdlSjurLuNf_Z_Tx8Wa1Gjilxh4uV9YhGbdARU_-VAvNV9R8pfy5mh7xMf2KxTnc99B_J86JlzvBs09FVBY2ATl2rYWWZfGOXVhG_v8y
x7r-w9rwArPziarbzjjUleHpXVWVGMDKkG38OtCU_9VMGghrlstwv_oSvL5Le8S774u_FrYLLBdDetq5GJF-DC6ZPky3ChB0RlEriKInYF0lzw3pznie342r
MfEplxaO2L5n_jIkaGgyvaSOtNuzpBSsNw5lYQVNAlVyf1wx__I-DUwm0riDRV6-VsMAxlttfn6BgTi-Ivpixa-NZmBXjFaM-sql8a9dd-_zfprhP6r_srfi
_gvWROyO_dK1hmi3YJvVkgpqt_5IsuHRVbAFEc9ryr7jQTJxb_Scw3a_Nu8bdFa42rZPRxlnHPmC8Yc7_wm2mVWZnVvroCEFka4UlcVlNDtdXnxQpyTz6xWp
I7xl0opCrFDCrI7dTdB1fmdYCEXTUYfO7eQ5EiNU8py6VVnPjyQOlzy2IZlsxCALGQ5_8Elu_xgtNFjF4x7cSuKFxmNk_3byjbFpeUm9ulLyGyUt7yyp0txa
Vq5FSBl5NkCpndzNGATtdFLZrcpvg220K7rhpNti4SBcqoFMVAzS9q7LRbw_y1Udf6hM_AWqgge0_WezmQeO_qiL7FhlIA-i-Iy
}

