sprite $Visual_Studio_Workstation [96x97/16z] {
jPVXTgim38D97CjE5lR-Ztld67pQ07IzsxIs__P9bdF2OJbJOj3oDt9wjkyVuJF8NVXl79XfD-Bq1tmmburBe3_XsmYnYh_8_uSEdhzmAVblrW3s0KgXM4Fv
LJwO6xWKT_ZbahoVjdOsFkrdzVSSWC5VFniF0-Sc-fqr49Wn-5yEMWeLehGa-nJGp-y6pidx6Ueev0vcyDCr90ODYlFTWMaeZH5-j8Q2ajB4jpLOHvboClt_
6WYy8HW8lg_1AY9t-CyrP32bDF537OOV9QKewUtYh_c-1YyfZvAGtwANz23mnFSrq93Xiw_XhUBpzfSA0ywV7SG6o7auvCpVN0EOV6ZFnJppvpNiec-jWKef
Yx6zLmO3Si5lQozkuFfEIOLqLJQ7GGSp2u0pVWNgPtD-ZC3f9LzbrN7g67j-j1E31a3QfvX36lWllLe3M_vL6QPHFSFor_Kec7Jjl2sPA0-7_9gFaVeXlxRJ
WanrxJGC4kNXS5SIP-UpuRqW4K5JkHe0Omr-w684Vi4NXc0e-DS3-1foCeN3VJ_YjN3ahw8t0_WQKegIW7J9PrKLbcq3mPTr_RmSm4lAcmFXbiyYoh8l63k_
Vfhc8_haeCu7N_9X-PcLHURyiXh_sKBWYZLWyF4jFkGflm_WcWeAwITzExyRH7uVO7R0fCRVpHy5YOeulnftVC92Zlpx_6NdXu6gRdm9SanHR_A_pw-VizQt
yqlmtI3ufkWdz6v-3huRFFFRvooT-9Zot_EZdoP3klSVgZC_l-W_-4CGuokwkDe63xK3Fz_drsS-H4tWfm7k-OoNV3pcDu7uT0Fh__9dWq8PPqVqFJxlV0s3
pO7fIn1P9xwyno-3By7tEmYgGiKS3WFKYKylypi_3C0y78eRS7_1f_lyCv-PmLIOcJQ7vnMtz_YHtmqmwCISaZcGEJ3waVz-VdKw2XLE2nKMGJ435fRfWBxT
lnYV6MBXQHb7Hy4O8q306WQ7_EM6NrXP1byGz4p4rbLUahSbOgXhFh_c2qDGHl4ZiO3JzhvToComhq7UuTFEXmWNHl9gnD-mab7jAuBXiCODFV5DN7Awu3lT
1YXbL4FB5fxTmWt66kh4nqUe0_HiaU5y30zX7lIoc1AuV8a1Dp0njuO7zPqS5k1my0P4d3qWwiLltbI6V7wRW04kV4xlkud52p6WgZmApoDXNZRj-1Z2Ty0f
OqWVeVtn5ta9bT4DQ9idFOmM_1Z20_WZqN4pt0nx5ySvfp3JSb0gpW-H3S63drEMZr2mGxrhMUwK6G2RWaxs6JFaBrN3p1RnwRqhNTC9G2dP1MN3suVyhDC9
Vef_Pv2DdaFQUzqkqc71p7I1Z_X3IEVXdHwglRb3eKtyAhthWy_nJW-rBGs5GRr7XngTb3FZSzyCActIQ_h7HntQd7309vI9N_gcjVchgDp0TLUjvj3op6T0
zMa4xFbNCw2CgzNMYjRqmS4tCCTNquE5HlvXm5VX5PonweFgiQ02w2x0se4bSVumkAABNJcbjsU3kQ0HFuJjPg8YrVbhFyLtzIipIzT7VNpGL0yUwSKVaF0p
tw_m7du8p_mwBI3BuDU1vnIcmm5jRRsVDbzs03i_DF49MbqAUjoAEzJMF_gCRph2kqgR-9ZMgmDUAsYwgW6kgntLGpVy673YroD_I0y7br770UeJteDyaq-o
yP4cVdPy6CIvISij_x3VZJ_XQU338AgVnopt_0JZjpe_t4hWmy3mKfP9FF7dPmmKjTMgTD9zg7U_Rv2NMPZuagUW5TfQq_nKlRJrcT_6PjC1doR-eUU4OV2G
FpEq1peCcc8vYhJga_XGO5L5hPoJkMLYI5sFwhMYBE_MumEOGqXqFL4pXpZweIpFyTl9ZAL-ILjLKT7QrpDvOQtAv81w6z-5Qbfl992z9F4xriKwnUVbH6aO
z4jw0orSjptNgc1o2y9jEw6Ckm7yMA8PtjJ6ifXoUSQtZhIyRT3ZpQCvVeoWvY7rYTxXvRzLKLprPk3uLiUDKeCkMbllRS9FAcB_TQ3JKuOjVcsjzKbjBcTM
uicXAqgQClGhAT_ZtG5gsInD4p2Tx4dR6RtvdA-L2sCx7UTvCgJDS6_njvGAHBt_RSwy_B9IZ5bEnlm7
}

