sprite $Voice_Workload [96x95/16z] {
jPYBakEi4eDJBQarNHJl_xhdGB3NcN6yoVnPxSwLgg_L0co6stzL2BT_fr0g5VyAZzHGuX-PbwYX5FuDdTHKVZgaO4xwpi_aPuCdGVB0_rn88H4WTVJlT2e-
HiUol_FJjWyhANuTF2C03Bp8HxxrnmH-6Nn4n8b_fxNnGxbglHqDOcZvVyXVktzaVlrVrk_eH_yxNti-8UNNB93n3fwvw2V-9T-ba2A2NqFMky4FdUHFRv9a
1A1P8D-89WvwN3-KTq5L9P1U_3U2F_TFEht4CLHLfCO4b9uI1o6swPcFbYV-eTpm6LEiigJdyGTIKod6v8zAf_wnjbRUpK__h2f25ixfIYm6gHGcF-Bsqp_u
P-yobaXNGSyUfn91PQu7f9J2u8C__EEmjmPuuwiinHFpGvXkeHGvxSLiNZZoWrfASS4NFnVz3EyyZ46Yx0ov525numT8BlwnCoOlNiTIBVonWkr8jr4XhSNP
zov9xlIPw-sPg39__f9fIwuQ5KQnmCIJZ_J8l7mF3vDvFYSkKrMjEM2lnId-C7_vnA5QdKQNmR8Hz6Wl381BZtHVyjCzuvmVhCg8CHfX45mL7kZN_50rdHVM
BE05Cx3un-2TV-5JlNZEn-hWmFyMpGl-vMuyuKT5g4gB_pqQQMj0b_4xdl6ZChBQXEQtQ8u725t5tpEUvXzkSgk8-1QD7avOl-F34M1pjIBp8Pg74zOrlptd
Hm6WihMlFDA_7u5-pKS99BEr3N-dImyD_9Al25GDmzLgCy-xjEa_yCChZb1hUVyU025IV9LVpS_uKUGzUBUsw21-DF0tFfxmRymXHh1w9IAm7o74Q_vESJFF
HnWvz3NusJiUZw0lykLMfyEHlEE_Pl3LQ_Ad7fVGDL-jyWollEFpQqxXQc3HXxIKzWKVWn_FyFF4dM1QZmqSbf0l_OUgZBF7nbSE-4X_ohqVpeZt2dTTyzDb
dU1xPHBSjwvRzzu0XxOAr-zVgIed51HcKa5LAoCp05Op1z-zRNmkVl9wVeSm-1Y1YzfE6Y4X4Ud9acrQlNCl09Avpy4LF-Ioa6ArLkN4uVsIjLPAod6OOH9Q
7LpcCoJPARgL2O3IueiHRAMDFmBQ2uZYoiUwv4EUveihMM7vJmQWAj_v-hE7jNL0fNJD3uciCe2iLgQq-641f3nAEAAwzmOWhNmk-KCYgX9GwqEbZCKF7_CF
zzhur9hX5swo19S13_pGck8K8jIyyqT0COK426dMJiKbdjB4zqrjyM74A5iRduiFR1r86lGhXL15gFtaHn43KYj_jAwjG88aLpHN4bq9JlpIpeyo3ldl4now
T_32xLWage3gHtvi_73JWRyc60m0hrs1GYv1HtmxyC5gtlav-5EWTlgbzDD-qwgC283qbd-ejuL_zNOrairWFwguniJ17r8-y9Ly_Igv2NxWE_R1jNzbJZvd
Fgz6i-9lP_4SRpm7NNU-41ZqbmLMWMsHx_RnxSPMoaeFvxZnpMjjJlup-oj1jzPxAmT2Q_Gj_pfBVyUxpJcNgnY9D_agF_1BZ_YiqHDPhRNEy9lya5V-f-c4
1hwGjVWjR-z96kR-u1_JsV6kKI7K7MytO7hXwniU7ZMHhX80eNhZxJr1rfp3rlmD7zbczkiI3-GAy2s5CeT3vxBsc8vXAuOm-zJjRM5KI2xpZ_OhjF11SV7V
LaISbAs1OsPiVAnyFYFTxITdzQ02lHS-XO-ShqffuJaF48wFyTrx2shQr_pYtlDZV7Z4Gs60on4HxPFnZ-arg04kZpN0yOkFyWKozdleUjr-W7WXVu94BEbr
-v5LplZh-i61ZpVIprxLM-flwv-Wv9YgrZ9UZRPvFj0IrnCWi5gRxgiry-MTwTRNNrkN0TaZ500QUDtUuBTMBbyLYApMMwNjgde3VuFTgigsdivoAAlt9as-
Q-1VbZpngUgbSmlJl7FnAtLxHyWSUFNUh3WzreqHX6Q1THH_iuB8SMQhrCcPfrLY7KB5I_hrQ-kE4YBkxA1Sg-X_LiGzYjxAUPUhhT0-9UIeCFPRMryjt3uf
QDYUgd8E-eSLWAIKY0y4ypy
}

