sprite $Web_Cam [96x149/16z] {
jPkBSjivhyCx4WbIe-dxl-unZZ0oPIlnffCFVwVt_W22gg-xVpwgcG60cxK_loy3vUu0PRzEzyxOLEj6g_Pxz7TQeqNxVVhfuEr_afqtETXlqwLbqHnelqqN
Mwi6x9VfPqS_7-7pzjh-lZraGFyf_iFcb5y6F-wewIyqwSivckImduLdjbCYrloj6lWFy5ReHUS2pWW6_qTyrQMTdnfquU-gc_qdWmO8VrLlr_GoiCzyuJyO
AFxF3JhwT-bvBOTsawD_YkyVudTwYF-kJtSLXlOTdl16Yw_u7VZN-6f7Ad_i1uUeVuY_1lXWOFzuUBhAjpB1ptRSO1_Ygn_xsg1_im9xZT_D0RDdDricWykC
Mi7dUZo75DwBW-qbtqlyig6Z7X-7G63RwNdrTXcWVzrGgwSd1fKHcLaSQlnkfy4-NGRxL7yI3Y22ocLceg_qTZ7GW8vsuRluIe-bwe2IdtYhAzWBiYyQWkjF
DxpWaorfX9BVYa4vlgMX-tfD-EgG6i6U-OrIGnLl_Jf00yEe_21POGqqe9P1oT_DQlLDTDC0z-DZQxNMdecS0so34byDbVXQ4DvMtBbUnGVGMskb2IJnCYZn
rL2fNhk7tVYABtnJ6ADYDIG3mYMbB-tmoz7kV8m1RzGkSmavga5jg6RNo6y3cFWvXYsw0cqIX1yfUjS0IYyjTmFQZT-5huV19AGSO8Sqm3vPMfdT-3OCIKP0
rKkgQCbDjcf8QMIo1Dpuo3b7CkWSOQU1FmtiKDbLjrqfx9rlSoO0TpV7677YtJ5oh-0OGFbhdy3R-V4vG3aDp71MxG_5MCBB0ABNy-1eBtmJdWxcPdI84fyE
buOqW6sw17-vVn1-J4eHCpV-8JXa4Ay3b7OauEHZng8FIWuMwS8RyS0-GqMz7VSQ4dhbhtPuRa057NWQ80E74myDaEy3Y7qTW2SpGlY8K57elIDMESHJbnMB
RwS5oeOD9ESSeNlxe4yrWF28wm1Ty2hOvYDcHX0VW_ICeCDO1d0AKju7u7VzYu8QnWmaFGRvCWWP18J_RW3Hh_oECOWM_Z3mtYqW_3S3s9iSlTRFUd8yHBhu
WJcjjqg_3z35loz0_8o5fsA9hbp18JrMUedAWgHBGOwPaJEKh3fmCxqRgcBnurD1-uI2_34p2pr36jDwTrIDPL3pz-yMWDLDv5Wg1hU6GW_6sFHhGMwmax_f
Qv8z08w60h7ukKdtWXmG7vilXp6f32erm1CVOnbilDyASZlvSzSp5dxG82FF0I9U2lBrLVag3LgmF_aoc7yV-CUtB4i3-8wlUn4M910dE1QWgT3s-HTVUk3f
yFTlKkjVSS4V1Vcr8ES54v-7P_CP_A4v8_xEnH-zcszybeBSN2CKlijK_4P-J1OlYHzp3J2dhG521kGd-QucoWBAqk7Yf_WRJys8eG4cZFiYNVoX1QWTBmlm
dNyVe1Z9Jaizr8Z7ZrIGFGJ1C_S2NF7Twe9bkVcEKGxGd5C6_7uGDQVuP_u1eGXxBbYc9lvUiF3aFZLee89s_kS2I5vVrfvqIlsS2vZ47_ovJCCUqkl9sFmm
4ns5hu74fx0BcYhcv9S5vDAwEym5ru9BUbF_RHUKgw12B_oz0E9PF_cn5gpuyDQ9B-d5VnQqozU6I_xf3BVAeSHNKehyZPS3sbdGUptYhmKRwIkz-Bu5xrtr
d_bLK6R4PExJOavgyrT-yNc0NFd10rh2KwXFWOA1viQgexca0zHrT4RXFsNjkLzilkHWj5cB9xpmtQs7kd_oInVMLdQT7KVbDqHg09BNDv_v49subLziTuWl
0HdQmDQDFuI_vwTMGQ21F_aTM0DenzfqvJlvEQJ0og_RuZ-t_VPHAn3l0wYbXoq0yeK_-a79N-adlu46UURNeiLl1J-0qZz0_ewlNz7nbupy67K2kOp5jmjV
TF7BjhNUAco3Sm3MFmZemj_pzrwMVUDt039uvbSzGRuLV09Z35K1yIjTzLVvDgZvf-f1H-77ubELJq5I_KLO1fFI00kV0D2Yy45-CYrSD5FwIprImvv05fDu
ji_wptfYZ2XnlTczdgfU38e2dDzhVAqNvVY8Vgz7CXdaUCLxouEl-a69ZyF0l_pe6b4THe3gLl6gH_5B_PVuLmEAWJC2WOZZyEUA3yLN_SAVxTyD377A6ofU
fqV0NG-Axd0jsOqpvBTunPTw_xpSUaoD3hA0zO8F0CYt-EOLtpz-JWvxQ9txPY5snlD5F0vU-uolQawozOVCaHaXSi4xl6uN_bRE9uVMp5RsH56o9J_Z_o1z
_MyuQ01LymnFF70UJb1cvlpk8xs3eIYJmo7uDRxw_4_xrVkED31tPA47MFPnU415ndBuC483VD5bOERcqBzd-EiT3V5mpYa7ixBa6zv8bvgU6Bi4uRTQSxWj
8HFz8PV17TzR-QpHh3NYEODStex-geLoZQ09hlZM25-oc7Fqrcj-Tb_mzl-yxN0QtF6c-AHJQEqUttipA4ctPO4C_z9W1P8mfpIC8mZ-D61rK9toa87kNTuF
fhNzNcdEekojANy9lnQvFn6YLD533jXxEsRIAFIHpChcp0Kt6ke0FHsi6Bmtv21XgS03yDQQXVV5wloUsSMdTaLz7TDbu6TyRs_u0M1nBIC2EkgEhIPf3sOn
Ccu36FfhEKDhtFn014urIHl6e483ME4_suztklWPkFFbW26b1gZrM3_Q2LKZzLl-6g3IOHU-y1OxF3UvbOp_Yi_d19v4ire8v7K1VVE7yDOFlci054L08rYk
u9LlG3_Mwxp87w9NViCoA4hzp2sqLj0W1NB0Ab-_IhnRDvwuLcLv51G3qgPx1-OSllc--OwkbwzZcFMbTgeZCZFqBY9y2PlUk4RC98YtA0l6VhzhUDC_TlMp
zSVAFOJUy85E3DIr8SEbFFWmtS4pgTHUP2_o51rMG9eB9p_CGRu-9jS2JdKxLEbI8txTOXpzPtTGAtUdGnF_Rh3NQgtUIsuTV4F2e3jsEdIxxrYoOwq5yzGO
n_cCr5FQ9Q7UHg2llQrLwgZn4xtyJYHiyNdJ2CMX3E1PwVVqmU5QtKkcwPapBtswUt6uhLNT5-KOnqCm-Mh8A1gegtgGEZ97ZjHQhzq8F-27UMJ6Mh4L7GxT
CidNMeikdoIg_bgG360lMWwaCtoe-7jsuLNFML3S3QI5VrjhCzpm2NlDa9JvLmuXkXLsDxpHSr206Zmta0c37BW8h_7BMblhIdB7XsBK3SWW74lkLguW7l2J
UgUFLFkNXZY28n0X2zqoyus6M3Ve4huijye0qgdb88-7uElX_Vp2SObUohyPPAmPb0zwr5tV7-Hzer3eAVpLWFYb4FMp5Fq3NZk8F2paaIyuVQCV5Fe8uUzg
16OLgeTkrL5iAJ--n3Pe2qKH-y0KANUb_-StE0fyPD5kRxmhG-4_gKCj2JvubHzUbJ_vtvEQ78xyOpjTeyCA_QEQrI5qNV22gvaVgJksH-sgU2JPFun-lNEF
45ni7Qf_XrSFnrUoJlOlQBt-TM7Tp7hxZFu_
}

