sprite $Web_Cam_HD [96x105/16z] {
j95RaiGm20D1Gept_XTULmtE-yUJf0-W5i8kGKWf1UqDA14TXb9u8zq6e8HNqWjtflozTEz4qfxWl8L_3PJyXVIAx-3s5o2DFVRf1Uzjn8Gv1bw2uhw0SiCE
F_G7RWYGxZXY-_WxWeJX2B7fZri2nKLy1qE0WWcR1sb-AazY4S1HHBfD8rxNvn1WHR9P_5mVv31OjI-ei4aeksnV1j_9EVy2mPTrMoTLuONlnI6R8wi-sr_H
aXlWkzbc5qBD4wtdffIVrWsw4jHLSminhDf_L6Gt9CyByOja4yItNiMlXdOIS15m8b_k0B9FegXwrm8kHCxacmDiBLNzoj05mS6oplm1QGwehqDi2XulyFzE
p0IxSLq7eXQ1Ae3YqT7-T_l5qPHR-O_sxSwSt0ABo1ZazlOlrzCZfW5LbSm19WqDGMOWN_abGXhD3rvuP7zPjrk0yYk_MamNZg532q0NoYy7Q7w9oUt2oy1Q
vYy1LkvO2_U6W2_yqQtZhXbaZFKADF-x7q2LONd_pSryJsdVFGUWsdi0H2jtFtJLBudqjBlxdah22A2LXkhyym5K55prczFtF7X9A06TN5Ya5g3XRTVbWW8J
kRlv7lTzTq-xcQ52kkK3D6G4P1OB4ejvVB_aDI47iEdP3Y2A_6-JJEjhiI1rPsvdzxtYkI8sFzqykXQzOcf7iLWGed4tzwPF-S6pdmNB0MWhAw6DhpLkpS_i
p_I0sX0hsM_r040OuvSNL_ni_hqrb4f3azyjEkhya2oNPWU_yBVjJ6al_ynwFwKWLZqqrF6XnRzzrS_kAHtfUhWUkNMzkUSRHYLefRsqudUYzv_bXRJt0rH_
H2EqScg0BEsdlVt7UNWwwW7Q-jS0ej8_jogwzFdbsltdUVcz7O2WjNuyMZU6CdiFMF07Ndxl_kFSzte0CrYc-XtJ1NJzweB2zhh-ntbczIYew-SB6FRL1OMZ
N43U_REeKoq87DFxy8lebtuna-RVZzbFJFxfWl6TVwEBxTM_5ttpcnRztQ-2PNy31arU0zAOFvc9-V3RxtwXYUyz8EkRNoU_ex7k7z0KoMj0scl0dlsi-fi_
O6BDBwHulu6qZtv0B_pgdmyW-znGcz-gFLuyzgElzGCWjGCKVRhTRtpkd_9Q18JORkyBsFD-IdQt-Ut9lwtwDr9oGtt-AyIpln1dlyx-rpBI0hpEVpscKT_Z
Jv-_tzVV6n9F_QUKP7olJmODKNGONjy6C3MzanIFzL_wOtrUtx2LmwkLUdW1FDIFyEFu8q2H8J76p_Fpd-ibNjy2GhiVO_d_gkVrFKAeQF7qtQcW4vvtVxqZ
GbG4z4gSsfcsv_U_U8EwAUpolkUtZ_5_zmSWXB2fmcF7YVlu8gAW_A1NIX2Hi0a0ys8tDFhoq7B2J_k389KWU200cjLcA07Rhter17tGgrHe5D4MyBLUFQNa
GPxq3HY_hKYwdgd2Mu84KEJtW8rj-DZqqJG4aNQnEOiIWdHOxo2i-XMYcIvdNbIdIf62PF6F1D9KTVq055NHEdqaKLnk5wpK-Li0tDsekdo0aCU7bkwjsMT_
cxyWy4Bno-hjYgAqunpwpMSzQcT1pJscH2Xq-ORRr-MiXqZtotG067EoMAac9KE6NFEZw9aysuT_4_Ecj-OhzlAUt_ahCSZDlmMm7c6sNtSAgtxZjkPdEK3V
y302H0VmYso_s5gYh_gj-CD3W8YAIBEtVTdG3qGyeH8-_VNLCW8QMn11-wN0gNtTB5MEz4oiDGwKfe0KMa1799uLxyiU6C__9CrVNuLE438p0ewpqhiMCfqB
n7V0HdE0KCd_vWIXdvM3TNYGFCuL4gOBy1n0xKY5xd5-Rm4pvngkxu9Q0BG1LPIjIVsu6fGL7nsJOAC_t-PfH-w0PRj9OiBTsFt6GPfl7Ebe__85RK6dzapc
6t0tt1FStbrpODtFl8Fyh5iu_4bVdL02sfyroAQ_6EkGnh-paOyVxFpSNwGvShw2Z96qJ7v2Y_-n7_fE2xF_VW5jyzpdY4BwFtuTijar-_7nuwrvmumrv7dL
Ho7RN7-3nrC_6I7DPrhzpt1xh5_ix4HvVI3uIEWdZPbykMvp8Pe-wnSUjmaU4cWZ8_MJJZSp7Vwp_aqmDHhnUc8JbEvdVwmt0jd6miIF-XKWFKtttyP_8fIC
ssSN96ppn1RchbFcjWofDVOtc_3VHUPKRgl_aRJmmv5CNJS2vzt6N-jxsCgVfyTuBYFIfy-kZN_OuyBmSzSCZv7YJ_9abEsr0jDHc3O1wQZaIFNZHly1yxL6
O0VZoZd8-H_y-wF9_m
}

