sprite $Web_Application [96x78/16z] {
xTMBZbgz3ePXbE_WvFvlUECGBvYrOKh-WevzAwNdnvueQFpjskNFjJy5D3IS8a3xijSlCsm3UNAU0aXxctyr0X41vCbv2iIkN_fR_lx-gRyCae3xIG3fDxsV
torcIfziNqfM-WtVwkR3NuhBRrzg-UtofJxh__DRmworp_iDicDb2-sJFkGuPUDJFXnFCp_X7xfNKK72htwyuKiwyFWvWQ3uTtwpQ5O-Yeo4vFQBx_9VywP8
aEgzamGeNoEP0oYwxVXddcH7kZOhsPOSSu1L0xPzM0bBwRCodNuehX6k0Pj-tJr0KAHo191pv5cOdiFattozyYUV7DG79I8ZmUNFYNQtz1_y56bcO2UN3rBo
35p3kh3fdrzcLrgh6a1owkvss_MjfMCoTv-afEN3jm7Ife-rFgGSuNaklgweNbE_vhRdgzQFOAAJhLzv-iByTP--zC9lQhyz7enHQjsLLhT1jdlcBH_o8I9R
U7KCKEwV2Jk-PPffK-KJdB-ePDAi_SDxFcUexh_caPUU0pIU-V72RxN-GyJgaMVF2R9wH7lVh-j_mdFvNLrsVRpw687tVQtzIxKVPpskdtpNbH-XztsxzYzV
EldYv2svzv43lE7BnH_YsPTegneZjdncXtRoLxQ2uN24zdtVI4fwwjUt-Nbitq-2axJFFWzVaXMXVFzxlgS0q8VFq_MJadsLh_mOU_uqxO3BpuhFfFNsip76
zT3xla9KH73wFmQmVANknM--VqIGGn7oumNLKNpww_7lVNvRX4Y4TFe2k5BOxhN-pEqDl_8S43eDg6JPlTPV_cN3LqG8Z0Zg_tt9TtuD2EtuBQw92YlYF43N
YZzTprj-vhY6n6T9Fl8wzBeVNxPyH8mH52bdcYrSbdlnjmAlV2__b4V42E7Q7A5xjjL_RDzp_JqVkVy8P7HsyEMFF6hzBJ_pV1GaG43oGpL04N7ZVTdsMmuG
gzE0K6JBTtlfuvMVDnJYym5nrEjszlRFb2-815VIYS_gexMxVmqetRGjdVKeVdV_6Z2AfrbsDOhVthzI0dVTYaenAtxNhvYlwARJbYAK7VkRbx_mwvbwhHzZ
5fcY7kPV-FKbsAR7wdZtjVokVuwEw94LNVed_0nrDvM5I_OHFskWAn7rdpxbLwt-zSVzwiF-Fz_yKZ5z-MdnaMokTChpny-9tlU_tVy
}

