sprite $Web_Conferencing [96x114/16z] {
bDC7SlDA3WHWa-W0aFU_xovcKD9VgaU7TZQbhoT-_LUE04YHH1nVdpa3f3GF_vmJacnR4yJ7KwB3LO8_wcWxHnTN9Cn03ufndcTqLeU4F-gPEJvt5XFzE8Hp
wSDZjVFufHvILjNudV61w0OeXXzzHTBnsy5NP_kMEC6Ag7ZhdAZ3N-W7IML4415K-zBBZmWHeqCz16dhjXK_ywB81RLtHk3Semn45u2C7RJkrRrvYx_WpM20
GPlWAZcZ3GXTC3x0rlTWv4vAl-1DEa2HiBi3M3vbeiFPLdhqYANdppvfUzk0mFRPliZt4Thw3YBEa9qT_k0lq0GH9leDsyVB3mACuQUHewU9dywzErpZ0pEP
NS2N7ximtcVIdTo1pczzoIlS1P6YlK69uvDJyAaRFmoVKhg33jt-lc8ldp3OzG5-wX1_MfsbpRkJ5BFMgdOeTZoxh0ZolV012pzixlYKID1KiQgypF6n-aaW
AucOG7Nzw3VV1NGb6icIgvgKrHcVfA_xkgegE_N_NDTTudVyATNolN00LSMKrmui7k1EtlVL_YjN5rp-hW3EySdbj9zSEwnL0484gMozoTsnVbnT83pxShry
UlpAZhrziKla-nxue-LEFVB7-7Fas-T70K62ThuMvvhKRC5DFFanVcxV952TvKz1FnX_Fwhxlg_-EHCWdvVVwnsMsYUXyQT09kV6llt9szUZdxbzarsWzluj
wC3PtyT_5ymHkg_WayzSun-9f2JLAEdvVrShSWew2v-jk44y-jv-GvJf-jVe1bjIV-DHK_1n0NG--qeDPJfxsphZxrYLsGquSXw_yJuy1nMFVlNvMRxkpWju
DsnV9e-eUKNJI_SHvFFvPxbCAUNMFmjg-TwdIsGSfsg_ghydZvEaujdFIfFK6lt33EJPQB8hlawGH9nVFNPI-5-jve7SHW-3KHBb0xXx__l6ImX3GLvJ6cVy
_bxoq5Wa9flZnm-B6HP_gS0i5vWXx-ClH1zWUxkSi366uRW9420Ns8fG0E-Ev_E8SzBF-m2sFlG6YcNMoUu3Beup6gJdRG0phECem0CLJTfcmETfXiE-k0-m
TdEYw_JTToW6S5LWXm4sLe0WklzI0AGbd06s3JhEM3vMPX2uZTS0p-qMw9ibAdRwwR2nxAM2vSy0MlexsNo7wJWElqOmia4bGEfN051PW9yKCFmyS1bWhm4C
hm6q5HJR0c82mzsc07QyH32BPMe8FwXLW4iFsIwXOMiNlKp10Bkk1Sm2ldi4mMOFs3dCLWlgd9DPO7IdWe2tcyonLc7fKPcqbpRN0dHt2etJxMc8kP8M9hZq
VBi2WxuxHiUgO5B7u53uMCs_BK3QhW8_emCP0Kzs0pRwHjcWRG3x4ld86d86XyTNKFFDr_HzWuAkSn-CHmtcat747O01fVOJaYjeYy2El5FyJEO6WEsxMmQm
Ay6ZFyTPkcCh-Ms3sZj8OJwEilGTOT-XPG0xkYXW_kMTRWDKUaks0rZNs9xEeWW-VIEay4lxAyAlV-RNow_uCx-4l_-LFrugG7_bf_3BVqawCKl2JBsyi5ty
ob-NR4L5A6_XYz-u7-fy26MPlx5Qle6gS7wC-CLhUgZv6p3gDEFXuXV-7dBXMw3infqYXeQVFhUJflmUvKPJ7yZqy-Vsa6-OIwW-f-F35TeL5y9xY6ZP0tnI
WinfaMG1UzAU0RI_Jrw4kbB_xgVhj-jFJBVwzqrYc39JKzT6HJt55MOElI6UZJrAsFHcwcFpzqvBVK_wFVGYGrKKsd_MoyFPltYCaMddbsU_pxz0D_eARSa6
kJth-OS039UjlIyeo0d39tbAwLs03jUVzI7buF6FQmE8NaZO-VvXMWq_wf_azD0-HvI44mEzwyvBxhbZeHf_io9KH9Y8J5j5NJVw-I_4py7mSHvWeWmGv8vJ
xQrJw_fI0C5bcpsHds1J7Qx28bU067KozK0tjzR9TTlzek_Cn0fcLMv2OZXEpW9AW3mVUZCKVowUGkel5JlOvywa-PtSee2Bqg6OCX70TN5AxXOWoP_iclxJ
zNHgdRXZMF4dzGQLslvY3diYqNvrOHFs0spd5PMAdujVNUlgl9G6M9K7iuPnCe_J-HZkQxub_xtViD3MDP1eAH69N6eQn-bv2Exonqt-CuQ8ghiAiZaSCsCI
c34qKkrzbpzU_6FbtrjdXO-OhqXTjMlt9aMVsAi_kYu0N3g9Ff0BBiG5j4zV_9jVkR5CiOt3bZrBo0BwND1BV-yVnKyOBjmDt4GqGMIVK-1o3MpJPnjb_NIC
eTHRxoJ5NYCi_Jvx5XykzNmOetTYqSLqvv_Z4zUdUXi3_F9MFqoJJ5xNdmN0Q_gqu8B6QrGTy1XOzeSVyMUT_dIt5lAghzt9zfS6ZKSpREOR8O3uCpZjNtJQ
s2zzjcSX63C0Vt4vDPAFIjIaftxoJhzMPorWw5phWYZ1CCknR0spH81NESnKL9O-qrzG1818h00LXLu1p3XpnnNYsS-1c19pdwCDYxPlI0J8UrXzzjzTGix2
ZOOhqizFe9CxDIOP5uPsGxumQIO5KTV-G7jdQXo5ymkYF8FQ53YexG9a2UAspdWUobbrvnk8T2pzDi3XNCvuLbMXTMKGtw0ZiAM_dq54aBLRHMQmrX9-HTJ7
yKXU-_uBZ4U0Ou0VUks0jDuIuehQzR-d_iDtn754YCRpOf2sg9cR7yiE_l2NacM8mpMVIvAbnkLUTbl9Rv4I8O8mzKSGKWNCFV_RM7Qgddq47nbZmqWxmlun
h14YkLMlr27z5sy_4MABEm2XtpvTAMQl_LOztPho_tqUCr-O0Slz_tHYoG_lSVCplstuFm
}

