sprite $Workflow_Application [96x78/16z] {
xT05Zk0m58FXWEsNtl_0Y-bWmVDs8mtz1V6No5fTzMk7zLVXCQcMsvoJUkkIq1__zFnwr16VyckfvkqxVFzHz_ZsTtQozquI7IGn_SP_JASHKWNQeaXA5NrL
c3uN1Vtrsw9slopgNVlVVWstfA_kbVRXbVT1t7zvdrPfF-ZrVdqvvNrvvVsmIlinXl7c_M4Luz9dtf-bVREaN_Iw63h8yCrg5AFtwqErs45wcry9i2_pcm02
MEI384c0vaQ8wTlR_0tilj_OxMtsG2HyOvkPkP7l4o3rvwKeQoFVhmBr8cCZsyU1BqBLzwzhhmy0-H_tho9UN1x5zuqWA6Pp6zztwW9t_d4RsxSsuXyUGadu
vaQ4MaduvaR6Ddc_L0bbeLzQbFVanwNVNeTe1rtv_THl8xosf1_qIlkoUiT-E2djnrf_n73A-rxnVltDAUzlLcEr_rxttuQNuIze-j3dzhzzOb7wu_DfkYxU
ceGzNYRgiD0blxoV
}

