sprite $XMPP_Gateway [96x67/16z] {
jPIDcgCW34LDGY01t_zvrs2eV5IcRgrdTsRwUnBlLPShG8WnuF8Kcvrvcm2Fs6cp6pRXztRatUuJwBTs2vvx8kCJqJH-MWEEzf_M03pOSvhLS3zuG-AiXll1
fqaDlme-2rUatA_1WvzphuOmHbFQW-mFz2YQuMRmVVOo-Bs6Ey5hcv7cHTEDu9jVsuDoLZHU3luwYOthDT3KdlDOjBG7NGsNWv_pqcgRB7qDU8e7VzNjq4YW
4DZ-3SIwF7yajtxt1mZNeBW09ydyd-0oPV13b8rL-JEgxS7S_xO_Qybg4oJm1rBww7VjSlXZsSWYeciAbyzx_B0ycihzgji4EuIySlYeBtC_7DIZtVrPLNF9
TKB9t_SB7MZwpg_Pq5fq-CuFFSYfynkvebThWBdUuDJxVK0fclEr6WBCxPxFgr-LtMy3ikPQG-4_8OAfliVznu1rLVKQ_hAR_u8T0NU_r1ccNzi4dLrlL85h
-fUVMKnVoLABpklCtljX3gBvWwWOnNPsT583qUZtbCCR1BZd0p6fwBQxiAoDqaBgQmZqvcyjde0LYij2KV9grMupv0Xfg25G3pZpvD7pjor2qhBQFnPPxK4T
f-rwQz4mqpdCV-nl02VDzIvNicXnBAIDKdYt4625sZ_37Y0mES7-XK1Xtp-Otq2VK9IbDBBceXlhlZxWMmpWunWEy01U_hq6cr1FfNnCoBgn-mUmEnn2fEuP
eOts_Ri9cWqMDN5ZujyLdbCOsTzoVoCaLHDAlSyvvToF1hGQ-bmS6lVteckhmg8x4x_9VNlZE2AlXSRzkw8DhjVru9-4q_RteGOD-myrLBZti_9fjIz_i_lo
tVwp2SBDlzeZ1kotz-mT4r_Stw_eYhZV7lDiUsDitg5plnSjzg_pOx-zRNZ0vyIupC2Oh67tYoJtUnAkRwH0vxXjLiFBdwBxMyH4FGcMBmXHjTWjEqMAZDXb
Vz_lHKjUDOLbCNz_vjprEq210opk7xQ_xtVStvqvZ_Wz6wHd_0xHatvwr6_wX_T_pa_sxr4_qhD-UixF0ZG3EIvteSI07T3E9liblDo6a_24566v3t4yXyCo
vHy
}

